spectrocloud/librarium

- vale.ini
- vale/styles/spectrocloud/condescending.yml
- vale/styles/spectrocloud/plural-parantheses.yaml
This PR addresses backport issues from PR #2364
> docs: DOC-1096 DOC-1095 (#2364)

- docs/docs-content/vertex/supported-platforms.md
This PR updates the VerteX supported platforms page with a new entry reflecting support for AKS.
💻 [Preview URL](https://65e8ec7cf661f165af46a0c2--docs-spectrocloud.netlify.app/vertex/supported-platforms#azure)
🎫 [PCP-2607](https://spectrocloud.atlassian.net/browse/PCP-2607)
This is for a new Palette release.
[PCP-2607]: https://spectrocloud.atlassian.net/browse/PCP-2607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VerteX support for AKS

- src/css/custom.scss
- src/css/dark-mode.scss
- src/css/light-mode.scss
- src/theme/Admonition/Icon/TechPreview.js
- src/theme/Admonition/Type/TechPreview.js
This PR adds the TP update to release-4-3.
> Update the TechPreview component in release-4-3

- docs/docs-content/clusters/public-cloud/azure/aks.md
- docs/docs-content/clusters/public-cloud/azure/azure.md
- docs/docs-content/clusters/public-cloud/azure/windows.md
This PR addresses the backport issues with PR #2130.
💻 [Deploy Windows Workloads](https://deploy-preview-2408--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/windows)
> [version-4-1] backport Windows node pool PR 2130

- docs/docs-content/clusters/public-cloud/azure/aks.md
- docs/docs-content/clusters/public-cloud/azure/azure.md
- docs/docs-content/clusters/public-cloud/azure/windows.md
This PR addresses the backport issues with PR #2130.
💻 [Deploy Windows Workloads](https://deploy-preview-2410--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/windows)
> [version-3-4] backport Windows node pool PR 2130

- docs/docs-content/clusters/public-cloud/azure/aks.md
- docs/docs-content/clusters/public-cloud/azure/azure.md
- docs/docs-content/clusters/public-cloud/azure/windows.md
This PR addresses the backport issues with PR #2130.
💻 [Deploy Windows Workloads](https://deploy-preview-2409--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/windows)
> [version-4-0] backport Windows node pool PR 2130

- docs/docs-content/clusters/public-cloud/azure/aks.md
- docs/docs-content/clusters/public-cloud/azure/windows.md
- docs/docs-content/integrations/kubernetes-generic.md
- docs/docs-content/integrations/kubernetes.md
This PR backports the refactoring efforts on the Azure AKS cluster creation guide from [PR#2405](https://github.com/spectrocloud/librarium/pull/2405).
> Backport Azure AKS refactoring to version 4.2

- docs/docs-content/clusters/public-cloud/azure/aks.md
- docs/docs-content/clusters/public-cloud/azure/windows.md
- docs/docs-content/integrations/kubernetes-generic.md
- docs/docs-content/integrations/kubernetes.md
This PR backports the refactoring efforts on the Azure AKS cluster creation guide from [PR#2405](https://github.com/spectrocloud/librarium/pull/2405).
> Backport Azure AKS refactoring to version 4.0

- docs/docs-content/integrations/rook-ceph.md
This PR adds the 4.3 notes for Rook Ceph pack. 
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PAC-1468)
> docs: add rook ceph documentation

- docs/docs-content/clusters/public-cloud/azure/aks.md
- docs/docs-content/clusters/public-cloud/azure/gateways.md
- docs/docs-content/clusters/public-cloud/azure/windows.md
- docs/docs-content/integrations/kubernetes-generic.md
- docs/docs-content/integrations/kubernetes.md
This PR backports the refactoring efforts on the Azure AKS cluster creation guide from [PR#2405](https://github.com/spectrocloud/librarium/pull/2405).
> Backport Azure AKS refactoring to version 4.1

- docs/docs-content/clusters/cluster-management/kubeconfig.md
This PR updates the Kubeconfig table.
> docs: Update kubeconfig.md

- docs/docs-content/clusters/edge/edge-configuration/cloud-init.md
- vale/styles/spectrocloud/colon.yml
> chore: backport Colon usage 4 2

- docs/docs-content/integrations/hello-universe.md
This PR fixed Hello Universe no longer rendering
> chore: fixed incorrect image type

- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR addresses the backport issues from PR #2472
> [version-4-1]docs: PEM-4073 (#2472)

- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR addresses the backport issues with PR #2472
> [version-4-0]Backport/version 4 0/pr 2472

- docs/docs-content/clusters/data-center/nutanix/create-manage-nutanix-cluster.md
This PR updates the **Create and Manage Nutanix Cluster** page to add an **Update a Deployed Cluster** section.
💻 [Create and Manage Nutanix Cluster](https://66044d0f1c095c1ecebb3882--docs-spectrocloud.netlify.app/clusters/data-center/nutanix/create-manage-nutanix-cluster)
🎫 [DOC-1119](https://spectrocloud.atlassian.net/browse/DOC-1119)
[DOC-1119]: https://spectrocloud.atlassian.net/browse/DOC-1119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add update cluster section

- docs/docs-content/introduction/introduction.md
This PR is the manually backport the following commits from `master` to `version-3-4`:
- [docs: add Getting Started callout to landing page DOC-1124 (#2487)](https://github.com/spectrocloud/librarium/pull/2487)
> [version-3-4] docs: add Getting Started callout to landing page DOC-1124 (#2487)

- docs/docs-content/release-notes.md
- package-lock.json
- package.json
- src/components/ReleaseNotesVersions/ReleaseNotesVersions.module.scss
- src/components/ReleaseNotesVersions/ReleaseNotesVersions.test.tsx
- src/components/ReleaseNotesVersions/ReleaseNotesVersions.tsx
- src/components/ReleaseNotesVersions/index.ts
- src/css/dark-mode.scss
- src/css/light-mode.scss
- src/theme/MDXComponents/MDXComponents.ts
This PR addresses the backport issues for PR #2483
> [version-4-1] docs:  DOC-1122  Tip for past release notes (#2483)

- docs/docs-content/release-notes.md
- package-lock.json
- package.json
- src/components/ReleaseNotesVersions/ReleaseNotesVersions.module.scss
- src/components/ReleaseNotesVersions/ReleaseNotesVersions.test.tsx
- src/components/ReleaseNotesVersions/ReleaseNotesVersions.tsx
- src/components/ReleaseNotesVersions/index.ts
- src/css/dark-mode.scss
- src/css/light-mode.scss
- src/theme/MDXComponents/MDXComponents.ts
This PR fixes the backport issues from PR #2483
> [version-4-0]docs:  DOC-1122  Tip for past release notes (#2483)

- docs/docs-content/release-notes.md
- package-lock.json
- package.json
- src/components/ReleaseNotesVersions/ReleaseNotesVersions.module.scss
- src/components/ReleaseNotesVersions/ReleaseNotesVersions.test.tsx
- src/components/ReleaseNotesVersions/ReleaseNotesVersions.tsx
- src/components/ReleaseNotesVersions/index.ts
- src/css/dark-mode.scss
- src/css/light-mode.scss
- src/theme/MDXComponents/MDXComponents.ts
This PR addresses the backport issues from PR #2483
> [version-3-4] docs:  DOC-1122  Tip for past release notes (#2483)

- package-lock.json
- package.json
This PR addresses the backport issues from PR #2427
> [version-4-0]chore: bump sass from 1.69.5 to 1.72.0 (#2427)

- package-lock.json
- package.json
This PR addresses the backport issues from PR #2427
> [version-4-1] chore: bump sass from 1.69.5 to 1.72.0 (#2427)

- package-lock.json
- package.json
This PR addresses the backport issues in PR #2427
> [version-4-2] chore: bump sass from 1.69.5 to 1.72.0 (#2427)

- src/components/ReleaseNotesVersions/ReleaseNotesVersions.tsx
This PR fixes an issue when redirecting to the release page for a previous version.
> chore: fixed react hook logic

- src/components/ReleaseNotesVersions/ReleaseNotesVersions.tsx
This PR fixes an accidental code logic that snuck in.
> chore: fixed logic

- docs/docs-content/clusters/public-cloud/gcp/required-permissions.md
This PR fixes the backport issues from PR #2583
> [version-3-4] docs: Update required-permissions.md (#2583)

- Makefile
- scripts/versions.sh
This PR fixes an issue that the OpenAPI plugin beta 10 introduced. The sidebar.ts file is no longer automatically removed. This causes issues during version builds and as the file remains while moving across different branches.
> Fix Production Build Issue

- docs/docs-content/release-notes.md
This PR adds a security notice to the release notes.
💻 [Preview URL for Page](https://661705c88e9d7c550cb0a8cb--docs-spectrocloud.netlify.app/release-notes)
This is for a release.
> chore: add security section

- docs/docs-content/clusters/edge/architecture.md
- docs/docs-content/clusters/edge/edge.md
This PR clarifies our ARM64 support. 
🎫 [DOC-1146](https://spectrocloud.atlassian.net/browse/DOC-1146
[DOC-1146]: https://spectrocloud.atlassian.net/browse/DOC-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: clarify arm64 support

- docs/docs-content/clusters/edge/architecture.md
- docs/docs-content/clusters/edge/edge.md
> docs: clarify arm64 support (#2616)

- .github/workflows/aloglia_crawler.yaml
- Makefile
- docs/api-content/api-docs/2-samples.mdx
- docs/docs-content/registries-and-packs/deploy-pack.md
- docsearch.config.json
- scripts/url-checker.sh
This PR enables searching for API pages, except for version branches.
> chore: add API values to algolia

- .github/workflows/aloglia_crawler.yaml
- Makefile
- docs/api-content/api-docs/2-samples.mdx
- docs/docs-content/registries-and-packs/deploy-pack.md
- docsearch.config.json
- scripts/url-checker.sh
This PR fixes backport issues for PR #2621
> [version-4-0] ci: add API values to algolia and fix broken URL (#2621)

- .github/workflows/aloglia_crawler.yaml
- Makefile
- docs/docs-content/registries-and-packs/deploy-pack.md
- docsearch.config.json
- scripts/url-checker.sh
This PR fixes backport issues from PR #2621
> [version-3-4] ci: add API values to algolia and fix broken URL (#2621)

- docsearch.config.json
This PR updates the Algolia search index
> chore: updated alogilia behavior

- Makefile
- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
- docs/docs-content/clusters/public-cloud/gcp/required-permissions.md
- docs/docs-content/devx/services/service-listings/mysql.md
- docs/docs-content/devx/services/service-listings/vault.md
- docs/docs-content/integrations/citrix-ipam.md
- docs/docs-content/integrations/cloudanix.md
- docs/docs-content/integrations/falco.md
- docs/docs-content/integrations/longhorn.md
- docs/docs-content/integrations/nutanix-csi.md
- docs/docs-content/integrations/portworx.md
- docs/docs-content/integrations/portworx_operator.md
- docs/docs-content/integrations/prometheus-operator.md
- docs/docs-content/integrations/vault.md
- docs/docs-content/vertex/system-management/enable-non-fips-settings/use-non-fips-addon-packs.md
This PR fixes broken URLs detected.
> chore: fix broken URLs

- Makefile
- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
- docs/docs-content/clusters/public-cloud/gcp/required-permissions.md
- docs/docs-content/devx/services/service-listings/mysql.md
- docs/docs-content/devx/services/service-listings/vault.md
- docs/docs-content/integrations/citrix-ipam.md
- docs/docs-content/integrations/cloudanix.md
- docs/docs-content/integrations/falco.md
- docs/docs-content/integrations/longhorn.md
- docs/docs-content/integrations/portworx.md
- docs/docs-content/integrations/portworx_operator.md
- docs/docs-content/integrations/prometheus-operator.md
- docs/docs-content/integrations/vault.md
- docs/docs-content/vertex/system-management/enable-non-fips-settings/use-non-fips-addon-packs.md
This PR fixes backport issues for PR #2631
> [version-4-1] chore: fix broken URLs (#2631)

- Makefile
- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
- docs/docs-content/clusters/public-cloud/gcp/required-permissions.md
- docs/docs-content/devx/services/service-listings/mysql.md
- docs/docs-content/devx/services/service-listings/vault.md
- docs/docs-content/integrations/citrix-ipam.md
- docs/docs-content/integrations/cloudanix.md
- docs/docs-content/integrations/falco.md
- docs/docs-content/integrations/longhorn.md
- docs/docs-content/integrations/portworx.md
- docs/docs-content/integrations/portworx_operator.md
- docs/docs-content/integrations/prometheus-operator.md
- docs/docs-content/integrations/vault.md
- docs/docs-content/introduction/resource-usage-estimation.md
- docs/docs-content/vertex/system-management/enable-non-fips-settings/use-non-fips-addon-packs.md
This PR fixes backport issues from PR #2631
> [version-4-0] chore: fix broken URLs (#2631)

- Makefile
- docs/docs-content/clusters/public-cloud/gcp/required-permissions.md
- docs/docs-content/devx/services/service-listings/mysql.md
- docs/docs-content/devx/services/service-listings/vault.md
- docs/docs-content/integrations/citrix-ipam.md
- docs/docs-content/integrations/cloudanix.md
- docs/docs-content/integrations/falco.md
- docs/docs-content/integrations/longhorn.md
- docs/docs-content/integrations/portworx.md
- docs/docs-content/integrations/portworx_operator.md
- docs/docs-content/integrations/prometheus-operator.md
This PR fixes backport issues from PR #2631
> [version-3-4]chore: fix broken URLs (#2631)

- docs/docs-content/release-notes.md
This PR acts as a stop gap related to release notes numbering.
> docs: Update release-notes.md

- .github/workflows/aloglia_crawler.yaml
- docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
- docs/docs-content/devx/services/service-listings/vault.md
- docsearch.config.json
- scripts/url-checker.sh
This PR fixes an issue with the URL checker not reporting accurate values.
> ci: fix URL logic

- .github/workflows/aloglia_crawler.yaml
- .gitignore
- docs/docs-content/devx/services/service-listings/vault.md
- docsearch.config.json
- scripts/url-checker.sh
This PR fixes the backport issue for PR #2638
> [version-4-2] ci: fix URL logic (#2638)

- .github/workflows/aloglia_crawler.yaml
- .gitignore
- docs/docs-content/devx/services/service-listings/vault.md
- docsearch.config.json
- scripts/url-checker.sh
This PR fixes backport issues for PR #2638
> [version-4-1] ci: fix URL logic (#2638)

- .github/workflows/aloglia_crawler.yaml
- .gitignore
- docs/docs-content/devx/services/service-listings/vault.md
- docsearch.config.json
- scripts/url-checker.sh
This PR fixes the backport issues for PR #2638
> [version-4-0] ci: fix URL logic (#2638)

- .github/workflows/aloglia_crawler.yaml
- .gitignore
- docs/docs-content/devx/services/service-listings/vault.md
- docsearch.config.json
- scripts/url-checker.sh
This PR fixes the backport issues for PR #2638
> [version-3-4] ci: fix URL logic (#2638)

- docs/docs-content/clusters/public-cloud/azure/gateways.md
- docs/docs-content/clusters/public-cloud/azure/windows.md
- docs/docs-content/integrations/k3s.md
- docs/docs-content/integrations/oidc-eks.md
- redirects.js
This PR fixes the backport issues from PR #2656
> [version-3-4] chore: merge master

- .github/workflows/aloglia_crawler.yaml
- .gitleaksignore
- Makefile
- docsearch.dev.config.json
- docusaurus.config.js
This PR fixes the backport issues from PR #2654
> [version-3-4] chore: added dev aloglia config (#2654)

- .github/workflows/aloglia_crawler.yaml
- .gitleaksignore
- Makefile
- docsearch.dev.config.json
- docusaurus.config.js
This PR fixes the backport issues for PR #2654
> [version-4-0] chore: added dev aloglia config (#2654)

- .github/workflows/aloglia_crawler.yaml
- .gitleaksignore
- Makefile
- docsearch.dev.config.json
- docusaurus.config.js
This PR addresses backport issues for PR #2654
> [version-4-1] chore: added dev aloglia config (#2654)

- .github/workflows/aloglia_crawler.yaml
- .gitleaksignore
- Makefile
- docsearch.dev.config.json
- docusaurus.config.js
This PR addresses backport issues for PR #2654
> [version-4-2] chore: added dev aloglia config (#2654)

- docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-dynamic.md
- docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-static.md
This PR fixes the backport issues in PR #2690
> [version-4-2] docs: fix backport issues

- .github/workflows/nightly-docker-build.yaml
This PR fixes the issue with the Docker build job missing a `.env` file. 
No pages affected 
> Docker fix

- .github/workflows/nightly-docker-build.yaml
This PR ixes the backport issues from PR #2697 
> [version-3-4] ci: docker fix (#2697)

- .github/workflows/release-preview.yaml
- .github/workflows/release.yaml
This PR fixes the broken prod builds
> ci: fix build issue

- Makefile
This PR fixes an issue where the `.env` file is missing and make commands are issued.
N/A
N/A
> chore: fixed an issue with missing .env

- jest.config.js
- package-lock.json
- package.json
- src/css/custom.scss
This PR fixes the backport issues from PR #2737
> [version-3-4] chore: fix css spacing issue and correct edge forge indentation (#2737)

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- jest.config.js
- package-lock.json
- package.json
- src/css/custom.scss
This PR fixes the backport issues from PR #2737
> [version-4-0] chore: fix css spacing issue and correct edge forge indentation (#2737)

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- jest.config.js
- package-lock.json
- package.json
- src/css/custom.scss
This PR fixes the backport issues from PR #2737
> [version-4-2] chore: fix css spacing issue and correct edge forge indentation (#2737)

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- jest.config.js
- package-lock.json
- package.json
- src/css/custom.scss
This PR fixes the backport issues from PR #2737
> [version-4-1] chore: fix css spacing issue and correct edge forge indentation (#2737)

- docs/docs-content/clusters/edge/local-ui/host-management/theming.md
- docs/docs-content/integrations/portworx_operator.md
This PR fixes two broken URLs identified in the broken URL report.
> docs: fixed broken URLs

- docs/docs-content/integrations/portworx_operator.md
This PR fixes the backport issues from PR #2749
> [version-4-1] docs: fixed broken URLs (#2749)

- docs/docs-content/integrations/portworx_operator.md
This PR fixes the backport issues from PR #2749
> [version-4-0] docs: fixed broken URLs (#2749)

- docs/docs-content/integrations/portworx_operator.md
This PR fixes the backport issues from PR #2753
> [version-3-4] docs: fixed broken URLs (#2749)

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
- docs/docs-content/integrations/portworx_operator.md
This PR fixes the broken links found in production.
💻 [Build FIPS-Compliant Edge Artifacts](https://arc.net/l/quote/ewnkkhcv)
💻 [Portworx Operator](https://arc.net/l/quote/gkyzksmk)
🎫 [DOC-1171](https://spectrocloud.atlassian.net/browse/DOC-1171)
[DOC-1171]: https://spectrocloud.atlassian.net/browse/DOC-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix broken links found in productiong

- docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-custom-registries.md
- docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
This PR fixes an issue where we did not correctly call out how to deploy to an external registry. 
🎫 [Jira Ticket](DOC-1177)
> docs: DOC-1177

- docs/api-content/api-docs/3-postman-collection.md
- src/components/IconMapper/dynamicFontAwesomeImports.js
> docs: update postman collection 4.1

- docs/api-content/api-docs/3-postman-collection.md
> docs: update postman link 3.4

- docs/docs-content/clusters/edge/architecture.md
- docs/docs-content/clusters/edge/hardware-requirements.md
> docs: add new hardware requirements backport

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
This PR fixes a broken link to the Git downloads.
💻 [Build Provider Images](https://deploy-preview-2810--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images/)
> chore: Fix a broken link

- docs/docs-content/integrations/byoos.md
This PR fixes broken TF code in the BYOOS pack.
> chore: fix tf code

- docs/docs-content/automation/palette-cli/commands/validator.md
This PR fixes the backport issues with PR #2875
> [version-4-2] docs: PAD-219 chore: update validator URL (#2875)

- docs/docs-content/release-notes/release-notes.md
This PR contains the 4.3.8 release notes.
💻 [Preview URL for Page](https://spectrocloud.atlassian.net/browse/DOC-1188)
🎫 [DOC-1188](https://spectrocloud.atlassian.net/browse/DOC-1188)
[DOC-1188]: https://spectrocloud.atlassian.net/browse/DOC-1188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DOC-1188

- docs/docs-content/release-notes/release-notes.md
This PR fixes the release date.
💻 [Preview URL for Page](https://deploy-preview-2880--docs-spectrocloud.netlify.app/release-notes/)
> chore: fix path release date

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
This PR updates the build branch for the FIPS guide. I was told to build from main specifically when I worked on this one, but have learned that we should tell users to use a specific version instead. 
> docs: change fix build branch

- README.md
- docs/docs-content/user-management/authentication/authorization-token.md
This PR fixes an issue with the quotes in a curl command causing the token to get ignored.
💻 [Preview URL for Page](https://deploy-preview-2896--docs-spectrocloud.netlify.app/user-management/authentication/authorization-token/)
> docs: Update authorization-token.md

- README.md
- docs/docs-content/user-management/authentication/authorization-token.md
* docs: Update authorization-token.md
* chore: fix example
This PR fixes the backport issue from PR #2896
> [version-4-2] docs: Update authorization-token.md (#2896)

- README.md
- docs/docs-content/user-management/authentication/authorization-token.md
This PR fixes the merge conflict with PR #2896
> [version-4-1] docs: Update authorization-token.md (#2896)

- README.md
This PR updates the README change from PR #2896
> [version-3-4] docs: Update authorization-token.md (#2896)

- .gitignore
- Makefile
- README.md
- _partials/_partial_example.mdx
- docs/docs-content/getting-started/getting-started.md
- docusaurus.config.js
- package.json
- scripts/generate-partials.sh
- src/components/PartialsComponent/PartialsComponent.test.tsx
- src/components/PartialsComponent/PartialsComponent.tsx
- src/components/PartialsComponent/PartialsImporter.tsx
- src/components/PartialsComponent/index.ts
- src/components/VersionedLink/CheckVersion.tsx
- src/components/VersionedLink/VersionedLink.test.tsx
- src/components/VersionedLink/VersionedLink.tsx
- src/components/VersionedLink/index.ts
- src/theme/MDXComponents/MDXComponents.ts
- tsconfig.json
This PR manually cherry-picks the changes from [docs: add PartialsComponent to handle Docusaurus Markdown Imports in librarium DOC-1189  (#2887)](https://github.com/spectrocloud/librarium/pull/2887).
> [version-3-4] docs: add PartialsComponent to handle Docusaurus Markdown Imports in librarium DOC-1189 (#2887)

- docs/docs-content/clusters/cluster-management/palette-webctl.md
- docs/docs-content/integrations/kubevirt.md
- docs/docs-content/vm-management/create-manage-vm/access-cluster-with-virtctl.md
- docs/docs-content/vm-management/create-manage-vm/create-disk-templates.md
- docs/docs-content/vm-management/create-manage-vm/create-manage-vm.md
- docs/docs-content/vm-management/create-manage-vm/create-vm-template.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/clone-vm.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/deploy-vm-from-template.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/migrate-vm-to-different-node.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/standard-vm-operations.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/take-snapshot-of-vm.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/update-vm-configuration.md
- docs/docs-content/vm-management/create-manage-vm/vm-oversubscription.md
- docs/docs-content/vm-management/vm-management.md
- docs/docs-content/vm-management/vm-packs-profiles/add-roles-and-role-bindings.md
- docs/docs-content/vm-management/vm-packs-profiles/configure_OIDC.md
- docs/docs-content/vm-management/vm-packs-profiles/create-vmo-profile.md
- docs/docs-content/vm-management/vm-roles-permissions.md
This PR addresses some markup and layout issues in the VMO section.
💻 [Virtual Machine Orchestrator](https://deploy-preview-2928--docs-spectrocloud.netlify.app/vm-management/)
> Fix the markup and layout of pages in the VMO section

- docs/docs-content/clusters/cluster-management/palette-webctl.md
- docs/docs-content/integrations/kubevirt.md
- docs/docs-content/vm-management/create-manage-vm/access-cluster-with-virtctl.md
- docs/docs-content/vm-management/create-manage-vm/create-manage-vm.md
- docs/docs-content/vm-management/create-manage-vm/create-vm-template.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/clone-vm.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/deploy-vm-from-template.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/migrate-vm-to-different-node.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/standard-vm-operations.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/take-snapshot-of-vm.md
- docs/docs-content/vm-management/create-manage-vm/standard-vm-operations/update-vm-configuration.md
- docs/docs-content/vm-management/create-manage-vm/vm-oversubscription.md
- docs/docs-content/vm-management/vm-management.md
- docs/docs-content/vm-management/vm-packs-profiles/add-roles-and-role-bindings.md
- docs/docs-content/vm-management/vm-packs-profiles/create-vmo-profile.md
- docs/docs-content/vm-management/vm-roles-permissions.md
This PR backports (https://github.com/spectrocloud/librarium/pull/2928) to version 3.4.
> Fix the markup and layout of pages in the VMO section (#2928)

- plugins/packs-integrations.js
> OCI packs added along with public packs

- _partials/index.ts
- docs/docs-content/clusters/edge/local-ui/host-management/diagnostic-tools.md
- vale/styles/config/vocabularies/Internal/accept.txt
This PR documents the diagnostic tools available in local UI. 
💻 [Add Preview URL for Page](https://spectrocloud.atlassian.net/jira/software/c/projects/PE/issues/PE-4190)
🎫 [PE-4190]()
[PE-4190]: https://spectrocloud.atlassian.net/browse/PE-4190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: local ui diagnostic tools

- docs/docs-content/integrations/metallb.md
- docs/docs-content/integrations/ngrok.md
This PR fixes some broken links on the ngrok pack page.
💻 [ngrok]()
> Fix broken links for ngrok

- .github/workflows/pull_request.yaml
- docs/docs-content/architecture/palette-public-ips.md
- docs/docs-content/enterprise-version/install-palette/install-palette.md
- docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
- package-lock.json
- package.json
This PR fixes the backport issues from PR #2966
> [version-4-2] docs: updated proxy domain table (#2966)

- .github/workflows/pull_request.yaml
- docs/docs-content/architecture/palette-public-ips.md
- docs/docs-content/enterprise-version/install-palette/install-palette.md
- docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
- package-lock.json
- package.json
This PR fixes the backport issues for PR #2966
> [version-4-1] docs: updated proxy domain table (#2966)

- .github/workflows/pull_request.yaml
- docs/docs-content/architecture/palette-public-ips.md
- docs/docs-content/enterprise-version/install-palette/install-palette.md
- docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
- package-lock.json
- package.json
This PR fixes the backport issues from PR #2966
> [version-4-0] docs: updated proxy domain table (#2966)

- .github/workflows/pull_request.yaml
- docs/docs-content/architecture/palette-public-ips.md
- docs/docs-content/enterprise-version/install-palette/install-palette.md
- package-lock.json
- package.json
This PR fixes the backport issues from PR #2966
> [version-3-4] docs: updated proxy domain table (#2966)

- scripts/netlify.sh
This PR fixes a situation where Netlify builds are occurring after a PR is merged into `master`
> chore: fix netlify issue that caused master to build

- plugins/packs-integrations.js
- src/components/Integrations/IntegrationTypes.ts
- src/components/PacksReadme/PacksReadme.tsx
- src/components/Technologies/PacksFilters.tsx
- src/components/Technologies/Technologies.tsx
> Pac 1796 nageswari

- apisidebar.js
- docs/api-content/api-docs/edge-v1/emc-api.json
This PR updates the Edge Management API for 4.4. 
> docs: Edge mgmt api 4 4

- docusaurus.config.js
This PR adds an announcement banner highlighting the new Kubernetes report we published.
💻 [Preview URL for Page](https://deploy-preview-3023--docs-spectrocloud.netlify.app/)
> chore: k8s report

- docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
- docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
This PR adds a requirement for Edge clusters to have a stable IP address. 
💻 [Create Cluster Definition](https://deploy-preview-3033--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/site-installation/cluster-deployment/)
🎫 [PE-4525](https://spectrocloud.atlassian.net/browse/PE-4525)
[PE-4525]: https://spectrocloud.atlassian.net/browse/PE-4525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add stable IP requirements

- docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
This PR backports the stable IP requirements. 
> docs: edge stable ip 4 1

- docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
> docs: Edge stable ip 4 0

- docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
> docs: add edge stable ip requirement 3-4

- docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
This PR fixes a small user data alignment issue
Not ticketed. 
> docs: fix user data alignment issue

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/vmware-system-requirements.md
This PR fixes the backport issues from #3053
> [version-3-4] docs: DOC-1216 updated version (#3053)

- .github/workflows/pull_request.yaml
> ci: update Vale

- vale/styles/spectrocloud/colon.yml
This PR updates the regex to the colon rule to reduce false positives. Admonitions kept getting caught and other valid use cases. The new regex handles the valid use cases.
> docs: Update colon.yml

- docs/docs-content/clusters/data-center/vmware.md
This PR resolves the backport issues from PR #3090
> [version-3-4] docs: updated VMware permissions (#3090)

- package-lock.json
- package.json
- plugins/packs-integrations.js
- src/components/Integrations/IntegrationTypes.ts
- src/components/PacksReadme/PacksReadme.module.scss
- src/components/PacksReadme/PacksReadme.tsx
- src/components/Technologies/PackCardIcon.tsx
- src/services/api/index.js
- static/scripts/constants.js
> PAC-1855-union of versions, json icon files download logic

- docs/docs-content/spectro-downloads.md
This PR updates the version, download link, and SHA for Palette and Edge CLIs.
💻 [Downloads]()
🎫 [DOC-1193](https://spectrocloud.atlassian.net/browse/DOC-1193)
[DOC-1193]: https://spectrocloud.atlassian.net/browse/DOC-1193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update the Palette and Edge CLIs download information

- docs/docs-content/clusters/data-center/vmware/vmware.md
This PR addresses the backport issues with PR #3101.
💻 [VMware](https://deploy-preview-3106--docs-spectrocloud.netlify.app/clusters/data-center/vmware/)
> [version-4-0] backport add vsphere supported versions table PR 3101

- docs/docs-content/clusters/data-center/vmware/vmware.md
This PR addresses the backport issues with PR #3101.
💻 [VMware](https://deploy-preview-3107--docs-spectrocloud.netlify.app/clusters/data-center/vmware/)
> [version-4-1] backport add vsphere supported versions table PR 3101

- docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-provider-image.md
- docs/docs-content/clusters/edge/trusted-boot/keys/generate-keys.md
This PR fixes the broken links found in production on Monday, June 17.
💻 [Build Provider Images with Trusted Boot](https://deploy-preview-3109--docs-spectrocloud.netlify.app/clusters/edge/trusted-boot/edgeforge/build-trusted-provider-image)
💻 [Generate Keys for Trusted Boot](https://deploy-preview-3109--docs-spectrocloud.netlify.app/clusters/edge/trusted-boot/keys/generate-keys)
> Fix broken links found in production

- docs/docs-content/integrations/aws-autoscaler.md
This PR addresses the backport issues with PR #3022.
💻 [Autoscaler](https://deploy-preview-3114--docs-spectrocloud.netlify.app/integrations/aws-autoscaler)
> [version-4-2] backport docs: refactor and update aws cluster autoscaler pack page PR 3022

- docs/docs-content/integrations/aws-autoscaler.md
This PR addresses the backport issues with PR #3022.
💻 [Autoscaler](https://deploy-preview-3117--docs-spectrocloud.netlify.app/integrations/aws-autoscaler/)
> [version-3-4] backport docs: refactor and update aws cluster autoscaler pack page (#3022)

- docs/docs-content/integrations/aws-autoscaler.md
This PR backports the changes introduced by PR #3022.
💻 [Autoscaler](https://deploy-preview-3118--docs-spectrocloud.netlify.app/integrations/aws-autoscaler/?version=1.29.x)
> [version-4-4] backport docs: refactor and update aws cluster autoscaler pack page (#3022)

- docs/api-content/api-docs/3-postman-collection.md
> chore: correct Postman URL

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
This PR addresses backport issues for PR #
> [version-4-2] docs: DOC-1224 Self-Hosted Custom CA Update (#3061)

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
This PR fixes the backport issues for PR #3061
> [version-4-1] docs: DOC-1224 Self-Hosted Custom CA Update (#3061)

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
This PR fixes the backport issues in PR #3061
> [version-4-0] docs: DOC-1224 Self-Hosted Custom CA Update (#3061)

- .github/workflows/release-branch-pr.yaml
This PR improves the release workflow so that PRs targeting a release branch with `-a`, `-b` , or `-c` will trigger a Netlify preview.
> ci: update CI workflow for new release format

- docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
This PR fixes the backport issues from PR #3225
> [version-4-2] docs: update cluster-deployment.md (#3225)

- docs/docs-content/troubleshooting/cluster-deployment.md
- docs/docs-content/troubleshooting/edge.md
- docs/docs-content/troubleshooting/nodes.md
- docs/docs-content/troubleshooting/palette-dev-engine.md
- docs/docs-content/troubleshooting/pcg.md
- docs/docs-content/troubleshooting/troubleshooting.md
This PR cleans up markup and alignment in the Troubleshooting section.
💻 [Troubleshooting](https://deploy-preview-3255--docs-spectrocloud.netlify.app/troubleshooting/)
> Clean up markup and alignment in the Troubleshooting section

- docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
This PR documents the `fullyPrivateAddressing` property and its limitations for Azure clusters.
💻 [Create and Manage Azure IaaS Cluster](https://deploy-preview-3258--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/create-azure-cluster/)
🎫 [PCP-3168](https://spectrocloud.atlassian.net/browse/PCP-3168)
🎫 [DOC-1237](https://spectrocloud.atlassian.net/browse/DOC-1237)
🎫 [PCP-3169](https://spectrocloud.atlassian.net/browse/PCP-3169)
[PCP-3168]: https://spectrocloud.atlassian.net/browse/PCP-3168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1237]: https://spectrocloud.atlassian.net/browse/DOC-1237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PCP-3169]: …
> Document the `fullyPrivateAddressing` property and its limitations for Azure

- docs/docs-content/tutorials/tutorials.md
This PR fixes a broken link on the Deploy a Custom Pack intro card.
💻 [Welcome to Palette Tutorials]()
> chore: Fix a broken intro card link

- src/components/PacksReadme/PacksReadme.module.scss
> issue in displaying treeselect in responsive page

- docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
This PR adds a self-hosted PCG as a prereq for the `fullyPrivateAddressing`  parameter.
💻 [Create and Manage Azure IaaS Cluster](https://deploy-preview-3339--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/create-azure-cluster/)
> docs: Update prereqs for the `fullyPrivateAddressing`  parameter

- docs/docs-content/user-management/saml-sso/palette-sso-with-custom-ca.md
This PR converts the HTTPS/TLS admonition to a bullet in the guide prerequisites.
💻 [Enable SSO with a Custom Certificate Authority]()
> Convert the HTTPS/TLS admonition to a bullet

- docs/docs-content/user-management/saml-sso/palette-sso-with-adfs.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-okta-saml.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-okta.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-onelogin.md
- docs/docs-content/user-management/saml-sso/saml-sso.md
This PR fixes the markup and alignment in the User Management (SSO) section and also adds notes that require users to configure HTTPS and TLS to successfully integrate with Palette.
💻 [SAML and OIDC SSO Setup](https://deploy-preview-3345--docs-spectrocloud.netlify.app/user-management/saml-sso/)
💻 [Palette SSO with Microsoft AD FS](https://deploy-preview-3345--docs-spectrocloud.netlify.app/user-management/saml-sso/palette-sso-with-adfs/)
💻 [Palette SSO with Okta SAML](https://deploy-preview-3345--docs-spectrocloud.netlify.app/user-management/saml-sso/palette-sso-with-okta-saml/)
💻 [Palette SSO with Okta OIDC](https://deploy-preview-3345--docs-spectrocloud.netlify.app/user-management/saml-sso/palette-sso-with-okta/)
💻 [Palette SSO with …
> Fix markup and alignment in User Management (SSO) and add HTTPS and TLS requirements

- docs/docs-content/user-management/saml-sso/palette-sso-with-adfs.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-okta-saml.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-okta.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-onelogin.md
- [Fix markup and alignment in User Management (SSO) and add HTTPS and TLS requirements (#3345)](https://github.com/spectrocloud/librarium/pull/3345)
> [version-4-0] Fix markup and alignment in User Management (SSO) and add HTTPS and TLS requirements (#3345)

- docs/docs-content/user-management/saml-sso/palette-sso-with-adfs.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-okta-saml.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-okta.md
- docs/docs-content/user-management/saml-sso/palette-sso-with-onelogin.md
- [Fix markup and alignment in User Management (SSO) and add HTTPS and TLS requirements (#3345)](https://github.com/spectrocloud/librarium/pull/3345)
> [version-3-4] Fix markup and alignment in User Management (SSO) and add HTTPS and TLS requirements (#3345)

- docs/docs-content/clusters/pcg/deploy-pcg/maas.md
- docs/docs-content/clusters/pcg/deploy-pcg/openstack.md
- docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
- docs/docs-content/tutorials/cluster-deployment/pcg/deploy-app-pcg.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR documents the step for removing `kind` images after self-hosted EC and PCG installation.
💻 [Install Palette on VMware](https://deploy-preview-3362--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/install/)
💻 [Install Palette on VMware (Airgap)](https://deploy-preview-3362--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/airgap-install/install/)
💻 [Install VerteX on VMware](https://deploy-preview-3362--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/install/)
💻 [Install VerteX on VMware (Airgap)](https://deploy-preview-3362--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/airgap-install/install/)
💻 [Deploy App Workloads with a …
> Document the step for removing kind images after EC and PCG installation

- docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
- docusaurus.config.js
- src/css/custom.scss
- src/css/dark-mode.scss
- src/css/light-mode.scss
- src/theme/Admonition/Icon/FurtherGuidance.js
- src/theme/Admonition/Type/FurtherGuidance.js
- src/theme/Admonition/Types.js
- [Add the Further Guidance admonition + link to the VMware PCG tutorial (#3379)](https://github.com/spectrocloud/librarium/pull/3379)
> [version-4-2] Add the Further Guidance admonition + link to the VMware PCG tutorial (#3379)

- docusaurus.config.js
- src/css/custom.scss
- src/css/dark-mode.scss
- src/css/light-mode.scss
- src/theme/Admonition/Icon/FurtherGuidance.js
- src/theme/Admonition/Icon/TechPreview.js
- src/theme/Admonition/Type/FurtherGuidance.js
- src/theme/Admonition/Type/TechPreview.js
- src/theme/Admonition/Types.js
- [Add the Further Guidance admonition + link to the VMware PCG tutorial (#3379)](https://github.com/spectrocloud/librarium/pull/3379)
> [version-3-4] Add the Further Guidance admonition + link to the VMware PCG tutorial (#3379)

- README.md
This PR updates the docs repo README with details on admonitions.
> chore: Update README for admonitions

- docs/docs-content/clusters/public-cloud/azure/architecture.md
This PR fixes an incorrect statement about the proxy label. A commit was missed in a previous release PR.
💻 [Preview URL for Page](https://deploy-preview-3441--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/architecture/#proxy-configuration)
> chore: add missing azure arch commit

- Makefile
- package-lock.json
- package.json
This PR pins the linkinator version in package JSON to ensure the CI uses the expected version. This PR also bumps up the retry count to `5` and introduces `jitter` to when retrying. 
🎫 [DOC-1314](https://spectrocloud.atlassian.net/browse/DOC-1314)
[DOC-1314]: https://spectrocloud.atlassian.net/browse/DOC-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: update linkinator config

- _partials/self-hosted/_required-domains.mdx
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
- docs/docs-content/enterprise-version/install-palette/install-palette.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
- docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
This PR adds a partial for proxy domains and adds `ecr` to the table.
- [Palette Proxy](https://deploy-preview-3483--docs-spectrocloud.netlify.app/enterprise-version/install-palette/#proxy-requirements)
- [VerteX Proxy](https://deploy-preview-3483--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/#proxy-requirements)
🎫 [DOC-1325](https://spectrocloud.atlassian.net/browse/DOC-1325)
[DOC-1325]: https://spectrocloud.atlassian.net/browse/DOC-1325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DOC-1325

- docusaurus.config.js
This PR removes the banner message from the documentation site.
💻 [Preview URL for Page](https://deploy-preview-3489--docs-spectrocloud.netlify.app/)
> Remove Banner Msg

- README.md
This PR documents behaviors that operate to the new Pack component and how to handle edge cases. [Link to README preview](https://github.com/spectrocloud/librarium/tree/packs-docs#packs-component).
💻 [Preview URL for Page](https://github.com/spectrocloud/librarium/tree/packs-docs#packs-component)
🎫 [DOC-1283](https://spectrocloud.atlassian.net/browse/DOC-1283)
[DOC-1283]: https://spectrocloud.atlassian.net/browse/DOC-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Document Pack's Component

- docs/deprecated/clusters/edge/edgeforge-workflow/build-images.md
- docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md
This PR fixes a broken link to the FOG project downloads.
💻 [Apply Site User Data](https://deploy-preview-3572--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/site-installation/site-user-data)
> chore: Fix broken links

- docs/docs-content/clusters/edge/local-ui/host-management/download-core-dump.md
This PR adds documentation for core dump file download. 
🎫 [PE-4733](https://spectrocloud.atlassian.net/issues/PE-4733)
[PE-4733]: https://spectrocloud.atlassian.net/browse/PE-4733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add core dump file docs

- docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
> docs: add enhancement language

- docs/api-content/api-docs/edge-v1/emc-api.json
This PR updates Edge api for release 4.4.b. 
> docs: update edge api

- docs/docs-content/troubleshooting/vmo-issues.md
This PR adds extra troubleshooting steps to the VMO Troubleshooting section.
💻 [VMO Troubleshooting](https://deploy-preview-3588--docs-spectrocloud.netlify.app/troubleshooting/vmo-issues/)
🎫 [PEM-5587](https://spectrocloud.atlassian.net/browse/PEM-5587)
[PEM-5587]: https://spectrocloud.atlassian.net/browse/PEM-5587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kubevirt resource not getting updated after updating the pack values in UI

- docs/docs-content/spectro-downloads.md
This PR updates the downloads for the CLI tools to the latest available versions
Downloads page
None
None
> Update CLI versions

- docs/api-content/api-docs/v1/api.json
This PR updates the hubble API spec. 
> docs: update api files

- docs/docs-content/spectro-downloads.md
This PR fixes the prettier formatting of the downloads.
> docs: reformat downloads

- docs/api-content/api-docs/edge-v1/emc-api.json
- docs/api-content/api-docs/v1/api.json
This PR parses the API files. 
> docs: api parser issue

- docs/api-content/api-docs/edge-v1/emc-api.json
- docs/api-content/api-docs/v1/api.json
This PR parses the API files. 
> docs: parses api files

- docs/docs-content/clusters/edge/site-deployment/site-installation/edge-host-registration.md
This PR adds a warning about deleting registered Edge hosts if you want to reinstall Palette on the same node. 
💻 [Edge Host Registration](https://deploy-preview-3626--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/site-installation/edge-host-registration/)
🎫 [PE-4784](https://spectrocloud.atlassian.net/browse/PE-4784)
[PE-4784]: https://spectrocloud.atlassian.net/browse/PE-4784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add a warning about deleting registered Edge hosts

- docs/docs-content/clusters/public-cloud/azure/required-permissions.md
This PR removes an invalid Azure permission.
💻 [Preview URL for Page](https://deploy-preview-3641--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/required-permissions/#dynamic-placement)
🎫 [DOC-1349](https://spectrocloud.atlassian.net/browse/DOC-1349)
[DOC-1349]: https://spectrocloud.atlassian.net/browse/DOC-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove Invalid Azure Permission

- src/components/Technologies/PackCardIcon.tsx
This PR fixes the issues related to Netligy build errors due to the Pack list icons failing to load.
> chore: iconmapper error fix

- docs/docs-content/security-bulletins/reports/cve-2015-8855.md
- docs/docs-content/security-bulletins/reports/cve-2022-25883.md
8-22-24 cve updates
This PR ....
> 8-22-24 cve updates

- README.md
This PR places admonition examples inside code blocks. The reason for this is that GitHub doesn't render MDX admonitions, so the final output looks like some formatting broke.
> chore: update README.md (admonitions)

- docs/docs-content/release-notes/release-notes.md
This PR backports a bug fix that was not called out in the release notes.
> docs: minor backport to clarify bug fix

- .github/workflows/pull_request.yaml
- docs/docs-content/byoos/byoos.md
This PR adds logic to handle prettier format errors automatically. In case the prettier check fails, an auto-commit will occur.
🎫 [DOC-1361](https://spectrocloud.atlassian.net/browse/DOC-1361)
[DOC-1361]: https://spectrocloud.atlassian.net/browse/DOC-1361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: automatic format prettier error

- .github/workflows/pull_request.yaml
This PR fixes the backport issues with PR #3743
> [version-4-1] ci: DOC-1361 automatic format prettier error (#3743)

- .github/workflows/pull_request.yaml
This PR fixes the backport issues from PR #3743
> [version-4-2] ci: DOC-1361 automatic format prettier error (#3743)

- .github/workflows/pull_request.yaml
This PR fixes the backport issues with PR #3743
> [version-4-0] ci: DOC-1361 automatic format prettier error (#3743)

- .github/workflows/pull_request.yaml
This PR fixes the backport issues from PR #3743
> [version-3-4] ci: DOC-1361 automatic format prettier error (#3743)

- README.md
- _partials/self-hosted/_login-banner.mdx
- docs/docs-content/enterprise-version/system-management/login-banner.md
- docs/docs-content/enterprise-version/system-management/system-management.md
- docs/docs-content/tenant-settings/login-banner.md
- docs/docs-content/vertex/system-management/login-banner.md
- docs/docs-content/vertex/system-management/system-management.md
- src/components/PaletteVertexUrlMapper/PaletteVertexUrlMapper.tsx
- src/components/PaletteVertexUrlMapper/index.ts
- src/theme/MDXComponents/MDXComponents.ts
This PR fixes the backport from PR #3738
> [version-4-3] docs: DOC-1356 ATO message (#3738)

- README.md
- _partials/self-hosted/_login-banner.mdx
- docs/docs-content/enterprise-version/system-management/login-banner.md
- docs/docs-content/enterprise-version/system-management/system-management.md
- docs/docs-content/tenant-settings/login-banner.md
- docs/docs-content/vertex/system-management/login-banner.md
- docs/docs-content/vertex/system-management/system-management.md
- src/components/PaletteVertexUrlMapper/PaletteVertexUrlMapper.tsx
- src/components/PaletteVertexUrlMapper/index.ts
- src/theme/MDXComponents/MDXComponents.ts
This PR fixes the backport issues from PR #3738
> [version-4-2] docs: DOC-1356 ATO message (#3738)

- README.md
- _partials/self-hosted/_login-banner.mdx
- docs/docs-content/enterprise-version/system-management/login-banner.md
- docs/docs-content/enterprise-version/system-management/system-management.md
- docs/docs-content/tenant-settings/login-banner.md
- docs/docs-content/vertex/system-management/login-banner.md
- docs/docs-content/vertex/system-management/system-management.md
- src/components/PaletteVertexUrlMapper/PaletteVertexUrlMapper.tsx
- src/components/PaletteVertexUrlMapper/index.ts
- src/theme/MDXComponents/MDXComponents.ts
This PR fixes the backport issues from PR #3738
> [version-4-1] docs: DOC-1356 ATO message (#3738)

- README.md
- _partials/self-hosted/_login-banner.mdx
- docs/docs-content/enterprise-version/system-management/login-banner.md
- docs/docs-content/enterprise-version/system-management/system-management.md
- docs/docs-content/tenant-settings/login-banner.md
- docs/docs-content/vertex/system-management/login-banner.md
- docs/docs-content/vertex/system-management/system-management.md
- src/components/PaletteVertexUrlMapper/PaletteVertexUrlMapper.tsx
- src/components/PaletteVertexUrlMapper/index.ts
- src/theme/MDXComponents/MDXComponents.ts
This PR fixes the backport issues from PR #3738
> [version-4-0] docs: DOC-1356 ATO message (#3738)

- README.md
- _partials/self-hosted/_login-banner.mdx
- docs/docs-content/enterprise-version/system-management/login-banner.md
- docs/docs-content/enterprise-version/system-management/system-management.md
- docs/docs-content/tenant-settings/login-banner.md
- docs/docs-content/vertex/system-management/login-banner.md
- src/components/PaletteVertexUrlMapper/PaletteVertexUrlMapper.tsx
- src/components/PaletteVertexUrlMapper/index.ts
- src/theme/MDXComponents/MDXComponents.ts
This PR fixes the backport issues from PR #3738
> [version-3-4] docs: DOC-1356 ATO message (#3738)

- package-lock.json
- package.json
> chore: backport argos change

- docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/duplicate-pack-in-profile.md
This PR ....
💻 [Preview](https://deploy-preview-3846--docs-spectrocloud.netlify.app/profiles/cluster-profiles/create-cluster-profiles/duplicate-pack-in-profile/)
> docs: alter yaml spacing in duplicate profile pack docs

- docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-provider-image.md
This PR corrects the accepted version and k8s distro for trusted boot. 
> docs: update version and k8s distro

- docs/api-content/api-docs/edge-v1/emc-api.json
This PR adds the Edge management API. 
> docs: Edge mgmt api 4.4.c

- docs/docs-content/troubleshooting/automation.md
- docs/docs-content/troubleshooting/troubleshooting.md
- plugins/packs-integrations.js
- vale.ini
This PR fixes the backport issues from PR #3879
> [version-3-4] docs: DOC-1369 (#3879)

- docs/docs-content/troubleshooting/automation.md
- docs/docs-content/troubleshooting/troubleshooting.md
- plugins/packs-integrations.js
- vale.ini
This PR fixes the backport issues from PR #3879
> [version-4-1] docs: DOC-1369 (#3879)

- docs/docs-content/troubleshooting/automation.md
- docs/docs-content/troubleshooting/troubleshooting.md
- plugins/packs-integrations.js
- vale.ini
This PR fixes the backport issues from PR #3879
> [version-4-0] docs: DOC-1369 (#3879)

- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
This PR updates a step in the self-hosted Palette airgap install related to the OCI CA.
🎫 [DOC-1379](https://spectrocloud.atlassian.net/browse/DOC-1379)
[DOC-1379]: https://spectrocloud.atlassian.net/browse/DOC-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DOC-1379

- docs/docs-content/clusters/cluster-management/certificate-management.md
- docs/docs-content/clusters/cluster-management/cluster-management.md
- docs/docs-content/clusters/edge/cluster-management/certificate-renewal.md
This PR adds explanation of impact on cluster availability during the cert renewal process. 
💻 [Renew Certs](https://deploy-preview-3872--docs-spectrocloud.netlify.app/clusters/cluster-management/certificate-management/)
> docs: add cert renewal availability impact

- docs/docs-content/enterprise-version/upgrade/upgrade-notes.md
- docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
- docs/docs-content/enterprise-version/upgrade/upgrade-vmware/non-airgap.md
- docs/docs-content/troubleshooting/enterprise-install.md
- docs/docs-content/vertex/upgrade/upgrade-vmware/airgap.md
- docs/docs-content/vertex/upgrade/upgrade-vmware/non-airgap.md
> Vsphere backport 4 1

- docs/docs-content/release-notes/release-notes.md
Small clarification and typo fix on 4.4.18 release notes
> Small release notes fixes

- docs/docs-content/clusters/edge/cluster-management/certificate-renewal.md
This PR updates where the user should look to confirm that certs were renewed. 
> docs: fix missed mention of renewal

- .github/workflows/url-checks.yaml
- Makefile
- docs/docs-content/legal-licenses/oss-licenses.md
- docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md
- linkinator/linkinator-ci.config.json
- linkinator/linkinator-rate-limit-ci.config.json
- linkinator/linkinator-rate-limit.config.json
- linkinator/linkinator.config.json
- scripts/url-checker.sh
This PR fixes a few broken links and adjusts the linkinator config to avoid npm broken links. 
🎫 [DOC-1382](https://spectrocloud.atlassian.net/browse/DOC-1382)
[DOC-1382]: https://spectrocloud.atlassian.net/browse/DOC-1382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: fix broken links and adjust linkinator config DOC-1382

- docs/docs-content/automation/automation.md
- docs/docs-content/automation/palette-sdk/list-clusters-sdk.md
- docs/docs-content/automation/palette-sdk/palette-sdk.md
- docs/docs-content/user-management/authentication/api-key/api-key.md
- docs/docs-content/user-management/authentication/api-key/delete-api-key.md
- docs/docs-content/user-management/saml-sso/saml-sso.md
This PR fixes the backport issues from PR #3929
> [version-4-3] docs: DOC-1362 (#3929)

- docs/docs-content/automation/automation.md
- docs/docs-content/automation/palette-sdk/list-clusters-sdk.md
- docs/docs-content/automation/palette-sdk/palette-sdk.md
- docs/docs-content/user-management/authentication/api-key/api-key.md
- docs/docs-content/user-management/authentication/api-key/delete-api-key.md
- docs/docs-content/user-management/saml-sso/saml-sso.md
This PR fixes backport issues from PR #3929
> [version-4-2] docs: DOC-1362 (#3929)

- .github/workflows/api_format.yaml
This PR adds the missing dependency nodejs and npm ci
> chore: add nodejs

- .github/workflows/api_format.yaml
This PR fixes the label logic for the api-format label.
> chore: final fix

- .github/workflows/api_format.yaml
This PR adds missing requirements for the API parser action.
> chore: api label action

- docs/docs-content/troubleshooting/enterprise-install.md
This PR adds a missing letter in the verify command. 
> docs: add missing letter in namespace

- docs/docs-content/byoos/capi-image-builder/config-reference.md
This PR removes a sentence that is no longer valid from the Configuration Reference page.
💻 [Configuration Reference](https://deploy-preview-4018--docs-spectrocloud.netlify.app/byoos/capi-image-builder/config-reference/)
- [x ] Yes. _Remember to add the relevant backport labels to your PR._
> docs: Update config-reference.md

- docs/docs-content/clusters/cluster-management/palette-lock-cluster.md
> docs: backport pause agent upgrade 4-1

- docs/docs-content/release-notes/release-notes.md
This PR comments out the 4.4.20 Release Notes.
💻 [Release Notes](https://deploy-preview-4077--docs-spectrocloud.netlify.app/release-notes/)
> docs: revert release notes

- docs/docs-content/release-notes/release-notes.md
This PR adds the 4.4.20 Release Notes.
💻 [Release Notes](https://deploy-preview-4079--docs-spectrocloud.netlify.app/release-notes/)
> docs: add 4.4.20 release notes

- docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
> docs: add calico instructions version-4-2

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
This PR backports PR #4131 from master to version-4-1.
💻 [Add Preview URL for Page](https://deploy-preview-4150--docs-spectrocloud.netlify.app/)
- [x ] No. _Please leave a short comment below about why this PR cannot be backported._Backport PR.
> [version-4-1] docs: update airgap self-hosted pages (#4131)

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
This PR backports PR #4131 from master to version-4-0.
💻 [Add Preview URL for Page](https://deploy-preview-4151--docs-spectrocloud.netlify.app/)
> [version-4-0] docs: update airgap self-hosted pages (#4131)

- .github/workflows/backport.yaml
This PR improves the backport messaging in failure scenarios. 
> chore: improve backport message

- Dockerfile
- Makefile
- README.md
This PR fixes the Librarium Docker-based local development approach.
- Updated the `make init` command to create the .env file and include the required variables
- Updated the docker run command to use the local .env file
- Removed the .env file from the container
- Updated the README file with instructions
> docs: update dockerfile

- docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-helm.md
- docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-packs.md
- docs/docs-content/registries-and-packs/registries/oci-registry/oci-registry.md
- docs/docs-content/registries-and-packs/registries/registries.md
This PR updates the documentation to reflect synchronization support for OCI Helm registries. 
💻 [OCI Index Page](https://deploy-preview-4181--docs-spectrocloud.netlify.app/registries-and-packs/registries/oci-registry/)
💻 [Add OCI Helm](https://deploy-preview-4181--docs-spectrocloud.netlify.app/registries-and-packs/registries/oci-registry/add-oci-helm/)
🎫 [PEM-5472](https://spectrocloud.atlassian.net/browse/PEM-5472)
Release PR
[PEM-5472]: https://spectrocloud.atlassian.net/browse/PEM-5472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OCI Helm Registries - Sync Supported

- docs/deprecated/integrations/kubernetes.md
- docs/docs-content/glossary-all.md
- docs/docs-content/integrations/kubernetes.md
This PR fixes the backport issues from PR #4197
> [version-4-3] chore: correct wording of pxk (#4197)

- docs/deprecated/integrations/kubernetes.md
- docs/docs-content/glossary-all.md
- docs/docs-content/integrations/kubernetes.md
This PR fixes the backport issues for PR #4197
> [version-4-2] chore: correct wording of pxk (#4197)

- docs/deprecated/integrations/kubernetes.md
- docs/docs-content/glossary-all.md
- docs/docs-content/integrations/kubernetes.md
This PR fixes the backport issues for PR #4197
> [version-4-0] chore: correct wording of pxk (#4197)

- docs/deprecated/integrations/kubernetes.md
- docs/docs-content/glossary-all.md
- docs/docs-content/integrations/kubernetes.md
This PR fixes the backport issue for PR #4197
> [version-3-4] chore: correct wording of pxk (#4197)

- docs/api-content/api-docs/v1/api.json
> Palette API docs - 4.5

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
- docs/docs-content/clusters/edge/local-ui/host-management/custom-link.md
- docs/docs-content/clusters/edge/local-ui/host-management/theming.md
- docs/docs-content/clusters/edge/networking/connect-wifi.md
- docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR fixes an issue noticed by the marketing team.
🎫 [DOC-1417](https://spectrocloud.atlassian.net/browse/DOC-1417)
[DOC-1417]: https://spectrocloud.atlassian.net/browse/DOC-1417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: remove free-tier mention

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR fixes the backport issues for PR #4220
> [version-4-2] docs: remove free-tier mention (#4220)

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
- docs/docs-content/clusters/edge/local-ui/host-management/theming.md
- docs/docs-content/clusters/edge/networking/connect-wifi.md
- docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR fixes the backport issues from PR #4220
> [version-4-3] docs: remove free-tier mention (#4220)

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR fixes the backport issues for PR #4220
> [version-4-1] docs: remove free-tier mention (#4220)

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR fixes the backport issues for PR #4220
> [version-4-0] docs: remove free-tier mention (#4220)

- .github/workflows/api_format.yaml
This PR updates the API label GitHub Actions job. After testing the workflow in production, we learned that sub-folders are being ignored. The new changes specify a file pattern
> docs: fix api-label

- .github/workflows/api_format.yaml
This PR removes the reference to the target branch in the API format job.
> ci: fix api label job

- docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
- docs/docs-content/getting-started/aws/setup.md
This PR fixes an incorrect URL in the AWS Setup page for the Getting Started series.
💻 [Preview URL for Page](https://deploy-preview-4250--docs-spectrocloud.netlify.app/getting-started/aws/setup/)
🎫 [DOC-1421](https://spectrocloud.atlassian.net/browse/DOC-1421)
[DOC-1421]: https://spectrocloud.atlassian.net/browse/DOC-1421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DOC-1421

- docs/docs-content/getting-started/aws/setup.md
This PR addresses the backport issue for PR #4250
> [version-4-3] docs: DOC-1421  DOC-1420 (#4250)

- docs/docs-content/getting-started/aws/setup.md
This PR fixes the backport issues for PR #4250
> [version-4-2] docs: DOC-1421  DOC-1420 (#4250)

- docs/docs-content/getting-started/aws/setup.md
This PR fixes the backport issues from PR #4250
> [version-4-1] docs: DOC-1421  DOC-1420 (#4250)

- docs/docs-content/getting-started/aws/setup.md
This PR fixes the backport issues for PR #4250
> [version-4-0] docs: DOC-1421  DOC-1420 (#4250)

- docs/docs-content/getting-started/aws/setup.md
This PR fixes the backport issues for PR #4250
> [version-3-4] docs: DOC-1421  DOC-1420 (#4250)

- docs/docs-content/clusters/edge/local-ui/host-management/theming.md
This PR removes an extra return character. 
> docs: fix extra return char

- docs/docs-content/spectro-downloads.md
> docs: update spectro-downloads.md

- README.md
- src/components/PaletteVertexUrlMapper/PaletteVertexUrlMapper.tsx
This PR backports PR #4305 from master to version-3-4.
> [version-3-4] docs: update url mapper component (#4305)

- .github/workflows/versions_robot.yaml
- scripts/noindex_docusaurus_config.js
- scripts/update_docusarus_config.js
This PR adds logic to ensure version branches get the `noIndex` attribute configured automatically and a robots.txt file.
🎫 [DOC-1426](https://spectrocloud.atlassian.net/jira/software/c/projects/DOC/boards/62?selectedIssue=DOC-1426)
[DOC-1426]: https://spectrocloud.atlassian.net/browse/DOC-1426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version Branches Automation Improvements

- .github/workflows/versions_robot.yaml
This PR adds logic to ensure version branches have the correct robots.txt content.
> Version Branches Robots.txt Update

- .github/workflows/aloglia_crawler.yaml
- .github/workflows/api_format.yaml
- .github/workflows/backport.yaml
- .github/workflows/container-prune.yaml
- .github/workflows/packs-data.yaml
- .github/workflows/release-preview.yaml
- .github/workflows/versions_robot.yaml
This PR fixes the issue that is causing backport slack messages to not include the message. This is caused by an upstream [issue](https://github.com/rtCamp/action-slack-notify/issues/203).
This PR also ensures the docs-latest site has a robot.txt that disallows crawling. And that that noIndex attribute is set to `true` in the docusaurus.config.js file.
> Backports Message

- .github/workflows/versions_robot.yaml
This PR adds prettier to the robots.txt check CI workflow.  
> ci: add prettier to remove uneccessary triggers

- .github/workflows/versions_robot.yaml
- scripts/noindex_docusaurus_config.js
> Backport prettier update

- .github/workflows/versions_robot.yaml
- docusaurus.config.js
- netlify.toml
> Robots Txt Fix

- .github/workflows/versions_robot.yaml
- docusaurus.config.js
- netlify.toml
- scripts/noindex_docusaurus_config.js
This PR fixes the backport issues from #4380
> [version-4-4] ci: Robots Txt Fix (#4380)

- .github/workflows/versions_robot.yaml
- docusaurus.config.js
- netlify.toml
- scripts/noindex_docusaurus_config.js
> [version-4-3] Backport/version 4 3/pr 4380

- .github/workflows/versions_robot.yaml
- docusaurus.config.js
- netlify.toml
- scripts/noindex_docusaurus_config.js
> [version-4-2] ci: Robots Txt Fix (#4380)

- .github/workflows/versions_robot.yaml
- docusaurus.config.js
- netlify.toml
- scripts/noindex_docusaurus_config.js
> [version-4-1] ci: Robots Txt Fix (#4380)

- .github/workflows/versions_robot.yaml
- docusaurus.config.js
- netlify.toml
- scripts/noindex_docusaurus_config.js
> [version-3-4] ci: Robots Txt Fix (#4380)

- .github/workflows/versions_robot.yaml
- docusaurus.config.js
- netlify.toml
- scripts/noindex_docusaurus_config.js
> [version-4-0] ci: Robots Txt Fix (#4380)

- package-lock.json
- package.json
This PR fixes the backport issues from PR #4388
> [version-4-1] ci: remove package.json prepare (#4388)

- package-lock.json
- package.json
This PR fixes the backport issues from PR #4388
> [version-4-0] ci: remove package.json prepare (#4388)

- package-lock.json
- package.json
This PR fixes backport issues from PR #4388
> [version-3-4] ci: remove package.json prepare (#4388)

- .github/workflows/release-preview.yaml
- .github/workflows/release.yaml
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
This PR fixes the release branch CI actions job. Other changes including fixing incorrect URLs used for the image-swap registry.
> Registry URLs Fixes

- .github/workflows/release-preview.yaml
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
This PR fixes the backport issues from PR #4411
> [version-4-1] ci: registry URLs Fixes (#4411)

- .github/workflows/release-preview.yaml
This PR fixes the backport issues from PR #4411
> [version-3-4] ci: registry URLs Fixes (#4411)

- .github/workflows/release-preview.yaml
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
This PR fixes the backport issue from PR #4411
> [version-4-0] ci: registry URLs Fixes (#4411)

- docs/api-content/api-docs/edge-v1/emc-api.json
This PR updates the Edge management API for release 4.5.5
> docs: update edge managament api for 4.5.5

- docs/deprecated/clusters/public-cloud/azure/required-permissions.md
- docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
- docs/docs-content/clusters/public-cloud/azure/required-permissions.md
This PR fixes the backport issues from PR #4272
> [version-4-3] docs: DOC-928 DOC-929 DOC-930 DOC-931 DOC-927  (#4272)

- docs/deprecated/clusters/public-cloud/azure/required-permissions.md
- docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
- docs/docs-content/clusters/public-cloud/azure/required-permissions.md
This PR fixes the backport issue from PR #4272
> [version-4-1] docs: DOC-928 DOC-929 DOC-930 DOC-931 DOC-927  (#4272)

- docs/deprecated/clusters/public-cloud/azure/required-permissions.md
- docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
- docs/docs-content/clusters/public-cloud/azure/required-permissions.md
This PR fixes the issues with PR #4272
> [version-4-2] docs: DOC-928 DOC-929 DOC-930 DOC-931 DOC-927  (#4272)

- docs/deprecated/clusters/public-cloud/azure/required-permissions.md
- docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
- docs/docs-content/clusters/public-cloud/azure/required-permissions.md
This PR fixes the backport issues from PR #4272
> [version-4-0] docs: DOC-928 DOC-929 DOC-930 DOC-931 DOC-927  (#4272)

- docs/deprecated/clusters/public-cloud/azure/required-permissions.md
- docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
- docs/docs-content/clusters/public-cloud/azure/required-permissions.md
This PR fixes the backport issues from PR #4272
> [version-3-4] docs: DOC-928 DOC-929 DOC-930 DOC-931 DOC-927  (#4272)

- docs/docs-content/clusters/public-cloud/azure/required-permissions.md
This PR fixes the backport issues from PR #4513
> [version-4-2] docs:  small fixes for Azure v2 docs (#4513)

- docs/docs-content/clusters/public-cloud/azure/required-permissions.md
- docs/docs-content/security-bulletins/reports/cve-2022-2879.md
- docs/docs-content/security-bulletins/reports/cve-2022-2880.md
- docs/docs-content/security-bulletins/reports/cve-2022-41716.md
- docs/docs-content/security-bulletins/reports/cve-2022-41720.md
- docs/docs-content/security-bulletins/reports/cve-2022-41722.md
- docs/docs-content/security-bulletins/reports/cve-2023-29402.md
- docs/docs-content/security-bulletins/reports/cve-2023-29404.md
- docs/docs-content/security-bulletins/reports/cve-2023-29405.md
- docs/docs-content/security-bulletins/reports/cve-2023-39323.md
- docs/docs-content/security-bulletins/reports/cve-2023-45283.md
- docs/docs-content/security-bulletins/reports/cve-2023-45285.md
- docs/docs-content/security-bulletins/reports/cve-2023-46129.md
- docs/docs-content/security-bulletins/reports/cve-2024-8260.md
This PR fixes the backport issues from PR #4513
> [version-4-3] docs:  small fixes for Azure v2 docs (#4513)

- docs/docs-content/clusters/public-cloud/azure/required-permissions.md
This PR fixes the backport issues from PR #4513
> [version-3-4]docs:  small fixes for Azure v2 docs (#4513)

- docs/docs-content/clusters/public-cloud/azure/required-permissions.md
This PR fixes the backport issues from PR #4513
> [version-4-0] docs:  small fixes for Azure v2 docs (#4513)

- docs/docs-content/clusters/public-cloud/azure/required-permissions.md
Similar to https://github.com/spectrocloud/librarium/pull/4513. Noticed a small issue that needs to be fixed while browsing the docs.
> docs: small fix for Azure v2 docs

- docs/docs-content/clusters/cluster-management/cluster-tag-filter/create-add-filter.md
- docs/docs-content/workspace/adding-a-new-workspace.md
This PR fixes some issues that were reported by a reader.
🎫 [DOC-1462](https://spectrocloud.atlassian.net/browse/DOC-1462)
🎫 [DOC-1463](https://spectrocloud.atlassian.net/browse/DOC-1463)
[DOC-1462]: https://spectrocloud.atlassian.net/browse/DOC-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1463]: https://spectrocloud.atlassian.net/browse/DOC-1463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Docs Feedback

- docs/docs-content/clusters/cluster-management/cluster-tag-filter/create-add-filter.md
- docs/docs-content/workspace/adding-a-new-workspace.md
This PR fixes the backport issues from PR #4567
> [version-4-1] docs: DOC-1462 DOC-1463 Docs Feedback (#4567)

- docs/docs-content/clusters/cluster-management/cluster-tag-filter/create-add-filter.md
- docs/docs-content/workspace/adding-a-new-workspace.md
This PR fixes the backport issues from PR #4567
> [version-4-2] docs: DOC-1462 DOC-1463 Docs Feedback (#4567)

- docs/docs-content/clusters/cluster-management/cluster-tag-filter/create-add-filter.md
- docs/docs-content/workspace/adding-a-new-workspace.md
This PR fixes the backport issues from PR #4567
> [version-3-4] docs: DOC-1462 DOC-1463 Docs Feedback (#4567)

- docs/docs-content/clusters/public-cloud/azure/azure-disk-encryption.md
- docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
Documentation for the new Azure Disk Encryption support using Disk Encryption Sets with customer-managed keys.
Only available to Azure IaaS for 4.5.a.
💻 [Azure Disk Encryption](https://deploy-preview-4558--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/azure-disk-encryption/)
🎫 [PCP-3720](https://spectrocloud.atlassian.net/browse/PCP-3720)
🎫 [PCP-3735](https://spectrocloud.atlassian.net/browse/PCP-3735)
4.5.a release ticket.
[PCP-3720]: https://spectrocloud.atlassian.net/browse/PCP-3720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PCP-3735]: https://spectrocloud.atlassian.net/browse/PCP-3735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: Azure Disk Encryption (PCP-3720 & PCP-3735)

- docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
This PR fixes a YAML indentation issue. This PR addresses the issue PR #4612 raised.
💻 [Preview URL for Page](https://deploy-preview-4613--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/prepare-user-data/)
> docs: fixes YAML issue

- docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/local-registry.md
- docs/docs-content/integrations/harbor-edge-native-config.md
This PR adds the instructions to add an additional project to the harbor registry. 
🎫 [PE-5063](https://spectrocloud.atlassian.net/browse/PE-5063)
[PE-5063]: https://spectrocloud.atlassian.net/browse/PE-5063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: PE-5063

- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/palette-helm-ref.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
Reverts spectrocloud/librarium#4640
> Revert "docs: PLT-1467 image pull secret"

- docs/docs-content/enterprise-version/upgrade/upgrade.md
- docs/docs-content/vertex/upgrade/upgrade.md
This PR removes an incorrect upgrade path that was identified as unsupported.  Other changes include improving the page description, making the requirement to upgrade to latest patch version a danger admonition so it's less likely to be missed.
> docs: update upgrade paths

- redirects.js
This PR adds a redirect for the ngrok pack's former integration page. 
> chore: add ngrok

- docs/docs-content/clusters/edge/site-deployment/site-installation/edge-host-registration.md
This PR removes the Vercel link that others can claim. 
> docs: remove vercel link

- .github/actions/build-cached-packs/action.yaml
- .github/workflows/nightly-docker-build.yaml
- .github/workflows/post_release.yaml
- .github/workflows/pull_request.yaml
- .github/workflows/release-branch-pr.yaml
- .github/workflows/release-preview.yaml
- .github/workflows/release.yaml
- .github/workflows/screenshot_capture.yaml
- .github/workflows/visual-comparison.yaml
- Makefile
- README.md
- plugins/packs-integrations.js
- scripts/get-cached-packs.sh
- [docs: add packs caching solution DOC-1460 (#4632)](https://github.com/spectrocloud/librarium/pull/4632)
> [version-4-2] docs: add packs caching solution DOC-1460 (#4632)

- .github/actions/build-cached-packs/action.yaml
- .github/workflows/nightly-docker-build.yaml
- .github/workflows/post_release.yaml
- .github/workflows/pull_request.yaml
- .github/workflows/release-branch-pr.yaml
- .github/workflows/release-preview.yaml
- .github/workflows/release.yaml
- .github/workflows/screenshot_capture.yaml
- .github/workflows/visual-comparison.yaml
- Makefile
- README.md
- plugins/packs-integrations.js
- scripts/get-cached-packs.sh
- [docs: add packs caching solution DOC-1460 (#4632)](https://github.com/spectrocloud/librarium/pull/4632)
> [version-3-4] docs: add packs caching solution DOC-1460 (#4632)

- docs/docs-content/release-notes/release-notes.md
This PR adds the release notes for 4.5.11. 
💻 [Release Notes](https://deploy-preview-4734--docs-spectrocloud.netlify.app/release-notes/)
🎫 [DOC-1486](https://spectrocloud.atlassian.net/browse/DOC-1486)
[DOC-1486]: https://spectrocloud.atlassian.net/browse/DOC-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add release notes for release 4.5.11 DOC-1486

- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
This PR removes a Jira link from the self-hosted Palette installation guide.
💻 [Add Preview URL for Page](https://deploy-preview-4843--docs-spectrocloud.netlify.app/)
> docs: Update install.md

- docs/docs-content/clusters/edge/edgeforge-workflow/build-content-bundle.md
> docs: backport #4888

- utils/cves/index.js
This PR adds pagination support for the internal security API endpoint
💻 [Preview URL for Page](https://deploy-preview-4897--docs-spectrocloud.netlify.app/security-bulletins/reports/#palette)
🎫 [DOC-1501](https://spectrocloud.atlassian.net/browse/DOC-1501)
[DOC-1501]: https://spectrocloud.atlassian.net/browse/DOC-1501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: security pagination support

- docs/docs-content/getting-started/introduction.md
This PR adjusts the relative path to make the buttons on the Introduction Page work. 
> docs: adjust broken links on GS Introduction page

- _partials/self-hosted/_cloud-provider-config.mdx
This PR updates the payload to the system cloud provider API. 
💻 [Palette](https://deploy-preview-4963--docs-spectrocloud.netlify.app/enterprise-version/system-management/change-cloud-config/)
💻 [VerteX](https://deploy-preview-4963--docs-spectrocloud.netlify.app/vertex/system-management/change-cloud-config/)
> docs: updated payload

- docs/docs-content/clusters/edge/local-ui/cluster-management/delete-cluster.md
- docs/docs-content/clusters/edge/local-ui/cluster-management/link-hosts.md
- docs/docs-content/clusters/edge/local-ui/cluster-management/scale-cluster.md
This PR updates terminology from nodes to hosts for linked hosts that are not part of a cluster. 
> docs: change node to host

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR fixes an outdated flag from the Palette CLI that changed a few releases ago. 
> Update CLI flag cmd in tooltip

- docs/docs-content/automation/palette-cli/palette-cli.md
- docs/docs-content/enterprise-version/upgrade/upgrade-notes.md
- docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
- docs/docs-content/enterprise-version/upgrade/upgrade-vmware/non-airgap.md
- docs/docs-content/troubleshooting/enterprise-install.md
- docs/docs-content/vertex/upgrade/upgrade-vmware/airgap.md
- docs/docs-content/vertex/upgrade/upgrade-vmware/non-airgap.md
> docs: backport/version-4-1/pr-4967

- docs/docs-content/automation/palette-cli/palette-cli.md
- docs/docs-content/enterprise-version/upgrade/upgrade-notes.md
- docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
- docs/docs-content/enterprise-version/upgrade/upgrade-vmware/non-airgap.md
- docs/docs-content/troubleshooting/enterprise-install.md
- docs/docs-content/vertex/upgrade/upgrade-vmware/airgap.md
- docs/docs-content/vertex/upgrade/upgrade-vmware/non-airgap.md
> docs: backport/version-4-0/pr-4967

- docs/docs-content/automation/palette-cli/palette-cli.md
> docs: backport/version 3 4/pr 4967

- docs/api-content/api-docs/edge-v1/emc-api.json
This PR updates the Edge API for the 4.5.b release.
🎫 [DOC-1514](https://spectrocloud.atlassian.net/browse/DOC-1514)
[DOC-1514]: https://spectrocloud.atlassian.net/browse/DOC-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Edge API Update

- docs/docs-content/integrations/harbor-edge-native-config.md
This PR removes duplicate content in the Edge Harbor Pack.
💻 [Preview URL for Page](https://deploy-preview-5003--docs-spectrocloud.netlify.app/integrations/packs/?pack=harbor-edge-native-config&version=1.1.2&parent=1.1.x&tab=custom)
🎫 [DOC-1505](https://spectrocloud.atlassian.net/browse/DOC-1505)
[DOC-1505]: https://spectrocloud.atlassian.net/browse/DOC-1505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DOC-1505

- docs/api-content/api-docs/edge-v1/emc-api.json
- docs/docs-content/clusters/edge/cluster-management/skip-draining.md
This PR updates the node draining low memory warning. 
🎫 [PE-5672](https://spectrocloud.atlassian.net/browse/PE-5672?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-113797)
[PE-5672]: https://spectrocloud.atlassian.net/browse/PE-5672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: node drain edit

- docs/docs-content/clusters/public-cloud/azure/aks.md
This PR adds an additional step for disabling local accounts on the AKS cluster.
It also corrects the ordering of the **Deploy an Azure AKS Cluster** steps by moving one of the steps to an earlier stage.
💻 [Create and Manage Azure AKS Cluster](https://deploy-preview-5035--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/aks/#deploy-an-azure-aks-cluster)
🎫 [PCP-1889](https://spectrocloud.atlassian.net/browse/PCP-1889)
[PCP-1889]: https://spectrocloud.atlassian.net/browse/PCP-1889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PCP-1889: add disableLocalAccounts method and correct order of steps

- _partials/self-hosted/_kubernetes_palette_versions.mdx
- _partials/self-hosted/_setup-steps.mdx
- docs/docs-content/clusters/pcg/deploy-pcg-k8s.md
- docs/docs-content/clusters/pcg/pcg.md
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/env-setup-vm.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
- docs/docs-content/enterprise-version/install-palette/install-palette.md
- docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md
- docs/docs-content/enterprise-version/upgrade/upgrade-k8s/non-airgap.md
- docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
- docs/docs-content/enterprise-version/upgrade/upgrade-vmware/non-airgap.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/env-setup-vm-vertex.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
- docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
This PR adds Kubernetes requirements tables for self-hosted, vertex and PCG install pages.
💻 [Self-Hosted Palette](https://deploy-preview-5056--docs-spectrocloud.netlify.app/enterprise-version/install-palette/#kubernetes-requirements)
💻 [Palette Vertex](https://deploy-preview-5056--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/#kubernetes-requirements)
💻 [PCG](https://deploy-preview-5056--docs-spectrocloud.netlify.app/clusters/pcg/#kubernetes-requirements)
🎫 [DOC-1519](https://spectrocloud.atlassian.net/browse/DOC-1519)
Can be backported to 4.5
[DOC-1519]: https://spectrocloud.atlassian.net/browse/DOC-1519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add kubernetes requirements to self-hosted, vertex and pcg DOC-1519

- _partials/self-hosted/_kubernetes_palette_versions.mdx
- _partials/self-hosted/_setup-steps.mdx
- docs/docs-content/clusters/pcg/deploy-pcg-k8s.md
- docs/docs-content/clusters/pcg/pcg.md
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/env-setup-vm.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
- docs/docs-content/enterprise-version/install-palette/install-palette.md
- docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md
- docs/docs-content/enterprise-version/upgrade/upgrade-k8s/non-airgap.md
- docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md
- docs/docs-content/enterprise-version/upgrade/upgrade-vmware/non-airgap.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/env-setup-vm-vertex.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
- docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
…1519 (#5056)
* docs: add kubernetes requirements to self-hosted, vertex and pcg DOC-1519
* docs: add links to requirements in install guides
This PR ....
> [version-4-2]docs: Backport/version 4 2/pr 5056

- docs/docs-content/release-notes/annoucements.md
This PR removes a duplicate row from the Announcements table. The duplicate entry was also breaking the table.
💻 [Announcements](https://deploy-preview-5076--docs-spectrocloud.netlify.app/release-notes/annoucements/)
> docs: remove duplicate entry

- _partials/self-hosted/_kubernetes_palette_versions.mdx
This PR adds a new entry to the Kubernetes/Self-hosted requirement table . 
💻 [Preview URL for Page](https://deploy-preview-5079--docs-spectrocloud.netlify.app/enterprise-version/install-palette/#kubernetes-requirements)
> docs: added missing k8s version for 4.5.15

- docs/docs-content/release-notes/annoucements.md
- docs/docs-content/release-notes/release-notes.md
This PR adds the PE-5567 fix to release notes. 
> docs: add PE-5567 to release notes

- docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
This PR fixes the backport issues from PR #5084
> [version-3-4] docs: DOC-1528 (#5084)

- docs/docs-content/clusters/cluster-management/cluster-updates.md
- docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
- docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/webhook-disable.md
This PR fixes three broken links. 
💻 [Update a Cluster](https://deploy-preview-5155--docs-spectrocloud.netlify.app/clusters/cluster-management/cluster-updates)
💻 [Disable Webhook to Customize Image Pull Behavior](https://deploy-preview-5155--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/deploy-custom-registries/webhook-disable)
💻 [Create and Manage MAAS Clusters](https://deploy-preview-5155--docs-spectrocloud.netlify.app/clusters/data-center/maas/create-manage-maas-clusters)
🎫 [DOC-1532](https://spectrocloud.atlassian.net/browse/DOC-1532)
[DOC-1532]: https://spectrocloud.atlassian.net/browse/DOC-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: fix up broken links DOC-1532

- docs/docs-content/getting-started/aws/aws.md
- docs/docs-content/getting-started/azure/azure.md
- docs/docs-content/getting-started/gcp/gcp.md
- docs/docs-content/getting-started/vmware/vmware.md
This PR fixes a grammar error reported in the Getting Started intro pages.
🎫 [DOC-1548](https://spectrocloud.atlassian.net/browse/DOC-1548)
[DOC-1548]: https://spectrocloud.atlassian.net/browse/DOC-1548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DOC-1548

- docs/api-content/api-docs/2-samples.md
This PR fixes invalid shell commands for the sample code and adds information on valid values for the cloud provider parameter. These errors were discovered by a prospective customer.
💻 [Preview URL for Page](https://deploy-preview-5220--docs-spectrocloud.netlify.app/api/samples/)
None.
> Fix sample shell commands

- docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md
This PR updates a request from the field that corrects a minor mistake.
🎫 [DOC-1574](https://spectrocloud.atlassian.net/browse/DOC-1574)
[DOC-1574]: https://spectrocloud.atlassian.net/browse/DOC-1574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DOC-1574 Update palette-sso-with-entra-id.md

- docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/eks-hybrid-nodes.md
This PR adds the tech preview admonition to the EKS Hybrid docs index page.
4.5.c release ticket.
> docs: mark EKS Hybrid as tech preview

- docs/api-content/api-docs/v1/api.json
This PR updates the API spec and removes Tencent endpoints.
> Palette 4.5 - Hide Tencent & Tke APIs

- static/packs-data/exclude_packs.json
This PR disables the VMO pack due to some upstream issues.
> chore: disable vmo pack

- docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md
- docs/docs-content/vertex/system-management/ssl-certificate-management.md
This PR fixes the backport issues from PR #5377
> [version-4-2] docs: PEM-6276 updated DNS and certificate prereqs (#5377)

- docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md
- docs/docs-content/vertex/system-management/ssl-certificate-management.md
This PR fixes the backport issues from PR #5377
> [version-4-1] docs: PEM-6276 updated DNS and certificate prereqs (#5377)

- docs/api-content/api-docs/edge-v1/emc-api.json
This PR updates the 4.5.c edge management API
> docs: update Edge mgmt api 4.5.c

- docs/docs-content/release-notes/release-notes.md
This PR changes 4.5.15 release notes by changing `airgaped` to `airgapped`.
> fix: spelling

- docs/docs-content/release-notes/release-notes.md
This PR adds a release not for the 4.4.21 patch release.
🎫 [DOC-1596](https://spectrocloud.atlassian.net/browse/DOC-1596)
No - We are targeting the version branch directly.
[DOC-1596]: https://spectrocloud.atlassian.net/browse/DOC-1596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 4.4.21 Patch Note

- package-lock.json
- package.json
This PR aims to address duplicate React context that may have contributed to the 1/15/25 outage.  Actions take:
- Issued `npm ddp` to remove duplicates.
- Removed `jest-config-docusaurus` from `package.json`. It's outdated and not needed.
- Issued `npm test` to verify test suit completed successfully. 
> Remove Dependency Duplication

- docs/docs-content/release-notes/release-notes.md
This PR fixes a small typo in the release notes. 
> docs: fix typo release notes

- docs/docs-content/vm-management/rbac/configure_OIDC.md
- docs/docs-content/vm-management/rbac/rbac.md
This PR adds extra steps to the VMO OIDC guide and refactors it to accommodate the changes.
💻 [Configure OIDC](https://deploy-preview-5481--docs-spectrocloud.netlify.app/vm-management/rbac/configure_OIDC/)
🎫 [DOC-1602](https://spectrocloud.atlassian.net/browse/DOC-1602)
[DOC-1602]: https://spectrocloud.atlassian.net/browse/DOC-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add extra VMO oidc configuration and refactor guide

- docs/docs-content/devx/services/service-listings/redis-db.md
This PR fixes a broken Redis link and some numbered step indentation.
💻 [Redis](https://deploy-preview-5485--docs-spectrocloud.netlify.app/devx/services/service-listings/redis-db/)
> docs: fix redis link and indentation

- docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
This PR updates the requirements for Agent mode and adds additional clarification. 
💻 [Preview URL for Page](https://deploy-preview-5576--docs-spectrocloud.netlify.app/deployment-modes/agent-mode/install-agent-host/)
> docs: added clarification related to agent-modfe

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/checklist.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
This PR backports PR #5564 from master to version-4-2.
> [version-4-2] docs: fix third-party references in self-hosted airgap guides (#5564)

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/checklist.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
This PR backports PR #5564 from master to version-4-1.
> [version-4-1] docs: fix third-party references in self-hosted airgap guides (#5564)

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/checklist.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
This PR backports PR #5564 from master to version-4-3.
> [version-4-3] docs: fix third-party references in self-hosted airgap guides (#5564)

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/checklist.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
This PR backports PR #5564 from master to version-4-0.
> [version-4-0] docs: fix third-party references in self-hosted airgap guides (#5564)

- docs/docs-content/tutorials/profiles/deploy-pack.md
This PR backports PR #5633 from master to version 4-1.
> [version-4-1] docs: add oci recommendation (#5633)

- docs/docs-content/tutorials/profiles/deploy-pack.md
This PR backports PR #5633 from master to version 4-0.
> [version-4-0] docs: add oci recommendation (#5633)

- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
This PR addresses Appzi feedback about self-hosted installations.
💻 [Install Palette](https://deploy-preview-5669--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/airgap-install/install/)
💻 [Install VerteX](https://deploy-preview-5669--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/airgap-install/install/)
🎫 [DOC-1657](https://spectrocloud.atlassian.net/browse/DOC-1657)
[DOC-1657]: https://spectrocloud.atlassian.net/browse/DOC-1657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add extra sentence, fix command

- docs/docs-content/clusters/public-cloud/aws/architecture.md
- docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/architecture.md
This PR makes a minor description change for the EKS architecture and Palette agent.
💻 [Worker Node Requirements](https://deploy-preview-5689--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/architecture/#worker-node-requirements)
💻 [Amazon EKS Cluster Requirements](https://deploy-preview-5689--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks-hybrid-nodes/architecture/#amazon-eks-cluster-requirements)
> docs: minor EKS description change

- docs/api-content/api-docs/v1/api.json
> Palette 4.6.0 API docs

- .github/workflows/release-preview.yaml
This PR changes the branch matching from `release-preview.yaml` to match `release-branch-pr.yaml`.  This will only match the actual release branch, as opposed to anything that starts with the word `release-`. 
No user facing changes.
No ticket.
> docs: update the release preview workflow to more specific branch matching

- docs/api-content/api-docs/v1/api.json
> DOC-1687 - Added description to the oidc syncSsoTeams field

- docs/docs-content/release-notes/release-notes.md
This PR adds the release notes for latest patch 4.5.22 
💻 [Release Notes](https://deploy-preview-5720--docs-spectrocloud.netlify.app/release-notes/)
🎫 [DOC-1692](https://spectrocloud.atlassian.net/browse/DOC-1692)
4.5
[DOC-1692]: https://spectrocloud.atlassian.net/browse/DOC-1692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add notes for patch 4.5.22 DOC-1692

- archiveVersions.json
- scripts/versions.sh
This PR moves `version-4-4` to legacy, as we are releasing 4.6. 
No ticket.
> docs: move branch 4.4 to legacy

- docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables/create-cluster-profile-variables.md
This PR fixes a broken link to getting started.
> docs: fix broken link to Getting Started

- docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
- docs/docs-content/clusters/data-center/maas/register-manage-maas-cloud-accounts.md
This PR fixes some broken links relating to MAAS documentation.
> docs: fix broken MAAS doc links

- docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/prepare-environment/prepare-eks-cluster.md
This PR removes a duplicate step and cleans up some existing steps on the new Prepare EKS Cluster page.
💻 [Prepare EKS Cluster](https://deploy-preview-5769--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks-hybrid-nodes/prepare-environment/prepare-eks-cluster/#create-the-eks-cluster)
🎫 [DOC-1652](https://spectrocloud.atlassian.net/browse/DOC-1652)
[DOC-1652]: https://spectrocloud.atlassian.net/browse/DOC-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: fix some steps in prepare EKS cluster

- static/packs-data/exclude_packs.json
This PR removes the vmo pack from the pack exclusions list.
💻 [VMO pack](https://deploy-preview-5781--docs-spectrocloud.netlify.app/integrations/packs/?pack=virtual-machine-orchestrator&version=4.6.1&parent=4.6.x&tab=main)
No ticket.
All versions
> docs: remove vmo pack from exclusion list

- docs/docs-content/release-notes/release-notes.md
This PR adds release notes for the 4.6.7 patch.
🎫 [DOC-1697](https://spectrocloud.atlassian.net/browse/DOC-1697)
To 4.6
[DOC-1697]: https://spectrocloud.atlassian.net/browse/DOC-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add patch 4.6.7 release notes DOC-1697

- docs/docs-content/clusters/edge/architecture/two-node.md
- docs/docs-content/clusters/edge/networking/vxlan-overlay.md
- docs/docs-content/clusters/edge/site-deployment/cluster-deployment.md
- docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
* docs: add harbor limitation for arm
* Update docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
* docs: update limitation
---------
This PR ....
> docs: add harbor limitation for arm (#5735)

- utils/cves/index.js
This PR updates the CVE table filter to use should publish instead of filtering by severity. 
> chore: update cve filter

- docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
- docs/docs-content/clusters/pcg/deploy-pcg/maas.md
This PR fixes some more broken links relating to MAAS documentation.
> docs: fix newly broken MAAS doc links

- docs/docs-content/vm-management/vm-migration-assistant/create-source-providers.md
This PR adds a limitation regarding OVA imports for the VM Migration Assistant. We already call this out in the steps, but adding to Limitations to make it clear from the beginning.
> docs: add limitation to VM Migration Assistant for OVAs

- docs/docs-content/release-notes/release-notes.md
This PR adds the release notes for 4.6.9
💻 [Release Notes](https://deploy-preview-5933--docs-spectrocloud.netlify.app/release-notes/)
🎫 [DOC-1713](https://spectrocloud.atlassian.net/browse/DOC-1713)
Only to 4.6.
[DOC-1713]: https://spectrocloud.atlassian.net/browse/DOC-1713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add release notes for 4.6.9 DOC-1713

- docusaurus.config.js
> chore: try kapa fix

- docs/docs-content/clusters/pcg/deploy-pcg/maas.md
This PR removes duplicated section from Maas PCG prereqs. The rest of the file has been formatted, with no other changes.
💻 [Prerequisites](https://deploy-preview-6002--docs-spectrocloud.netlify.app/clusters/pcg/deploy-pcg/maas/#prerequisites)
🎫 [DOC-1702](https://spectrocloud.atlassian.net/browse/DOC-1702)
Everywhere
[DOC-1702]: https://spectrocloud.atlassian.net/browse/DOC-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: remove duplicated PCG IP address section DOC-1702

- docs/docs-content/clusters/pcg/deploy-pcg/maas.md
- [docs: remove duplicated PCG IP address section DOC-1702 (#6002)](https://github.com/spectrocloud/librarium/pull/6002)
> [version-4-4] docs: remove duplicated PCG IP address section DOC-1702 (#6002)

- docs/docs-content/clusters/pcg/deploy-pcg/maas.md
- [docs: remove duplicated PCG IP address section DOC-1702 (#6002)](https://github.com/spectrocloud/librarium/pull/6002)
> [version-4-3] docs: remove duplicated PCG IP address section DOC-1702 (#6002)

- docs/docs-content/clusters/pcg/deploy-pcg/maas.md
- [docs: remove duplicated PCG IP address section DOC-1702 (#6002)](https://github.com/spectrocloud/librarium/pull/6002)
> [version-4-1] docs: remove duplicated PCG IP address section DOC-1702 (#6002)

- docs/docs-content/clusters/pcg/deploy-pcg/maas.md
- [docs: remove duplicated PCG IP address section DOC-1702 (#6002)](https://github.com/spectrocloud/librarium/pull/6002)
> [version-4-0] docs: remove duplicated PCG IP address section DOC-1702 (#6002)

- docs/api-content/api-docs/2-samples.md
> fix: case sensitve uri argument ProjectUid

- docs/api-content/api-docs/v1/api.json
> Palette 4.6.a API docs

- .gitleaksignore
This PR adds failing fingerprints to gitleaksignore.
No ticket.
> docs: change gitleaksignore for release branch

- docs/api-content/api-docs/edge-v1/emc-api.json
This PR adds Edge management API for 4.6.a. 
> docs: Add Edge mgmt API for 4.6.a

- .github/workflows/clean-up-unused-images.yaml
- scripts/find-unused-images.sh
This PR backports PR #6040 from master to version-4-1.
> [version-4-1] docs: debug unused images pipeline (#6040)

- _partials/self-hosted/_aws-sts-config.mdx
This PR adjusts the STS endpoint and login command.
💻 [STS](https://deploy-preview-6132--docs-spectrocloud.netlify.app/enterprise-version/system-management/configure-aws-sts-account/)
🎫 [DOC-1751](https://spectrocloud.atlassian.net/browse/DOC-1751)
[DOC-1751]: https://spectrocloud.atlassian.net/browse/DOC-1751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: adjust STS pages DOC-1751

- docs/docs-content/registries-and-packs/spectro-cli-reference.md
This PR updates the `spectro-cli` version.
💻 [Spectro CLI](https://deploy-preview-6202--docs-spectrocloud.netlify.app/registries-and-packs/spectro-cli-reference/)
🎫 [DOC-1766](https://spectrocloud.atlassian.net/browse/DOC-1766)
[DOC-1766]: https://spectrocloud.atlassian.net/browse/DOC-1766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: update spectro cli version

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR backports Edge tutorial changes from [docs: Edge Tutorial Updates (#6207)](https://github.com/spectrocloud/librarium/pull/6207) to version 4.2.
> [version-4-2] docs: backport/version-4-2/pr-6207

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR backports Edge tutorial changes from [docs: Edge Tutorial Updates (#6207)](https://github.com/spectrocloud/librarium/pull/6207) to version 4.1.
> [version-4-1] docs: backport/version-4-1/pr-6207 

- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR backports Edge tutorial changes from [docs: Edge Tutorial Updates (#6207)](https://github.com/spectrocloud/librarium/pull/6207) to version 4.0.
> [version-4-0] docs: backport/version-4-0/pr-6207 

- docs/docs-content/security-bulletins/security-advisories/security-advisories.md
- docs/docs-content/security-bulletins/security-bulletins.md
This PR adds a security advisory page for the recent Nginx-related CVEs, providing additional details and offering remediation steps. 
💻 [Security Advisories](https://deploy-preview-6235--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
🎫 [DOC-1773](https://spectrocloud.atlassian.net/browse/DOC-1773)
[DOC-1773]: https://spectrocloud.atlassian.net/browse/DOC-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DOC-1773: Nginx Security Advisory

- docs/docs-content/security-bulletins/security-advisories/security-advisories.md
> docs: update cves links

- docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR adds links to the CVE advisories for nginx 
> docs: add direct links

- docs/docs-content/release-notes/release-notes.md
- docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR adds release notes for version 4.6.18.
- [Release Notes](https://deploy-preview-6250--docs-spectrocloud.netlify.app/release-notes/)
- [Security Advisories](https://deploy-preview-6250--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
🎫 [DOC-1770](https://spectrocloud.atlassian.net/browse/DOC-1770) and [DOC-1781](https://spectrocloud.atlassian.net/browse/DOC-1781)
[DOC-1770]: https://spectrocloud.atlassian.net/browse/DOC-1770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1781]: https://spectrocloud.atlassian.net/browse/DOC-1781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DOC-1770: 4.6.18 Release Notes

- docs/docs-content/release-notes/release-notes.md
- docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR updates the release notes and security advisory for 4.5.
- [Release Notes](https://deploy-preview-6251--docs-spectrocloud.netlify.app/release-notes/)
- [Security Advisories](https://deploy-preview-6251--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
🎫 [DOC-1779](https://spectrocloud.atlassian.net/browse/DOC-1779) and [DOC-1781](https://spectrocloud.atlassian.net/browse/DOC-1781)
Release notes not friendly for backports.
[DOC-1779]: https://spectrocloud.atlassian.net/browse/DOC-1779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1781]: https://spectrocloud.atlassian.net/browse/DOC-1781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DOC-1779: 4.5 Release Notes - Security Advisory

- docs/docs-content/clusters/palette-virtual-clusters/palette-virtual-clusters.md
- docs/docs-content/devx/palette-virtual-clusters/palette-virtual-clusters.md
This PR makes a minor change to headings.
> doc: update to virtual clusters headings

- docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
- docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
This PR adds links to the application proxy settings for discoverability. 
> docs: add cross links for application proxy settings

- docs/docs-content/release-notes/release-notes.md
- docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR updates the release notes and security advisory with the latest Nginx updates.
- [Release Notes](https://deploy-preview-6310--docs-spectrocloud.netlify.app/release-notes/)
- [Security Advisories](https://deploy-preview-6310--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
Patch note backport shenanigans.
> docs: Nginx 4-3-25 Update (Version 4.5)

- docs/docs-content/release-notes/release-notes.md
- docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR updates the release notes and security advisory with the latest Nginx updates.
- [Release Notes](https://deploy-preview-6311--docs-spectrocloud.netlify.app/release-notes/)
- [Security Advisories](https://deploy-preview-6311--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
Patch note backport shenanigans.
> docs: Nginx 4-3-25 Update (Version 4.4)

- docs/api-content/api-docs/edge-v1/emc-api.json
This PR updates the Edge API for 4.6.b
🎫 [DOC-1796](https://spectrocloud.atlassian.net/browse/DOC-1796)
[DOC-1796]: https://spectrocloud.atlassian.net/browse/DOC-1796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: upload edge api file

- docs/docs-content/clusters/cluster-management/cluster-updates.md
This PR will backport changes from PR-6391 to version 4.1
- [ x] No. _Please leave a short comment below about why this PR cannot be backported._
> [version 4.1] docs: backport changes from pr-6391 for version 4-1

- docs/docs-content/clusters/cluster-management/cluster-updates.md
This PR backports changes from #6391  to version 4.0
- [ x] No. _Please leave a short comment below about why this PR cannot be backported._
> [version 4.0] docs: backport changes from pr-6391 for version 4-0

- docs/docs-content/clusters/edge/cluster-management/remote-shell.md
This PR adds a version constraint for remote shell. 
> docs: Remote sh version constraint

- docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
This PR fixes some indentation for a bullet point and details dropdown on the Install Agent Host page.
💻 [Install Palette Agent](https://deploy-preview-6447--docs-spectrocloud.netlify.app/deployment-modes/agent-mode/install-agent-host/#prerequisites)
> doc: fix indentation on Install Agent Host

- docs/docs-content/integrations/lb-metallb-helm.mdx
This PR adds a workaround to the metallb pack. 
💻 [Metallb Helm pack](https://deploy-preview-6478--docs-spectrocloud.netlify.app/integrations/packs/?pack=lb-metallb-helm)
🎫 [PAC-2733](https://spectrocloud.atlassian.net/browse/PAC-2733)
Release branch only.
[PAC-2733]: https://spectrocloud.atlassian.net/browse/PAC-2733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: update mettallb values.yaml PAC-2733

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
- docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
- docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/migrate-edge-native-config.md
This PR adds the additional stylus upgrade steps needed to migrate off harbor to byor. 
🎫 [PE-6539]()
[PE-6539]: https://spectrocloud.atlassian.net/browse/PE-6539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: PE-6539

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
This PR adds instructions on how to include content bundle in ISO if it was built by the Palette CLI. 
> docs: PE-6545

- _partials/self-hosted/_kubernetes_palette_versions.mdx
- docs/docs-content/automation/palette-cli/install-palette-cli.md
- docs/docs-content/clusters/pcg/pcg.md
- docs/docs-content/component.md
- docs/docs-content/release-notes/release-notes.md
- docs/docs-content/spectro-downloads.md
This PR  makes the release updates across various pages.
Spectro CLI and Spectro Registry are unchanged in this release.
🎫 [DOC-1792](https://spectrocloud.atlassian.net/browse/DOC-1792)
Release only.
[DOC-1792]: https://spectrocloud.atlassian.net/browse/DOC-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: make release updates across the various pages DOC-1792

- docs/docs-content/release-notes/release-notes.md
This PR adds bug fixes to 4.6.b release notes. 
> docs: add bug fixes

- docs/docs-content/clusters/public-cloud/aws/eks.md
This PR fixes a missing header in the EKS article.
> [version-4-2] doc: fix EKS header

- docs/docs-content/clusters/public-cloud/aws/eks.md
(cherry picked from commit b8b23838784d1c0eafdae94ab15c8c05c561f175)
This PR fixes a missing header in the EKS article.
> [version-4-1] doc: fix EKS header

- docs/docs-content/clusters/public-cloud/aws/eks.md
(cherry picked from commit b8b23838784d1c0eafdae94ab15c8c05c561f175)
This PR fixes a missing header in the EKS article.
> [version-4-0] doc: fix EKS header

- docs/docs-content/clusters/cluster-management/node-labels.md
This PR provides an accurate and more detailed explanation of the node label modification limitation.
💻 [Node Labels](https://deploy-preview-6538--docs-spectrocloud.netlify.app/clusters/cluster-management/node-labels/)
🎫 [PE-3218](https://spectrocloud.atlassian.net/browse/PE-3218)
[PE-3218]: https://spectrocloud.atlassian.net/browse/PE-3218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs:  fix node labels modification limitation

- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR adds `install.poweroff` parameter to the `user-data` file and removes PointsOfInterest markdown element.
💻 [Add Preview URL for Page](https://deploy-preview-6591--docs-spectrocloud.netlify.app/tutorials/edge/deploy-cluster/)
🎫 No Jira ticket.
> Fix user-data

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
- docs/docs-content/clusters/edge/site-deployment/site-installation/create-registration-token.md
- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR backports changes from #6595 to version 4.5.
💻 Not applicable
🎫 Not applicable
> [version-4-5] docs: fix warning and formatting (#6595)

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
- docs/docs-content/clusters/edge/site-deployment/site-installation/create-registration-token.md
- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR backports changes from #6595 to version 4.5.
💻 Not applicable
🎫 Not applicable
> Backport commit

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
- docs/docs-content/clusters/edge/site-deployment/site-installation/create-registration-token.md
- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR backports changes from #6595 to version 4.3.
💻 Not applicable 
🎫 Not applicable
> [version-4-3] docs: fix warning and formatting (#6595)

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- docs/docs-content/clusters/edge/site-deployment/site-installation/create-registration-token.md
- docs/docs-content/tutorials/edge/deploy-cluster.md
This PR backports changes from #6595 to version 4.2.
💻 Not applicable.
🎫  Not applicable.
> [version-4-2] docs: fix warning and formatting (#6595)

- docusaurus.config.js
This PR adds a consent screen for Kapa. 
💻 [Preview](https://deploy-preview-6603--docs-spectrocloud.netlify.app/)
🎫 [/DOC-1861](https://spectrocloud.atlassian.net/browse/DOC-1861)
> docs: add consent screen

- docs/docs-content/clusters/public-cloud/aws/eks.md
- docs/docs-content/release-notes/release-notes.md
This PR adds guidance for assigning AMIs to EKS cluster node pools. It also adds a release note.
🎫 [DOC-1858](https://spectrocloud.atlassian.net/browse/DOC-1858)
[DOC-1858]: https://spectrocloud.atlassian.net/browse/DOC-1858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> doc: Assign AMI to node pool for EKS clusters

- docs/docs-content/clusters/palette-virtual-clusters/migrate-virtual-clusters.md
This PR fixes the final spell check error in librarium
🎫 [DOC-1746](https://spectrocloud.atlassian.net/browse/DOC-1746)
Only to 4.6
[DOC-1746]: https://spectrocloud.atlassian.net/browse/DOC-1746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: fix final spellcheck error DOC-1746

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
- docs/docs-content/clusters/edge/trusted-boot/edgeforge/build-trusted-provider-image.md
> docs: correct the k8s version filename issue (#6653)

- scripts/ai_robots.txt
This PR removes useful bots from the block list. This was introduced in https://github.com/spectrocloud/librarium/pull/6418
No UI changes.
Backporting to all the places the original PR was merged to.
> docs: remove useful bots from block list

- docs/docs-content/registries-and-packs/add-custom-packs.md
- docs/docs-content/registries-and-packs/adding-add-on-packs.md
This PR adds the requirements that images must be specified in the `pack.content.images` list. 
🎫 [PE-6557](https://spectrocloud.atlassian.net/browse/PE-6557)
[PE-6557]: https://spectrocloud.atlassian.net/browse/PE-6557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add requirements of pack.content.images

- docs/docs-content/user-management/users-and-teams/create-a-team.md
This PR documents the **Description** field added to the team creation workflow.
💻 [Create and Manage a Team](https://deploy-preview-6727--docs-spectrocloud.netlify.app/user-management/users-and-teams/create-a-team/)
🎫 [DOC-1850](https://spectrocloud.atlassian.net/browse/DOC-1850)
[DOC-1850]: https://spectrocloud.atlassian.net/browse/DOC-1850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> doc: add Description field to the Team entity

- docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
- docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-primary-registry.md
This PR adds the note that we now allow additional ZST files to be uploaded. 
🎫 [DOC-1852](https://spectrocloud.atlassian.net/browse/DOC-1852?atlOrigin=eyJpIjoiOTljZDA0OTY5NDRhNDE4MDk5NTU3Y2QzZDgxMDZiYmIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[DOC-1852]: https://spectrocloud.atlassian.net/browse/DOC-1852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: allow additional uploads of ZST files

- docs/docs-content/clusters/edge/cluster-management/remote-shell.md
This PR adds a prerequisite for remote shell about sshd configurations. 
🎫 [DOC-1875](https://spectrocloud.atlassian.net/issues/DOC-1875?filter=11884)
[DOC-1875]: https://spectrocloud.atlassian.net/browse/DOC-1875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add ssh prereq

- docs/docs-content/clusters/edge/cluster-management/remote-shell.md
This PR adds a small correction to 1875
> docs: Small correction 1875

- docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/local-registry.md
This PR addresses a failed backport from [PR 6745](https://github.com/spectrocloud/librarium/pull/6745).
It is the backport.
> [version-4-5] docs: backport/version-4-5/pr-6745

- vale-spellcheck-ignore.txt
This PR adds a new ignore line for userinfo endpoint. 
_No userfacing changes._
No ticket. 
> docs: add spellcheck ignore for userinfo endpoint

- docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
This PR updates a code snippet that had wrong config.
💻 [Install Agent Host](https://deploy-preview-6803--docs-spectrocloud.netlify.app/deployment-modes/agent-mode/install-agent-host/)
🎫 [DOC-1883](https://spectrocloud.atlassian.net/browse/DOC-1883)
4.5 and 4.6
[DOC-1883]: https://spectrocloud.atlassian.net/browse/DOC-1883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: fix code snippet DOC-1883

- docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
This PR adds a limitation to the content bundle batch upload operation. 
> docs: PE 6747

- docs/docs-content/troubleshooting/edge/collect-support-bundles.md
This PR adds the information about the `support-bundle-edge.sh` script embedded since the 4.6.c version
💻 [Collect Support Bundles for Edge Cluster Troubleshooting](https://deploy-preview-6821--docs-spectrocloud.netlify.app/troubleshooting/edge/collect-support-bundles/)
🎫 [PE-6675](https://spectrocloud.atlassian.net/browse/PE-6675)
[PE-6675]: https://spectrocloud.atlassian.net/browse/PE-6675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add the information about the embedded script

- docs/api-content/api-docs/v1/api.json
> Palette 4.6.c API docs

- docs/api-content/api-docs/edge-v1/emc-api.json
This PR adds the 4.6.c Edge mgmt api
> docs: 4.6.c swagger

- Makefile
- scripts/release/generate-compatibility-matrix.sh
- scripts/release/generate-downloads.sh
- scripts/release/generate-kubernetes-palette-versions.sh
- scripts/release/generate-spectro-cli-reference.sh
- scripts/release/templates/compatibility-cli.md
- scripts/release/templates/compatibility-edge-cli.md
- scripts/release/templates/edge-cli.md
- scripts/release/templates/palette-cli.md
- scripts/release/templates/vertex-vmware-kubernetes-version.md
- scripts/release/templates/vmware-kubernetes-version.md
- scripts/release/utilities.sh
Reverts spectrocloud/librarium#6839
> Revert "[version-4-5] docs: update release scripts DOC-1863 (#6837)"

- docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
* Updated reference for tagsFromScript
tagsFromScript must be a bash script.  Python was given as an example.
The script must be a bash script and must return labels in JSON format.
* ci: auto-formatting prettier issues
---------
This PR ....
> docs: Updated reference for tagsFromScript (#6743)

- utils/helpers/cveHelpers.js
This PR removes the duplicated entries in the OS CVE linked vulnerabilities list. 
💻 [Preview](https://deploy-preview-6885--docs-spectrocloud.netlify.app/security-bulletins/os-k8s/u-2204-0-k-13010-0)
> chore: remove duplicate entries in OS CVE

- docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode.md
This PR adds a small addition to the EKS Hybrid docs as an addition to https://github.com/spectrocloud/librarium/pull/6376.
💻 [Import EKS Cluster and Enable Hybrid Mode](https://deploy-preview-6908--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode/#limitations)
🎫 [PEM-7063](https://spectrocloud.atlassian.net/browse/PEM-7063)
[PEM-7063]: https://spectrocloud.atlassian.net/browse/PEM-7063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: PEM-7063 changes for EKS Hybrid docs

- docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md
This PR removes a missed harbor edit from the registry connect change. 
> docs: remove missed harbor edit

- docs/docs-content/release-notes/release-notes.md
This PR updates the release notes to add missing links and improve the description of an item according to received feedback.
💻 [Release Notes](https://deploy-preview-6937--docs-spectrocloud.netlify.app/release-notes/)
🎫 [DOC-1910](https://spectrocloud.atlassian.net/browse/DOC-1910)
[DOC-1910]: https://spectrocloud.atlassian.net/browse/DOC-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: update release notes

- _partials/permissions/_aws-eks-controller-policy.mdx
This PR adds an additional permission to the Controllers EKS policy.
💻 [IAM Policies](https://deploy-preview-6958--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/required-iam-policies/)
🎫 [PCP-4465](https://spectrocloud.atlassian.net/browse/PCP-4465?focusedCommentId=142568&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-142568)
[PCP-4465]: https://spectrocloud.atlassian.net/browse/PCP-4465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add extra permission

- docs/docs-content/release-notes/release-notes.md
This PR addresses the additional comments made in https://github.com/spectrocloud/librarium/pull/6978.
💻 [Release Notes](https://deploy-preview-6979--docs-spectrocloud.netlify.app/release-notes/#breaking-changes-4.6.c)
🎫 [PCP-4611](https://spectrocloud.atlassian.net/browse/PCP-4611)
[PCP-4611]: https://spectrocloud.atlassian.net/browse/PCP-4611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: adjust Portworx breaking change wording and ordering of Breaking Changes

- docs/docs-content/clusters/public-cloud/gcp/required-permissions.md
This PR adds some new permissions identified on https://spectrocloud.atlassian.net/browse/SUS-940 and reorders some of them to be in alphabetical order.
It also removes two permissions and expands on `Recommender` permissions as per DOC-1890.
💻 [Required IAM Permissions](https://deploy-preview-6980--docs-spectrocloud.netlify.app/clusters/public-cloud/gcp/required-permissions/#required-permissions)
🎫 [DOC-1933](https://spectrocloud.atlassian.net/browse/DOC-1933)
🎫 [DOC-1890](https://spectrocloud.atlassian.net/browse/DOC-1890)
[DOC-1933]: https://spectrocloud.atlassian.net/browse/DOC-1933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1890]: https://spectrocloud.atlassian.net/browse/DOC-1890?atlOrigin=eyJpIjoiNWRkN …
> DOC-1933 / DOC-1890 - Update GCP Required Permissions

- docs/docs-content/clusters/public-cloud/aws/eks.md
This PR adds a warning against using both AMI label and nodepool customization.
💻 [EKS](https://deploy-preview-7078--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks/#assign-an-ami-to-a-node-pool)
🎫 [DOC-1955](https://spectrocloud.atlassian.net/browse/DOC-1955)
Just 4.6
[DOC-1955]: https://spectrocloud.atlassian.net/browse/DOC-1955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add warning on node pool customization DOC-1955

- docs/docs-content/release-notes/release-notes.md
This PR adds release notes for 4.6.34 patch.
💻 [Release Notes](https://deploy-preview-7081--docs-spectrocloud.netlify.app/release-notes/#june-6-2025---release-4634)
🎫 [DOC-1962](https://spectrocloud.atlassian.net/browse/DOC-1962)
Only 4.6.
[DOC-1962]: https://spectrocloud.atlassian.net/browse/DOC-1962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add patch release notes DOC-1960

- docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR will backport PR #7176 changes from master to version-4-3.
> [version-4-3] docs: apply suggestions from joi (#7176)

- docs/docs-content/clusters/cluster-management/kubernetes-dashboard.md
> docs: fix broken link

- docs/docs-content/vm-management/vm-migration-assistant/create-migration-plans.md
- docs/docs-content/vm-management/vm-migration-assistant/create-source-providers.md
- docs/docs-content/vm-management/vm-migration-assistant/start-migration-plans.md
- docs/docs-content/vm-management/vm-migration-assistant/vm-migration-assistant.md
This PR adds a table of verified VM Migration Assistant OS + migration methods to the landing VM Migration Assistant page. It also increases the "Limitations" visibility and cross-references back to the newly added table where necessary.
- [Virtual Machine Migration Assistant](https://deploy-preview-7230--docs-spectrocloud.netlify.app/vm-management/vm-migration-assistant/)
- [Create Source Providers](https://deploy-preview-7230--docs-spectrocloud.netlify.app/vm-management/vm-migration-assistant/create-source-providers/)
- [Create Migration Plans](https://deploy-preview-7230--docs-spectrocloud.netlify.app/vm-management/vm-migration-assistant/create-migration-plans/)
- [Start Migration Plans](https://deploy-preview-7230--docs-spectrocloud.netlify.app/vm-management/vm-migration-assistant/star …
> docs: DOC-1990: Verified VM Migration Assistant Migration Combinations

- .github/workflows/clean-up-unused-images.yaml
This PR adds environment variables to the unused images GitHub Action, as it failed to find the Algolia details.
> docs: add env vars to unused images action

- docs/docs-content/clusters/edge/edgeforge-workflow/edgeforge-workflow.md
- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
This PR makes small grammatical corrections and formatting changes to two Edge pages. These changes are also included in [PR 7266](https://github.com/spectrocloud/librarium/pull/7266) for 4.7. 
- [EdgeForge Workflow](https://deploy-preview-7267--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/#edge-installer-iso)
- [Build Installer ISO](https://deploy-preview-7267--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso/)
> docs: Edge Grammar Fixes

- docs/api-content/api-docs/1-introduction.md
This PR remove tech preview from Edge API introduction page. (pointing to correct branch)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-2005)
- [X ] No. _Please leave a short comment below about why this PR cannot be backported._
Applies to 4.7.0 release
> release 4.7.0: doc-2005 remove tech preview edge api

- docs/docs-content/clusters/edge/cluster-management/remote-shell.md
This PR clarifies the remote shell inactivity behavior. 
🎫 [PEM-7755](https://spectrocloud.atlassian.net/browse/PEM-7755)
[PEM-7755]: https://spectrocloud.atlassian.net/browse/PEM-7755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: Remote shell inactivity

- docs/api-content/api-docs/edge-v1/emc-api.json
This PR updates the 4.7.0 edge swagger file
> docs: update swagger 4 7 0 edge

- docs/docs-content/troubleshooting/enterprise-install.md
This PR describes resolving a time skew on Palette/Palette VerteX installations using the Management Appliance. This is noticed when users encounter unexpected logouts in the tenant console.
💻 [Troubleshooting - Enterprise Install](https://deploy-preview-7338--docs-spectrocloud.netlify.app/troubleshooting/enterprise-install/#scenario---unexpected-logouts-in-tenant-console-after-palettevertex-management-appliance-installation)
🎫 [DOC-2023](https://spectrocloud.atlassian.net/browse/DOC-2023)
Release ticket.
[DOC-2023]: https://spectrocloud.atlassian.net/browse/DOC-2023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-2023 Troubleshooting steps for NTP issue on Palette/VerteX Management Appliance Installations

- docs/docs-content/clusters/cluster-management/monitoring/deploy-monitor-stack.md
- docs/docs-content/clusters/cluster-management/monitoring/open-telemetry.md
This PR makes style fixes to the OTel guide introduced in https://github.com/spectrocloud/librarium/pull/7329
🎫 [PAC-2946](https://spectrocloud.atlassian.net/browse/PAC-2946)
[PAC-2946]: https://spectrocloud.atlassian.net/browse/PAC-2946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: various fixes to the OTel guide PAC-2946

- package-lock.json
This PR backports [PR 7259](https://github.com/spectrocloud/librarium/pull/7259) to version-4-3.
'Tis the backport!
> [version-4-3] chore: backport/version-4-3/pr-7259

- docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
This PR adds username and removes the insecure flag. The insecure flag apparently never existed (though it has been here since 4.0)
🎫 [PE-7159](https://spectrocloud.atlassian.net/browse/PE-7159?focusedCommentId=153958&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&sourceType=mention#comment-153958)
[PE-7159]: https://spectrocloud.atlassian.net/browse/PE-7159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add username and remove insecure

- .gitleaksignore
> docs: fix gitleak

- _partials/security/_artifact-studio-signature-verification.mdx
- docs/docs-content/security/artifact-signatures/artifact-signatures.md
This PR adds information regarding how we sign artifacts, what we sign, and how to verify signatures for artifacts downloaded from Artifact Studio. 
**NOTE**: Addressing how to verify the signatures of individual images is currently out of scope. This has been investigated and, per Rob, set aside for now. In the future, the stakeholders will discuss validation flow, which can then be incorporated properly into the docs. 
This PR was recreated from [PR 7437](https://github.com/spectrocloud/librarium/pull/7437).
💻 [Artifact Signatures]()
🎫 [DOC-1992](https://spectrocloud.atlassian.net/browse/DOC-1992)
Release work into temp branch. The subsequent merge into master will need to be backported.
[DOC-1992]: https://spectrocloud.atlassian.net/browse/DOC-1992?atlOrigin=e …
> docs: DOC-1992: Artifact Signatures

- docs/docs-content/automation/palette-cli/commands.md
This will backport the following commits from `version-4-2` to `version-4-0`:
- [docs: review repo secrets (#7439) (#7496)](https://github.com/spectrocloud/librarium/pull/7496)
> [version 4-0] docs: review repo secrets (#7439) (#7496)

- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/palette-helm-ref.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
- docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
- docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md
- docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
- docs/docs-content/vertex/system-management/ssl-certificate-management.md
This PR backports changes from #7456 to version 4.3.
> [version-4-3] docs: Add information about tenants/hostnames to Self-hosted and VerteX installation processes (#7456)

- .gitleaksignore
This PR adds false positives to our `gitleaksignore` file.
💻 [No public facing changes]()
🎫 [OPS-6891](https://spectrocloud.atlassian.net/browse/OPS-6891)
[OPS-6891]: https://spectrocloud.atlassian.net/browse/OPS-6891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add entries to gitleaksignore 4-0

- docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-addon-profile.md
This PR adds information about packs deletion order,
💻 [Create an Add-on Profile](https://deploy-preview-7580--docs-spectrocloud.netlify.app/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/#deletion-order)
🎫 [DOC-2064](https://spectrocloud.atlassian.net/browse/DOC-2064)
[DOC-2064]: https://spectrocloud.atlassian.net/browse/DOC-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: Add packs deletion order

- docs/docs-content/clusters/edge/cluster-management/agent-upgrade-airgap.md
- docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
- docs/docs-content/clusters/edge/local-ui/cluster-management/update-cluster.md
This PR backports changes from PR #7579 to version 4.5.
🎫 [DOC-2072](https://spectrocloud.atlassian.net/browse/DOC-2072)
[DOC-2072]: https://spectrocloud.atlassian.net/browse/DOC-2072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [version-4-5] docs: Add information about agent upgrade (#7579)

- docs/docs-content/release-notes/release-notes.md
This PR adds Crossplane to release notes. 
💻 [Release Notes](https://deploy-preview-7633--docs-spectrocloud.netlify.app/release-notes/#automation)
🎫 [PLT-1868](https://spectrocloud.atlassian.net/browse/PLT-1868)
Only 4.7
[PLT-1868]: https://spectrocloud.atlassian.net/browse/PLT-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add crossplane to release notes PLT-1868

- docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
- docs/docs-content/clusters/data-center/maas/register-manage-maas-cloud-accounts.md
- docs/docs-content/clusters/edge/trusted-boot/trusted-boot.md
This PR fixes broken URLs discovered on 4th August 2025 (Part 1).
> docs: Fix broken URLs on 4th August 2025 (Part 1)

- docs/docs-content/clusters/edge/networking/kubevip.md
- docs/docs-content/release-notes/release-notes.md
This PR updates the release notes for 4.7.8.
💻 [Release Notes](https://deploy-preview-7685--docs-spectrocloud.netlify.app/release-notes/#august-4-2025---release-478)
💻 [Kubevip](https://deploy-preview-7685--docs-spectrocloud.netlify.app/clusters/edge/networking/kubevip/)
🎫 [DOC-2080](https://spectrocloud.atlassian.net/browse/DOC-2080)
Only 4.7
[DOC-2080]: https://spectrocloud.atlassian.net/browse/DOC-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: update release notes DOC-2080

- docs/docs-content/clusters/edge/cluster-management/remote-shell.md
This PR exits the remote shell feature from tech preview. 
🎫 [DOC-1996](https://spectrocloud.atlassian.net/browse/DOC-1996)
[DOC-1996]: https://spectrocloud.atlassian.net/browse/DOC-1996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: Remote shell preview exit

- docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-helm.md
- docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-packs.md
This PR completes a backport for [PR 7694](https://github.com/spectrocloud/librarium/pull/7694) for version-4-3.
- [Add OCI Helm Registry](https://deploy-preview-7706--docs-spectrocloud.netlify.app/registries-and-packs/registries/oci-registry/add-oci-helm/)
- [Add OCI Packs Registry](https://deploy-preview-7706--docs-spectrocloud.netlify.app/registries-and-packs/registries/oci-registry/add-oci-packs/)
🎫 [DOC-1899](https://spectrocloud.atlassian.net/browse/DOC-1899)
[DOC-1899]: https://spectrocloud.atlassian.net/browse/DOC-1899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [version-4-3] docs: backport/version-4-3/pr-7694

- docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-helm.md
- docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-packs.md
This PR completes a backport for [PR 7694](https://github.com/spectrocloud/librarium/pull/7694) for version-4-2.
- [Add OCI Helm Registry](https://deploy-preview-7707--docs-spectrocloud.netlify.app/registries-and-packs/registries/oci-registry/add-oci-helm/)
- [Add OCI Packs Registry](https://deploy-preview-7707--docs-spectrocloud.netlify.app/registries-and-packs/registries/oci-registry/add-oci-packs/)
🎫 [DOC-1899](https://spectrocloud.atlassian.net/browse/DOC-1899)
[DOC-1899]: https://spectrocloud.atlassian.net/browse/DOC-1899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [version-4-2] docs: backport/version-4-2/pr-7694

- .github/workflows/GHA-ready-for-review.yaml
This PR removes Slack ID from GitHub comment. 
I will backport all versions with this release.
> chore(sec): sec fix for GH comment

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md
- docs/docs-content/clusters/edge/networking/vxlan-overlay.md
- docs/docs-content/integrations/cni-calico.mdx
- docs/docs-content/integrations/cni-cilium-oss.mdx
- docs/docs-content/integrations/cni-flannel.mdx
This PR completes a manual backport from [PR 7643](https://github.com/spectrocloud/librarium/pull/7643) for version-4-4.
- [Build Edge Artifacts](https://deploy-preview-7730--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/)
- [Enable Overlay Network](https://deploy-preview-7730--docs-spectrocloud.netlify.app/clusters/edge/networking/vxlan-overlay/)
- [Packs - Cilium](https://deploy-preview-7730--docs-spectrocloud.netlify.app/integrations/packs/?pack=cni-cilium-oss)
- [Packs - Calico](https://deploy-preview-7730--docs-spectrocloud.netlify.app/integrations/packs/?pack=cni-calico)
- [Packs - Flannel](https://deploy-preview-7730--docs-spectrocloud.netlify.app/integrations/packs/?pack=cni-flannel)
- [DOC-2011](https://spectrocloud.atlassian.net/browse/DOC-2011)
- …
> [version-4-4] docs: backport/version-4-4/pr-7643

- docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
- docs/docs-content/clusters/edge/networking/vxlan-overlay.md
- docs/docs-content/integrations/cni-calico.mdx
- docs/docs-content/integrations/cni-cilium-oss.mdx
- docs/docs-content/integrations/cni-flannel.mdx
This PR completes a manual backport from [PR 7643](https://github.com/spectrocloud/librarium/pull/7643) for version-4-2.
- [Build Edge Artifacts](https://deploy-preview-7728--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/)
- [Enable Overlay Network](https://deploy-preview-7728--docs-spectrocloud.netlify.app/clusters/edge/networking/vxlan-overlay/)
- [Packs - Cilium](https://deploy-preview-7728--docs-spectrocloud.netlify.app/integrations/packs/?pack=cni-cilium-oss)
- [Packs - Calico](https://deploy-preview-7728--docs-spectrocloud.netlify.app/integrations/packs/?pack=cni-calico)
- [Packs - Flannel](https://deploy-preview-7728--docs-spectrocloud.netlify.app/integrations/packs/?pack=cni-flannel)
- [DOC-2011](https://spectrocloud.atlassian.net/browse/DOC-2011)
- …
> [version-4-2] docs: backport/version-4-2/pr-7643

- .husky/pre-commit
- Makefile
- scripts/check_branch_name.sh
- scripts/sanitize-ignore-file.sh
This PR updates `.husky/pre-commit` from `#!/bin/sh` to `#!/bin/bash`
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-2089)
> chore(ci): updated ./husky/pre-commit script from sh to bash

- .husky/pre-commit
- Makefile
- scripts/check_branch_name.sh
- scripts/sanitize-ignore-file.sh
This PR backports #7751 to version 4.5
- [ X] No. _Please leave a short comment below about why this PR cannot be backported._
This is a backport
> chore(ci): backport of pr7751 to version 4.5

- .husky/pre-commit
- Makefile
- scripts/check_branch_name.sh
- scripts/sanitize-ignore-file.sh
This PR backports #7751  to version 4.7
- [ X] No. _Please leave a short comment below about why this PR cannot be backported._
This is a backport
> chore(ci): backport of pr7751 to version 4.7

- .husky/pre-commit
- Makefile
- scripts/check_branch_name.sh
- scripts/sanitize-ignore-file.sh
This PR backports #7751 to version 4.3
This is a backport
> Backport/version 4 3/pr 7751

- docs/api-content/api-docs/edge-v1/emc-api.json
- docs/api-content/api-docs/v1/api.json
This PR adds Hubble + Edge API files for 4.7.a
💻 [API](https://deploy-preview-7781--docs-spectrocloud.netlify.app/api/category/palette-api-v1/)
🎫 [DOC-1927](https://spectrocloud.atlassian.net/browse/DOC-1927)
[DOC-1927]: https://spectrocloud.atlassian.net/browse/DOC-1927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add 4.7.a Palette + Edge APIs DOC-1927

- _partials/pcg/_pcg-cluster-provisioning.mdx
- _partials/pcg/_pcg-initial-installation.mdx
- _partials/pcg/_pcg-kind-cleanup.mdx
- _partials/pcg/_pcg-validate.mdx
- docs/docs-content/clusters/pcg/architecture.md
- docs/docs-content/clusters/pcg/deploy-pcg/maas.md
- docs/docs-content/clusters/pcg/deploy-pcg/openstack.md
- docs/docs-content/clusters/pcg/deploy-pcg/vmware.md
This PR completes a manual backport for [PR 7710 ](https://github.com/spectrocloud/librarium/pull/7710)for version-4-4.
- [Architecture](https://deploy-preview-7810--docs-spectrocloud.netlify.app/clusters/pcg/architecture/#network-proxy)
- [Deploy to MAAS](https://deploy-preview-7810--docs-spectrocloud.netlify.app/clusters/pcg/deploy-pcg/maas/)
- [Deploy to OpenStack](https://deploy-preview-7810--docs-spectrocloud.netlify.app/clusters/pcg/deploy-pcg/openstack/)
- [Deploy to VMware vSphere](https://deploy-preview-7810--docs-spectrocloud.netlify.app/clusters/pcg/deploy-pcg/vmware/)
🎫 [DOC-1916](https://spectrocloud.atlassian.net/browse/DOC-1916)
[DOC-1916]: https://spectrocloud.atlassian.net/browse/DOC-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
> [version-4-4] docs: backport/version-4-4/pr-7710

- _partials/self-hosted/upgrade/_airgap-binary-execution.mdx
- docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
- docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md
- docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md
- docs/docs-content/vertex/upgrade/upgrade-k8s/airgap.md
This PR completes a manual backport for [PR 7791 ](https://github.com/spectrocloud/librarium/pull/7791) for version-4-2.
- [Self-Hosted Palette Kubernetes Airgap Installation](https://deploy-preview-7815--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions/)
- [Self-Hosted Palette Kubernetes Airgap Upgrade](https://deploy-preview-7815--docs-spectrocloud.netlify.app/enterprise-version/upgrade/upgrade-k8s/airgap/)
- [Self-Hosted VerteX Kubernetes Airgap Installation](https://deploy-preview-7815--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions/)
- [Self-Hosted VerteX Kubernetes Airgap …
> [version-4-2] docs: backport/version-4-2/pr-7791

- docs/docs-content/security/product-architecture/platform-security.md
This PR updates the **Operating Systems** section to Ubuntu 22.04 LTS. 
💻 [Platform Security --> Operating Systems](https://deploy-preview-7844--docs-spectrocloud.netlify.app/)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-2101)
- [ X] No. _Please leave a short comment below about why this PR cannot be backported._
> doc-2102: updated Operating Systems section to Ubuntu 22.04

- docs/docs-content/clusters/edge/hardware-requirements.md
This PR corrects an incorrect VMO initialism, changing it from `Virtual Machine Operator` > `Virtual Machine Orchestrator`. 
💻 [Hardware Requirements](https://deploy-preview-7846--docs-spectrocloud.netlify.app/clusters/edge/hardware-requirements/#virtual-machine-orchestrator-vmo)
🎫 [DOC-2093](https://spectrocloud.atlassian.net/browse/DOC-2093)
[DOC-2093]: https://spectrocloud.atlassian.net/browse/DOC-2093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: DOC-2093: Updating Incorrect VMO Initialism

- docs/docs-content/clusters/edge/hardware-requirements.md
This PR completes a manual backport for [PR 7846](https://github.com/spectrocloud/librarium/pull/7846) for version-4-3.
💻 [Hardware Requirements](https://deploy-preview-7851--docs-spectrocloud.netlify.app/clusters/edge/hardware-requirements/#virtual-machine-orchestrator-vmo)
🎫 [DOC-2093](https://spectrocloud.atlassian.net/browse/DOC-2093)
[DOC-2093]: https://spectrocloud.atlassian.net/browse/DOC-2093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [version-4-3] docs: backport/version-4-3/pr-7846

- docs/docs-content/downloads/artifact-studio.md
This PR adds links to **Upload Packs** sections of Palette and VerteX appliances
💻 [Add Preview URL for Page](https://deploy-preview-7891--docs-spectrocloud.netlify.app/downloads/artifact-studio/#upload-packs-to-management-appliances)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-2125)
- [ X] Yes. _Remember to add the relevant backport labels to your PR._
> doc-2125: adding links to Palette/VerteX appliances upload sections

- docs/docs-content/byoos/usecases/vmware/konvoy.md
- docs/docs-content/byoos/usecases/vmware/rhel-pxk.md
- linkinator/linkinator-rate-limit-ci.config.json
This PR manually backports changes from [PR 7896](https://github.com/spectrocloud/librarium/pull/7896) to version-4-2.
> docs: backport/version-4-2/pr-7896

- docs/docs-content/byoos/usecases/vmware/konvoy.md
- docs/docs-content/byoos/usecases/vmware/rhel-pxk.md
- linkinator/linkinator-rate-limit-ci.config.json
This PR manually backports changes from [PR 7896](https://github.com/spectrocloud/librarium/pull/7896) to version-4-3.
> docs: backport/version-4-3/pr-7896

- docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md
- docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rhel-capi.md
- docs/docs-content/byoos/image-builder/build-image-vmware/konvoy.md
- docs/docs-content/byoos/image-builder/build-image-vmware/rhel-pxk.md
- linkinator/linkinator-rate-limit-ci.config.json
This PR manually backports changes from [PR 7896](https://github.com/spectrocloud/librarium/pull/7896) to version-4-4.
> docs: backport/version-4-4/pr-7896

- _partials/self-hosted/management-appliance/_installation-steps-prereqs.mdx
This PR changes the warning for secure boot to apply to all envs, not just vmware.
💻 [Palette Management Appliance](https://deploy-preview-7916--docs-spectrocloud.netlify.app/enterprise-version/install-palette/palette-management-appliance/)
No ticket.
Only 4.7
> docs: update secure boot warning on management appliance

- docs/docs-content/release-notes/release-notes.md
This PR adds 2 breaking changes (that are also documented as known issues) to the Release notes.
Please note: 4.7.b is a placeholder value that should be replaced before the release once the exact version is known.
💻 [Release Notes](https://deploy-preview-7952--docs-spectrocloud.netlify.app/release-notes/)
🎫 Not applicable
> docs: Add Edge breaking changes to release notes

- docs/docs-content/enterprise-version/system-management/backup-restore.md
> Update S3 permissions list for EC backup

- docs/deprecated/integrations/external-secrets-operator.md
- docs/deprecated/integrations/vault.md
- docs/docs-content/automation/automation.md
- docs/docs-content/automation/terraform/terraform.md
- docs/docs-content/devx/services/service-listings/vault.md
- docs/docs-content/integrations/external-secrets-operator.mdx
- linkinator/linkinator-ci.config.json
- linkinator/linkinator-rate-limit-ci.config.json
- linkinator/linkinator-rate-limit.config.json
- linkinator/linkinator.config.json
- scripts/url-checker-developer-portals.sh
This PR updates developer portals link checking and redirected links (vaultproject.io and terraform.io) to fix the broken links check from Sept 15th. 
_No user-facing changes._
🎫 [DOC-2248](https://spectrocloud.atlassian.net/browse/DOC-2248)
[DOC-2248]: https://spectrocloud.atlassian.net/browse/DOC-2248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add more developer portals and update redirected links DOC-2248

- _partials/crossplane/_cluster-profile-existing.mdx
- _partials/crossplane/_install-crossplane.mdx
- _partials/crossplane/_palette-crossplane-provider-version.mdx
- _partials/crossplane/_provider-palette-created.mdx
- _partials/crossplane/_provider-palette-yaml.mdx
- _partials/crossplane/_secret-cloud-yaml.mdx
- docs/docs-content/automation/crossplane/crossplane.md
- docs/docs-content/automation/crossplane/deploy-cluster-aws-crossplane.md
- docs/docs-content/automation/crossplane/deploy-cluster-azure-crossplane.md
- docs/docs-content/automation/crossplane/deploy-cluster-gcp-crossplane.md
This PR updates the existing Crossplane documents and examples for Crossplane v2 compatibility.
- [Crossplane](https://deploy-preview-8039--docs-spectrocloud.netlify.app/automation/crossplane/)
- [Deploy an AWS IaaS Cluster with Crossplane](https://deploy-preview-8039--docs-spectrocloud.netlify.app/automation/crossplane/deploy-cluster-aws-crossplane/)
- [Deploy an Azure IaaS Cluster with Crossplane](https://deploy-preview-8039--docs-spectrocloud.netlify.app/automation/crossplane/deploy-cluster-azure-crossplane/)
- [Deploy a GCP IaaS Cluster with Crossplane](https://deploy-preview-8039--docs-spectrocloud.netlify.app/automation/crossplane/deploy-cluster-gcp-crossplane/)
🎫 [DOC-2135](https://spectrocloud.atlassian.net/browse/DOC-2135)
Release work
[DOC-2135]: …
> docs: DOC-2135: Crossplane v2 Support

- docs/docs-content/integrations/cni-calico.mdx
- docs/docs-content/release-notes/release-notes.md
This PR:
1. Adds a warning about an Edge compatibility issue to the Calico pack Additional details.
2. Adds this information to relese notes.
💻 [Calico - Additional Details](https://deploy-preview-8128--docs-spectrocloud.netlify.app/integrations/packs/?pack=cni-calico)
💻 [Release notes](https://deploy-preview-8128--docs-spectrocloud.netlify.app/release-notes/#packs)
🎫 [PAC-3194](https://spectrocloud.atlassian.net/browse/PAC-3194)
[PAC-3194]: https://spectrocloud.atlassian.net/browse/PAC-3194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: Document Calico version that fixes Edge compatibility issue

- docs/docs-content/legal-licenses/compliance.md
This PR updates the tested configurations for the new certificate. Configurations are provided here https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/5061
💻 [Compliance](https://deploy-preview-8160--docs-spectrocloud.netlify.app/legal-licenses/compliance/#fips-140-3)
🎫 [DOC-2253](https://spectrocloud.atlassian.net/browse/DOC-2253)
Only 4.7
[DOC-2253]: https://spectrocloud.atlassian.net/browse/DOC-2253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: update configurations for new certificate DOC-2253

- docs/docs-content/clusters/public-cloud/azure/azure-disk-storage-sse.md
- docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
- docs/docs-content/release-notes/release-notes.md
- redirects.js
This PR backports #8268 
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-2272)
This is a backport.
> chore(ci): backport of pr8268 to version 4.5

- docs/docs-content/release-notes/release-notes.md
This PR adds component updates to release notes for 2025-40. 
💻 [Release Notes](https://deploy-preview-8314--docs-spectrocloud.netlify.app/release-notes/#component-updates-2025-40)
🎫 [DOC-2279](https://spectrocloud.atlassian.net/browse/DOC-2279)
Only 4.7
[DOC-2279]: https://spectrocloud.atlassian.net/browse/DOC-2279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add component updates 2025-40 DOC-2279

- docs/docs-content/release-notes/release-notes.md
This PR adds patch notes for 4.7.x October patch.
💻 [Release Notes](https://deploy-preview-8330--docs-spectrocloud.netlify.app/release-notes/)
🎫 [DOC-2291](https://spectrocloud.atlassian.net/browse/DOC-2291)
Only 4.7
[DOC-2291]: https://spectrocloud.atlassian.net/browse/DOC-2291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add patch notes DOC-2291

- docs/docs-content/release-notes/release-notes.md
This PR tweaks the wording of the patch release notes
🎫 [DOC-2291](https://spectrocloud.atlassian.net/browse/DOC-2291)
Only 4.7
[DOC-2291]: https://spectrocloud.atlassian.net/browse/DOC-2291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: adjust release notes 4.7.23 wording DOC-2291
