spectrocloud/librarium

packages/docs/content/13-release-notes.md
Changed from 2.6.x to 2.6.1 for Portworx and from 3.16.x to 3.16 for Calico.
=> Corrected Portworx and Calico version numbers

packages/docs/content/04-clusters.md
=> Fix typo in aws permissions

packages/docs/content/06-integrations/01-pack-constraints.md
Updated three new supported variables to Pack Constraints - Macros
cloudaccount.name
cloudaccount.uid 
kubernetes.version
=> 1.10 MacrosVariables 

packages/docs/content/06-integrations/00-kubernetes.md
Kubernetes packs versions: Release 2.1.0
1. 1.19.16
2. 1.21.6
=> k8s-packs-2.1.0

packages/docs/content/15-compliance.md
https://spectrocloud.atlassian.net/browse/DOC-86
Removed PCI-DSS compliance. Spectro Cloud is not PCI-compliant. Only Stripe is compliant, which is our payment processor.
=> pci-dss-removed

packages/docs/content/04-clusters/1-new-clusters/02-eks.md
Since we now delete dangling ENIs in palette, we need perms for the same.
=> fix ENI perms

content/docs/06-integrations/00-calico.md, content/docs/06-integrations/00-certmanager.md, content/docs/06-integrations/00-falco.md, content/docs/06-integrations/00-portworx.md, content/docs/06-integrations/00-rook-ceph.md
Version updated for the following packs:
- cert-manager 1.7.1
- calico - 3.22.0
- calico-azure - 3.22.0
- falco - 1.16.3 
- portworx-vsphere - 2.8.0
- rook-ceph - 1.8.3
=> pack-version-updates

content/docs/16-component.md, content/docs/16-spectro-downloads.md
**|Palette Release|On-Premises Installer Version|**
-|2.6|2.0.2| - Removed
+|2.6|2.1.0| - Added
**|Version|URL|Info|**
-|2.0.2|hubble-installer-202-10152021.ova|Oct 15 2021| -Removed 
+|2.1.0|hubble-installer-210.ova|Jun 1 2022 (Cert Manager change to 1.8)| - Added
=> on-prem-installer-2.6-rel

content/docs/06-integrations/00-portworx_operator.md
Adds documentation for the new `portworx-generic` pack that can eventually replace all existing Portworx packs.
=> add portworx_operator docs

content/docs/04-clusters/2-brownfield-clusters.md
While importing EKS clusters, Palette encourages importing Standard clusters over [Autopilot Clusters](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview).
=> gke-autopilot

content/docs/04-clusters/3-cluster-management/05-backup-restore.md
In Configure your Backup in MinIO :  [Managing Cluster Update Events on Palette](https://docs.spectrocloud.com/clusters/cluster-management/backup-restore/#configureyourbackupinminio) 
Point 8: Authenticate using the MinIo access key and secret access key.
should be removed, as we don't validate Minio buckets
We need accessKey and SecretKey from the user, but should not validate those as minio URL may not be publicly accessible.
Also for region”
Region: Region in which Minio server is configured. Example: us-east-1
=> minio-pem-203

content/docs/13-terraform.md
Issue: Cannot override addon profile pack value for vsphere_edge cloud type
Fix: added missing profile name in addon profile pack parameters index.
=> tf-0.9.1-release

content/docs/04-clusters/01-public-cloud/01-aws.md, content/docs/04-clusters/01-public-cloud/02-eks.md
Reverts spectrocloud/librarium#899
=> Revert "To resolve for stale pr"

content/docs/04.5-devx.md, content/docs/06-integrations/00-aws-autoscaler.md, content/docs/06-integrations/00-aws-ebs.md, content/docs/06-integrations/00-calico.md, content/docs/06-integrations/00-certmanager.md, content/docs/06-integrations/00-dex.md, content/docs/06-integrations/00-external-dns.md, content/docs/06-integrations/00-fluentbit.md, content/docs/06-integrations/00-frp.md, content/docs/06-integrations/00-generic-vm-libvirt.md, content/docs/06-integrations/00-generic-vm-vsphere.md, content/docs/06-integrations/00-istio.md, content/docs/06-integrations/00-kubernetes-dashboard.md, content/docs/06-integrations/00-kubernetes.md, content/docs/06-integrations/00-metallb.md, content/docs/06-integrations/00-opa-gatekeeper.md
**Release 3.0 Pack Version Updates**
* Istio version 1.14.3
* Spectro Proxy version 1.1.0
* Kubernetes-dashboard-2.6.1
* Generic VM vSphere version 1.0.3
* Calico version 3.24
* Calico version 3.24_azure
* MetalLB-version 0.13.5
* AWS Cluster Autoscaler version 1.22.2
* K3s version 1.24.4
* Calico Network Policy version 3.24
* Generic-VM Libvirt version 1.0.1
* Cert-Manager version 1.9.1
* AWS EBS CSI version 1.10.0
* External DNS version 0.12.2
* Open Policy Agent version 3.9.0
* Fluentbit version 1.9.6
=> 3.0-pack-updates

content/docs/06-integrations/00-external-secrets-operator.md
This PR removes a duplicate YAML entry in the [External Secrets Operator Page](https://docs.spectrocloud.com/integrations/external-secrets-operator/)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/jira/software/c/projects/DOC/boards/62?modal=detail&selectedIssue=DOC-373)
=> docs: removed duplicate yaml entry

.dockerignore, Dockerfile, Makefile, README.md, scripts/entry.sh
This PR adds support for local development with Docker for Arm architecture-based workstations.  The current Makefile logic copies over the users `node_modules/`. Copying the node modules folder generates an issue with the dependencies [Sharp](https://github.com/lovell/sharp/issues/3166). The workaround is to issue an `npm install` from inside the container during the build. 
- Added a `.dockerignore` file
- Updated README with logo, overview section, and Docker local development steps.
- Updated `entry.sh` script
The Makefile also had the following updates:
- initialize now does an `npm ci` vs `npm install`. This removes the situation where a contributor updates the `package-lock.json` when not intending to.
- Unused make commands are removed
- Split out the docker build step from the …
=> ci: added steps for local docker development that support arm

content/docs/04-clusters/02-data-center/03-vmware.md
This PR addresses missing information when standing up a VMware Private Cloud Gateway
Note: The `|` cannot be escaped inside a markdown table, so the command has to be displayed without code blocks.
=> docs: added more context pertatining to the certificate field

content/docs/13-terraform.md, content/docs/14-troubleshooting/04-cluster-deployment.md
This PR updates the Cluster Deployment page to include the main heading. A New Terraform version has also been added.
=> docs: terraform related changes and minor header fix

prow/functions.sh, prow/presubmit.sh
This PR changes the behavior of the CI flow.  In order to push the changes to production, a comment with the following value is required `/test librarium_release_build`. The comment in the PR triggers the build step for production. Now that preview URLs are available, we no longer need the `docs-latests.spectrocloud.com` URL and flow. We want to merge into the base branch, `master`, to automatically deploy to production.
=> ci: change behavior for CI flow

content/docs/04.5-devx/04-resource-quota.md
Changed 'Resourse' to 'Resource' in navigation.
=> Fixed Resource typo

content/docs/04.5-devx/04-resource-quota.md
This PR adds details about size limits automatically updated if cluster group limits are lower than default size limits.
Jira: https://spectrocloud.atlassian.net/browse/PPD-791
[Preview](https://deploy-preview-1048--docs-spectrocloud.netlify.app/devx/resource-quota)
=> Add cluster group auto update detail

content/docs/00-release-notes.md
This PR adds a section called "Upgrade Notes" in the 3.1 release notes. A statement pertaining to MaaS clusters has been added.
=> Release Notes - minor update

content/docs/00-release-notes.md, content/docs/02.5-architecture/04-networking-ports.md, content/docs/09-registries-and-packs/3-add-custom-packs.md, vale/styles/Vocab/Internal/accept.txt, vale/styles/Vocab/Internal/reject.txt
I noticed and fixed minor typos on 3 pages:
- VMWare > VMware
- Vsphere > vSphere
- VSphere > vSphere
=> Romain - fix typos on VMware and vSphere

content/docs/04-clusters/04-palette-virtual-clusters/00-add-virtual-cluster-to-host-cluster.md
This PR addresses feedback about missing IAM Policies for virtual clusters in an AWS environment.  The highlighted area in the following image displays the new additions.
=> docs: added explanation for AWSEBSCSI policy to virtual clusters

content/docs/06-integrations/00-frp.md, content/docs/06-integrations/00-kubernetes-dashboard.md
This PR fixes an issue with broken links related to the Kubernetes dashboard page.
=> docs: fixed issue related to redirect error

content/docs/04-clusters/01-public-cloud/01-aws/10-required-iam-policies.md
Recently we have made a change that when EKS clusters are created, a functionality has been added to also tag OIDC providers. The AWS user should have the required permission in its attached IAM policy to be able to tag OIDC providers.
This PR is for the information to the user to also have `iam:TagOpenIDConnectProvider"` as a permission. The `iam:GetOpenIDConnectProvider"` permission wasn't present previously, so I have added it now.
=> Adding Tag OIDC permission for EKS as IAM policy

content/docs/04.5-devx/03-cluster-groups/35-ingress-cluster-group.md
This PR documents steps to add Ingress to a Cluster Group. 
Jira: https://spectrocloud.atlassian.net/browse/PPD-944
[Preview.](https://deploy-preview-1089--docs-spectrocloud.netlify.app/devx/cluster-groups/ingress-cluster-group)
=> Ingress for Cluster Groups

content/docs/04-clusters/01-public-cloud/01-aws/02-architecture.md
This PR adds a section related to tags for AWS resources. 
🎫 [PCP-753](https://spectrocloud.atlassian.net/browse/PCP-753)
💻 [Preview](https://deploy-preview-1105--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/architecture#tags)
=> AWS Resource Tags

content/docs/07-projects.md, content/docs/08-user-management/1.8-project-association.md, vale.ini
This PR adds content related to project deletion and the force delete behavior. The project page was also restructured to comply with the how-to layout format. Associating users to a project has been moved into its own page in the User Management section.
💻 [Preview](https://deploy-preview-1107--docs-spectrocloud.netlify.app/projects)
🎫 [PEM-801](https://spectrocloud.atlassian.net/browse/PEM-801)
=> Project Force Deletion

content/docs/06-integrations.mdx, content/docs/06-integrations/01-standalone-integrated-packs.md
This PR rewrites the Pack Integrations doc and changes the nav pane label from "Pack Integrations" to "Packs List". Alternatively, it can just be "Packs" but labeling it as "Packs List" distinguishes it from "Registries and Packs".
The 06-integrations.mdx file contains  <Content> and </Content> elements. Are these necessary and can they be deleted? Or are they related to the search bar?
Note: This PR doesn't present the Integrations filter button (that's in the spectro K8s dashboard PR).
[Doc Preview](https://deploy-preview-1112--docs-spectrocloud.netlify.app/integrations)
See also the "Stand-Alone and Integrated Packs" doc in the nav pane below Packs List.
=> Revise pack overview doc

content/docs/04-clusters/01-public-cloud/01-aws/05-add-aws-accounts.md
This PR adds documentation on how to use AWS STS with AWS Gov cloud accounts.
💻 [Preview](https://deploy-preview-1113--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/add-aws-accounts)
🎫 [PCP-711](https://spectrocloud.atlassian.net/browse/PCP-711)
=> Document AWS Gov cloud STS authentication

content/docs/04-clusters/01-public-cloud/01-aws/08-create-cluster.md, content/docs/04-clusters/01-public-cloud/01-aws/09-eks.md
This PR fixes an incorrect URL in the AWS Create Cluster how-to page.
=> docs: fixed url redirect

content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md, content/docs/04-clusters/01-public-cloud/03-azure/04-aks.md
Azure only supports RSA public-private key pairs with a minimum length of 2048 bits. Newer (and more secure) key formats such as ED25519 and ECDSA are not supported.
Source [here](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys).
=> fix: added note about sshkey support in Azure

content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
The description that we had so far, was not working if the user didn't specify the correct CA certificate.
=> DOC-295 - Improve docs custom pack registry

content/docs/04-clusters/04-palette-virtual-clusters.md
This PR was going to fix the "Add Virtual Clusters to a Host Cluster" doc to include a policy for ([PPD-969](https://spectrocloud.atlassian.net/browse/PPD-969)). However, as of 3.2 this method is deprecated. Instead, I added mention of CNI and CSI in the "Palette Virtual Clusters" doc. Should we also mention in the Overview that Host Clusters are deprecated in 3.2? Please advise.
Host Cluster also appears in the glossary.
In this PR, I also edited the "Palette Virtual Clusters" doc.
=> Virtual clusters use cni csi of host cluster

content/api/v1/12-edgehosts.md
This PR fixes a rename bug related to Edge hosts.
=> docs: fixed incorrect name for edge hosts

content/docs/16-component.md
This PR adds the Stlys CLI to the compatible page.
💻 [Preview](https://deploy-preview-1150--docs-spectrocloud.netlify.app/component#styluscliversions)
🎫 [DOC-730](https://spectrocloud.atlassian.net/browse/DOC-730)
=> docs: DOC-730 added docs for stylus CLI

content/docs/04-clusters/02-data-center/01-maas.md
I noticed a broken link (missing an `s` to `clusters` at the end), here's a quick PR to fix it.
=> Quick 404 links fix

content/docs/09-registries-and-packs/1-adding-a-custom-registry.md, content/docs/09-registries-and-packs/7-advanced-configuration.md, vale/styles/Vocab/Internal/accept.txt
This PR extends the documentation of the PAX registry. It adds information on previously
undocumented features and shows how to deploy the registry with letsencrypt, which was added in v3.2.
🎫 [Jira ticket](https://spectrocloud.atlassian.net/browse/DOC-295)
=> Doc 472/custom pack registry updates

content/docs/00-release-notes.md
This PR fixes a broken URL reported in the weekly automation job.
💻 [Preview](https://deploy-preview-1235--docs-spectrocloud.netlify.app/)
=> docs: fixed broken URL in release notes

content/docs/04-clusters/01-public-cloud/01-aws/10-required-iam-policies.md
This PR adds a warning to the AWS IAM policies page. Users that exceed the policy attachment limit will result in cluster creation failures.
💻 [Preview](https://deploy-preview-1240--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/required-iam-policies)
=> docs: updated IAM policies page with a warning

content/docs/12-enterprise-version/03-deploying-palette-with-helm.md, content/docs/19-kubernetes-knowlege-hub/00-how-to/02-how-to-retrieve-images-from-private-registry.md
This PR fixes two identified broken URLs and a typo in the Helm Install page.
💻 [Preview](https://deploy-preview-1244--docs-spectrocloud.netlify.app/kubernetes-knowlege-hub/how-to/how-to-retrieve-images-from-private-registry)
=> chore: fixed broken urls and reported typo

content/docs/04-clusters/06-cluster-management/01.9-monitoring/20-deploy-agent.md, content/docs/06-integrations/00-prometheus-cluster-metrics.md
This PR adds a warning box to the cluster metrics pack page and the deploy Prometheus agent guide.
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PEM-1615)
=> docs: added warning about missing metrics PEM-1615

content/docs/02.5-architecture/04.5-palette-public-ips.md
This PR publishes the Public Palette IP addresses that customers must know when configuring their Firewall rules.
💻 [Preview](https://deploy-preview-1256--docs-spectrocloud.netlify.app/architecture/palette-public-ips)
🎫 [DOC-755](https://spectrocloud.atlassian.net/browse/DOC-755)
=> docs: doc-755 added public IP addresses

content/docs/09-registries-and-packs/5-pack-constraints.md
This PR documents a new Packs macro variable `{{.spectro.system.kubernetes.version}}`.
💻 [Preview URL](https://deploy-preview-1262--docs-spectrocloud.netlify.app/registries-and-packs/pack-constraints#typesofmacros)
🎫 [PEM-1632](https://spectrocloud.atlassian.net/browse/PEM-1632)
=> docs: PEM-1632 added new macro variable

content/docs/00-release-notes.md, content/docs/14-troubleshooting/06-nodes.md
This PR explains how to disable the Palette agent from sending workloads to the control plane.
💻 [Preview URL](https://deploy-preview-1296--docs-spectrocloud.netlify.app/troubleshooting/nodes#paletteagentsworkloadpayloadsizeissue)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PE-1530)
=> docs: Disable workloads Settting

content/docs/04-clusters/03-edge/02-edge-configuration/30-cloud-init.md, content/docs/04-clusters/03-edge/04-edgeforge-workflow/03-prepare-user-data.md
This PR fixes some indentation issues in the examples for the user-data file. With the current indentation all of the user-data examples, apart from the 1st one, result in invalid user-data files 
=> fixing edge stages indentation

.gitignore, .vscode/settings.json
This PR adds a default settings file for vscode. 
```json
{
"[markdown]": {
"editor.tabSize": 2,
"editor.insertSpaces": true,
},
"[mdx]": {
"editor.tabSize": 2,
"editor.insertSpaces": true,
}
}
```
=> chore: added .vscode file to set standard editor config for vscode

content/docs/02.5-architecture/01-architecture-overview.md, content/docs/02.5-architecture/04-networking-ports.md
=> Docs:Typos Edit under Architecture section

content/docs/00-release-notes.md, content/docs/09.5-security.md, content/docs/09.5-security/11-product-architecture/03-saas-operation.md
This PR fixes broken URLs reported in the Weekly Broken URL report.
=> docs: broken URL fixed

__tests__/hitComps.test.js, src/shared/layouts/Default/search/hitComps.js, src/shared/layouts/Default/search/index.js
To make the entire Algolia search result clickable, the <Link> component was removed and the styling was done using CSS. The navigation is now handled programmatically.
=> Make Algolia search result clickable

content/docs/02.5-architecture/01-architecture-overview.md, content/docs/04-clusters.md, content/docs/04-clusters/03-edge.md, content/docs/09.5-security/10-product-architecture.md
This PR adds images created by the Design team in the Architecture section that displays the Palette deployment models.
The Edge Index page was also re-arranged to remove the term Edge Native.
💻 [Architecture](https://deploy-preview-1377--docs-spectrocloud.netlify.app/architecture/architecture-overview)
💻 [Edge](https://deploy-preview-1377--docs-spectrocloud.netlify.app/clusters/edge)
=> docs: added images

content/docs/04-clusters/06-cluster-management/16-cluster-tag-filter.md, src/shared/utils/redirects.js
[Cluster ](https://docs.spectrocloud.com/clusters/cluster-management/cluster-tag-filter/) page has some broken urls with localhost. removed localhost from urls
Made the following changes to the **redirects.js** file.
Removed this redundant block. We already have a separate rule available for the `/clusters/edge/native` source. 
```
{
fromPath: `/clusters/edge/native`,
toPath: `/clusters/edge/site-deployment/installer`,
redirectInBrowser: true,
isPermanent: true,
},
```
Added a new rule:
```
{
fromPath: `/clusters/edge/install/installer-image`,
toPath: `/clusters/edge/site-deployment/site-installation`,
redirectInBrowser: true,
isPermanent: true,
},
```
Changed the following destination 
```
toPath: `/clusters/edge/site-deployment/installer`,
```
to
```
toPath: …
```
=> Fix cluster page broken urls

content/docs/09-registries-and-packs/5-pack-constraints.md
This PR updates the macro table with a new parameter  `{{.spectro.system.cluster.kubevip}}'
💻 [Preview URL](https://deploy-preview-1407--docs-spectrocloud.netlify.app/registries-and-packs/pack-constraints#typesofmacros)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PE-1982)
=> docs: PE-1982 added macro to table

content/docs/04-clusters/01-public-cloud/01-aws/08-create-cluster.md, content/docs/06-integrations/00-frp.md
This PR adds new content to the AWS section and addresses minor feedback.
💻 [Preview URL](https://deploy-preview-1410--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/create-cluster)
🎫 [DOC-813](https://spectrocloud.atlassian.net/browse/DOC-813) 
🎫 [PCP-1334](https://spectrocloud.atlassian.net/browse/PCP-1334)
=> AWS Cluster Updates

content/api/1-introduction.md, content/docs/08-user-management/3-palette-resource-limits.md
This PR updates the Palette resource limits page and moves the API Rate limit to the API index page.
**[API Rate](https://deploy-preview-1431--docs-spectrocloud.netlify.app/api/introduction#ratelimits)**
**[Resource Limits Table](https://deploy-preview-1431--docs-spectrocloud.netlify.app/user-management/palette-resource-limits)**
💻 [Preview URL](https://deploy-preview-1431--docs-spectrocloud.netlify.app/user-management/palette-resource-limits)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PFR-414)
=> docs: PFT-414 updated limits page

content/docs/04-clusters/06-cluster-management/05-backup-restore.md
This PR changes the indents of the JSON Code so it formats correctly. 
https://docs.spectrocloud.com/clusters/cluster-management/backup-restore/#configureyourbackupinawss3
Note that this issue also exists in https://github.com/spectrocloud/docs-prototype. @nagesh161007
https://github.com/spectrocloud/docs-prototype/blob/99ad8a10b618893a7b9923dc4be807a422fb6527/docs/docs-content/clusters/cluster-management/backup-restore.md?plain=1#L100-L161
🎫 No open JIRA ticket.
=> Update Formatting in 05-backup-restore.md

content/docs/00-release-notes.md, content/docs/04-clusters/06-cluster-management/15-node-pool.md, content/docs/17-glossary-all.md, vale/styles/Vocab/Internal/accept.txt
This PR adds documentation about the new node repavement configuration.
New Glossary definition
Moved the Node Settings tables to a dedicated section for easier referencing.
Added a repave section that explains the topic and raises awareness of the ability to configure the time interval.
💻 [Preview URL](https://deploy-preview-1462--docs-spectrocloud.netlify.app/clusters/cluster-management/node-pool)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PCP-1511)
=> Node Repave Configuration

content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
Add the full path to the tenant settings option (ie. from the tenant admin view, as opposed to a project view, that can be confusing).
=> add menu details to add new certificate

content/docs/04-clusters.md, content/docs/12-enterprise-version/00-on-prem-system-requirements.md
This PR adds `k8s.gcr.io` and `registry.k8s.io` to the proxy whitelist, de-duplicates the two proxy whitelists, and alphabetizes the remaining list.
💻 [Preview URL](https://deploy-preview-1468--docs-spectrocloud.netlify.app/)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-836)
=> DOC-836: Update & de-duplicate proxy whitelists

content/docs/04-clusters/06-cluster-management/03-compliance-scan.md
This PR adds an InfoBox that informs users about the best practice for running scans when a node is in maintenance mode.
💻 [Add Preview URL](https://deploy-preview-1473--docs-spectrocloud.netlify.app/clusters/cluster-management/compliance-scan)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PEM-3207)
=> Content for PEM-3207 - scans and node maintenance mode

content/docs/04-clusters/02-data-center/03-vmware.md
This PR adds prerequisite information about vSphere support for port groups and updates step 4 in the Tenant Portal section  to explain port groups and distributed port groups are listed with their names.
💻 
[Prerequisite](https://deploy-preview-1482--docs-spectrocloud.netlify.app/clusters/data-center/vmware#prerequisites)
[Tenant Portal](https://deploy-preview-1482--docs-spectrocloud.netlify.app/clusters/data-center/vmware#tenantportal-launchcloudgateway)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PCP-1587) and [Jira Ticket](https://spectrocloud.atlassian.net/browse/PCP-1174)
=> Document prerequisite: PCP-1587, named port groups: PCP-1174

content/docs/04-clusters/02-data-center/03-vmware.md
This recording is already present in the `OVA/OVF Template` tab below and is not relevant as introduction of this section
Remove the 1st occurrence of the 2 min video recording that describes the PCG deployment using the OVA method.
=> Remove the 1st occurrence of the OVA PCG video

content/docs/12.5-vertex/00-fips/01-fips-compliant-components.md
This PR updates the FIPS documentation with internal component information.
💻 [Preview URL](https://deploy-preview-1496--docs-spectrocloud.netlify.app/vertex/fips/fips-compliant-components)
🎫 [DOC-852](https://spectrocloud.atlassian.net/browse/DOC-852)
=> docs: DOC-853 provide FIPS content

content/docs/04.6-vm-management.md
This PR updates the VMO use cases and pre-reqs
=> Update VMO prereq

docs/docs-content/integrations/kubernetes-generic.md, docs/docs-content/integrations/kubernetes.md
This PR details the `serviceDomain` parameter and adds a section on changing the default cluster DNS service domain. All tabs are updated. The PR also fixes formatting after migrating to Docusaurus.
💻 
[Preview Standard Kubernetes](https://deploy-preview-1527--docs-spectrocloud.netlify.app/integrations/kubernetes-generic)
[Preview Palette eXtended Kubernetes](https://deploy-preview-1527--docs-spectrocloud.netlify.app/integrations/kubernetes)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PCP-935)
=> Document serviceDomain parameter in k8s config: PCP-935

docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-dynamic.md, docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-static.md, docs/docs-content/enterprise-version/air-gap-repo.md, docs/docs-content/enterprise-version/helm-chart-install-reference.md, docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
- This PR updates the Helm reference page with a new attribute for Palette 4.0+. 
- [Palette](https://deploy-preview-1536--docs-spectrocloud.netlify.app/enterprise-version/helm-chart-install-reference#config)
- [Vertex](https://deploy-preview-1536--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref#install-mode)
- Minor fixes to callout boxes not displaying in the [Airgap document](https://deploy-preview-1536--docs-spectrocloud.netlify.app/enterprise-version/air-gap-repo?install-method=palette-installer).
- Updated the backup instructions to reflect field feedback. 
- [Static Credentials](https://deploy-preview-1536--docs-spectrocloud.netlify.app/clusters/cluster-management/backup-restore/add-backup-location-static#prerequisites)
- [Dynamic …
=> Helm update

docs/docs-content/clusters/data-center/vmware.md
This PR adds a caution that explains when the password for a user account changes in Vcenter, the password in Palette for the same VMware cloud account must also be changed. PR also removes unneeded breaks.
💻 [Preview](https://deploy-preview-1547--docs-spectrocloud.netlify.app/clusters/data-center/vmware#create-a-vmware-cloud-account)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-866)
=> Document action needed in Palette if Vcntr pwd changes: doc-866

.github/workflows/release.yaml, .github/workflows/version-branch-update.yaml, README.md
This PR updates the README with documentation that guides how to reference other documentation pages.
💻 [Preview URL](https://github.com/spectrocloud/librarium/tree/readme-updated-9-19#markdown-links-and-urls)
=> docs: updated README and release concurrency

.github/workflows/release.yaml, .github/workflows/version-branch-update.yaml, docs/docs-content/audit-logs/audit-logs.md, scripts/netlify.sh
This PR updates the backport to use `pull_request` so that the build uses the commit code.
=> ci: updates to CI workflow

docs/docs-content/clusters/edge/edge.md
Although edge is under active development, so is the rest of palette. the warning was written earlier in the year when edge was indeed under greater change, however now as it is maturing it isn't a good message for us to show while we are working on customer opportunities. This commit simply removes the warning box.
This PR .....
=> Remove warning about active development - Update edge.md

.dockerignore, .github/workflows/version-branch-update.yaml, Dockerfile, Makefile, README.md
This PR updates the Docs README and removes redundant builds in a backport CI.
=> ci: updated README and backport CI

docs/docs-content/clusters/cluster-groups/create-cluster-group.md
This PR aims to add clarifications around cluster groups and virtual clusters.
=> Cluster group and virtual cluster clarifications

docs/api-content/api-docs/1-introduction.md, docs/docs-content/clusters/cluster-groups/create-cluster-group.md
This PR removes the double infobox introduced by PR #1598 .  @cloudmaniac in the future, avoid creating back-to-back info boxes. This is an anti-pattern due to how distracting they can be, and the text appears a bit too busy when info boxes are stacked. In your defense, we should have caught this before merging. 
=> docs: fix virtual cluster text that used double infobox

docusaurus.config.js
This PR updates the privacy experience button to become an inline link. This addresses the issue of the privacy button obstructing items from the navigation menu.
💻 [Add Preview URL](https://deploy-preview-1635--docs-spectrocloud.netlify.app/#)
🎫 [DOC-885](https://spectrocloud.atlassian.net/browse/DOC-885)
=> chore: updated privacy settings experience

docs/docs-content/spectro-downloads.md
This PR adds a new CLI version to the downloads page. 
💻 [Preview URL](https://deploy-preview-1658--docs-spectrocloud.netlify.app/spectro-downloads)
=> docs: added CLI download URL

.github/workflows/aloglia_crawler.yaml, .github/workflows/eslint-test.yaml, .github/workflows/image_optimizer.yaml, .github/workflows/pull_request.yaml, .github/workflows/release-preview.yaml, .github/workflows/release.yaml, .github/workflows/url-checks.yaml, .github/workflows/version-branch-update.yaml, docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
This PR captures the new MAAS tag feature. 
💻 [Preview URL](https://deploy-preview-1656--docs-spectrocloud.netlify.app/clusters/data-center/maas/create-manage-maas-clusters#deploy-a-maas-cluster)
🎫 [PCP-1930](https://spectrocloud.atlassian.net/browse/PCP-1930)
=> docs: maas node tags PCP-1930

docs/docs-content/release-notes.md, docs/docs-content/vertex/supported-platforms.md, docs/docs-content/vertex/vertex.md
This PR adds a support table in the VerteX docs that informs the reader of supported deployment providers.
💻 [Preview URL](https://deploy-preview-1682--docs-spectrocloud.netlify.app/vertex/)
🎫 [PEM-3751](https://spectrocloud.atlassian.net/browse/PEM-3751)
=> Vertex platform

Makefile, docs/docs-content/clusters/edge/edge-configuration/cloud-init.md, vale/styles/Vocab/Internal/accept.txt
This PR updates the cloud-init.md file to add a Netplan network configuration section.
💻 [Preview URL](https://deploy-preview-1705--docs-spectrocloud.netlify.app/clusters/edge/edge-configuration/cloud-init)
🎫 [PE-2882](https://spectrocloud.atlassian.net/browse/PE-2882)
=> User Data Netplan 

Makefile, docs/docs-content/troubleshooting/cluster-deployment.md
This PR adds the steps to change Pod Security Standards by applying labels to namespaces if users encounter problems during deployment of cluster profiles with Packs that require elevated privileges. 
💻 [Preview](https://deploy-preview-1706--docs-spectrocloud.netlify.app/troubleshooting/cluster-deployment#deployment-violates-pod-security)
🎫 [PAC-828](https://spectrocloud.atlassian.net/browse/PAC-828)
=> Document addition of namespace labels for pods needing elevated privileges

.github/workflows/pull_request.yaml, .github/workflows/release.yaml
This PR fixes a missing condition flag. WIthout the modification, the CI steps for building the website could occur in parallel.
=> ci: added missing condition for non-cron workflows

docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
This PR adds guidance pertaining to nginx when installing Palette or VerteX in a Kubernetes cluster.
- [Palette Kubernetes Install](https://deploy-preview-1722--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-kubernetes/install)
- [VerteX Kubernetes Install](https://deploy-preview-1722--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-kubernetes/install)
💻 [Preview URL](https://deploy-preview-1722--docs-spectrocloud.netlify.app/)
🎫 [DOC-902](https://spectrocloud.atlassian.net/browse/DOC-902)
=> Self-Hosted guidance for nginx

docs/docs-content/registries-and-packs/deploy-pack.md
This PR updates the container image to 1.0.8 on deploy-pack.md.
=> docs: update container image

src/components/PacksTable/PackTable.test.tsx, src/components/PacksTable/PacksTable.tsx
This PR adds the cloud types column to the Deprecated Packs table:
- Adds a function that handles string transformation for cloud types. 
- Adds a test that ensures cloud provider names are displayed correctly 
💻 [Deprecated packs table](https://deploy-preview-1731--docs-spectrocloud.netlify.app/integrations/deprecated-packs)
🎫 [DOC-903](https://spectrocloud.atlassian.net/browse/DOC-903)
=> chore: add cloud types column to deprecated packs list (DOC-903)

src/components/PacksTable/PacksTable.tsx
This PR adds the missing logic to display the `prodStatus` field.
=> chore: added correct field to display

src/components/PacksTable/PackTable.test.tsx, src/components/PacksTable/PacksTable.tsx
This PR backports the cloud type column  to the 4.0 branch. 
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-903)
=> Backport cloudtype display 4.0

src/components/PacksTable/PackTable.test.tsx, src/components/PacksTable/PacksTable.tsx
* chore: add cloud types column to deprecated packs list
* Update src/components/PacksTable/PacksTable.tsx
---------
This PR .....
=> chore: add cloud types column to deprecated packs list (DOC-903) (#1731)

scripts/netlify.sh
This PR removes the `version-*` element from the netlify.sh script. This will enable branch-deploys for our version branches.
=> chore: updated netlify.sh script

docs/docs-content/devx/devx.md
This PR updates the App mode table that explains what modes of Palette users can use app mode. 
💻 [Preview URL](https://deploy-preview-1750--docs-spectrocloud.netlify.app/devx/#supported-platforms)
=> Update App Mode Table

docs/docs-content/enterprise-version/install-palette/airgap/kubernetes-airgap-instructions.md, docs/docs-content/enterprise-version/install-palette/airgap/vmware-vsphere-airgap-instructions.md, docs/docs-content/vertex/install-palette-vertex/airgap/kubernetes-airgap-instructions.md, docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md
This PR updates the Oras version prereqs statement.
- [VerteX Airgap Kubernetes](https://deploy-preview-1759--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/airgap/kubernetes-airgap-instructions)
- [VerteX Airgap VMware](https://deploy-preview-1759--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions)
- [Airgap Kubernetes](https://deploy-preview-1759--docs-spectrocloud.netlify.app/enterprise-version/install-palette/airgap/kubernetes-airgap-instructions)
- [AIrgap VMware](https://deploy-preview-1759--docs-spectrocloud.netlify.app/enterprise-version/install-palette/airgap/vmware-vsphere-airgap-instructions)
💻 [Preview URL](https://deploy-preview-1759--docs-spectrocloud.netlify.app/)
🎫 …
=> docs: updated oras statement DOC-909

docs/docs-content/release-notes.md
Node affinity is only meant for vSphere target clusters, adding the clarification in release notes.
=> Minor clarification for node affinity

docs/docs-content/clusters/cluster-groups/ingress-cluster-group.md, docs/docs-content/clusters/clusters.md
This PR addresses two minor issues reported in Slack. 
- [Ingress SSL Passthrough statement correction.](https://deploy-preview-1779--docs-spectrocloud.netlify.app/clusters/cluster-groups/ingress-cluster-group)
- [Proxy List sub-domain verbiage](https://deploy-preview-1779--docs-spectrocloud.netlify.app/clusters/#proxy-whitelist).
🎫 [DOC-911](https://spectrocloud.atlassian.net/browse/DOC-911)
🎫 [DOC-910](https://spectrocloud.atlassian.net/browse/DOC-910)
=> docs: minor touches DOC-910 DOC-911

CODEOWNERS, README.md
This PR makes the following changes:
- Updates `Approvers/Reviewers`README section
- Update `Images` assets path
- Moves `CODEOWNERS` file from `/docs` to root for a more standard layout
🎫 [DOC-913](https://spectrocloud.atlassian.net/browse/DOC-913)
=> chore: update approvers readme section and move CODEOWNERS (DOC-913)

docs/docs-content/clusters/edge/edge-configuration/cloud-init.md
Changed "Pass a Sensitive Information" to "Pass Sensitive Information".
This PR corrects a heading to remove the word "a".
💻 [Preview URL](https://deploy-preview-1805--docs-spectrocloud.netlify.app/clusters/edge/edge-configuration/cloud-init)
=> Correct a heading

src/components/PacksTable/PackTable.test.tsx, src/components/PacksTable/PacksTable.tsx
This PR fixed the issue when some packs are not in the git packs repository but are available through the API. These packs don't have a DisplayName value, nor do they have modified date information. 
💻 [Preview URL](https://deploy-preview-1819--docs-spectrocloud.netlify.app/integrations/deprecated-packs)
=> Deprecated packs style

.github/workflows/nightly-docker-build.yaml, .github/workflows/release.yaml, Caddyfile, Dockerfile-offline, docs/docs-content/vertex/install-palette-vertex/airgap/airgap.md, docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md
This PR adds documentation and logic for how to access the offline documentation.
💻 [Preview URL](https://deploy-preview-1830--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/airgap/offline-docs)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-922)
=> Offline Docs

docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
This PR updates the tutorial image and docker run command
=> docs: update the tutorial image and docker run command

Charts/Chart.yaml, Charts/templates/deployment.yaml, Charts/templates/job.yaml, Charts/templates/namespace.yaml, Charts/templates/service.yaml, Charts/values.yaml
This PR creates a simple helm chart that deploys Spectro Cloud docs. In addition is a CronJob task that will re-deploy the deployment once a day, ensuring docs are up to date with the upstream OCI.
=> Helm Chart Deployments

docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md, docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
This PR adds a warning about silent build failures due to insufficient disk space and tells users how to comment out versions they do not want. 
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PE-3086)
=> docs: add warning about silent build failures

docs/docs-content/vertex/install-palette-vertex/airgap/supplemental-packs.md, docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md
This PR adds a list of OVAs that customer may need for their VerteX airgap install.
💻 [Preview URL](https://deploy-preview-1848--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/airgap/supplemental-packs#additional-ovas)
🎫 [DOC-925](https://spectrocloud.atlassian.net/browse/DOC-925)
=> docs: updated airgap binaries and ova list DOC-925

docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md
This PR adds two new airgap packs to the non-FIPS list.
💻 [Preview URL](https://deploy-preview-1880--docs-spectrocloud.netlify.app/enterprise-version/install-palette/airgap/supplemental-packs)
=> docs: new airgap. packs

docs/docs-content/clusters/cluster-management/cluster-updates.md, docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md, docs/docs-content/clusters/edge/site-deployment/deploy-private-registry.md, docs/docs-content/clusters/edge/site-deployment/model-profile.md, docs/docs-content/integrations/byoos.md
This PR:
- Adds how-to for authenticating with a private registry
- Refactor the cluster update page
- [Private registry](https://6572190b9850ae007ea916cc--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/deploy-private-registry)
- [Cluster update](https://6572190b9850ae007ea916cc--docs-spectrocloud.netlify.app/clusters/cluster-management/cluster-updates)
- [BYOOS pack](https://6572190b9850ae007ea916cc--docs-spectrocloud.netlify.app/integrations/byoos)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/jira/software/c/projects/PE/issues/PE-3032?filter=myopenissues)
=> docs: add draft for private registry and refactor cluster update 

docs/docs-content/clusters/cluster-management/kubeconfig.md
This PR updates the Kubeconfig file behavior. For Cluster Admins, if OIDC is enabled, then the regular Kubeconfig file is unavailable. 
💻 [Preview URL](https://65774118294e941a3fd96824--docs-spectrocloud.netlify.app/clusters/cluster-management/kubeconfig)
🎫 [PEM-4198](https://spectrocloud.atlassian.net/browse/PEM-4198)
=> docs: update kubeconfig behavior PEM-4198

.github/workflows/container-prune.yaml
This PR introduces a running job that removes outdated instances of the nightly docs container. The image repository will continue to occupy space unless these images are pruned.  The new  GitHub Actions workflow introduced will be triggered upon completion of the Nighly Docker image creation. 
Before:
🎫 [DOC-957](https://spectrocloud.atlassian.net/browse/DOC-957)
=> Docker prune

docs/docs-content/clusters/cluster-management/cluster-updates.md, docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
This PR adds a limitation on edge cluster updates wrt CNI packs
Adds a note about VIPs in edge cluster definition. 
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-959)
=> Add notes about edge cluster update limitations

docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md
This PR adds the Argocd airgap binary and the updated version of Nginx to the supplemental pack's page. 
💻 [Preview URL](https://deploy-preview-1913--docs-spectrocloud.netlify.app/enterprise-version/install-palette/airgap/supplemental-packs)
=> chore: added arigap binary

.gitleaksignore, docs/docs-content/integrations/ngrok.md, docs/docs-content/integrations/portworx_operator.md
This PR refreshes the Portworx /w Operator documentation to the latest 3.x version.
💻 [Preview URL](https://deploy-preview-1917--docs-spectrocloud.netlify.app/integrations/portworx_operator)
🎫 [DOC-594](https://spectrocloud.atlassian.net/browse/DOC-594)
=> Update Portworx /w Operator docs

docs/docs-content/enterprise-version/install-palette/airgap/kubernetes-airgap-instructions.md, docs/docs-content/enterprise-version/install-palette/airgap/vmware-vsphere-airgap-instructions.md, docs/docs-content/vertex/install-palette-vertex/airgap/kubernetes-airgap-instructions.md, docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md
This PR removes the airgap binary version. Support wants customers to explicitly ask what version to use. 
🎫 [PEM-4239](https://spectrocloud.atlassian.net/browse/PEM-4239)
=> docs: removed version PEM-4239

docs/docs-content/clusters/edge/networking/vxlan-overlay.md, docs/docs-content/clusters/edge/site-deployment/deploy-private-registry.md, docs/docs-content/integrations/byoos.md, docs/docs-content/registries-and-packs/spectro-cli-reference.md
This PR:
- Adds an extra step for overlay enablement
- Adds extra context for registry parameter
- Fixes prerequisites
=> docs: miscellaneous updates (edge)

README.md, docs/docs-content/clusters/data-center/maas/install-manage-maas-pcg.md, docs/docs-content/clusters/data-center/openstack.md, docs/docs-content/clusters/data-center/vmware.md, docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/registries-and-packs/spectro-cli-reference.md, docs/docs-content/release-notes.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md, docusaurus.config.js
This patch makes the following changes:
- sets the `toc_max_heading_level` to default value 3
- removes redundant frontmatter settings for this level
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-938)
=> docs: set toc_max_heading_level to default value 3 for all docs DOC-938

docs/docs-content/palette-cli/install-palette-cli.md
This PR updates the Palette CLI install steps. Previously, the `login` command was only available from within the `pde` subcommand. The `login` command now sits in the root of the CLI menu.
=> docs: updated Palette CLI install

docs/docs-content/clusters/public-cloud/azure/azure-cloud.md, docs/docs-content/clusters/public-cloud/azure/azure.md, vale/styles/Vocab/Internal/accept.txt
This PR updates the Azure account registration steps to include the option of Azure Government. The steps are identical; the only difference is the drop-down option selected for cloud type. 
💻 [Preview URL](https://6595c4d518a1ba00a1b5ad89--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/azure-cloud)
🎫 [PCP-810](https://spectrocloud.atlassian.net/browse/PCP-810)
=> Azure account gov create

vale/styles/Vocab/Internal/accept.txt, vale/styles/Vocab/Internal/reject.txt
This PR updates the Vale rules to enforce README and disallow the usage of readme or Readme.
=> chore: updated Vale rule to standarize on README

docs/docs-content/clusters/edge/networking/local-registry.md, docs/docs-content/clusters/edge/networking/vxlan-overlay.md, docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md, docs/docs-content/integrations/harbor-edge.md
This PR adds several known issues related to 4.2 edge features. 
💻 [Preview URL](https://659859d87241e3465d626dea--docs-spectrocloud.netlify.app/clusters/edge/networking/vxlan-overlay#limitations)
🎫 Jira Tickets:
- https://spectrocloud.atlassian.net/browse/PE-3366
- https://spectrocloud.atlassian.net/browse/PE-3337
=> docs: add several known issues

docs/docs-content/glossary-all.md
This PR removes the PCG-E paragraph from the glossary-all.md file, as this concept is no longer used.
💻 [Add Preview URL](https://deploy-preview-2019--docs-spectrocloud.netlify.app/glossary-all)
=> docs: removed PCG-E from glossary

docs/docs-content/clusters/data-center/nutanix/nutanix.md, docs/docs-content/clusters/edge/networking/vxlan-overlay.md, docs/docs-content/integrations/harbor-edge.md, docs/docs-content/introduction/introduction.md, docusaurus.config.js, src/css/custom.scss, src/css/dark-mode.scss, src/css/light-mode.scss, src/theme/Admonition/Icon/TechPreview.js, src/theme/Admonition/Type/TechPreview.js, src/theme/Admonition/Types.js, src/theme/Admonition/index.js
This PR includes a custom admonition for Tech Preview content.
```
:::preview
:::
```
💻 [Nutanix](https://deploy-preview-2017--docs-spectrocloud.netlify.app/clusters/data-center/nutanix/)
💻 [Harbor Edge](https://deploy-preview-2017--docs-spectrocloud.netlify.app/integrations/harbor-edge/)
💻 [Vxlan Overlay](https://deploy-preview-2017--docs-spectrocloud.netlify.app/clusters/edge/networking/vxlan-overlay/)
🎫 [DOC-1017](https://spectrocloud.atlassian.net/browse/DOC-1017)
=> chore: Add a custom admonition for Tech Preview content

.prettierignore, Makefile, README.md, package.json
This PR manually backports the Prettier docs to v.4.1 (PR#2104).
=> Backport Prettier docs to v.4.1

vale/styles/spectrocloud/admonitions.yml
This PR adds a custom Vale rule to check for admonitions of type `:::note` and suggests using `:::info` or another approved admonition.
🎫 [DOC-1001](https://spectrocloud.atlassian.net/browse/DOC-1001)
=> Add a Vale rule to check for admonitions of type `:::note`

docs/docs-content/clusters/cluster-management/backup-restore/create-cluster-backup.md, docs/docs-content/clusters/cluster-management/backup-restore/restore-cluster-backup.md, docs/docs-content/integrations/ubuntu.md, docs/docs-content/registries-and-packs/registries/registries.md
This PR fixes minor items that were provided through Slack feedback. 
- Removed Cox Edge from Terraform block in [Ubuntu packs page](https://deploy-preview-2194--docs-spectrocloud.netlify.app/integrations/ubuntu#terraform).
- Removed an incorrect sentence from [Backup index page](https://deploy-preview-2194--docs-spectrocloud.netlify.app/clusters/cluster-management/backup-restore/).
- [Added FIPS OCI registry to table](https://deploy-preview-2194--docs-spectrocloud.netlify.app/registries-and-packs/registries/#default-registries).
💻 [Preview URL](https://deploy-preview-2194--docs-spectrocloud.netlify.app)
=> Backup and other fix

docs/docs-content/vm-management/vm-packs-profiles/create-vmo-profile.md
This PR adds. the requirement that an existing spectro proxy pod must be restarted if the user wants to add the vmo to the cluster. 
💻 [Preview URL](https://deploy-preview-2193--docs-spectrocloud.netlify.app/vm-management/vm-packs-profiles/create-vmo-profile)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PEM-4221)
=> docs: add note that exiting proxy pod must be restarted for vmo

docs/docs-content/clusters/cluster-management/update-k8s-cluster.md, docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md
This PR makes the following changes.
- Adds Podman to Deploy Cluster and Deploy Cluster Profile Updates  tutorials
- Updates the tutorial version
- Clean up unnecessary  break tags
💻 [Preview URL - Deploy a Cluster](https://deploy-preview-2216--docs-spectrocloud.netlify.app/clusters/public-cloud/deploy-k8s-cluster)
💻 [Preview URL - Deploy Cluster Profile Updates](https://deploy-preview-2216--docs-spectrocloud.netlify.app/clusters/cluster-management/update-k8s-cluster)
🎫 [DOC-1009](https://spectrocloud.atlassian.net/browse/DOC-1009)
🎫 [DOC-1010](https://spectrocloud.atlassian.net/browse/DOC-1009)
=> docs: add podman to tutorials DOC-1010 DOC-1009

vale/styles/Vocab/Internal/accept.txt
This PR manually backports changes from [PR#2246](https://github.com/spectrocloud/librarium/pull/2246).
=> Backport Vale updates to version 4.1

vale/styles/Vocab/Internal/accept.txt
This PR manually backports changes from [PR#2246](https://github.com/spectrocloud/librarium/pull/2246).
=> Backport Vale updates to version 4.2

docs/docs-content/spectro-downloads.md
This PR updates the download link for Palette CLI from 4.2.2 to 4.2.4.
💻 [Downloads](https://deploy-preview-2257--docs-spectrocloud.netlify.app/spectro-downloads)
🎫 [DOC-1077](https://spectrocloud.atlassian.net/browse/DOC-1077)
[DOC-1077]: https://spectrocloud.atlassian.net/browse/DOC-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Palette CLI download link

vale/styles/spectrocloud/acronym.yml
This PR adds a vale rule that ensures acronyms are defined using title case, as described in our [style guide](https://spectrocloud.atlassian.net/wiki/spaces/DE/pages/1765933057/Spectro+Cloud+Internal+Style+Guide#Acronyms).
This rule applies to acronyms of 2-5 characters length. 
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-940)
=> chore: add acronym rule to vale DOC-940

docs/docs-content/clusters/edge/edge.md
This PR addresses feedback. The link is no longer available and instead links to an Intel Portal.
💻 [Preview URL](https://deploy-preview-2344--docs-spectrocloud.netlify.app/clusters/edge/)
🎫 [DOC-1093](https://spectrocloud.atlassian.net/browse/DOC-1093)
[DOC-1093]: https://spectrocloud.atlassian.net/browse/DOC-1093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: removing link

vale/styles/spectrocloud/condescending.yml
This PR removes `---` from a Vale rule that got added by accident.
=> Vale Rule Fix

src/css/custom.scss, src/css/dark-mode.scss, src/css/light-mode.scss, src/theme/Admonition/Icon/TechPreview.js, src/theme/Admonition/Type/TechPreview.js
This PR updates the TechPreview component to accept custom text if necessary. If no custom text is provided, the admonition displays our standard message: *This is a Tech Preview feature and is subject to change. Do not use this feature in production workloads.*
🎫 [DOC-1099](https://spectrocloud.atlassian.net/browse/DOC-1099)
[DOC-1099]: https://spectrocloud.atlassian.net/browse/DOC-1099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update the TechPreview component to also accept custom text

docs/docs-content/clusters/edge/site-deployment/initial-setup.md
This PR adds the command to bring up the initial setup TUI before cluster deployment. 
💻 [Preview URL for Page](https://65ea6527f899fb139e2688ed--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/initial-setup)
🎫 [PE-3694](https://spectrocloud.atlassian.net/browse/PE-3694)
[PE-3694]: https://spectrocloud.atlassian.net/browse/PE-3694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add the command to bring up TUI before cluster deployment

vale/styles/spectrocloud/longform.yml
This PR adds a Vale rule to avoid the utilization of short-form commands, as described in our [internal style guide](https://spectrocloud.atlassian.net/wiki/spaces/DE/pages/1765933057/Spectro+Cloud+Internal+Style+Guide#Commands-%26-Parameters).
The rule applies to short-form flags (1-3 characters length) that are preceded by a word. The flag can appear multiple times. Below are presented a few illustrative examples that would trigger the rule.
- palette -d
- palette -ALL
- palette -d -f
- palette -lls -d -ALL
When the short-form flag is not preceded by a word, as for example in the [Palette CLI PCG commands](https://docs.spectrocloud.com/palette-cli/commands/pcg) page, the rule is not triggered. There are also commands that don't have long-form flags (e.g.,`ls` command), which were …
=> chore: add vale rule - commands longform DOC-941

docs/docs-content/clusters/edge/upgrade-behavior.md
This PR documents a known issue for PE-4011. Updates to the OS pack and K8s pack in the stages section trigger a repave instead of a reboot. 
🎫 [PE-4011](https://spectrocloud.atlassian.net/browse/PE-4011)
🎫 [PE-3874](https://spectrocloud.atlassian.net/browse/PE-3874)
[PE-4011]: https://spectrocloud.atlassian.net/browse/PE-4011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PE-3874]: https://spectrocloud.atlassian.net/browse/PE-3874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: address PE-4011 and PE-3874

.gitleaksignore, docs/docs-content/integrations/k3s.md, docs/docs-content/integrations/kubernetes-edge.md, docs/docs-content/integrations/kubernetes.md, docs/docs-content/integrations/rke2.md
This PR updates the PXK and PXK-E packs docs to include K8s v.1.29 and fixes alignment in these topics.
💻 [Palette eXtended Kubernetes](https://65f89b3e735a940c0aa91024--docs-spectrocloud.netlify.app/integrations/kubernetes/)
💻 [Palette eXtended Kubernetes - Edge](https://65f89b3e735a940c0aa91024--docs-spectrocloud.netlify.app/integrations/kubernetes-edge/)
🎫 [DOC-1089](https://spectrocloud.atlassian.net/browse/DOC-1089)
[DOC-1089]: https://spectrocloud.atlassian.net/browse/DOC-1089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Update the PXK and PXK-E packs docs

.gitleaksignore, docs/docs-content/enterprise-version/enterprise-version.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/integrations/kubernetes.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR documents a new feature that was added to the Palette CLI. When used inside an airgap support VM. The CLI will automatically detect Harbor and OCI registry values hosted locally. Users can now skip filling out these values. 
One additional change is the removal of a value that triggered get leaks in `/integrations/Kubernetes.md`. The value was replaced with `*******`.
- [VMware Install Instructions](https://65f9f927568faa17801ba93f--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/install)
- [Vertex VMware Install Instructions](https://65f9f927568faa17801ba93f--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/install)
💻 [Preview URL for Page](https://65f9f927568faa17801ba93f--docs-spectrocloud.netlify.app/vertex/install …
=> Palette CLI Airgap auto detect

docs/docs-content/integrations/hello-universe.md, docs/docs-content/integrations/ngrok.md
This PR introduces a new custom content page for the **Hello Universe** pack and addresses an issue with the title of the custom content page of the **ngrok** pack.
💻 [Hello Universe](https://deploy-preview-2433--docs-spectrocloud.netlify.app/integrations/hello-universe)
💻 [ngrok](https://deploy-preview-2433--docs-spectrocloud.netlify.app/integrations/ngrok)
🎫 [DOC-1111](https://spectrocloud.atlassian.net/browse/DOC-1111)
[DOC-1111]: https://spectrocloud.atlassian.net/browse/DOC-1111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add hello universe pack page, fix ngrok pack title

docs/docs-content/clusters/edge/edge-configuration/cloud-init.md, vale/styles/spectrocloud/colon.yml
This PR ensures that colons are only used to introduce a list. It specifically looks for a colon, followed by two new line characters, and then any character that is not a dash or a new line. I think this is also the most frequent mistake for us which is to introduce a command with a colon. 
It does not try to catch instances of inline colon usage such as `There are three kinds of apples: fuji, honey crisp, and cosmic crisp`, which I think is permissible and avoids flagging all the false positives in code blocks. 
It is possible that this rule could lead to some false positives in code snippets, but there should be only very few of these, and i think we can usually remove the extra new line character if they occur. 
N/A
🎫 [DOC-1114](https://spectrocloud.atlassian.net/browse/DOC-1114)
Can …
=> chore: add vale rule to enforce colon usage

docs/docs-content/component.md, docs/docs-content/palette-cli/install-palette-cli.md, docs/docs-content/registries-and-packs/advanced-configuration.md, docs/docs-content/registries-and-packs/spectro-cli-reference.md, docs/docs-content/spectro-downloads.md
This PR updates download URLs and other references to Palette CLI and Palette Edge CLI.
💻 [Downloads](https://6602e8b3aa38174d4176f56c--docs-spectrocloud.netlify.app/spectro-downloads)
💻 [Advanced CLI Configuration](https://6602e8b3aa38174d4176f56c--docs-spectrocloud.netlify.app/registries-and-packs/advanced-configuration)
💻 [Palette CLI: Installation](https://6602e8b3aa38174d4176f56c--docs-spectrocloud.netlify.app/palette-cli/install-palette-cli)
💻 [Spectro Cloud CLI Tool](https://6602e8b3aa38174d4176f56c--docs-spectrocloud.netlify.app/registries-and-packs/spectro-cli-reference)
💻 [Palette Components Compatibility Matrix](https://6602e8b3aa38174d4176f56c--docs-spectrocloud.netlify.app/component)
🎫 [DOC-1121](https://spectrocloud.atlassian.net/browse/DOC-1121) …
=> Update download URLs

docs/docs-content/release-notes.md, docs/docs-content/troubleshooting/pcg.md
This PR adds a known issue to the release notes. Additionally, a new troubleshooting section explaining how to address the issue has been added.
- [Release Notes](https://660440a31c095c134cbb38ec--docs-spectrocloud.netlify.app/release-notes)
- [Troubleshooting](https://660440a31c095c134cbb38ec--docs-spectrocloud.netlify.app/troubleshooting/pcg#scenario---vmware-resources-remain-after-cluster-deletion)
💻 [Preview URL for Page](https://660440a31c095c134cbb38ec--docs-spectrocloud.netlify.app/release-notes)
🎫 [DOC-1127](https://spectrocloud.atlassian.net/browse/DOC-1127)
This is release PR.
[DOC-1127]: https://spectrocloud.atlassian.net/browse/DOC-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1127

docs/docs-content/introduction/introduction.md
This patch adds a call out box to the Docs landing page. It also adds 2 sentences to break up the sequential headers.
This patch adds a call out box to the Docs landing page.
It also adds 2 sentences to break up the sequential headers.
💻 [Landing Page](https://deploy-preview-2487--docs-spectrocloud.netlify.app/)
🎫 [DOC-1124](https://spectrocloud.atlassian.net/browse/DOC-1124)
[DOC-1124]: https://spectrocloud.atlassian.net/browse/DOC-1124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add Getting Started callout to landing page DOC-1124

package-lock.json, package.json
This PR addresses the backport issues for PR #2427
=> [version-3-4]chore: bump sass from 1.69.5 to 1.72.0 (#2427)

docs/docs-content/integrations/longhorn.md
This PR adds a troubleshooting section for the Longhorn pack that users need to change the image reference in the Longhorn pack to reference the Harbor registry. 
💻 [Longhorn](https://6605e2200798463e24d9c977--docs-spectrocloud.netlify.app/integrations/longhorn)
🎫 [DOC-1130](https://spectrocloud.atlassian.net/browse/DOC-1130)
[DOC-1130]: https://spectrocloud.atlassian.net/browse/DOC-1130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add note to change Longhorn images to reference harbor

docs/docs-content/security-bulletins/cve-reports.md
This PR adds the security advisory for recent critical CVE on x-utils package used in our OS images.
💻 [Preview URL](https://deploy-preview-2557--docs-spectrocloud.netlify.app/security-bulletins/cve-reports#april-2-2024---cve-2024-3094-malicious-code-was-discovered-in-the-upstream-tarballs-of-xz---10-cvss)
No JIRA ticket.
Not required
=> xz-utils security advisory

.github/workflows/visual-comparison.yaml, tsconfig.eslint.json, visuals/screenshot.api.spec.ts, visuals/screenshot.docs.spec.ts
This PR fixes a couple of things that surfaced during the backport.
- Eslint was not capturing playwright config and test files.
- Fixed minor eslint errors, such as import vs require and removing async from functions not using await in the test run.
- The CI trigger logic was not working correctly. The final logic is to only trigger when label is added.
- The branch delete logic was not cleaning up because the report was stored using `github.ref_name`. This variable changes context depending on a PR or not. What we need is `github. GITHUB_HEAD_REF` as this will always pull down the branch name.
=> ci: fix branch determination logic

package-lock.json, package.json
Reverts spectrocloud/librarium#2543
=> Revert "chore: bump semantic-release from 20.1.3 to 23.0.6"

vale/styles/spectrocloud/oxford-comma.yml
This PR adds a Vale rule to check usage of the Oxford commas.
🎫 [DOC-1115](https://spectrocloud.atlassian.net/browse/DOC-1115)
[DOC-1115]: https://spectrocloud.atlassian.net/browse/DOC-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implement a Vale rule for the Oxford comma

docs/docs-content/integrations/rook-ceph.md, docs/docs-content/release-notes.md
This PR documents a known issue and workaround for a rook-ceph pack. 
💻 [Rook-Ceph](https://6615c57476886c4f45b2ae96--docs-spectrocloud.netlify.app/integrations/rook-ceph)
🎫 [PE-4202](https://spectrocloud.atlassian.net/browse/PE-4202)
[PE-4202]: https://spectrocloud.atlassian.net/browse/PE-4202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add rook-ceph known issue

docs/docs-content/release-notes.md
This PR adds the known issue that Edge clusters don't work on Arm64. 
💻 [Page](https://deploy-preview-2614--docs-spectrocloud.netlify.app/release-notes)
🎫 [PE-4233](https://spectrocloud.atlassian.net/browse/PE-4233)
[PE-4233]: https://spectrocloud.atlassian.net/browse/PE-4233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add Arm64 known issue

docs/docs-content/registries-and-packs/deploy-pack.md
This PR removes the requirement for an empty 'spectro-packs' project in Harbor registries (Deploy a Custom Pack tutorial), which was fixed in 4.3.
💻 [Deploy a Custom Pack](https://deploy-preview-2657--docs-spectrocloud.netlify.app/registries-and-packs/deploy-pack)
=> docs: remove spectro-packs project requirement

docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md, docs/docs-content/vertex/upgrade/upgrade-vmware/airgap.md
This PR removes an unnecessary prerequisite from the Enterprise and VerteX guides on upgrading self-hosted Palette.
=> Remove unnecessary prerequisite from VMware airgap guide

docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md, src/css/custom.scss
This PR reduces the line height for code elements so that our code does not look like it has double space. Also fixes an indentation issue in the EdgeForge documentation. 
💻 [Build Edge Artifacts](https://deploy-preview-2737--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/)
🎫 [DOC-1168](https://spectrocloud.atlassian.net/browse/DOC-1168)
[DOC-1168]: https://spectrocloud.atlassian.net/browse/DOC-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: fix css spacing issue and correct edge forge indentation

docs/docs-content/integrations/portworx_operator.md
- [chore: Fix broken links (#2778)](https://github.com/spectrocloud/librarium/pull/2778)
=> [version-4-2] chore: Fix broken links (#2778)

docs/docs-content/integrations/portworx_operator.md
- [chore: Fix broken links (#2778)](https://github.com/spectrocloud/librarium/pull/2778)
=> [version-4-1] chore: Fix broken links (#2778)

docs/docs-content/integrations/portworx_operator.md
- [chore: Fix broken links (#2778)](https://github.com/spectrocloud/librarium/pull/2778)
=> [version-4-0] chore: Fix broken links (#2778)

docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md, docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md
This PR fixes an indentation issue in the site-user-data page. 
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-1173)
=> docs: fix userdata indentation

docs/api-content/api-docs/3-postman-collection.md
This PR updates the postman link for postman collection 4.3. 
🎫 [Jira Ticket](DOC-1175)
=> docs: update postman link 4.3

docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/checklist.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md, docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md, docs/docs-content/vertex/system-management/ssl-certificate-management.md
This PR adds instructions on providing a custom SSL certificate to the airgap support VM.
- [VerteX Airgap Checklist](https://deploy-preview-2846--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist/)
- [Palette Airgap Checklist](https://deploy-preview-2846--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/airgap-install/checklist/)
- [VerteX Airgap Setup Guide](https://deploy-preview-2846--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions/)
- [Palette Airgap Setup Guide](https://deploy-preview-2846--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instruction …
=> Airgap Support VM custom SSL Certs

docs/docs-content/automation/palette-cli/commands/validator.md
This PR updates the Validator URL in all documentation spots. 
🎫 [PAD-2019](https://spectrocloud.atlassian.net/browse/PAD-219)
=> chore: update validator URL

.github/workflows/clean-up-report.yaml, .github/workflows/release-branch-pr.yaml, scripts/netlify.sh, scripts/netlify_add_branch.sh, scripts/netlify_remove_branch.sh
This PR updates Netlify logic to support the Netlify collab drawer on release branch PRs. A limitation on the Netlify platform is to only support the collab drawer on deploy-previews generated from a PR. You cannot get the drawer when triggering a Netlify build manually (API, CLI, UI).  The other catch is the automatic Netlify triggers from a PR, only work for a PR against a default branch OR, a branch you have specified in Netlify to have branch deploy deatures.
The workaround is to explicitly add a branch as a deploy branch in the UI. The logic in this PR handles this manual insertion through a script and ensures the branch is removed after a PR is merged so the branch deploy list does not get polluted. 
The following is a screenshot of where in Netlify these branches are updated in the …
=> ci: updated logic to enable Netlify previews for release branch PRs

README.md, docs/docs-content/user-management/authentication/authorization-token.md
This PR fixes the backport issue with PR #2896
=> [version-4-0] docs: Update authorization-token.md (#2896)

_partials/index.ts, docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md, docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md, docs/docs-content/clusters/edge/local-ui/cluster-management/update-cluster.md, docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md
This PR documents the new functionality of updating profile variable values in existing clusters in local UI.
💻 [Update Local Cluster](https://deploy-preview-2911--docs-spectrocloud.netlify.app/clusters/edge/local-ui/cluster-management/update-cluster/)
🎫 [PE-4326](https://spectrocloud.atlassian.net/browse/PE-4326)
[PE-4326]: https://spectrocloud.atlassian.net/browse/PE-4326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Day-2 operations for profile variables

plugins/packs-integrations.js
This is added to fix a small compilation issue. since docusaurus got upgraded in master branch, after master branch merge with the private branch, there was a small issue encountered coz of which compilation failed. 
https://github.com/facebook/docusaurus/pull/9931
So, added allContentLoaded method as part of plugin lifecycle.
=> compilation issue, since docusaurus upgraded in master branch

_partials/index.ts, docs/docs-content/enterprise-version/upgrade/upgrade.md, docs/docs-content/vertex/upgrade/upgrade.md
This PR updates the upgrade matrices for self-hosted and VerteX.
💻 [Self-Hosted Palette > Upgrade](https://deploy-preview-2923--docs-spectrocloud.netlify.app/enterprise-version/upgrade/)
💻 [Palette VerteX > Upgrade](https://deploy-preview-2923--docs-spectrocloud.netlify.app/vertex/upgrade/)
🎫 [DOC-1195](https://spectrocloud.atlassian.net/browse/DOC-1195)
[DOC-1195]: https://spectrocloud.atlassian.net/browse/DOC-1195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update the self-hosted and VerteX upgrade matrices

docs/docs-content/clusters/data-center/nutanix/register-nutanix-cloud.md, docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
Add details that only an Operations Admin is allowed to register a Nutanix cloud. We should link to a page that explains the difference between the different tenant admin roles: I only found [this one](https://docs.spectrocloud.com/vertex/system-management/account-management/#system-administrators), but it's relevant to VerteX only. Do we have a similar page for Palette?
[Register Nutanix Cloud](https://docs.spectrocloud.com/clusters/data-center/nutanix/register-nutanix-cloud/#register-the-cloud)
=> Clarity on which system administrator role can register Nutanix cloud

docs/docs-content/automation/terraform/terraform.md
This PR adds a Gov Cloud support introduction section to the Terraform index page.
💻 [Terraform](https://deploy-preview-2927--docs-spectrocloud.netlify.app/automation/terraform/)
🎫 [PLT-235](https://spectrocloud.atlassian.net/browse/PLT-235)
[PLT-235]: https://spectrocloud.atlassian.net/browse/PLT-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add introduction to govcloud terraform support

docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md, docs/docs-content/integrations/calico.md, docs/docs-content/integrations/rook-ceph.md
This PR adds documentation on how to create bind mounts. 
🎫 [DOC-1201](https://spectrocloud.atlassian.net/browse/DOC-1201)
[DOC-1201]: https://spectrocloud.atlassian.net/browse/DOC-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: document creating bind mount 

.github/workflows/pull_request.yaml, docs/docs-content/architecture/palette-public-ips.md, docs/docs-content/enterprise-version/install-palette/install-palette.md, docs/docs-content/integrations/metallb.md, docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md, package-lock.json, package.json
This PR updates the domain list table to reflect the [newer official k8s registry](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/)  `registry.k8s.io` .
- [Palette Proxy](https://deploy-preview-2966--docs-spectrocloud.netlify.app/enterprise-version/install-palette/#proxy-requirements)
- [VerteX Proxy](https://deploy-preview-2966--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/#proxy-requirements)
Other changes include:
- [Fixed](https://deploy-preview-2966--docs-spectrocloud.netlify.app/architecture/palette-public-ips/) a bug where the domain table was double rendered. 
- Added a link to the gRPC and Proxy page 
💻 [Preview URL for Page](https://deploy-preview-2966--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/#proxy-requirements)
🎫 [Jira …
=> docs: updated proxy domain table

docs/docs-content/integrations/metallb.md, docs/docs-content/integrations/microk8s.md
This PR updates the version of the Microk8s pack in the Terraform snippet as version 1.28 will no longer be included in 4.4.
💻 [Microk8s](https://deploy-preview-3003--docs-spectrocloud.netlify.app/integrations/microk8s/)
=> docs: update pack version in the terraform snippet

_partials/index.ts
This PR removes the _partials/index.ts from the release-4-4 branch to avoid gitignore conflicts.
=> Remove _partials/index.ts

docs/docs-content/clusters/edge/architecture.md, docs/docs-content/clusters/edge/edge.md, docs/docs-content/clusters/edge/edgeforge-workflow/edgeforge-workflow.md
This PR highlights CIS hardening that we apply to Edge artifacts by default. 
💻 [Edge Overview](https://deploy-preview-3034--docs-spectrocloud.netlify.app/clusters/edge/)
- [EdgeForge](https://deploy-preview-3034--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow)
🎫 [PE-4303](https://spectrocloud.atlassian.net/browse/PE-4303)
[PE-4303]: https://spectrocloud.atlassian.net/browse/PE-4303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: highlight CIS hardening

docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md, docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md
=> Backport alignment 3 4

docs/docs-content/clusters/pcg/deploy-pcg/vmware.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/vmware-system-requirements.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/vmware-system-requirements.md
This PR explicitly states that vSphere 6.7U3 is supported.
- [VerteX vSphere Permissions](https://deploy-preview-3053--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/vmware-system-requirements/)
- [Palette vSphere Permissions](https://deploy-preview-3053--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/vmware-system-requirements/)
- [PCG vSphere Requirement](https://deploy-preview-3053--docs-spectrocloud.netlify.app/clusters/pcg/deploy-pcg/vmware/)
🎫 [DOC-1216](https://spectrocloud.atlassian.net/browse/DOC-1216)
[DOC-1216]: https://spectrocloud.atlassian.net/browse/DOC-1216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> vSphere Version 6 series support

docs/docs-content/clusters/edge/networking/vxlan-overlay.md
This PR adds RKE2 as a supported K8s distro to enable the Overlay Network on Edge clusters.
🎫 [DOC-1229](https://spectrocloud.atlassian.net/browse/DOC-1229)
[DOC-1229]: https://spectrocloud.atlassian.net/browse/DOC-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RKE2 Overlay Network Support

docs/docs-content/clusters/edge/networking/vxlan-overlay.md
This PR removes a previous limitation of network overlay. 
🎫 [PE-4568](https://spectrocloud.atlassian.net/browse/PE-4568)
[PE-4568]: https://spectrocloud.atlassian.net/browse/PE-4568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: remove overlay limitation

docs/docs-content/clusters/data-center/vmware/vmware.md, docs/docs-content/vertex/supported-platforms.md
This PR adds a VMware vSphere supported versions table to the VMware index page and fixes the vSphere 6.7U3 version in the Vertex Supported Platforms page.
Note: disregard the name of the branch.
💻 [VMware](https://deploy-preview-3101--docs-spectrocloud.netlify.app/clusters/data-center/vmware/)
💻 [VerteX Supported Platforms](https://deploy-preview-3101--docs-spectrocloud.netlify.app/vertex/supported-platforms/)
=> docs: add vsphere supported versions table

docs/docs-content/integrations/aws-autoscaler.md
This PR addresses the backport issues with PR #3022.
💻 [Autoscaler](https://deploy-preview-3115--docs-spectrocloud.netlify.app/integrations/aws-autoscaler/?version=1.29.x)
=> [version-4-1] backport docs: refactor and update aws cluster autoscaler pack page (#3022)

docs/docs-content/integrations/aws-autoscaler.md
This PR addresses the backport issues with PR #3022.
💻 [Autoscaler](https://deploy-preview-3116--docs-spectrocloud.netlify.app/integrations/aws-autoscaler/?version=1.29.x)
=> [version-4-0] backport docs: refactor and update aws cluster autoscaler pack page (#3022)

docs/docs-content/clusters/edge/site-deployment/deploy-cluster.md
This PR updates the Edge VMware tutorial to use the latest version of the tutorials container. 
🎫 [PE--4577](https://spectrocloud.atlassian.net/browse/PE-4577)
=> docs: update tutorials container version

docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md
This PR incorporated feedback from @JPedro2 provided in PR #3061 
=> docs: feedback from Pedro

docs/docs-content/troubleshooting/palette-upgrade.md
This PR updates the debug steps to ask users to wait for the MongoDB pod replication to complete.
💻 [Palette Upgrade > Volume Attachment Errors Volume in VMware Environment](https://deploy-preview-3165--docs-spectrocloud.netlify.app/troubleshooting/palette-upgrade/#volume-attachment-errors-volume-in-vmware-environment)
🎫 [PLT-1265](https://spectrocloud.atlassian.net/browse/PLT-1265)
[PLT-1265]: https://spectrocloud.atlassian.net/browse/PLT-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Add a note about MongoDB replication completion

docs/docs-content/troubleshooting/palette-upgrade.md
- [docs: Add a note about MongoDB replication completion (#3165)](https://github.com/spectrocloud/librarium/pull/3165)
=> [version-4-2] Add a note about MongoDB replication completion (#3165)

docs/docs-content/integrations/prometheus-operator.md, plugins/packs-integrations.js, src/components/PacksInformation/PacksInformation.tsx, src/components/PacksReadme/PacksReadme.antd.css, src/components/PacksReadme/PacksReadme.module.scss, src/components/PacksReadme/PacksReadme.tsx, src/components/Technologies/CategorySelector/CustomLabel.module.scss, src/components/Technologies/CategorySelector/FilterSelect.tsx, src/components/Technologies/CategorySelector/filterSelect.antd.css, src/components/Technologies/Technologies.tsx, src/components/Technologies/TechnologyCard.tsx, src/components/Technologies/technologies.antd.css
This integrates the version change in the *.md file with the packs detail information react component version dropdown.
So, had to change the md file with the query string "parent", and changed the router in plugin as well.
The refresh issue which we had with the build serve is fixed, i mean while refreshing in dark mode, the antd components were little bit jumbled and was not properly aligned. This issue was fixed.
This PR ....
Packs List
🎫 [Jira Ticket](PAC-1893)
=> PAC-1893-integrate custom readme versions with dropdown versions

docs/docs-content/troubleshooting/cluster-deployment.md, docs/docs-content/troubleshooting/edge.md, docs/docs-content/troubleshooting/nodes.md, docs/docs-content/troubleshooting/palette-dev-engine.md, docs/docs-content/troubleshooting/pcg.md, docs/docs-content/troubleshooting/troubleshooting.md
This PR documents the steps for deleting the incorrectly created `kubernetes` load balancer and public IP from the associated Azure account.
💻 [Scenario - Incorrect LoadBalancer kubernetes Created by Azure Cloud Controller Manager](https://deploy-preview-3252--docs-spectrocloud.netlify.app/troubleshooting/nodes/#scenario---incorrect-loadbalancer-kubernetes-created-by-azure-cloud-controller-manager)
🎫 [PCP-3149](https://spectrocloud.atlassian.net/browse/PCP-3149)
[PCP-3149]: https://spectrocloud.atlassian.net/browse/PCP-3149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Steps for deleting the incorrectly created `kubernetes` LB and public IP

docs/docs-content/troubleshooting/cluster-deployment.md, docs/docs-content/troubleshooting/edge.md, docs/docs-content/troubleshooting/enterprise-install.md, docs/docs-content/troubleshooting/nodes.md, docs/docs-content/troubleshooting/palette-dev-engine.md, docs/docs-content/troubleshooting/pcg.md, docs/docs-content/troubleshooting/troubleshooting.md
- [Clean up markup and alignment in the Troubleshooting section (#3255)](https://github.com/spectrocloud/librarium/pull/3255)
=> [version-4-2] Clean up markup and alignment in the Troubleshooting section (#3255)

docs/docs-content/troubleshooting/cluster-deployment.md, docs/docs-content/troubleshooting/enterprise-install.md, docs/docs-content/troubleshooting/nodes.md, docs/docs-content/troubleshooting/palette-dev-engine.md, docs/docs-content/troubleshooting/palette-upgrade.md, docs/docs-content/troubleshooting/pcg.md, docs/docs-content/troubleshooting/troubleshooting.md
- [Clean up markup and alignment in the Troubleshooting section (#3255)](https://github.com/spectrocloud/librarium/pull/3255)
=> [version-4-1] Clean up markup and alignment in the Troubleshooting section (#3255)

docs/docs-content/troubleshooting/cluster-deployment.md, docs/docs-content/troubleshooting/edge.mdx, docs/docs-content/troubleshooting/enterprise-install.md, docs/docs-content/troubleshooting/nodes.md, docs/docs-content/troubleshooting/palette-dev-engine.md, docs/docs-content/troubleshooting/palette-upgrade.md, docs/docs-content/troubleshooting/pcg.md, docs/docs-content/troubleshooting/troubleshooting.md
- [Clean up markup and alignment in the Troubleshooting section (#3255)](https://github.com/spectrocloud/librarium/pull/3255)
=> [version-4-0] Clean up markup and alignment in the Troubleshooting section (#3255)

docs/docs-content/troubleshooting/cluster-deployment.md, docs/docs-content/troubleshooting/nodes.md, docs/docs-content/troubleshooting/palette-dev-engine.md, docs/docs-content/troubleshooting/palette-upgrade.md, docs/docs-content/troubleshooting/pcg.md, docs/docs-content/troubleshooting/troubleshooting.md
- [Clean up markup and alignment in the Troubleshooting section (#3255)](https://github.com/spectrocloud/librarium/pull/3255)
=> [version-3-4] Clean up markup and alignment in the Troubleshooting section (#3255)

docs/api-content/api-docs/1-introduction.md, src/components/IconMapper/dynamicFontAwesomeImports.js
This PR adds a clarification that Edge management APIs are only available to airgapped Edge hosts. 
=> docs: add note that edge management apis are not available 4.3

.github/workflows/nightly-docker-build.yaml
This PR fixes the backport issues from PR #3204
=> [version-4-2] chore: bump docker/build-push-action from 5 to 6 (#3204)

.github/workflows/nightly-docker-build.yaml
This PR solves the backport issues from PR #3204
=> [version-4-1] chore: bump docker/build-push-action from 5 to 6 (#3204)

.github/workflows/nightly-docker-build.yaml
This PR fixes the backport issue from PR #3204
=> [version-4-0] chore: bump docker/build-push-action from 5 to 6 (#3204)

docs/docs-content/clusters/edge/site-deployment/cluster-deployment.md
This PR clarifies that DHCP is not supported when Edge hosts have more than one NIC. 
🎫 [PE-4680](https://spectrocloud.atlassian.net/issues/PE-4680?filter=11900)
[PE-4680]: https://spectrocloud.atlassian.net/browse/PE-4680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add additional qualifier for network environments

docs/docs-content/user-management/saml-sso/palette-sso-with-adfs.md, docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md, docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md, docs/docs-content/user-management/saml-sso/palette-sso-with-okta-saml.md, docs/docs-content/user-management/saml-sso/palette-sso-with-okta.md, docs/docs-content/user-management/saml-sso/palette-sso-with-onelogin.md
- [Fix markup and alignment in User Management (SSO) and add HTTPS and TLS requirements (#3345)](https://github.com/spectrocloud/librarium/pull/3345)
=> [version-4-2] Fix markup and alignment in User Management (SSO) and add HTTPS and TLS requirements (#3345)

docs/docs-content/user-management/saml-sso/palette-sso-with-adfs.md, docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md, docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md, docs/docs-content/user-management/saml-sso/palette-sso-with-okta-saml.md, docs/docs-content/user-management/saml-sso/palette-sso-with-okta.md, docs/docs-content/user-management/saml-sso/palette-sso-with-onelogin.md
- [Fix markup and alignment in User Management (SSO) and add HTTPS and TLS requirements (#3345)](https://github.com/spectrocloud/librarium/pull/3345)
=> [version-4-1] Fix markup and alignment in User Management (SSO) and add HTTPS and TLS requirements (#3345)

docs/docs-content/clusters/pcg/deploy-pcg/maas.md, docs/docs-content/clusters/pcg/deploy-pcg/openstack.md, docs/docs-content/clusters/pcg/deploy-pcg/vmware.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/tutorials/cluster-deployment/pcg/deploy-app-pcg.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR documents the step for removing `kind` images after self-hosted EC and PCG installation.
💻 [Install Palette on VMware](https://deploy-preview-3337--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/install/)
💻 [Install Palette on VMware (Airgap)](https://deploy-preview-3337--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/airgap-install/install/)
💻 [Install VerteX on VMware](https://deploy-preview-3337--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/install/)
💻 [Install VerteX on VMware (Airgap)](https://deploy-preview-3337--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/airgap-install/install/)
💻 [Deploy App Workloads with a …
=> Document the step for removing kind images after EC and PCG installation

docs/docs-content/clusters/pcg/deploy-pcg/maas.md, docs/docs-content/clusters/pcg/deploy-pcg/openstack.md, docs/docs-content/clusters/pcg/deploy-pcg/vmware.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/tutorials/cluster-deployment/pcg/deploy-app-pcg.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
- [Document the step for removing kind images after EC and PCG installation (#3337) (#3362)](https://github.com/spectrocloud/librarium/pull/3362)
=> [version-4-3] Document the step for removing kind images after EC and PCG installation (#3337)

docs/docs-content/clusters/pcg/deploy-pcg/maas.md, docs/docs-content/clusters/pcg/deploy-pcg/openstack.md, docs/docs-content/clusters/pcg/deploy-pcg/vmware.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/tutorials/cluster-deployment/pcg/deploy-app-pcg.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
- [Document the step for removing kind images after EC and PCG installation (#3337) (#3362)](https://github.com/spectrocloud/librarium/pull/3362)
=> [version-4-2] Document the step for removing kind images after EC and PCG installation (#3337)

docs/docs-content/clusters/pcg/deploy-pcg/maas.md, docs/docs-content/clusters/pcg/deploy-pcg/openstack.md, docs/docs-content/clusters/pcg/deploy-pcg/vmware.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/tutorials/cluster-deployment/pcg/deploy-app-pcg.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
- [Document the step for removing kind images after EC and PCG installation (#3337) (#3362)](https://github.com/spectrocloud/librarium/pull/3362)
=> [version-4-1] Document the step for removing kind images after EC and PCG installation (#3337)

docs/docs-content/clusters/pcg/deploy-pcg/maas.md, docs/docs-content/clusters/pcg/deploy-pcg/openstack.md, docs/docs-content/clusters/pcg/deploy-pcg/vmware.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/tutorials/cluster-deployment/pcg/deploy-app-pcg.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
- [Document the step for removing kind images after EC and PCG installation (#3337) (#3362)](https://github.com/spectrocloud/librarium/pull/3362)
=> [version-4-0] Document the step for removing kind images after EC and PCG installation (#3337)

docs/docs-content/clusters/pcg/deploy-pcg/vmware.md, docusaurus.config.js, src/css/custom.scss, src/css/dark-mode.scss, src/css/light-mode.scss, src/theme/Admonition/Icon/FurtherGuidance.js, src/theme/Admonition/Type/FurtherGuidance.js, src/theme/Admonition/Types.js
This PR adds the Further Guidance admonition and links to the VMware PCG tutorial from the VMware PCG guide.
💻 [Deploy to VMware vSphere](https://deploy-preview-3379--docs-spectrocloud.netlify.app/clusters/pcg/deploy-pcg/vmware/)
🎫 [DOC-1290](https://spectrocloud.atlassian.net/browse/DOC-1290)
[DOC-1290]: https://spectrocloud.atlassian.net/browse/DOC-1290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add the Further Guidance admonition + link to the VMware PCG tutorial

.prettierignore, _partials/tutorials/_checkout_tutorial_tag.mdx, _partials/tutorials/_download_tutorial_image_docker.mdx, _partials/tutorials/_download_tutorial_image_podman.mdx, _partials/tutorials/_run_tutorial_container_docker.mdx, _partials/tutorials/_run_tutorial_container_podman.mdx, _partials/tutorials/_stop_tutorial_container_docker.mdx, _partials/tutorials/_stop_tutorial_container_podman.mdx, docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md, docs/docs-content/getting-started/terraform.md, docs/docs-content/tutorials/cluster-deployment/pde/deploy-app.md, docs/docs-content/tutorials/cluster-deployment/public-cloud/deploy-k8s-cluster.md, docs/docs-content/tutorials/profiles/deploy-pack.md
This PR is manual cherry-pick. 
- [docs: bump tutorials tag DOC-1303 (#3396)](https://github.com/spectrocloud/librarium/pull/3396)
=> [version-3-4] docs: bump tutorials tag DOC-1303 (#3396)

.prettierignore, _partials/tutorials/_checkout_tutorial_tag.mdx, _partials/tutorials/_download_tutorial_image_docker.mdx, _partials/tutorials/_download_tutorial_image_podman.mdx, _partials/tutorials/_run_tutorial_container_docker.mdx, _partials/tutorials/_run_tutorial_container_podman.mdx, _partials/tutorials/_stop_tutorial_container_docker.mdx, _partials/tutorials/_stop_tutorial_container_podman.mdx, docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md, docs/docs-content/getting-started/terraform.md, docs/docs-content/tutorials/cluster-deployment/pde/deploy-app.md, docs/docs-content/tutorials/cluster-deployment/public-cloud/deploy-k8s-cluster.md, docs/docs-content/tutorials/cluster-management/update-maintain/update-k8s-cluster.md, docs/docs-content/tutorials/profiles/deploy-pack.md
This PR is manual cherry-pick. 
- [docs: bump tutorials tag DOC-1303 (#3396)](https://github.com/spectrocloud/librarium/pull/3396)
=> [version-4-0] docs: bump tutorials tag DOC-1303 (#3396)

.prettierignore, _partials/tutorials/_checkout_tutorial_tag.mdx, _partials/tutorials/_download_tutorial_image_docker.mdx, _partials/tutorials/_download_tutorial_image_podman.mdx, _partials/tutorials/_run_tutorial_container_docker.mdx, _partials/tutorials/_run_tutorial_container_podman.mdx, _partials/tutorials/_stop_tutorial_container_docker.mdx, _partials/tutorials/_stop_tutorial_container_podman.mdx, docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md, docs/docs-content/getting-started/terraform.md, docs/docs-content/tutorials/cluster-deployment/pde/deploy-app.md, docs/docs-content/tutorials/cluster-deployment/public-cloud/deploy-k8s-cluster.md, docs/docs-content/tutorials/cluster-management/update-maintain/update-k8s-cluster.md, docs/docs-content/tutorials/profiles/deploy-pack.md
This PR is manual cherry-pick. 
- [docs: bump tutorials tag DOC-1303 (#3396)](https://github.com/spectrocloud/librarium/pull/3396)
=> [version-4-1] docs: bump tutorials tag DOC-1303 (#3396)

.prettierignore, _partials/tutorials/_checkout_tutorial_tag.mdx, _partials/tutorials/_download_tutorial_image_docker.mdx, _partials/tutorials/_download_tutorial_image_podman.mdx, _partials/tutorials/_run_tutorial_container_docker.mdx, _partials/tutorials/_run_tutorial_container_podman.mdx, _partials/tutorials/_stop_tutorial_container_docker.mdx, _partials/tutorials/_stop_tutorial_container_podman.mdx, docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md, docs/docs-content/getting-started/terraform.md, docs/docs-content/tutorials/cluster-deployment/pde/deploy-app.md, docs/docs-content/tutorials/cluster-deployment/public-cloud/deploy-k8s-cluster.md, docs/docs-content/tutorials/cluster-management/update-maintain/update-k8s-cluster.md, docs/docs-content/tutorials/profiles/deploy-pack.md
This PR is manual cherry-pick. 
- [docs: bump tutorials tag DOC-1303 (#3396)](https://github.com/spectrocloud/librarium/pull/3396)
=> [version-4-2] docs: bump tutorials tag DOC-1303 (#3396)

docs/docs-content/automation/palette-cli/install-palette-cli.md, docs/docs-content/enterprise-version/upgrade/upgrade.md, docs/docs-content/registries-and-packs/advanced-configuration.md, docs/docs-content/registries-and-packs/spectro-cli-reference.md, docs/docs-content/spectro-downloads.md, docs/docs-content/vertex/upgrade/upgrade.md
This PR updates download URLs and references to Palette CLI and Palette Edge CLI.
💻 [Downloads](https://deploy-preview-3437--docs-spectrocloud.netlify.app/spectro-downloads/)
💻 [Advanced CLI Configuration](https://deploy-preview-3437--docs-spectrocloud.netlify.app/registries-and-packs/advanced-configuration/)
💻 [Palette CLI: Installation](https://deploy-preview-3437--docs-spectrocloud.netlify.app/automation/palette-cli/install-palette-cli/)
💻 [Spectro Cloud CLI Tool](https://deploy-preview-3437--docs-spectrocloud.netlify.app/registries-and-packs/spectro-cli-reference/)
💻 [Self-hosted Upgrade](https://deploy-preview-3437--docs-spectrocloud.netlify.app/enterprise-version/upgrade/)
💻 [VerteX Upgrade](https://deploy-preview-3437--docs-spectrocloud.netlify.app/vertex/upgrade/)
🎫 …
=> Update Palette CLI Binaries URLs

docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/signed-content.md, docs/docs-content/clusters/public-cloud/azure/architecture.md
This PR updates two minor items from the latest release:
- Updated to reference the latest CanvOS tag for signed content bundle `4.4.4`
- Fixed language in Azure architecture page.
=> chore: minor updates post 4-4-a release

docusaurus.config.js, plugins/packs-integrations.js, static/packs-data/exclude_packs.json
This PR adds the ability to exclude certain packs from being displayed in the pack's component. 
🎫 [DOC-1316](https://spectrocloud.atlassian.net/browse/DOC-1316)
[DOC-1316]: https://spectrocloud.atlassian.net/browse/DOC-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: DOC-1316

Makefile, docs/deprecated/integrations/prometheus-operator.md
This PR fixes one broken link. It also drops the concurrency from 100 to 50 connections on the linkinator job and increases its timeout. This should help with throttling and allow the nist links to stop failing. 
🎫 [DOC-1329](https://spectrocloud.atlassian.net/browse/DOC-1329)
[DOC-1329]: https://spectrocloud.atlassian.net/browse/DOC-1329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: fix broken link and slow down linkinator job DOC-1329

Makefile
- [docs: fix broken link and slow down linkinator job (#3549)](https://github.com/spectrocloud/librarium/pull/3549)
=> [version-4-1] docs: fix broken link and slow down linkinator job (#3549)

docs/deprecated/clusters/edge/edgeforge-workflow/build-images.md, docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md
- [chore: Fix broken links (#3572)](https://github.com/spectrocloud/librarium/pull/3572)
=> [version-4-1] chore: Fix broken links (#3572)

docs/deprecated/clusters/edge/edgeforge-workflow/build-images.md, docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md
- [chore: Fix broken links (#3572)](https://github.com/spectrocloud/librarium/pull/3572)
=> [version-4-2] chore: Fix broken links (#3572)

docs/docs-content/clusters/edge/local-ui/host-management/audit-logs.md, docs/docs-content/clusters/edge/local-ui/host-management/host-management.md
This PR documents how to configure applications logs to stylus audit log file and how to download logs.
💻 [Audit Logs](https://deploy-preview-3564--docs-spectrocloud.netlify.app/clusters/edge/local-ui/host-management/audit-logs/)
🎫 [PE-4732](https://spectrocloud.atlassian.net/browse/PE-4732)
[PE-4732]: https://spectrocloud.atlassian.net/browse/PE-4732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Audit logs

docs/docs-content/vm-management/create-vmo-profile.md
This PR adds airgap tabs to the Create VMO Profile page.
💻 [Create a VMO Profile](https://deploy-preview-3583--docs-spectrocloud.netlify.app/vm-management/create-vmo-profile/)
🎫 [PEM-5497](https://spectrocloud.atlassian.net/browse/PEM-5497)
[PEM-5497]: https://spectrocloud.atlassian.net/browse/PEM-5497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add airgap VMO profile creation PEM-5497

docs/docs-content/vm-management/create-vmo-profile.md, docs/docs-content/vm-management/install-vmo-in-airgap.md
This PR adds the No Proxy list as part of the VMO profile creation and airgap with VMO pages. 
💻 [Install VMO in Airgap Environments](https://deploy-preview-3586--docs-spectrocloud.netlify.app/vm-management/install-vmo-in-airgap/#prerequisites)
💻 [Create a VMO Profile](https://deploy-preview-3586--docs-spectrocloud.netlify.app/vm-management/create-vmo-profile/)
🎫 [PEM-5233](https://spectrocloud.atlassian.net/browse/PEM-5233)
[PEM-5233]: https://spectrocloud.atlassian.net/browse/PEM-5233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add no proxy list configuration for VMO PEM-5233

docs/docs-content/spectro-downloads.md
This PR updates the downloads page with the newest artifacts and adds the entries from https://github.com/spectrocloud/librarium/pull/3582 as well.
💻 [Downloads](https://deploy-preview-3594--docs-spectrocloud.netlify.app/spectro-downloads/)
🎫 [DOC-1335](https://spectrocloud.atlassian.net/browse/DOC-1335)
[DOC-1335]: https://spectrocloud.atlassian.net/browse/DOC-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: update downloads with new artifacts DOC-1335

docs/docs-content/automation/palette-cli/install-palette-cli.md, docs/docs-content/enterprise-version/upgrade/upgrade.md, docs/docs-content/spectro-downloads.md, docs/docs-content/vertex/upgrade/upgrade.md
This PR adds the new self-hosted and VerteX upgrade paths and updates the Palette CLI references.
💻 [Palette CLI: Installation](https://deploy-preview-3595--docs-spectrocloud.netlify.app/automation/palette-cli/install-palette-cli/)
💻 [Self-hosted Upgrade](https://deploy-preview-3595--docs-spectrocloud.netlify.app/enterprise-version/upgrade/)
💻 [VerteX Upgrade](https://deploy-preview-3595--docs-spectrocloud.netlify.app/vertex/upgrade/)
🎫 [DOC-1334](https://spectrocloud.atlassian.net/browse/DOC-1334)
🎫 [DOC-1339](https://spectrocloud.atlassian.net/browse/DOC-1339)
[DOC-1334]: https://spectrocloud.atlassian.net/browse/DOC-1334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1339]: …
=> [4.4.b] Binaries References and Upgrade Path

Makefile
This PR removes a stray space from `verify-security-bulletins-links-ci` make command. 
This is breaking the Github action. 
🎫 [DOC-1346](https://spectrocloud.atlassian.net/browse/DOC-1346)
[DOC-1346]: https://spectrocloud.atlassian.net/browse/DOC-1346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: remove space from broken URL check DOC-1346

src/components/Technologies/PackCardIcon.tsx
This PR fixes a bug introduced by PR #3522. The import statement was missing the `await` keyword and access to the default object returned by the import. 
💻 [Preview URL for Page](https://deploy-preview-3648--docs-spectrocloud.netlify.app/integrations/)
🎫 [DOC-1350](https://spectrocloud.atlassian.net/browse/DOC-1350)
[DOC-1350]: https://spectrocloud.atlassian.net/browse/DOC-1350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Production Issue with Packs List

docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md
This PR removes the "Vertex" word from a Palette self-hosted page.
💻 [Install Palette](https://deploy-preview-3732--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/airgap-install/install/)
=> docs: remove vertex from self-hosted page

docs/docs-content/clusters/cluster-management/node-pool.md, docs/docs-content/clusters/cluster-management/taints.md, docs/docs-content/profiles/profile-customization.md
This PR captures the ability to leverage a toleration label for avoiding pods getting evicted during a node drainage operation.
- [Node Pools Page](https://deploy-preview-3742--docs-spectrocloud.netlify.app/clusters/cluster-management/node-pool/#pod-drainage-toleration)
- [Taints and Tolerations](https://deploy-preview-3742--docs-spectrocloud.netlify.app/clusters/cluster-management/taints/)
💻 [Taints & Tolerations ](https://deploy-preview-3742--docs-spectrocloud.netlify.app/clusters/cluster-management/taints/)
💻 [Node Pools ](https://deploy-preview-3742--docs-spectrocloud.netlify.app/clusters/cluster-management/node-pool/#pod-drainage-toleration/)
🎫 [PCP-3421](https://spectrocloud.atlassian.net/browse/PCP-3421)
[PCP-3403]: …
=> docs: PCP-3421

.github/workflows/nightly-docker-build.yaml
This PR fixes the backport issues from PR #3770
=> [version-4-2] chore: bump sigstore/cosign-installer from 3.5.0 to 3.6.0 (#3770)

.github/workflows/nightly-docker-build.yaml
This PR fixes the backport issues from PR #3770
=> [version-4-1] chore: bump sigstore/cosign-installer from 3.5.0 to 3.6.0 (#3770)

.github/workflows/nightly-docker-build.yaml
This PR fixes the backport issues from PR #3770
=> [version-4-0] chore: bump sigstore/cosign-installer from 3.5.0 to 3.6.0 (#3770)

docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
This PR fixes a minor indentation issue on the VerteX Helm Install Reference page. The heading Reach System was  using `###` and H3 instead of an H2.
🎫 [DOC-1372](https://spectrocloud.atlassian.net/browse/DOC-1372)
[DOC-1372]: https://spectrocloud.atlassian.net/browse/DOC-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1372

docs/docs-content/clusters/cluster-management/backup-restore/backup-restore.md, docs/docs-content/clusters/cluster-management/backup-restore/create-cluster-backup.md, docs/docs-content/clusters/cluster-management/backup-restore/restore-cluster-backup.md
This PR adds documentation pertaining to the volume snapshot support with cluster backups. 
🎫 [PAC-1697](https://spectrocloud.atlassian.net/browse/PAC-1967)
[PAC-1697]: https://spectrocloud.atlassian.net/browse/PAC-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Volume Snapshot Support

_partials/permissions/_vsphere-permissions.mdx, docs/docs-content/clusters/data-center/vmware/create-manage-vmware-clusters.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
- Fix the role assignment / privileges for the Enterprise Cluster's VM Folder
- Correct the conditions for VM Folder and `spectro-templates` folder
- Add `System.*` privileges just to be explicit
- Document conditionality around spectro privileges on Cluster vs. non-default Resource Pool
During installation, palette (controller, not product) creates the VM Folder, but only in connected mode. The `spectro-templates` folder is always created in advance.
=> fix: move VM folder to spectro role, correct folder conditions

docs/docs-content/clusters/edge/cluster-management/certificate-renewal.md
The existing doc sentence here is misleading.
This will display all the certificates currently in use by your cluster. You can confirm that the certificates have been renewed by looking at the issue date of certificates.
it should instead be 
This will display all the certificates currently in use by your cluster. You can confirm that the certificates have been renewed by looking at the expiry date of certificates.
https://spectrocloud.atlassian.net/browse/PE-5011
=> docs: confirm cert renewal by looking at expiry date

docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR removes airgap instructions from non-airgap guides and "VerteX" occurrences from the non-airgap self-host Palette installation guide.
💻 [Self-hosted Palette Non-Airgap Installation](https://deploy-preview-3934--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/install/)
💻 [VerteX Non-Airgap Installation](https://deploy-preview-3934--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/install/)
🎫 [DOC-1383](https://spectrocloud.atlassian.net/browse/DOC-1383)
[DOC-1383]: https://spectrocloud.atlassian.net/browse/DOC-1383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: remove airgap instructions from non-airgap guides

docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR backports PR #3934 from master to version-4-3.
💻 [Self-hosted Palette Non-Airgap Installation](https://deploy-preview-3938--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/install/)
💻 [VerteX Non-Airgap Installation](https://deploy-preview-3938--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/install/)
=> [version-4-3] docs: remove airgap instructions from non-airgap guides (#3934)

docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR backports PR #3934 from master to version-4-2.
💻 [Self-hosted Palette Non-Airgap Installation](https://deploy-preview-3939--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/install/)
💻 [VerteX Non-Airgap Installation](https://deploy-preview-3939--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/install/)
=> [version-4-2] docs: remove airgap instructions from non-airgap guides (#3934)

docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR backports PR #3934 from master to version-4-1.
💻 [Self-hosted Palette Non-Airgap Installation](https://deploy-preview-3940--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/install/)
💻 [VerteX Non-Airgap Installation](https://deploy-preview-3940--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/install/)
=> [version-4-1] docs: remove airgap instructions from non-airgap guides (#3934)

docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR backports PR #3934 from master to version-4-0.
💻 [Self-hosted Palette Non-Airgap Installation](https://deploy-preview-3941--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/install/)
💻 [VerteX Non-Airgap Installation](https://deploy-preview-3941--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/install/)
=> [version-4-0] docs: remove airgap instructions from non-airgap guides (#3934)

docs/docs-content/release-notes/release-notes.md
This PR adds a new breaking change to the 4.4.18 release notes.
The `type` parameter in the `controlPlaneEndpoint` for Edge clusters no longer accepts IP addresses. The accepted values are now `VIP`, `External`, and `DDNS`.
💻 [Release Notes](https://deploy-preview-3942--docs-spectrocloud.netlify.app/release-notes/)
=> docs: add api breaking change

.github/workflows/url-checks.yaml, Makefile, docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md, linkinator/linkinator-ci.config.json, linkinator/linkinator-rate-limit-ci.config.json, linkinator/linkinator-rate-limit.config.json, linkinator/linkinator.config.json, scripts/url-checker.sh
- [docs: fix broken links and adjust linkinator config DOC-1382 (#3928)](https://github.com/spectrocloud/librarium/pull/3928)
=> [version-4-3] docs: fix broken links and adjust linkinator config DOC-1382 (#3928)

.github/workflows/url-checks.yaml, Makefile, docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md, linkinator/linkinator-ci.config.json, linkinator/linkinator-rate-limit-ci.config.json, linkinator/linkinator-rate-limit.config.json, linkinator/linkinator.config.json, scripts/url-checker.sh
- [docs: fix broken links and adjust linkinator config DOC-1382 (#3928)](https://github.com/spectrocloud/librarium/pull/3928)
=> [version-4-2] docs: fix broken links and adjust linkinator config DOC-1382 (#3928)

.github/workflows/url-checks.yaml, Makefile, docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md, linkinator/linkinator-ci.config.json, linkinator/linkinator-rate-limit-ci.config.json, linkinator/linkinator-rate-limit.config.json, linkinator/linkinator.config.json, scripts/url-checker.sh
- [docs: fix broken links and adjust linkinator config DOC-1382 (#3928)](https://github.com/spectrocloud/librarium/pull/3928)
=> [version-4-1] docs: fix broken links and adjust linkinator config DOC-1382 (#3928)

.github/workflows/url-checks.yaml, Makefile, docs/docs-content/vertex/install-palette-vertex/airgap/offline-docs.md, linkinator/linkinator-ci.config.json, linkinator/linkinator-rate-limit-ci.config.json, linkinator/linkinator-rate-limit.config.json, linkinator/linkinator.config.json, scripts/url-checker.sh
- [docs: fix broken links and adjust linkinator config DOC-1382 (#3928)](https://github.com/spectrocloud/librarium/pull/3928)
=> [version-4-0] docs: fix broken links and adjust linkinator config DOC-1382 (#3928)

docs/docs-content/automation/automation.md, docs/docs-content/automation/palette-sdk/list-clusters-sdk.md, docs/docs-content/automation/palette-sdk/palette-sdk.md, docs/docs-content/user-management/authentication/api-key/api-key.md, docs/docs-content/user-management/authentication/api-key/delete-api-key.md, docs/docs-content/user-management/saml-sso/saml-sso.md
This PR fixes the backport issues from PR #3929
=> [version-4-1] docs: DOC-1362 (#3929)

docs/docs-content/automation/automation.md, docs/docs-content/automation/palette-sdk/list-clusters-sdk.md, docs/docs-content/automation/palette-sdk/palette-sdk.md, docs/docs-content/user-management/authentication/api-key/api-key.md, docs/docs-content/user-management/authentication/api-key/delete-api-key.md, docs/docs-content/user-management/saml-sso/saml-sso.md
This PR fixes the backport issues from PR #3929
=> [version-4-0] docs: DOC-1362 (#3929)

docs/docs-content/enterprise-version/upgrade/upgrade.md, docs/docs-content/vertex/upgrade/upgrade.md
This PR updates VerteX and self-hosted upgrade paths tables.
💻 [Self-Hosted Upgrade](https://deploy-preview-3976--docs-spectrocloud.netlify.app/enterprise-version/upgrade/)
💻 [VerteX Upgrade](https://deploy-preview-3976--docs-spectrocloud.netlify.app/vertex/upgrade//)
🎫 [DOC-1386](https://spectrocloud.atlassian.net/browse/DOC-1386)
[DOC-1386]: https://spectrocloud.atlassian.net/browse/DOC-1386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: update vertex/self-hosted upgrade paths table

docs/docs-content/clusters/edge/edge-configuration/installer-reference.md, docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md, docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md
This PR adds the limitation that you cannot use external registries with content bundles if you don't have harbor. 
💻 [Build Content Bundle](https://deploy-preview-4049--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle/)
🎫 [PE-5123](https://spectrocloud.atlassian.net/browse/PE-5123)
[PE-5123]: https://spectrocloud.atlassian.net/browse/PE-5123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add limitation for external registry + content bundle

_partials/self-hosted/_required-domains.mdx, docs/docs-content/architecture/palette-public-ips.md
This PR updates the allow list of required domains.
🎫 [DOC-1410](https://spectrocloud.atlassian.net/browse/DOC-1410)
Release PR
[DOC-1410]: https://spectrocloud.atlassian.net/browse/DOC-1410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1410

docs/docs-content/vm-management/create-manage-vm/advanced-topics/migrate-vm-kubevirt.md
This PR removes the limitation that required VMO migrations using Multus CNI to have NAD in the target cluster's migration namespace.
🎫 [PLT-1407](https://spectrocloud.atlassian.net/browse/PLT-1407)
This is a release PR. 
[PLT-1407]: https://spectrocloud.atlassian.net/browse/PLT-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: PLT-1407

docs/docs-content/user-management/saml-sso/palette-sso-with-adfs.md, docs/docs-content/user-management/saml-sso/palette-sso-with-entra-id.md, docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md, docs/docs-content/user-management/saml-sso/palette-sso-with-okta.md, docs/docs-content/user-management/saml-sso/palette-sso-with-onelogin.md
This PR adds information about the new OIDC capability of extracting required claims from the userinfo endpoint. 
Added this prereq to each OIDC guide.
💻 [Preview URL for Page](https://deploy-preview-4119--docs-spectrocloud.netlify.app/user-management/saml-sso/palette-sso-with-okta/)
🎫 [PEM-5698](https://spectrocloud.atlassian.net/browse/PEM-5698)
Release PR
[PEM-5698]: https://spectrocloud.atlassian.net/browse/PEM-5698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OIDC userinfo

docs/docs-content/vm-management/architecture.md
This PR changes the link for the VMO Reference Architecture to the Spectro Cloud Resource Center, instead of linking to a hardcoded PDF file that no longer gets updated.
None
=> Fix link to VMO reference architecture

package-lock.json, package.json
This PR fixes the backport issue from PR #4136
=> [version-4-4] chore: bump @ant-design/icons from 4.8.3 to 5.5.1 (#4136)

docs/deprecated/integrations/kubernetes.md, docs/docs-content/glossary-all.md, docs/docs-content/integrations/kubernetes.md
This PR fixes the backport issues for PR #4197
=> [version-4-1] chore: correct wording of pxk (#4197)

docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md, docs/docs-content/vertex/system-management/ssl-certificate-management.md
This PR fixes the change that was introduced in 4.4. The system console certificate screen now expects the certificate strings to be in base64 format. 
💻 [Palette Page](https://deploy-preview-4242--docs-spectrocloud.netlify.app/enterprise-version/system-management/ssl-certificate-management/)
💻 [VerteX Page](https://deploy-preview-4242--docs-spectrocloud.netlify.app/vertex/system-management/ssl-certificate-management/)
🎫 [DOC-1419](https://spectrocloud.atlassian.net/browse/DOC-1419)
[DOC-1419]: https://spectrocloud.atlassian.net/browse/DOC-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1419

docs/docs-content/clusters/edge/edge-configuration/installer-reference.md, docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/webhook-disable.md
This PR adds the instructions for how to disable Palette Edge agent webhook. 
💻 [Image Pull Customizations](https://deploy-preview-4098--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/deploy-custom-registries/webhook-disable/)
🎫  [PE-4883](https://spectrocloud.atlassian.net/browse/PE-4883)
[PE-4883]: https://spectrocloud.atlassian.net/browse/PE-4883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: disable webhook 

docs/docs-content/clusters/edge/local-ui/cluster-management/share-auth.md
This PR documents how to consume local UI's authentication cookie. 
💻 [Share Local UI Auth](https://deploy-preview-4140--docs-spectrocloud.netlify.app/clusters/edge/local-ui/cluster-management/share-auth/)
=> docs: share local UI login

docs/docs-content/legal-licenses/oss-licenses-index/pxk-oss-licenses.md
This PR captures more information about PXK.
=> docs: pxk-license

docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
This PR updates the agent-mode URL
=> docs: updated agent-mode

plugins/packs-integrations.js
This PR fixes a bug related to packs
=> chore: fix bug in packs plugin

docs/deprecated/integrations/kubernetes.md, docs/docs-content/clusters/data-center/maas/architecture.md, docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md, docs/docs-content/integrations/kubernetes.md
The documentation on the Custom MAAS Endpoint was wrong. This PR corrects this.
💻 [PXK pack](https://deploy-preview-4302--docs-spectrocloud.netlify.app/integrations/packs/?pack=kubernetes&version=1.30.5&parent=1.30.x)
💻 [MAAS Architecture](https://deploy-preview-4302--docs-spectrocloud.netlify.app/clusters/data-center/maas/architecture/#custom-api-server-endpoint-for-maas-clusters)
💻 [Create and Manage MAAS Clusters](https://deploy-preview-4302--docs-spectrocloud.netlify.app/clusters/data-center/maas/create-manage-maas-clusters/)
=> Rewrote MAAS custom endpoint docs

docs/deprecated/integrations/kubernetes.md, docs/docs-content/clusters/data-center/maas/architecture.md, docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md, docs/docs-content/integrations/kubernetes.md
- [Rewrote MAAS custom endpoint docs (#4302)](https://github.com/spectrocloud/librarium/pull/4302)
=> [version-4-2] Rewrote MAAS custom endpoint docs (#4302)

docs/deprecated/integrations/kubernetes.md, docs/docs-content/clusters/data-center/maas/architecture.md, docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md, docs/docs-content/integrations/kubernetes.md
- [Rewrote MAAS custom endpoint docs (#4302)](https://github.com/spectrocloud/librarium/pull/4302)
=> [version-4-1] Rewrote MAAS custom endpoint docs (#4302)

docs/deprecated/integrations/kubernetes.md, docs/docs-content/clusters/data-center/maas/architecture.md, docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md, docs/docs-content/integrations/kubernetes.md
- [Rewrote MAAS custom endpoint docs (#4302)](https://github.com/spectrocloud/librarium/pull/4302)
=> [version-4-0] Rewrote MAAS custom endpoint docs (#4302)

docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
This PR updates the BYOS Edge pack version in the Agent Mode guide.
More info [here](https://spectrocloud.slack.com/archives/C07BFQ51ETA/p1729226914280999).
💻 [Install Palette Agent](https://deploy-preview-4334--docs-spectrocloud.netlify.app/deployment-modes/agent-mode/install-agent-host/)
🎫 [DOC-1431](https://spectrocloud.atlassian.net/browse/DOC-1431)
- [x ] Yes. _Remember to add the relevant backport labels to your PR._
[DOC-1431]: https://spectrocloud.atlassian.net/browse/DOC-1431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: update byos edge pack version

docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md, docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap.md
This PR fixes the capi image builder tag in one of the commands of the airgap guides.
💻 [RHEL and PXK](https://deploy-preview-4352--docs-spectrocloud.netlify.app/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap/)
💻 [Rocky and PXK](https://deploy-preview-4352--docs-spectrocloud.netlify.app/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap/)
🎫 [DOC-1434](https://spectrocloud.atlassian.net/browse/DOC-1434)
[DOC-1434]: https://spectrocloud.atlassian.net/browse/DOC-1434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: fix image tag

docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md
This PR fixes the backport issues from PR #4351
=> [version-4-2] docs: backport 4-2

.github/workflows/versions_robot.yaml, docusaurus.config.js, netlify.toml, scripts/noindex_docusaurus_config.js
=> [version-4-5] ci: Robots Txt Fix (#4380)

netlify.toml, package-lock.json, package.json
This PR removes a setting that needs more experimentation from Netlify. Two packages were also moved up to dependencies vs devDependencies. `axios` and `p-ratelimit` is needed for the packs download. If the env variable `NODE_ENV` is set to `production` then Netlify will not install dev dependencies. That will cause issues for our pre-build steps that retrieve packs, and security bulletins [future].
=> ci: remove package.json prepare

docs/docs-content/security-bulletins/reports/cve-2022-32190.md
This PR does not fix the link but places the link segments into monospace. This should also stop it being picked up as a broken link (and stop it being created as a hyperlink in Production).
💻 [cve-2022-32190](https://deploy-preview-4396--docs-spectrocloud.netlify.app/security-bulletins/reports/cve-2022-32190/)
=> docs: update cve-2022-32190

docs/deprecated/integrations/kubernetes.md, docs/docs-content/clusters/data-center/maas/architecture.md, docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md, docs/docs-content/integrations/kubernetes.md
This PR fixes an error in the Custom API Server endpoint for MAAS documentation. It turns out the customEndpointPort must be specified as an integer instead of a string, otherwise it does not work and you get the error
```
"failed to get Maas cloud items from pack" "error"="error unmarshaling JSON: json: cannot unmarshal string into Go struct field MaasCloudItems.maas.customEndpointPort of type int"
```
💻 [Preview URL](https://deploy-preview-4401--docs-spectrocloud.netlify.app/integrations/packs/?pack=kubernetes#custom-api-server-endpoint-for-maas-clusters)
Please backport this as well.
=> customEndpointPort must be an integer

docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
This PR removes the double slashes from the keycloak guide. While this renders correctly, it is wrong syntax and breaks the unused image detection automation.
💻 [Keycloak](https://deploy-preview-4429--docs-spectrocloud.netlify.app/user-management/saml-sso/palette-sso-with-keycloak/)
🎫 [DOC-1232](https://spectrocloud.atlassian.net/browse/DOC-1232)
[DOC-1232]: https://spectrocloud.atlassian.net/browse/DOC-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: remove double slashes from image reference DOC-1232

docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
=> [version-4-3] docs: remove double slashes from image reference DOC-1232 (#4429)

docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
=> [version-4-2] docs: remove double slashes from image reference DOC-1232 (#4429)

docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
=> [version-4-1] docs: remove double slashes from image reference DOC-1232 (#4429)

docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
=> [version-4-0] docs: remove double slashes from image reference DOC-1232 (#4429)

docs/docs-content/user-management/saml-sso/palette-sso-with-keycloak.md
=> [version-3-4] docs: remove double slashes from image reference DOC-1232 (#4429)

.github/workflows/clean-up-unused-images.yaml
This PR fixes a small bug in the clean up images GH action.  The script contained == instead of the bash `-eq` syntax. An `echo` was also missing.  Added checking that the file exists too and raised an error in case it was not created correctly. 
No user-facing changes.
🎫 [DOC-1232](https://spectrocloud.atlassian.net/browse/DOC-1232)
[DOC-1232]: https://spectrocloud.atlassian.net/browse/DOC-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: adjust script to handle zero unused images DOC-1232

docs/docs-content/profiles/profile-customization.md
Adds a new section to explain the namespace considerations in Palette.
It also provides a scenario to explain that shared namespace resources are deleted when cluster profiles are removed through Palette.
💻 [Profile Customization](https://deploy-preview-4473--docs-spectrocloud.netlify.app/profiles/profile-customization/#namespace-considerations)
🎫 [DOC-1178](https://spectrocloud.atlassian.net/browse/DOC-1178)
[DOC-1178]: https://spectrocloud.atlassian.net/browse/DOC-1178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: DOC-1178

docs/docs-content/clusters/pcg/architecture.md
This PR updates the PCG page where a specific callout to MAAS was left when refactored.
💻 [Preview URL for Page](https://deploy-preview-4551--docs-spectrocloud.netlify.app/clusters/pcg/architecture/)
🎫 [DOC-1458](https://spectrocloud.atlassian.net/browse/DOC-1458)
[DOC-1458]: https://spectrocloud.atlassian.net/browse/DOC-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1458

docs/docs-content/clusters/cluster-management/cluster-updates.md
This PR adds the limitation that version skipping during K8s upgrades are not supported. 
🎫 [PE-5494](https://spectrocloud.atlassian.net/browse/PE-5494)
[PE-5494]: https://spectrocloud.atlassian.net/browse/PE-5494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add limitation on version skipping during upgrades

docs/docs-content/automation/automation.md
This PR fixes the crossplane URL link as it will point at the latest crossplane version of the docs.
💻 [Automation](https://deploy-preview-4678--docs-spectrocloud.netlify.app/automation/)
=> docs: fix broken crossplane URL

docs/docs-content/automation/automation.md
- [docs: fix broken crossplane URL (#4678)](https://github.com/spectrocloud/librarium/pull/4678)
=> [version-3-4] docs: fix broken crossplane URL (#4678)

docs/docs-content/vm-management/create-manage-vm/advanced-topics/migrate-vm-kubevirt.md
This PR adds a note to the page about VM migration to VMO, directing the user to leave `namespace` blank when creating a `vddk-image-pull-secret` yaml.
💻 [Preview](https://deploy-preview-4713--docs-spectrocloud.netlify.app/vm-management/create-manage-vm/advanced-topics/migrate-vm-kubevirt/#prerequisites)
=> docs: add note about vddk secret namespace

docs/docs-content/registries-and-packs/add-custom-packs.md, docs/docs-content/registries-and-packs/adding-add-on-packs.md, docs/docs-content/registries-and-packs/registries-and-packs.md, docs/docs-content/tutorials/profiles/deploy-pack.md
This PR removes the mention of Ansible roles in Packs. The order of registries in the Add a Custom Pack tutorial has also been updated to start with Basic, followed by ECR, and Spectro Registry.
💻 [Add a Custom Pack Page](https://deploy-preview-4719--docs-spectrocloud.netlify.app/registries-and-packs/add-custom-packs/)
💻 [Tutorial](https://deploy-preview-4719--docs-spectrocloud.netlify.app/tutorials/profiles/deploy-pack/)
🎫 [DOC-1485](https://spectrocloud.atlassian.net/browse/DOC-1485)
🎫 [DOC-1487](https://spectrocloud.atlassian.net/browse/DOC-1487)
[DOC-1485]: https://spectrocloud.atlassian.net/browse/DOC-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1487]: …
=> Remove Ansible Roles in Pack Documentation

docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
The name of one of the policies is "PaletteControllerPolicy". This fixes a reference to it lower in the page to match that name.
=> docs: fix name of AWS IAM policy

docs/docs-content/clusters/public-cloud/aws/architecture.md
This PR adds the security group ingress rules documentation.
💻 [Custom Security Group Ingress Rules](https://deploy-preview-4781--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/architecture/#custom-security-group-ingress-rules)
🎫 [PCP-1906](https://spectrocloud.atlassian.net/browse/PCP-1906)
Merging to Release branch.
[PCP-1906]: https://spectrocloud.atlassian.net/browse/PCP-1906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add custom security group ingress rules section PCP-1906

docs/docs-content/architecture/architecture-overview.md
This PR adds a message brokers section explaining the HA and scaling of Palette message brokers.
💻 [Architecture](https://deploy-preview-4818--docs-spectrocloud.netlify.app/architecture/architecture-overview/#message-brokers)
🎫 [PEM-6141](https://spectrocloud.atlassian.net/browse/PEM-6141)
Merging to release branch.
[PEM-6141]: https://spectrocloud.atlassian.net/browse/PEM-6141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add message brokers section PEM-6141

docs/docs-content/tutorials/cluster-deployment/public-cloud/deploy-k8s-cluster.md
In the [tutorial to deploy public cloud clusters](https://docs.spectrocloud.com/tutorials/cluster-deployment/public-cloud/deploy-k8s-cluster/#update-cluster-profile), the manifests files in the update cluster profile flow are missing the namespace field, which leads to a reconciliation error when updating the cluster.
Added the namespace which fixes the issue.
=> Updated hello-universe yaml in tutorial

docs/docs-content/vm-management/create-manage-vm/clone-vm.md
This PR adds a warning for the Snapshot feature gate to the Clone a VM guide. 
🎫 [DOC-1491](https://spectrocloud.atlassian.net/browse/DOC-1491)
Merge to release branch.
[DOC-1491]: https://spectrocloud.atlassian.net/browse/DOC-1491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add feature gate to the vm clone guide DOC-1491

.github/workflows/nightly-docker-build.yaml
This PR fixes the backport issues from PR #4841
=> [version-4-2] chore: bump docker/metadata-action from 5.5.1 to 5.6.1 (#4841)

.github/workflows/nightly-docker-build.yaml
This PR fixes the backport issues from PR #4841
=> [version-4-1] chore: bump docker/metadata-action from 5.5.1 to 5.6.1 (#4841)

.github/workflows/nightly-docker-build.yaml
This PR fixes the backport issues from PR #4841
=> [version-4-0] chore: bump docker/metadata-action from 5.5.1 to 5.6.1 (#4841)

utils/cves/index.js
This PR adds an additional filter that removes CVE items that are not yet ready for publication.
This is the new filter added to the query payload.
```js
{
field: "status.state",
options: ["Analyzed", "Modified"],
operator: "in",
},
```
💻 [Preview URL for Page](https://deploy-preview-4869--docs-spectrocloud.netlify.app/security-bulletins/reports/#palette)
=> chore: added filter to exclude cves not ready for publication

docs/docs-content/clusters/edge/cluster-management/agent-upgrade-airgap.md, docs/docs-content/clusters/edge/cluster-management/certificate-renewal.md, docs/docs-content/clusters/edge/cluster-management/skip-draining.md, docs/docs-content/clusters/edge/cluster-management/upgrade-behavior.md
This PR adds instructions on how to skip node draining when running cluster upgrades. 
💻 [Preview URL for Page](https://deploy-preview-4851--docs-spectrocloud.netlify.app/clusters/edge/cluster-management/skip-draining/)
🎫 [PE-5647](https://spectrocloud.atlassian.net/issues/PE-5647?filter=11884)
[PE-5647]: https://spectrocloud.atlassian.net/browse/PE-5647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: PE-5647: Allow skipping of node drains when running cluster upgrades for single-node clusters.

src/components/CveReportsTable/CveReportsTable.tsx, utils/cves/index.js
This PR updates the filters for the security bulletin filters. It also includes an update to the field used for the last modified column. Switching to `advLastModifiedTimestamp` per the security team's guidance.
💻 [Preview URL](https://deploy-preview-4878--docs-spectrocloud.netlify.app/security-bulletins/reports/#palette)
=> chore: update filters

src/components/CveReportsTable/CveReportsTable.tsx, utils/cves/index.js, utils/helpers/urls.js, utils/helpers/urls.test.ts
This PR fixes issues with CVE URLs that are not NIST based, such as GitHub security advisories.
💻 [Preview URL for Page](https://deploy-preview-4936--docs-spectrocloud.netlify.app/security-bulletins/reports/#palette)
=> Fix CVE URL logic

.github/workflows/packs-data.yaml
This PR fixes the GitHub Actions issues with the deprecated packs CI action. The former action that was causing the issue is now replaced with official GCP GitHub Actions.
Here is a recent [run](https://github.com/spectrocloud/librarium/actions/runs/12279058543/job/34262200293?pr=4973) with the new steps. 
🎫 [DOC-1508](https://spectrocloud.atlassian.net/browse/DOC-1508)
[DOC-1508]: https://spectrocloud.atlassian.net/browse/DOC-1508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: fix GitHub action issue

docs/docs-content/deployment-modes/agent-mode/install-agent-host.md, docs/docs-content/deployment-modes/controller-mode.md
This PR adds iptables as a prerequisite for agent mode. 
🎫 [DOC-1509](https://spectrocloud.atlassian.net/browse/DOC-1509)
[DOC-1509]: https://spectrocloud.atlassian.net/browse/DOC-1509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add ip tables as a prerequisite

Makefile
This PR skips all files in the deprecated folder from broken URL checks, as we no longer wish to maintain them. 
No user facing changes.
🎫 [DOC-1503](https://spectrocloud.atlassian.net/browse/DOC-1503)
[DOC-1503]: https://spectrocloud.atlassian.net/browse/DOC-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: exclude deprecated files from broken url check DOC-1503

Makefile
This PR replaces `cve-reports` as a skipped match, as we want the `unlisted/cve-reports.md` file to be checked by the rate limited job instead. 
No user facing changes. 
🎫 [DOC-1503](https://spectrocloud.atlassian.net/browse/DOC-1503)
[DOC-1503]: https://spectrocloud.atlassian.net/browse/DOC-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: replace cve-reports as skipped path DOC-1503

_partials/self-hosted/_kubernetes_palette_versions.mdx, _partials/self-hosted/_setup-steps.mdx, docs/docs-content/clusters/pcg/deploy-pcg-k8s.md, docs/docs-content/clusters/pcg/pcg.md, docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md, docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/env-setup-vm.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/enterprise-version/install-palette/install-palette.md, docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md, docs/docs-content/enterprise-version/upgrade/upgrade-k8s/non-airgap.md, docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md, docs/docs-content/enterprise-version/upgrade/upgrade-vmware/non-airgap.md, docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/env-setup-vm-vertex.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md, docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
- [docs: add kubernetes requirements to self-hosted, vertex and pcg DOC-1519 (#5056)](https://github.com/spectrocloud/librarium/pull/5056)
=> [version-4-4] docs: add kubernetes requirements to self-hosted, vertex and pcg DOC-1519 (#5056)

_partials/self-hosted/_kubernetes_palette_versions.mdx, docs/docs-content/clusters/pcg/deploy-pcg-k8s.md, docs/docs-content/clusters/pcg/pcg.md, docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md, docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/enterprise-version/install-palette/install-palette.md, docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md, docs/docs-content/enterprise-version/upgrade/upgrade-k8s/non-airgap.md, docs/docs-content/enterprise-version/upgrade/upgrade-vmware/airgap.md, docs/docs-content/enterprise-version/upgrade/upgrade-vmware/non-airgap.md, docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/vmware-vsphere-airgap-instructions.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md, docs/docs-content/vertex/install-palette-vertex/install-palette-vertex.md
- [docs: add kubernetes requirements to self-hosted, vertex and pcg DOC-1519 (#5056)](https://github.com/spectrocloud/librarium/pull/5056)
=> [version-4-3] docs: add kubernetes requirements to self-hosted, vertex and pcg DOC-1519 (#5056)

.github/workflows/release.yaml
This PR adds a Slack notification for when the release to production build fails.
It was tested with a force failure step that successfully outputted a message to the Doc Team private slack channel: https://github.com/spectrocloud/librarium/actions/runs/12379389068/job/34553410821
🎫 [DOC-1499](https://spectrocloud.atlassian.net/browse/DOC-1499)
[DOC-1499]: https://spectrocloud.atlassian.net/browse/DOC-1499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: slack notification for release to production (gh-action)

docs/docs-content/clusters/cluster-management/cluster-updates.md, docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
=> [version-4-4] docs: fix up broken links DOC-1532 (#5155)

docs/docs-content/clusters/cluster-management/cluster-updates.md, docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
=> [version-4-3] docs: fix up broken links DOC-1532 (#5155)

docs/docs-content/clusters/cluster-management/cluster-updates.md, docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
=> [version-4-2] docs: fix up broken links DOC-1532 (#5155)

docs/docs-content/clusters/cluster-management/cluster-updates.md, docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md
=> [version-4-1] docs: fix up broken links DOC-1532 (#5155)

docs/docs-content/clusters/cluster-management/cluster-updates.md
=> [version-3-4] docs: fix up broken links DOC-1532 (#5155)

docs/docs-content/clusters/cluster-management/cluster-updates.md
=> [version-4-0] docs: fix up broken links DOC-1532 (#5155)

docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
This PR fixes a broken link in the Edge tutorial.
💻 [Edge Tutorial](https://deploy-preview-5186--docs-spectrocloud.netlify.app/tutorials/edge/deploy-cluster-virtualbox/)
🎫 [DOC-1549](https://spectrocloud.atlassian.net/browse/DOC-1549)
[DOC-1549]: https://spectrocloud.atlassian.net/browse/DOC-1549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: fix broken link

static/packs-data/packs_information.json
This PR changes the Pack information for Portworx packs to mention Portworx Enterprise instead of CSI Driver. 
As part of this work, we have also raised https://github.com/spectrocloud/pax/pull/2422 which fixes up the readme formats for Portworx Generic and Generic AddOn packs. 
💻 [Portworx Generic](https://deploy-preview-5200--docs-spectrocloud.netlify.app/integrations/packs/?pack=csi-portworx-generic)
💻 [Portworx Generic AddOn](https://deploy-preview-5200--docs-spectrocloud.netlify.app/integrations/packs/?pack=portworx-add-on)
🎫 [DOC-1521](https://spectrocloud.atlassian.net/browse/DOC-1521)
[DOC-1521]: https://spectrocloud.atlassian.net/browse/DOC-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: change pack information for Portworx DOC-1521

package-lock.json, package.json
This will backport PR #5194  from `master` to `version-4-5`.
=> [version-4-5] chore: bump typescript from 5.3.3 to 5.7.2 (#5194)

package-lock.json, package.json
This will backport PR #5194  from `master` to `version-4-3`.
=> [version-4-3] chore: bump typescript from 5.3.3 to 5.7.2 (#5194)

package-lock.json, package.json
This will backport PR #5194  from `master` to `version-4-1`.
=> [version-4-1] chore: bump typescript from 5.3.3 to 5.7.2 (#5194)

package-lock.json, package.json
This will backport PR #5194  from `master` to `version-3-4`.
=> [version-3-4] chore: bump typescript from 5.3.3 to 5.7.2 (#5194)

docs/api-content/api-docs/2-samples.md
- [Fix sample shell commands (#5220)](https://github.com/spectrocloud/librarium/pull/5220)
=> [version-3-4] Fix sample shell commands (#5220)

docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools.md
This PR adjusts the existing node pool repave workaround after testing confirmed this behaviour. The new steps are also more arbitrary.
💻 [Create Hybrid Node Pools](https://deploy-preview-5229--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools/#trigger-repave-on-hybrid-node-pool)
🎫 [DOC-1511](https://spectrocloud.atlassian.net/browse/DOC-1511)
Merge to feature branch.
[DOC-1511]: https://spectrocloud.atlassian.net/browse/DOC-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: node pool repave workaround adjustments

docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
- [docs: fix broken links (#5245)](https://github.com/spectrocloud/librarium/pull/5245)
=> [version-4-4] docs: fix broken links (#5245)

docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables.md
This PR updates the Cluster Profile variables table and removes sprig from the variables column.
🎫 [DOC-1570](https://spectrocloud.atlassian.net/browse/DOC-1570)
[DOC-1570]: https://spectrocloud.atlassian.net/browse/DOC-1570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1570

docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables.md
This PR removes the Edge limitation for cluster profile variables for 4.5.c. Cluster profile variables can now be used with any Palette-connected cluster. 
Notes:
- Decided to NOT remove tech preview, though I did remove the Local UI mention. [PEM-6535](https://spectrocloud.atlassian.net/browse/PEM-6535) confirms it is not leaving the tech preview phase until 4.6.0.
- Yuliia already leaned into Day-2 variable management with profile versioning. The majority of Day-2 features are coming in 4.6.0 ([PEM-4367](https://spectrocloud.atlassian.net/browse/PEM-4367)).
💻 [Define and Manage Profile Variables](https://deploy-preview-5217--docs-spectrocloud.netlify.app/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables/)
🎫 …
=> docs: PEM-6611: Cluster Profile Variables Updates

docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/architecture.md, docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools.md
This PR makes some minor terminology fixes to the EKS Hybrid Nodes docs.
💻 [Architecture](https://deploy-preview-5323--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks-hybrid-nodes/architecture/#supported-edge-hosts)
💻 [Create Hybrid Node Pools](https://deploy-preview-5323--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools/)
4.5.c release fix
=> docs: change from provider images to edgeforge

docs/docs-content/release-notes.md
This PR updates the release note page for 4.0 to accurately reflect that maintenance mode is not exclusive to VMO.
NOTE: Do NOT merge this into 4.0 until [PR 5100](https://github.com/spectrocloud/librarium/pull/5100) is complete.
💻 [Release Notes](https://deploy-preview-5332--docs-spectrocloud.netlify.app/release-notes/)
🎫 [DOC-912](https://spectrocloud.atlassian.net/browse/DOC-912)
Affects 4.0 only.
[DOC-912]: https://spectrocloud.atlassian.net/browse/DOC-912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-912 Continued: Updated Maintenance Mode Release Note

plugins/packs-integrations.js, static/packs-data/exclude_packs.json
This PR adds a safeguard against undefined children on pack version reading. This was causing outages on the VMO pack. This safeguards makes the code more robust. 
🎫 [DOC-1583](https://spectrocloud.atlassian.net/browse/DOC-1583)
[DOC-1583]: https://spectrocloud.atlassian.net/browse/DOC-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add safeguard against undefined pack versions DOC-1583

plugins/packs-integrations.js, static/packs-data/exclude_packs.json
This will backport the following commits from `master` to `version-4-5`:
- [docs: add safeguard against undefined pack versions DOC-1583 (#5350)](https://github.com/spectrocloud/librarium/pull/5350)
=> [version-4-5] docs: add safeguard against undefined pack versions DOC-1583 (#5350)

src/components/PacksReadme/PacksReadme.tsx, src/constants/packs.ts, static/packs-data/exclude_packs.json
This PR adds: 
- Guards for undefined children versions
- removes vmo from exclusion list 
- removes tencent from various places
💻 [VMO pack](https://deploy-preview-5366--docs-spectrocloud.netlify.app/integrations/packs/?pack=virtual-machine-orchestrator&version=4.5.5&parent=4.5.x&tab=main)
🎫 [DOC-1583](https://spectrocloud.atlassian.net/browse/DOC-1583)
[DOC-1583]: https://spectrocloud.atlassian.net/browse/DOC-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add nil guards to render pack versions DOC-1583

docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/create-addon-profile.md, docs/docs-content/profiles/profile-customization.md
This PR documents how to modify the Install Order priority of add-on packs through the YAML template. Two main changes were added to this PR:
1. The Install Order section got an example YAML.  This will help the reader better understand how to use the parameter in the Pack YAML.
2. Added a row to the profile customization table with a link to the Install Order section. This will help readers find the information. 
💻 [Profile Customization Page](https://deploy-preview-5418--docs-spectrocloud.netlify.app/profiles/profile-customization/)
💻 [Install Order Section](https://deploy-preview-5418--docs-spectrocloud.netlify.app/profiles/cluster-profiles/create-cluster-profiles/create-addon-profile/#install-order)
🎫 [DOC-1579](https://spectrocloud.atlassian.net/browse/DOC-1579)
Can this PR be …
=> docs: DOC-1579

docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
This PR updates the user-data config with the `projectName` parameter. It also clarifies that `projectName` is not required if a Default Project is set in the associated registration token.
💻 [Install Palette Agent](https://deploy-preview-5417--docs-spectrocloud.netlify.app/deployment-modes/agent-mode/install-agent-host/)
🎫 [DOC-1577](https://spectrocloud.atlassian.net/browse/DOC-1577)
[DOC-1577]: https://spectrocloud.atlassian.net/browse/DOC-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1577: Add projectName prereq to Palette Agent

docs/docs-content/vm-management/architecture.md, docs/docs-content/vm-management/create-vmo-profile.md, docs/docs-content/vm-management/install-vmo-in-airgap.md
This PR adjust the VMO profile guidance regarding the Spectro Proxy and Volume Snapshot Controller packs. 
💻 [Architecture](https://deploy-preview-5425--docs-spectrocloud.netlify.app/vm-management/architecture/)
💻 [Create a VMO Profile](https://deploy-preview-5425--docs-spectrocloud.netlify.app/vm-management/create-vmo-profile/)
💻 [Install VMO in Airgap Environments](https://deploy-preview-5425--docs-spectrocloud.netlify.app/vm-management/install-vmo-in-airgap/)
🎫 [DOC-1590](https://spectrocloud.atlassian.net/browse/DOC-1590)
🎫 [DOC-1591](https://spectrocloud.atlassian.net/browse/DOC-1591)
Merge to release branch.
[DOC-1590]: https://spectrocloud.atlassian.net/browse/DOC-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> docs: adjust VMO profile guidance for Spectro Proxy and Snapshot Controller DOC-1590 DOC-1591

docs/docs-content/automation/palette-cli/commands/commands.md, docs/docs-content/automation/palette-cli/commands/validate-auth.md, docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md, docs/docs-content/clusters/public-cloud/azure/required-permissions.md
This PR documents the new `validate-auth` command for the Palette CLI.
💻 [Commands](https://deploy-preview-5434--docs-spectrocloud.netlify.app/automation/palette-cli/commands/) - added `validate-auth` to command list.
💻 [Required IAM Policies](https://deploy-preview-5434--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/required-iam-policies/) - added tip admonition.
💻 [Required Permissions](https://deploy-preview-5434--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/required-permissions/) - changed existing tip admonition.
💻 [Validate-Auth](https://deploy-preview-5434--docs-spectrocloud.netlify.app/automation/palette-cli/commands/validate-auth/)
🎫 [PLT-1558](https://spectrocloud.atlassian.net/browse/PLT-1558)
4.5.c release ticket.
[PLT-1558]: …
=> docs: validate-auth command for Palette CLI

docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md, docs/docs-content/vertex/install-palette-vertex/airgap/supplemental-packs.md
This PR updates the supplemental pages for Palette and Vertex. Updates binaries and OVAs. 
💻 [Palette Supplemental Packs](https://deploy-preview-5478--docs-spectrocloud.netlify.app/enterprise-version/install-palette/airgap/supplemental-packs/)
💻 [VerteX Supplemental Packs](https://deploy-preview-5478--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/airgap/supplemental-packs/)
🎫 [DOC-1599](https://spectrocloud.atlassian.net/browse/DOC-1599)
[DOC-1599]: https://spectrocloud.atlassian.net/browse/DOC-1599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: update supplemental packs pages DOC-1599

docs/docs-content/integrations/kubernetes-microk8s.md
This PR removes the tech preview banner from the microk8s pack. 
💻 [MicroK8s](https://deploy-preview-5493--docs-spectrocloud.netlify.app/integrations/packs/?pack=kubernetes-microk8s&version=1.28&parent=1.28.x&tab=custom)
🎫 [PCP-4016](https://spectrocloud.atlassian.net/browse/PCP-4016)
[PCP-4016]: https://spectrocloud.atlassian.net/browse/PCP-4016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: remove tech preview banner from microk8s PCP-4016

docs/docs-content/release-notes/release-notes.md
This PR modifies the release notes to clarify the scope of cluster profile variables. 
🎫 [PE-5993](https://spectrocloud.atlassian.net/browse/PE-5993)
[PE-5993]: https://spectrocloud.atlassian.net/browse/PE-5993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: modify release notes for cl

docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
This PR corrects an incorrect flag in the "Install Agent Mode" prereq section for SELinux policy permissions.
💻 [Install Agent Mode](https://deploy-preview-5566--docs-spectrocloud.netlify.app/deployment-modes/agent-mode/install-agent-host/)
🎫 [DOC-1621](https://spectrocloud.atlassian.net/browse/DOC-1621)
[DOC-1621]: https://spectrocloud.atlassian.net/browse/DOC-1621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1621: semodule_package --outfile flag

.github/workflows/api_format.yaml, .github/workflows/backport.yaml, .github/workflows/clean-up-unused-images.yaml, .github/workflows/image_optimizer.yaml, .github/workflows/packs-data.yaml, .github/workflows/pull_request.yaml, .github/workflows/release.yaml
This PR fixes the backport issues for PR #5530
=> [version-4-2] chore: bump hashicorp/vault-action from 3.0.0 to 3.1.0 (#5530)

.github/workflows/api_format.yaml, .github/workflows/backport.yaml, .github/workflows/clean-up-unused-images.yaml, .github/workflows/image_optimizer.yaml, .github/workflows/packs-data.yaml, .github/workflows/pull_request.yaml, .github/workflows/release.yaml
This PR fixes the backport issues from PR #5530
=> [version-4-1] chore: bump hashicorp/vault-action from 3.0.0 to 3.1.0 (#5530)

docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/checklist.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/checklist.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions.md
This PR updates self-hosted and VerteX guides to replace references to the third-party binary with the release binary, as the release binary is the one responsible for installing packs and images that are specific to a release.
💻 [Self-hosted Env Setup](https://deploy-preview-5564--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions/)
💻 [Self-hosted Checklist](https://deploy-preview-5564--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/airgap-install/checklist/)
💻 [VerteX Env Setup](https://deploy-preview-5564--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/airgap-install/environment-setup/vmware-vsphere-airgap-instructions/) …
=> docs: fix third-party references in self-hosted airgap guides

docs/docs-content/clusters/clusters.md
This PR includes `us-docker.pkg.dev` domain in the proxy requirements. This is currently missing in [proxy-whitelist](https://docs.spectrocloud.com/4.5.x/clusters/#proxy-whitelist) doc page
=> Include us-docker domain in proxy requirements

docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools.md, docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode.md
This PR fixes some descriptions for the Cilium configuration during EKS Hybrid Nodes - Cluster Import steps. It also fixes the steps to enable agent mode when configuring the hybrid node pool cluster profile.
💻 [Import EKS Cluster and Enable Hybrid Mode](https://deploy-preview-5605--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode/#add-cni-cluster-profile)
💻 [Create Hybrid Node Pools](https://deploy-preview-5605--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools/#create-profile)
=> docs: update cilium parameter descriptions and agent mode steps for EKS Hybrid Nodes

docs/docs-content/spectro-downloads.md
This PR fixes the Edge binary download link to use the correct version (4.5.13 > 4.5.14).
💻 [Downloads](https://deploy-preview-5607--docs-spectrocloud.netlify.app/spectro-downloads/)
🎫 [DOC-1650](https://spectrocloud.atlassian.net/browse/DOC-1650)
[DOC-1650]: https://spectrocloud.atlassian.net/browse/DOC-1650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1650: Edge Binary Download Link Fix

docs/api-content/api-docs/1-introduction.md, docs/docs-content/release-notes/release-notes.md
This PR updates the API rate limit for `v1/cloudconfigs` resources and adds the updated limit to the release notes.
💻 
[Release Notes](https://deploy-preview-5609--docs-spectrocloud.netlify.app/release-notes/) - Added to release notes
[Palette API - Introduction](https://deploy-preview-5609--docs-spectrocloud.netlify.app/api/introduction/#rate-limits) - Increased rate/burst limit
🎫 [DOC-1646](https://spectrocloud.atlassian.net/browse/DOC-1646)
4.6 release work.
[DOC-1646]: https://spectrocloud.atlassian.net/browse/DOC-1646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1646: Update API Rate Limit for v1/cloudconfig Resources

_partials/permissions/_vsphere-permissions.mdx
This PR corrects a small typo, where "Local Operations" was listed as a category when it should be a subcategory of "Host." Small "propagation" spelling fix included.
💻 [VMware - Required Permissions](https://deploy-preview-5610--docs-spectrocloud.netlify.app/clusters/data-center/vmware/permissions/#spectro-role-privileges)
🎫 [DOC-1653](https://spectrocloud.atlassian.net/browse/DOC-1653)
[DOC-1653]: https://spectrocloud.atlassian.net/browse/DOC-1653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1653: Changing VMware vSphere Local Operations Permission to Subcategory

docs/docs-content/clusters/public-cloud/aws/eks.md, docs/docs-content/troubleshooting/pack-issues.md
- [Document workaround for enabling Cilium pack with EKS clusters (#5623)](https://github.com/spectrocloud/librarium/pull/5623)
=> [version-4-2] Document workaround for enabling Cilium pack with EKS clusters (#5623)

docs/docs-content/clusters/public-cloud/aws/eks.md, docs/docs-content/troubleshooting/pack-issues.md
- [Document workaround for enabling Cilium pack with EKS clusters (#5623)](https://github.com/spectrocloud/librarium/pull/5623)
=> [version-4-1] Document workaround for enabling Cilium pack with EKS clusters (#5623)

docs/docs-content/component.md, docs/docs-content/release-notes/release-notes.md, docs/docs-content/spectro-downloads.md
This PR adds release notes for patch 4.5.21. It also adds 4.5.15 edge CLI version. 
💻 [Release Notes](https://deploy-preview-5622--docs-spectrocloud.netlify.app/release-notes/)
🎫 [DOC-1655](https://spectrocloud.atlassian.net/browse/DOC-1655)
Only 4.5
[DOC-1655]: https://spectrocloud.atlassian.net/browse/DOC-1655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: release notes patch 4.5.21

docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
This PR removes the text "EOF" from the example Edgeforge .arg file. This was left over from a `cat << EOF > .arg` command in 4.2 documentation.
💻 [Build Installer ISO](https://deploy-preview-5682--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso/#instructions)
🎫 [DOC-1664](https://spectrocloud.atlassian.net/browse/DOC-1664)
[DOC-1664]: https://spectrocloud.atlassian.net/browse/DOC-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1664: Removing Erroneous "EOF" from .arg File

docs/docs-content/clusters/public-cloud/aws/architecture.md, docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/architecture.md, docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode.md, docs/docs-content/clusters/public-cloud/aws/eks.md
This PR adds additional important information when deploying AWS EKS or importing a cluster with Hybrid Nodes enabled.
It also includes a small fix to a couple of configure CNI steps.
💻 [EKS Hybrid Nodes - Architecture](https://deploy-preview-5661--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks-hybrid-nodes/architecture/#amazon-eks-cluster-requirements)
💻 [AWS Architecture](https://deploy-preview-5661--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/architecture/#worker-node-requirements)
💻 [Import EKS Cluster and Enable Hybrid Mode](https://deploy-preview-5661--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks-hybrid-nodes/import-eks-cluster-enable-hybrid-mode/#prerequisites)
💻 [Create and Manage AWS EKS …
=> docs: EKS cluster and EKS hybrid requirements

docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools.md
This PR adds an additional step and example when using Appliance Mode and configuring the hybrid node pool cluster profile for EKS Hybrid clusters.
💻 [Create Hybrid Node Pools](http://deploy-preview-5704--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks-hybrid-nodes/create-hybrid-node-pools/#create-profile)
🎫 [DOC-1652](https://spectrocloud.atlassian.net/browse/DOC-1652)
[DOC-1652]: https://spectrocloud.atlassian.net/browse/DOC-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Appliance Mode step for hybrid pool creation

docs/docs-content/enterprise-version/upgrade/upgrade.md, docs/docs-content/vertex/upgrade/upgrade.md
This PR updates self-hosted Palette and VerteX upgrade paths for 4.5.21 and also adds Helm (Kubernetes) upgrade paths.
Note: The paths for versions 4.4 and 4.3 are the same for both VMware and Kubernetes installations since we did not have separate tests at that time.
💻 [Self-hosted Upgrade](https://deploy-preview-5722--docs-spectrocloud.netlify.app/enterprise-version/upgrade/)
💻 [VerteX Upgrade](https://deploy-preview-5722--docs-spectrocloud.netlify.app/vertex/upgrade/)
=> docs: update 4.5.21 upgrade paths and helm paths

docs/docs-content/automation/palette-cli/commands/ec.md
This PR removes the admonition associated with the `palette ec install --validate` that stated internet connectivity was required. The `--validate` flag now works in airgapped environments as well.
💻 [EC](https://deploy-preview-5728--docs-spectrocloud.netlify.app/automation/palette-cli/commands/ec/#validate-environment)
🎫 [PLT-1601](https://spectrocloud.atlassian.net/browse/PLT-1601)
[PLT-1601]: https://spectrocloud.atlassian.net/browse/PLT-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: PLT-1601: EC --validate Works in Airgap

_partials/self-hosted/_kubernetes_palette_versions.mdx, docs/docs-content/component.md, docs/docs-content/enterprise-version/upgrade/upgrade.md, docs/docs-content/release-notes/release-notes.md, docs/docs-content/spectro-downloads.md, docs/docs-content/vertex/upgrade/upgrade.md
This PR updates VerteX and Palette self-hosted upgrade paths for 4.6.6.
It also updates binaries/names to 4.6.6.
💻 [Self-hosted Kubernetes Requirements](https://deploy-preview-5758--docs-spectrocloud.netlify.app/enterprise-version/install-palette/#kubernetes-requirements) -> VerteX and PCG use the same partial
💻 [Downloads](https://deploy-preview-5758--docs-spectrocloud.netlify.app/spectro-downloads/)
💻 [Compatibility Matrix](https://deploy-preview-5758--docs-spectrocloud.netlify.app/component/)
💻 [Release Notes](https://deploy-preview-5758--docs-spectrocloud.netlify.app/release-notes/)
💻 [VerteX upgrade](https://deploy-preview-5758--docs-spectrocloud.netlify.app/vertex/upgrade/)
💻 [Self-hosted upgrade](https://deploy-preview-5758--docs-spectrocloud.netlify.app/enterprise-version/upgrade/) …
=> docs: update upgrade path

docs/docs-content/clusters/data-center/maas/create-manage-maas-clusters.md, docs/docs-content/clusters/data-center/maas/register-manage-maas-cloud-accounts.md
- [docs: fix broken MAAS doc links (#5761)](https://github.com/spectrocloud/librarium/pull/5761)
=> [version-4-0] docs: fix broken MAAS doc links (#5761)

docs/docs-content/clusters/pcg/deploy-pcg-k8s.md, docs/docs-content/clusters/pcg/pcg.md
This PR updates the PCG Kubernetes requirement table to remove the OVA columns, as they only apply to self-hosted/vertex.
Note: I will manually remove the 4.6 version from the K8s table in the 4.5 backport PR.
💻 [PCG](https://deploy-preview-5791--docs-spectrocloud.netlify.app/clusters/pcg/)
💻 [Deploy a PCG to an Existing Kubernetes Cluster](https://deploy-preview-5791--docs-spectrocloud.netlify.app/clusters/pcg/deploy-pcg-k8s/)
=> docs: update pcg k8s requirements table

docs/docs-content/release-notes/release-notes.md
This will backport the following commits from `master` to `version-4-6`:
- [docs: add release notes for 4.6.9 DOC-1713 (#5933)](https://github.com/spectrocloud/librarium/pull/5933)
=> [version-4-6] docs: add release notes for 4.6.9 DOC-1713 (#5933)

.github/workflows/eslint-test.yaml, package-lock.json, package.json
This PR bumps the `free-solid-svg-icons` dependency to match `fontawesome-svg-core` which was updated in https://github.com/spectrocloud/librarium/pull/5921
The version mismatch lead to compile errors and test failures.  
It also adds `package.json` and `package-lock.json` as paths that can trigger the test workflows so that we can detect such breakages in the future.
💻 [Docs](https://deploy-preview-5959--docs-spectrocloud.netlify.app/)
None.
Everywhere
=> docs: bump free-solid-svg-icons to 6.7.2

docs/docs-content/deployment-modes/agent-mode/agent-mode.md, docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
This PR removes the tech preview admonitions for Agent Mode, which is entering GA in 4.6.a.
- [Agent Mode]()
- [Install Palette Agent]()
🎫 [DOC-1741](https://spectrocloud.atlassian.net/browse/DOC-1741)
4.6.a release work.
[DOC-1741]: https://spectrocloud.atlassian.net/browse/DOC-1741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1741: Agent Mode Exiting Tech Preview

docs/docs-content/clusters/clusters.md, docs/docs-content/registries-and-packs/add-custom-packs.md, docs/docs-content/registries-and-packs/registries-and-packs.md
This PR removes Ansible references from the Packs and Registries docs.
💻 [Registries and Packs](https://deploy-preview-6064--docs-spectrocloud.netlify.app/registries-and-packs/)
💻 [Add a Custom Pack](https://deploy-preview-6064--docs-spectrocloud.netlify.app/registries-and-packs/add-custom-packs/)
💻 [Clusters](https://deploy-preview-6064--docs-spectrocloud.netlify.app/clusters/)
🎫 [DOC-1742](https://spectrocloud.atlassian.net/browse/DOC-1742)
[DOC-1742]: https://spectrocloud.atlassian.net/browse/DOC-1742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: remove ansible references

docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md, docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md, docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions.md, docs/docs-content/vertex/upgrade/upgrade-k8s/airgap.md
This PR fixes the `oras login` flags.
💻 [Self-hosted Environment Setup](https://deploy-preview-6123--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions/)
💻 [Self-hosted Upgrade](https://deploy-preview-6123--docs-spectrocloud.netlify.app/enterprise-version/upgrade/upgrade-k8s/airgap/)
💻 [VerteX Environment Setup](https://deploy-preview-6123--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/kubernetes-airgap-instructions/)
💻 [VerteX Upgrade](https://deploy-preview-6123--docs-spectrocloud.netlify.app/vertex/upgrade/upgrade-k8s/airgap/)
=> docs: update flags in oras login commands

docs/docs-content/troubleshooting/nodes.md
This PR adds troubleshooting for removing unused namespaces from a cluster, using the NATS namespace `nats-system` as an example.
💻 [Troubleshooting - Nodes and Clusters](https://deploy-preview-6122--docs-spectrocloud.netlify.app/troubleshooting/nodes/#scenario---remove-unused-namespaces)
🎫 [PEM-7190](https://spectrocloud.atlassian.net/browse/PEM-7190)
Release work.
[PEM-7190]: https://spectrocloud.atlassian.net/browse/PEM-7190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: PEM-7190: Troubleshooting to Remove nats-system Namespace

docs/docs-content/enterprise-version/upgrade/upgrade.md, docs/docs-content/vertex/upgrade/upgrade.md
This PR adds the upgrade paths for 4.6.12.
🎫 [DOC-1719](https://spectrocloud.atlassian.net/browse/DOC-1719)
[DOC-1719]: https://spectrocloud.atlassian.net/browse/DOC-1719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: upgrade paths DOC-1719

docs/docs-content/clusters/palette-virtual-clusters/deploy-virtual-cluster.md
=> [version-4-4] docs: virtual cluster guidance for cluster mode (#6182)

docs/docs-content/clusters/palette-virtual-clusters/deploy-virtual-cluster.md
=> [version-4-3] docs: virtual cluster guidance for cluster mode (#6182)

docs/docs-content/clusters/palette-virtual-clusters/deploy-virtual-cluster.md
=> [version-4-2] docs: virtual cluster guidance for cluster mode (#6182)

docs/docs-content/clusters/palette-virtual-clusters/deploy-virtual-cluster.md
=> [version-4-1] docs: virtual cluster guidance for cluster mode (#6182)

docs/docs-content/clusters/palette-virtual-clusters/deploy-virtual-cluster.md
=> [version-4-0] docs: virtual cluster guidance for cluster mode (#6182)

docs/docs-content/tutorials/edge/deploy-cluster-virtualbox.md
This PR removes an additional Earthly link from the Edge Virtual Box tutorial that was left out of [PR 6027](https://github.com/spectrocloud/librarium/pull/6207). This fix is included in the backports for versions 4.4 - 4.0.
💻 [Edge - VirtualBox Tutorial](https://deploy-preview-6222--docs-spectrocloud.netlify.app/tutorials/edge/deploy-cluster-virtualbox/)
=> docs: Removing Additional Earthly Link from VirtualBox Edge Tutorial

docs/docs-content/clusters/edge/edgeforge-workflow/prepare-user-data.md
This PR corrects a "Portwox" spelling error.
🎫 [DOC-1782](https://spectrocloud.atlassian.net/browse/DOC-1782)
[DOC-1782]: https://spectrocloud.atlassian.net/browse/DOC-1782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1782: Fixing Portworx Spelling

docs/docs-content/release-notes/release-notes.md, docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR updates the release notes and security advisory for version 4.5 to reflect the delayed release of the Nginx 4.4 fix.
- [Release Notes](https://deploy-preview-6264--docs-spectrocloud.netlify.app/release-notes/)
- [Security Advisory](https://deploy-preview-6264--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
=> docs: 4.6 Nginx Security Updates

docs/docs-content/release-notes/release-notes.md, docs/docs-content/security-bulletins/security-advisories/security-advisories.md
Reverts spectrocloud/librarium#6252
The 4.4.22 patch is still not out, even though it is listed in Retool as GA.
=> Revert "docs: DOC-1778: 4.4 Release Notes - Security Advisory"

docs/docs-content/release-notes/release-notes.md, docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR updates the release notes and security advisory to refer to the correct date and patch for connected 4.4 installations.
- [Release Notes](https://deploy-preview-6287--docs-spectrocloud.netlify.app/release-notes/)
- [Security Advisory](https://deploy-preview-6287--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
Release notes and backports are not buddies.
=> docs: Version 4.5: Updated Release Notes + Security Advisory for 4.4 Nginx Patch

docs/docs-content/release-notes/release-notes.md, docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR updates the release notes and security advisory to refer to the correct date and patch for connected 4.4 installations.
- [Release Notes](https://deploy-preview-6288--docs-spectrocloud.netlify.app/release-notes/)
- [Security Advisory](https://deploy-preview-6288--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
Release notes and backports are not buddies.
=> docs: Version 4.4: Updated Release Notes + Security Advisory for 4.4 Nginx Patch

docs/docs-content/release-notes/release-notes.md, docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR updates the release notes and security advisory to refer to the correct date and patch for connected 4.4 installations.
- [Release Notes](https://deploy-preview-6286--docs-spectrocloud.netlify.app/release-notes/)
- [Security Advisory](https://deploy-preview-6286--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
=> docs: Version 4.6: Updated Release Notes + Security Advisory for 4.4 Nginx Patch

docs/docs-content/registries-and-packs/registries/oci-registry/add-oci-zarf.md
This PR updates the existing Add Zarf OCI Registry page to correctly reference Zarf instead of Helm and includes general cleanup. 
💻 [Add Zarf OCI Registry](https://deploy-preview-6295--docs-spectrocloud.netlify.app/registries-and-packs/registries/oci-registry/add-oci-zarf/)
🎫 [DOC-1745](https://spectrocloud.atlassian.net/browse/DOC-1745)
[DOC-1745]: https://spectrocloud.atlassian.net/browse/DOC-1745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1745: Zarf OCI Registry Cleanup

docs/docs-content/clusters/edge/edge-configuration/installer-reference.md
This PR corrects the`tagsFromFile` and `tagsFromScript` parameters on the Edge Configuration Reference page. 
💻 [Edge Configuration Reference](https://deploy-preview-6296--docs-spectrocloud.netlify.app/clusters/edge/edge-configuration/installer-reference/#tags)
🎫 [DOC-1789](https://spectrocloud.atlassian.net/browse/DOC-1789)
[DOC-1789]: https://spectrocloud.atlassian.net/browse/DOC-1789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1789: Updating Stylus tagsFromFile and tagsFromScript Parameters

docs/docs-content/release-notes/release-notes.md
This PR add the new TF provider to the release notes. 
💻 [Release Notes](https://deploy-preview-6314--docs-spectrocloud.netlify.app/release-notes/#april-3-2025---automation-updates)
🎫 [DOC-1804](https://spectrocloud.atlassian.net/browse/DOC-1804)
To 4.6
[DOC-1804]: https://spectrocloud.atlassian.net/browse/DOC-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add TF provider release DOC-1804

docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md
This PR updates the edge CLI version to the newest one. 
💻 [Export Cluster Definition](https://deploy-preview-6323--docs-spectrocloud.netlify.app/clusters/edge/local-ui/cluster-management/export-cluster-definition/#instructions)
🎫 [DOC-1801](https://spectrocloud.atlassian.net/browse/DOC-1801)
Only to 4.6.
[DOC-1801]: https://spectrocloud.atlassian.net/browse/DOC-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: update the edge CLI version DOC-1801

docs/docs-content/clusters/cluster-management/node-labels.md
This PR:
1. Adds a warning stating that editing labels on existing pods is currently not supported.
2. Removes the sentences stating that editing labels on existing pods is available.
3. Changes the "main menu" writing format in accordance with the Style Guide.
4. Rephrases sentences that contain "will".
💻 [Add Preview URL for Page](https://deploy-preview-6313--docs-spectrocloud.netlify.app/clusters/cluster-management/node-labels/)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PE-3218)
=> docs: add warning for non editable labels on existing nodes

docusaurus.config.js
This PR excludes Google tag Manager and FullStory from being loaded locally.
This will also fix the error related to Qualified.js that we're seeing locally on our dev environments.
_No user facing issues._
🎫 [DOC-1807](https://spectrocloud.atlassian.net/browse/DOC-1807)
Everywhere. 
[DOC-1807]: https://spectrocloud.atlassian.net/browse/DOC-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: exclude GTM and FullStory from being loaded locally DOC-1807

docs/docs-content/release-notes/release-notes.md, docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR updates the release notes and security advisory pages re: the final patch for airgapped self-hosted and VerteX 4.5 installations.
- [Release Notes](https://deploy-preview-6368--docs-spectrocloud.netlify.app/release-notes/)
- [Security Advisory](https://deploy-preview-6368--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
=> docs: Nginix 4-8-25 Updates (Version 4.6)

docs/docs-content/release-notes/release-notes.md, docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR updates the release notes and security advisory pages re: the final patch for airgapped self-hosted and VerteX 4.5 installations.
- [Release Notes](https://deploy-preview-6372--docs-spectrocloud.netlify.app/release-notes/)
- [Security Advisory](https://deploy-preview-6372--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
Release notes will not backport.
=> docs: Nginix 4-8-25 Updates (Version 4.5) 

docs/docs-content/release-notes/release-notes.md, docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR updates the release notes and security advisory pages re: the final patch for airgapped self-hosted and VerteX 4.5 installations.
- [Release Notes](https://deploy-preview-6370--docs-spectrocloud.netlify.app/release-notes/)
- [Security Advisory](https://deploy-preview-6370--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
Release notes will not backport.
=> docs: Nginix 4-8-25 Updates (Version 4.4)

docs/docs-content/clusters/edge/networking/vxlan-overlay.md
This PR adds PXK-E to the list of supported K8 distribution layers for Edge overlay networks. It also includes style guide adjustments and adjusts workflow steps where necessary.
💻 [Enable Overlay Network](https://deploy-preview-6375--docs-spectrocloud.netlify.app/clusters/edge/networking/vxlan-overlay/)
🎫 [DOC-1811](https://spectrocloud.atlassian.net/browse/DOC-1811)
[DOC-1811]: https://spectrocloud.atlassian.net/browse/DOC-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1811: Overlay PXK-E Support + Style Guide Adjustments

docs/api-content/api-docs/1-introduction.md
This PR increases the rate limit and burst limit for `v1/events/components`.
💻 [API - Introduction - Endpoint Prefix Rate]()
🎫 [DOC-1816](https://spectrocloud.atlassian.net/browse/DOC-1816)
Release work.
[DOC-1816]: https://spectrocloud.atlassian.net/browse/DOC-1816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1816: Increased Rate Limit for v1/events/components

docs/docs-content/getting-started/aws/deploy-manage-k8s-cluster-tf.md, docs/docs-content/getting-started/azure/deploy-manage-k8s-cluster-tf.md, docs/docs-content/getting-started/gcp/deploy-manage-k8s-cluster-tf.md, docs/docs-content/getting-started/vmware/deploy-manage-k8s-cluster-tf.md
This PR fixes a `cd` command in the Terraform tutorial.
💻 [Cluster Management with Terraform - AWS](https://deploy-preview-6420--docs-spectrocloud.netlify.app/getting-started/aws/deploy-manage-k8s-cluster-tf/)
💻 [Cluster Management with Terraform - GCP](https://deploy-preview-6420--docs-spectrocloud.netlify.app/getting-started/gcp/deploy-manage-k8s-cluster-tf/)
💻 [Cluster Management with Terraform - Azure](https://deploy-preview-6420--docs-spectrocloud.netlify.app/getting-started/azure/deploy-manage-k8s-cluster-tf/)
💻 [Cluster Management with Terraform - VMware](https://deploy-preview-6420--docs-spectrocloud.netlify.app/getting-started/vmware/deploy-manage-k8s-cluster-tf/)
=> docs: fix cd path

docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
This will backport the following commits from `master` to `version-4-5`:
- [doc: fix indentation on Install Agent Host (#6447)](https://github.com/spectrocloud/librarium/pull/6447)
=> [version-4-5] doc: fix indentation on Install Agent Host (#6447)

docs/docs-content/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables/create-cluster-profile-variables.md
This PR adds an admonition re: cluster profile variables stating that if the cluster profile variable contains a single quote, the definition should be wrapped in double quotes instead of single quotes to avoid an invalid YAML when resolving the variable.
💻 [Create Cluster Profile Variables](https://deploy-preview-6459--docs-spectrocloud.netlify.app/profiles/cluster-profiles/create-cluster-profiles/define-profile-variables/create-cluster-profile-variables/)
🎫 [DOC-1762](https://spectrocloud.atlassian.net/browse/DOC-1762)
[DOC-1762]: https://spectrocloud.atlassian.net/browse/DOC-1762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1762: Double Quote Cluster Profile Variable Exception

docs/docs-content/clusters/edge/site-deployment/site-installation/create-registration-token.md, docs/docs-content/tutorials/edge/deploy-cluster.md
This PR backports changes from #6446 to version 4.2.
💻 [Deploy an Edge Cluster on VMware](https://deploy-preview-6472--docs-spectrocloud.netlify.app/tutorials/edge/deploy-cluster/)
💻 [Create a Registration Token](https://deploy-preview-6472--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/site-installation/create-registration-token/)
=> [version-4-2] docs: update Deploy an Edge Cluster on VMware tutorial (#6446)

docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install.md, docs/docs-content/enterprise-version/system-management/registry-override.md, docs/docs-content/enterprise-version/upgrade/upgrade-k8s/airgap.md, docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install.md, docs/docs-content/vertex/upgrade/upgrade-k8s/airgap.md
This PR updates cert-manager images to use the latest `v1.17.0-spectro-4.6.1` tag.
- [Install Airgap Self-Hosted Palette](https://deploy-preview-6479--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-kubernetes/airgap-install/install/)
- [Install VerteX](https://deploy-preview-6479--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-kubernetes/airgap-install/install/)
- [Upgrade Airgap Palette Installed with Kubernetes](https://deploy-preview-6479--docs-spectrocloud.netlify.app/enterprise-version/upgrade/upgrade-k8s/airgap/)
- [Upgrade Airgap Palette VerteX Installed with Kubernetes](https://deploy-preview-6479--docs-spectrocloud.netlify.app/vertex/upgrade/upgrade-k8s/airgap/)
- [Override Registry …
=> docs: DOC-1832: Update cert-manager Version to 1.17

docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry.md, docs/docs-content/deployment-modes/agent-mode/install-agent-host.md
This PR corrects the nesting of `externalRegistries` and `registryMappingRules` for several `user-data` examples.
- [Install Palette Agent](https://deploy-preview-6486--docs-spectrocloud.netlify.app/deployment-modes/agent-mode/install-agent-host/)
- [Deploy Cluster with a Private External Registry](https://deploy-preview-6486--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/deploy-custom-registries/deploy-external-registry/)
🎫 [DOC-1833](https://spectrocloud.atlassian.net/browse/DOC-1833)
[DOC-1833]: https://spectrocloud.atlassian.net/browse/DOC-1833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1833: externalRegistries and registryMappingRules user-data Indentation

docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md
This PR changes the limitations section of build edge content bundle to specify registry connect.
💻 [Build Content Bundle limitation](https://deploy-preview-6493--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle/#limitation)
Release work.
=> docs: adjust guidance on build content bundle to mention Registry Connect

docs/docs-content/clusters/public-cloud/aws/eks.md
This PR adjusts a prettier-ignore flag to format the following headers correctly. I discovered this while looking into https://spectrocloud.atlassian.net/browse/DOC-1839.
I have also tried indenting the original `prettier-ignore-start/end` flags, but this didn't work.
💻 [Create and Manage AWS EKS Cluster](https://deploy-preview-6513--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks/)
=> doc: adjust prettier-ignore to fix EKS header formatting

docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md, docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap.md, docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rhel-capi.md, docs/docs-content/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rocky-capi.md
This PR clarifies the netmask parameter in the CAPI Builder documentation.
💻 [RHEL - Non airgap](https://deploy-preview-6529--docs-spectrocloud.netlify.app/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rhel-capi/)
💻 [Rocky - Non airgap](https://deploy-preview-6529--docs-spectrocloud.netlify.app/byoos/capi-image-builder/build-image-vmware/non-airgap-build/rocky-capi/)
💻 [RHEL - Airgap](https://deploy-preview-6529--docs-spectrocloud.netlify.app/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap/)
💻 [Rocky - Airgap](https://deploy-preview-6529--docs-spectrocloud.netlify.app/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap/)
🎫 [DOC-1775](https://spectrocloud.atlassian.net/browse/DOC-1775)
[DOC-1775]: …
=> docs: netmask specification

docs/docs-content/vertex/fips/fips-compliant-components.md
This PR adds additional info on Ubuntu Pro keys. 
💻 [FIPS Compliant Components](https://deploy-preview-6547--docs-spectrocloud.netlify.app/vertex/fips/fips-compliant-components/)
🎫 [DOC-1843](https://spectrocloud.atlassian.net/browse/DOC-1843)
Everywhere
[DOC-1843]: https://spectrocloud.atlassian.net/browse/DOC-1843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add extra information about Ubuntu Pro DOC-1843

docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md
This PR corrects the command `./earthly +build-provider-images-fips` > `./earthly.sh +build-provider-images-fips`. Relates to https://github.com/spectrocloud/librarium/pull/6563, which must be separate due to different backport versions.
💻 [Build FIPS-Compliant Edge Artifacts](https://deploy-preview-6562--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/fips/#validate)
🎫 [DOC-1856](https://spectrocloud.atlassian.net/browse/DOC-1856)
[DOC-1856]: https://spectrocloud.atlassian.net/browse/DOC-1856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1856: Correcting Earthly Script Command (FIPS)

docs/docs-content/clusters/public-cloud/gcp/required-permissions.md, docs/docs-content/release-notes/release-notes.md
This PR adds new permissions to the GCP required IAM permissions list due to a CAPG upgrade and includes a release note.
🎫 [DOC-1819](https://spectrocloud.atlassian.net/browse/DOC-1819)
[DOC-1819]: https://spectrocloud.atlassian.net/browse/DOC-1819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: Additional IAM Permissions for GCP due to CAPG upgrade

docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md, docs/docs-content/clusters/edge/site-deployment/site-installation/create-registration-token.md, docs/docs-content/tutorials/edge/deploy-cluster.md
This PR:
1. Updates file name and directory formatting to follow the style guide.
2. Improves project name warnings by handling both ways it can be set before edge host deployment—either through the registration token or in the user data field.
💻 [Build Edge Artifacts](https://deploy-preview-6595--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/)
💻 [Deploy an Edge Cluster on VMware](https://deploy-preview-6595--docs-spectrocloud.netlify.app/tutorials/edge/deploy-cluster/)
💻 [Create a Registration Token](https://deploy-preview-6595--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/site-installation/create-registration-token/)
🎫 [DOC-1817](https://spectrocloud.atlassian.net/browse/DOC-1817)
[DOC-1817]: …
=> Fix warning and formatting

docs/docs-content/clusters/cluster-management/remove-clusters.md
This PR adds an admonition informing users to check their cloud credentials before force-deleting a cluster.
It also improves the structure of the page with some additional headers.
🎫 [DOC-1862](https://spectrocloud.atlassian.net/browse/DOC-1862)
[DOC-1862]: https://spectrocloud.atlassian.net/browse/DOC-1862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: check cloud credentials before force-deleting a cluster

docs/docs-content/vm-management/create-manage-vm/advanced-topics/deploy-import-ova.md
This PR adds an info box with the VM prerequisite tools. 
💻 [Import and Deploy OVAs to Palette VMO](https://deploy-preview-6654--docs-spectrocloud.netlify.app/vm-management/create-manage-vm/advanced-topics/deploy-import-ova/#enablement)
🎫 [DOC-1847](https://spectrocloud.atlassian.net/browse/DOC-1847)
This guide is everywhere. 
[DOC-1847]: https://spectrocloud.atlassian.net/browse/DOC-1847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add VM tools to deploy import guide DOC-1847

_partials/_additional-deployment-options.mdx, docs/docs-content/downloads/palette-vertex/additional-packs.md, docs/docs-content/downloads/self-hosted-palette/additional-packs.md
This PR updates the VMO and vCluster airgap binary versions. It also moves these sections for VerteX and Self-Hosted into a partial for easier updates in the future.
💻 [Additional Deployment Options (self-hosted)](https://deploy-preview-6671--docs-spectrocloud.netlify.app/downloads/self-hosted-palette/additional-packs/#additional-deployment-options)
💻 [Additional Deployment Options (vertex)](https://deploy-preview-6671--docs-spectrocloud.netlify.app/downloads/palette-vertex/additional-packs/#additional-deployment-options)
🎫 [DOC-1880](https://spectrocloud.atlassian.net/browse/DOC-1880)
[DOC-1880]: https://spectrocloud.atlassian.net/browse/DOC-1880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: update VMO and vCluster airgap binary versions

.github/workflows/url-checks.yaml, Makefile, docs/docs-content/getting-started/getting-started.md, linkinator/linkinator-ci.config.json, linkinator/linkinator-rate-limit-ci.config.json, linkinator/linkinator-rate-limit.config.json, linkinator/linkinator.config.json, scripts/url-checker-github.sh, scripts/url-checker.sh
This PR adds a special job for handling URL checks on Github links. It also moves posting to the private team channel. Linkinator is now configured to skip validation of Github links.
_No UI changes._
🎫 [DOC-1877](https://spectrocloud.atlassian.net/browse/DOC-1877)
Job only executes in master, but can target other branches. Won't backport.
[DOC-1877]: https://spectrocloud.atlassian.net/browse/DOC-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add special handling for broken GitHub link detection DOC-1877

docs/docs-content/clusters/edge/edge-configuration/installer-reference.md, docs/docs-content/clusters/edge/local-ui/cluster-management/cluster-management.md, docs/docs-content/clusters/edge/local-ui/cluster-management/create-cluster.md, docs/docs-content/clusters/edge/local-ui/cluster-management/delete-cluster.md, docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md, docs/docs-content/clusters/edge/local-ui/cluster-management/link-hosts.md, docs/docs-content/clusters/edge/local-ui/cluster-management/local-to-central.md, docs/docs-content/clusters/edge/local-ui/cluster-management/scale-cluster.md, docs/docs-content/clusters/edge/local-ui/cluster-management/update-cluster.md, docs/docs-content/clusters/edge/local-ui/cluster-management/upload-content-bundle.md, docs/docs-content/clusters/edge/local-ui/host-management/access-console.md, docs/docs-content/clusters/edge/local-ui/host-management/configure-proxy.md, docs/docs-content/clusters/edge/local-ui/host-management/custom-link.md, docs/docs-content/clusters/edge/local-ui/host-management/edit-user-data.md, docs/docs-content/clusters/edge/local-ui/host-management/host-management.md, docs/docs-content/clusters/edge/local-ui/host-management/reset-reboot.md, docs/docs-content/clusters/edge/local-ui/host-management/theming.md, docs/docs-content/clusters/edge/local-ui/local-ui.md
This PR moves local UI out of tech preview status. It also removes the `enableMultinode` flag because that feature is no longer feature gated.
🎫 [PE-6574](https://spectrocloud.atlassian.net/issues/PE-6574?filter=11884)
[PE-6574]: https://spectrocloud.atlassian.net/browse/PE-6574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: GA Local UI.

docs/docs-content/clusters/public-cloud/aws/eks-hybrid-nodes/prepare-environment/prepare-edge-hosts.md, docs/docs-content/deployment-modes/agent-mode/agent-mode.md, docs/docs-content/deployment-modes/agent-mode/install-agent-host.md, docs/docs-content/downloads/agent-mode.md, docs/docs-content/release-notes/release-notes.md
This PR updates the Prepare Edge Hosts page in the EKS Hybrid docs to be more inline with the Appliance Mode documentation.
🎫 [DOC-1879](https://spectrocloud.atlassian.net/browse/DOC-1879)
[DOC-1879]: https://spectrocloud.atlassian.net/browse/DOC-1879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-1879 - Refactor 'connected/airgap' to 'central/local' on Prepare Edge Hosts page (EKS Hybrid)

docs/docs-content/clusters/edge/cluster-management/agent-upgrade-airgap.md
This PR adds a warning that upgrades to 4.6.16 or later cannot use the Edge CLI.
💻 [Add Preview URL for Page](https://spectrocloud.atlassian.net/issues/PE-6560?filter=11884)
🎫 [PE-6560](https://spectrocloud.atlassian.net/issues/PE-6560)
[PE-6560]: https://spectrocloud.atlassian.net/browse/PE-6560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: do not use Palette Edge CLI for upgrade to 4.6.16 or later

docs/docs-content/enterprise-version/install-palette/airgap/supplemental-packs.md, docs/docs-content/vertex/install-palette-vertex/airgap/supplemental-packs.md
This PR adds the missing third-party binary pack for version 4.4 and corrects the conformance capabilities section as the usage instructions should be pointing to download instructions.
🎫 [DOC-1874](https://spectrocloud.atlassian.net/browse/DOC-1874)
Only for version-4-4.
[DOC-1874]: https://spectrocloud.atlassian.net/browse/DOC-1874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [version-4-4] doc: fix third-party binary addition and conformance instructions

docs/docs-content/release-notes/release-notes.md
This PR adds a pack note mentioning the deprecation of  BYOS - Agent Mode pack.
💻 [Pack Notes](https://deploy-preview-6726--docs-spectrocloud.netlify.app/release-notes/#pack-notes)
🎫 [DOC-1882](https://spectrocloud.atlassian.net/browse/DOC-1882)
Release branch only.
[DOC-1882]: https://spectrocloud.atlassian.net/browse/DOC-1882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: deprecate BYOS - Agent Mode pack DOC-1882

_partials/_additional-deployment-options.mdx, docs/docs-content/release-notes/release-notes.md
This PR adds a release note covering airgap support for the VM Migration Assistant. It also adds the pack download URL and filename, and adjusts the Additional Deployment Options section for scalability.
💻 [Release Notes](https://deploy-preview-6742--docs-spectrocloud.netlify.app/release-notes/#improvements-3)
💻 [Additional Deployment Options (Self-Hosted)](https://deploy-preview-6742--docs-spectrocloud.netlify.app/downloads/self-hosted-palette/additional-packs/#additional-deployment-options)
💻 [Additional Deployment Options (VerteX)](https://deploy-preview-6742--docs-spectrocloud.netlify.app/downloads/palette-vertex/additional-packs/#additional-deployment-options)
🎫 [PEM-7413](https://spectrocloud.atlassian.net/browse/PEM-7413)
[PEM-7413]: …
=> docs: Airgap support for VM Migration Assistant (pack URL pending)

_partials/self-hosted/_smtp.mdx
This PR removes the anonymous SMTP limitation and provides guidance for configuring it. 
- [Configure SMTP - Palette](https://deploy-preview-6604--docs-spectrocloud.netlify.app/enterprise-version/system-management/smtp/)
- [Configure SMTP - VerteX](https://deploy-preview-6604--docs-spectrocloud.netlify.app/vertex/system-management/smtp/)
🎫 [DOC-1757](https://spectrocloud.atlassian.net/browse/DOC-1757)
Release work.
[DOC-1757]: https://spectrocloud.atlassian.net/browse/DOC-1757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1757: Self-Hosted Anonymous SMTP Configuration

docs/docs-content/release-notes/release-notes.md
This PR adds a release note and breaking change to cover the CAPG upgrade in the 4.6.c Palette release.
🎫 [PCP-4421](https://spectrocloud.atlassian.net/browse/PCP-4421)
[PCP-4421]: https://spectrocloud.atlassian.net/browse/PCP-4421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PCP-4421 - GKE repave release note due to CAPG upgrade

docs/docs-content/troubleshooting/edge/collect-support-bundles.md
This PR divides the troubleshooting scripts commands into 2 each: first one to download the script, the second one to run it.
💻 [Collect Support Bundles for Edge Cluster Troubleshooting](https://deploy-preview-6813--docs-spectrocloud.netlify.app/troubleshooting/edge/collect-support-bundles/)
🎫 [PE-6675](https://spectrocloud.atlassian.net/browse/PE-6675)
[PE-6675]: https://spectrocloud.atlassian.net/browse/PE-6675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Divide troubleshooting scripts commands

.husky/pre-commit, .husky/pre-push, Makefile, package.json
This PR adjusts the Husky commit hook scripts based on various deprecations and updates to how Husky operates post-upgrade.
- Removal of shebang and directory code setting as deprecated post v10.x.y. See [9.1.2](https://github.com/typicode/husky/releases/tag/v9.1.2) release notes.
- Removal of `npx` from package commands as no longer needed from [9.1.1](https://github.com/typicode/husky/releases/tag/v9.1.1) onwards.
- Changed `npx husky-init` to `npx husky` in `Makefile` as running `husky-init` replaces the `pre-commit` hook with a templated version regardless of whether it already exists.
- `"prepare": "husky"` has been added to the `package.json`. I've adjusted the `Makefile` command as `npx husky install` is now deprecated in favour of `npm run prepare` with the command being called …
=> Update Husky scripts for v9.1.7 compatibility

plugins/packs-integrations.js, utils/helpers/affected-table.js, utils/helpers/revision-history.js
This PR changes the cloud type from `aws` to `all` in the case that packs have `cloudType: all`.
The logic of  why it was previously set to `aws` eludes me at this time. 
The old configuration resulted in the pack README for the `harbor` pack to fail fetch with the following error. The setting `cloudType=aws` was the cause of this error.
```
[ERROR] Failed to fetch the details for the following pack v1/packs/harbor/registries/64eaff453040297344bcad5d?cloudType=aws&layer=addon
```
This PR also fixed lint errors detected  in other files. 
💻 [Harbor pack](https://deploy-preview-6884--docs-spectrocloud.netlify.app/integrations/packs/?pack=harbor&version=1.16.2&parent=1.16.x&tab=main)
🎫 [DOC-1888](https://spectrocloud.atlassian.net/browse/DOC-1888)
Everywhere. …
=> docs: adjust cloud type in the case that packs have cloudProvider=all DOC-1888

docs/docs-content/clusters/imported-clusters/cluster-import.md, docs/docs-content/clusters/imported-clusters/imported-clusters.md
- [PEM-7063 Imported cluster limitations (#6376)](https://github.com/spectrocloud/librarium/pull/6376)
=> [version-4-1] PEM-7063 Imported cluster limitations (#6376)

docs/docs-content/clusters/public-cloud/azure/create-azure-cluster.md
This PR adds a warning and guidance to select static IP allocation when configuring a private API Server LB for a private Azure IaaS cluster.
💻 [Create and Manage Azure IaaS Cluster](https://deploy-preview-6940--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/create-azure-cluster/#private-api-server-lb-settings)
🎫 [PCP-4572](https://spectrocloud.atlassian.net/browse/PCP-4572)
[PCP-4572]: https://spectrocloud.atlassian.net/browse/PCP-4572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PCP-4572 Warning for use of dynamic IP allocation for private Azure IaaS cluster LBs

docs/docs-content/troubleshooting/edge/collect-support-bundles.md
This PR updates the information about the embedded script:
1. Adjusts the limitation.
2. Lists default values for the flags.
3. Adds warnings that default flag values might change.
4. Adds a mentioning of remote shell as one of the possible ways to access edge hosts.
💻 [Collect Support Bundles for Edge Cluster Troubleshooting](https://deploy-preview-6956--docs-spectrocloud.netlify.app/troubleshooting/edge/collect-support-bundles/)
🎫 [PE-6675](https://spectrocloud.atlassian.net/browse/PE-6675)
[PE-6675]: https://spectrocloud.atlassian.net/browse/PE-6675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Adjust the embedded script information

Makefile, docs/docs-content/downloads/offline-docs.md, docusaurus.config.js, scripts/start-docker.sh
This PR allows the customization of logos in librarium Docker container.
💻 [Offline Documentation](https://deploy-preview-6966--docs-spectrocloud.netlify.app/downloads/offline-docs/)
🎫 [DOC-1886](https://spectrocloud.atlassian.net/browse/DOC-1886)
🎫 [DOC-1893](https://spectrocloud.atlassian.net/browse/DOC-1893)
We'll only take it back to 4.6 and 4.5, since the page is in the downloads section.
[DOC-1886]: https://spectrocloud.atlassian.net/browse/DOC-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1893]: https://spectrocloud.atlassian.net/browse/DOC-1893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: allow custom logos in Docs DOC-1886 DOC-1893

_partials/self-hosted/_airgap-cluster-profile-packs.mdx, _partials/vertex/_airgap-cluster-profile-packs.mdx, docs/docs-content/release-notes/release-notes.md
This PR updates the 4.6.c packs in the release notes. It also updates the airgap packs and adds the CanvOS version to the release notes.
💻 [Release Notes](https://deploy-preview-6962--docs-spectrocloud.netlify.app/release-notes/)
💻 [Self-hosted additional packs](https://deploy-preview-6962--docs-spectrocloud.netlify.app/downloads/self-hosted-palette/additional-packs/)
💻 [VerteX additional packs](https://deploy-preview-6962--docs-spectrocloud.netlify.app/downloads/palette-vertex/additional-packs/)
🎫 [DOC-1921](https://spectrocloud.atlassian.net/browse/DOC-1921)
[DOC-1921]: https://spectrocloud.atlassian.net/browse/DOC-1921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add additional packs

docs/docs-content/clusters/edge/architecture/architecture.md, docs/docs-content/clusters/edge/architecture/two-node.md, docs/docs-content/clusters/edge/site-deployment/cluster-deployment.md
This PR adds the following information on the new Canonical K8s pack:
1) High availability limitation.
2) Description of node roles.
3) Scaling down a cluster with two nodes limitation.
💻 [Clusters > Edge > Architecture](https://deploy-preview-6963--docs-spectrocloud.netlify.app/clusters/edge/architecture/#limitations)
💻 [Clusters > Edge > Deployment > Create Cluster Definition](https://deploy-preview-6963--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/cluster-deployment#limitations)
🎫 [PE-6846](https://spectrocloud.atlassian.net/browse/PE-6846)
[PE-6846]: https://spectrocloud.atlassian.net/browse/PE-6846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Clarify high availability and node roles in Canonical Kubernetes

docs/docs-content/release-notes/release-notes.md
This PR adds a release note for https://github.com/spectrocloud/librarium/pull/6980. It has been created separately as this portion cannot be backported except to 4.6.x.
💻 [Release Notes](https://deploy-preview-6985--docs-spectrocloud.netlify.app/release-notes/#bug-fixes)
🎫 [DOC-1933](https://spectrocloud.atlassian.net/browse/DOC-1933)
🎫 [DOC-1890](https://spectrocloud.atlassian.net/browse/DOC-1890)
[DOC-1933]: https://spectrocloud.atlassian.net/browse/DOC-1933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-1890]: https://spectrocloud.atlassian.net/browse/DOC-1890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Release note for updated GCP permissions

docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md, docs/docs-content/clusters/edge/site-deployment/deploy-custom-registries/upload-images-to-registry.md
- [docs: remove docker username &amp; password DOC-1941 (#7017)](https://github.com/spectrocloud/librarium/pull/7017)
=> [version-4-3] docs: remove docker username & password DOC-1941 (#7017)

docs/docs-content/enterprise-version/install-palette/install-on-vmware/airgap-install/install.md, docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/airgap-install/install.md, docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md
This PR removes the requirement "Shared Storage between VMware vSphere hosts" from VerteX and Self-hosted EC installation processes.
💻 [Palette VerteX > VMware > Airgap Installation > Install VerteX](https://deploy-preview-7116--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/airgap-install/install/)
💻 [Palette VerteX > VMware > Non-Airgap Install](https://deploy-preview-7116--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/install/)
💻 [Self-Hosted Palette > Installation > VMware > Airgap Installation > Install Palette](https://deploy-preview-7116--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/airgap-install/install/)
💻 [Self-Hosted Palette > Installation > VMware > Non-Airgap …
=> docs: Remove Shared Storage requirement from EC install

docs/docs-content/clusters/edge/site-deployment/virtual-deployment/ipxe-boot.md, docs/docs-content/release-notes/release-notes.md, vale-spellcheck-ignore.txt
This PR fixes spelling errors identified in librarium. Relates to new accept entries in https://github.com/spectrocloud/spectro-vale-pkg/pull/48
💻 [Provision an Edge Host VM Using iPXE Netboot](https://deploy-preview-7146--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/virtual-deployment/ipxe-boot)
No ticket. 
Only in 4.6 as that's when these errors were introduced
=> docs: fix spelling errors

docs/docs-content/clusters/edge/site-deployment/virtual-deployment/ipxe-boot.md, docs/docs-content/release-notes/release-notes.md, vale-spellcheck-ignore.txt
This will backport the following commits from `master` to `version-4-6`:
- [docs: fix spelling errors (#7146)](https://github.com/spectrocloud/librarium/pull/7146)
=> [version-4-6] docs: fix spelling errors (#7146)

docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md
This PR changes the wording across the Apply Site User Data page to highlight that site user data ISO is not bootable.
💻 [Apply Site User Data](https://deploy-preview-7175--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/site-installation/site-user-data/)
🎫 [DOC-1891](https://spectrocloud.atlassian.net/browse/DOC-1891)
[DOC-1891]: https://spectrocloud.atlassian.net/browse/DOC-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Specify that site user data ISO is not bootable

docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md
This PR backports changes from #7175 to version 4.2.
💻 [Apply Site User Data](https://deploy-preview-7189--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/site-installation/site-user-data/)
🎫 [DOC-1891](https://spectrocloud.atlassian.net/browse/DOC-1891)
[DOC-1891]: https://spectrocloud.atlassian.net/browse/DOC-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [version-4-2] docs: Specify that site user data ISO is not bootable (#7175)

docs/docs-content/release-notes/release-notes.md
This PR bumps two bug fixes recently excluded from 4.6.40 to 4.6.41.
💻 [Release Notes](https://deploy-preview-7202--docs-spectrocloud.netlify.app/release-notes/)
🎫 [DOC-1994](https://spectrocloud.atlassian.net/browse/DOC-1994)
[DOC-1994]: https://spectrocloud.atlassian.net/browse/DOC-1994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1994: Adding Removed 4.6.40 Bug Fixes to 4.6.41

docs/docs-content/clusters/public-cloud/gcp/create-gcp-gke-cluster.md, docs/docs-content/clusters/public-cloud/gcp/create-gcp-iaas-cluster.md
This PR creates a manual backport for version-4-2 regarding [PR 7234](https://github.com/spectrocloud/librarium/pull/7234).
- [Create and Manage GCP IaaS Cluster](https://deploy-preview-7253--docs-spectrocloud.netlify.app/clusters/public-cloud/gcp/create-gcp-iaas-cluster/#limitations)
- [Create and Manage GCP GKE Cluster](https://deploy-preview-7253--docs-spectrocloud.netlify.app/clusters/public-cloud/gcp/create-gcp-gke-cluster/#limitations)
🎫 [DOC-1929](https://spectrocloud.atlassian.net/browse/DOC-1929)
[DOC-1929]: https://spectrocloud.atlassian.net/browse/DOC-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [version-4-2] docs: backport/version-4-2/pr-7234

docs/docs-content/clusters/public-cloud/gcp/create-gcp-gke-cluster.md, docs/docs-content/clusters/public-cloud/gcp/create-gcp-iaas-cluster.md
This PR creates a manual backport for version-4-0 regarding [PR 7234](https://github.com/spectrocloud/librarium/pull/7234).
- [Create and Manage GCP IaaS Cluster](https://deploy-preview-7255--docs-spectrocloud.netlify.app/clusters/public-cloud/gcp/create-gcp-iaas-cluster/#limitations)
- [Create and Manage GCP GKE Cluster](https://deploy-preview-7255--docs-spectrocloud.netlify.app/clusters/public-cloud/gcp/create-gcp-gke-cluster/#limitations)
🎫 [DOC-1929](https://spectrocloud.atlassian.net/browse/DOC-1929)
[DOC-1929]: https://spectrocloud.atlassian.net/browse/DOC-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [version-4-0] docs: backport/version-4-0/pr-7234

docs/docs-content/clusters/edge/edgeforge-workflow/edgeforge-workflow.md, docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md
This PR removes all mentions of tech preview associated with cluster definitions and includes minor grammar/formatting fixes. The grammar/formatting fixes are also included in [PR 7267](https://github.com/spectrocloud/librarium/pull/7267) for backporting purposes.
- [EdgeForge Workflow](https://deploy-preview-7266--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/#edge-installer-iso)
- [Build Installer ISO](https://deploy-preview-7266--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso/)
🎫 [DOC-2007](https://spectrocloud.atlassian.net/browse/DOC-2007)
Release work.
[DOC-2007]: https://spectrocloud.atlassian.net/browse/DOC-2007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
=> docs: DOC-2007: Remove Cluster Definitions from Tech Preview

docs/deprecated/clusters/edge/edgeforge-workflow/build-artifacts.md, docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso.md, docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/fips.md, docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/palette-canvos.md, docs/docs-content/glossary-all.md
This PR removes leftover tech preview mentions related to Local UI, which exited tech preview in 4.6.c.
- [Build Installer ISO](https://deploy-preview-7268--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/build-installer-iso/#:~:text=You%20can%20also%20edit)
- [Build FIPS-Compliant Edge Artifacts](https://deploy-preview-7268--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/fips/#:~:text=You%20can%20also%20edit)
- [Build Edge Artifacts](https://deploy-preview-7268--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/#:~:text=You%20can%20also%20edit)
- [Glossary](https://deploy-preview-7268--docs-spectrocloud.netlify.app/glossary-all/#local-ui)
=> docs: Removing Leftover Local UI Tech Preview Mentions

docs/docs-content/clusters/edge/architecture/two-node.md
This PR clarifies kine usage is only in 2-node clusters. 
🎫 [PE-6909](https://spectrocloud.atlassian.net/browse/PE-6909)
[PE-6909]: https://spectrocloud.atlassian.net/browse/PE-6909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: clarify kine usage

docs/docs-content/clusters/edge/networking/kubevip.md
This PR reworks the existing limitations section for kube-vip into a default values section, as day-2 operations are now allowed.
💻 [Publish Cluster Services with Kube-vip](https://deploy-preview-7231--docs-spectrocloud.netlify.app/clusters/edge/networking/kubevip/#default-values)
🎫 [DOC-1989](https://spectrocloud.atlassian.net/browse/DOC-1989)
Release work.
[DOC-1989]: https://spectrocloud.atlassian.net/browse/DOC-1989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1989: Day-2 Support for kube-vip

.github/workflows/pull_request.yaml
This PR fixes the prettier auto-commit failure that occurs when code suggestions are applied directly via the GitHub UI.
Every time someone applies a suggestion using GitHub's UI in a PR, GitHub creates a temporary commit directly on the PR, not on a branch that the GH Actions runner checks out. This causes the checkout GH action to land the runner in a detached HEAD (and with no branch name). The auto-commit action then tries to determine the current branch using HEAD, but fails with a `fatal: invalid reference: <branch-name>` error.
If the PR gets merged into a release branch with an unresolved Prettier issue, all subsequent PRs targeting that release branch will fail their Prettier checks.
Example of PR with the issue:   #7277
- Added `branch: ${{ github.head_ref }}` to the auto-commit …
=> chore: fix auto commit action

docs/docs-content/troubleshooting/edge/collect-support-bundles.md
This PR replaces the "Stylus" term that shouldn't be used in the official documentation with "Palette agent" (the correct term).
💻 [Collect Support Bundles for Edge Cluster Troubleshooting](https://deploy-preview-7430--docs-spectrocloud.netlify.app/troubleshooting/edge/collect-support-bundles/)
🎫 [PE-7140](https://spectrocloud.atlassian.net/browse/PE-7140)
[PE-7140]: https://spectrocloud.atlassian.net/browse/PE-7140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Fix Palette agent terminology

_partials/self-hosted/appliance-framework/_installation-steps-prereqs.mdx
This PR increases the minimum disk requirements for the Palette/VerteX Management Appliance.
🎫 [PEM-8122](https://spectrocloud.atlassian.net/browse/PEM-8122) - Doc changes made off the back of the findings.
Release ticket.
[PEM-8122]: https://spectrocloud.atlassian.net/browse/PEM-8122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PEM-8122 -Increased disk recommendations in prerequisites for Mgmt Appliance

docs/docs-content/enterprise-version/install-palette/palette-management-appliance.md, docs/docs-content/vertex/install-palette-vertex/vertex-management-appliance.md
This PR documents that the Palette/VerteX Management Appliance can only support public registry connections if users use an external registry for their pack bundles.
💻 [Palette Management Appliance](https://deploy-preview-7461--docs-spectrocloud.netlify.app/enterprise-version/install-palette/palette-management-appliance/#limitations)
💻 [VerteX Management Appliance](https://deploy-preview-7461--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/vertex-management-appliance/#limitations)
🎫 [DOC-2049](https://spectrocloud.atlassian.net/browse/DOC-2049)
[DOC-2049]: https://spectrocloud.atlassian.net/browse/DOC-2049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-2049 - Public registry limitation for Management Appliance

package-lock.json, package.json
This PR changes the Stylus dependency version to `0.0.1-security`. NPM removed and re-added the Stylus package due to a [detected security issue](https://github.com/mrmckeb/typescript-plugin-css-modules/issues/287).
However, the owner is reporting that this may be incorrect and is trying to get Stylus reinstated: https://github.com/stylus/stylus/issues/2938
In the interim, we need to get builds operating again, as they fail because NPM cannot find the Stylus version.
🎫 [DOC-2054](https://spectrocloud.atlassian.net/browse/DOC-2054)
[DOC-2054]: https://spectrocloud.atlassian.net/browse/DOC-2054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-2054 - Manual stylus version change due to build failures

docs/docs-content/clusters/edge/architecture/two-node.md, docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images.md
This PR formats important information about two-node clusters creation as warnings so the users are less likely to miss it.
💻 [Build Provider Images](https://deploy-preview-7532--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/build-provider-images/#build-provider-images)
💻[Two-Node Architecture](https://deploy-preview-7532--docs-spectrocloud.netlify.app/clusters/edge/architecture/two-node/#architecture-overview)
🎫 [DOC-2036](https://spectrocloud.atlassian.net/browse/DOC-2036)
🎫 [DOC-2037](https://spectrocloud.atlassian.net/browse/DOC-2037)
[DOC-2036]: https://spectrocloud.atlassian.net/browse/DOC-2036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-2037]: …
=> docs: Add two-node architecture warnings

docs/docs-content/clusters/edge/cluster-management/agent-upgrade-airgap.md, docs/docs-content/clusters/edge/local-ui/cluster-management/export-cluster-definition.md, docs/docs-content/clusters/edge/local-ui/cluster-management/update-cluster.md
This PR adds information about the conditions under which the Palette agent gets upgraded to match the version specified in the content bundle.
💻 [Configure Palette Agent Version](https://deploy-preview-7579--docs-spectrocloud.netlify.app/clusters/edge/cluster-management/agent-upgrade-airgap/)
💻 [Export Cluster Definition](https://deploy-preview-7579--docs-spectrocloud.netlify.app/clusters/edge/local-ui/cluster-management/export-cluster-definition/)
💻 [Update Local Cluster](https://deploy-preview-7579--docs-spectrocloud.netlify.app/clusters/edge/local-ui/cluster-management/update-cluster/)
🎫 [DOC-2072](https://spectrocloud.atlassian.net/browse/DOC-2072)
[DOC-2072]: https://spectrocloud.atlassian.net/browse/DOC-2072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> docs: Add information about agent upgrade

docs/docs-content/registries-and-packs/registries/registries.md
This PR updates the default AWS ECR registry endpoint for VerteX from `http://415789037893.dkr.ecr.us-east-1.amazonaws.com` > `http://415789037893.dkr.ecr.us-west-2.amazonaws.com`.
💻 [Registries](https://deploy-preview-7593--docs-spectrocloud.netlify.app/registries-and-packs/registries/)
🎫 [DOC-1975](https://spectrocloud.atlassian.net/browse/DOC-1975)
[DOC-1975]: https://spectrocloud.atlassian.net/browse/DOC-1975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-1975: Update Default AWS ECR Endpoint for VerteX

docs/docs-content/integrations/cloudanix.mdx, docs/docs-content/integrations/gatekeeper.mdx, docs/docs-content/registries-and-packs/registries/registries.md, docs/docs-content/vm-management/vm-migration-assistant/create-vm-migration-assistant-profile.md, docusaurus.config.js
This PR removes all Spectro Addon Repo references from docs and the packs component.
💻 [Packs List](https://deploy-preview-7581--docs-spectrocloud.netlify.app/integrations/) - Removed Spectro Addon Repo.
💻 [Cloudanix pack](https://deploy-preview-7581--docs-spectrocloud.netlify.app/integrations/packs/?pack=cloudanix) - Updated TF snippet to Palette Community Registry. The pack page doesn't show up bc the pack is still hosted in the Spectro Addon Repo in prod. This will change after the release.
💻 [Gatekeeper pack](https://deploy-preview-7581--docs-spectrocloud.netlify.app/integrations/packs/?pack=gatekeeper) - Updated TF snippet to Palette Public Repo. 
💻 [Create a VM Migration Assistant Profile](https://deploy-preview-7581--docs-spectrocloud.netlify.app/vm-management/vm-migration-assistant …
=> docs: remove Spectro Addon Repo references DOC-2066

docs/docs-content/integrations/harbor-edge-native-config.mdx
This PR removes Technical Preview from the Harbor Edge-Native Config pack additional information. The pack was deprecated in the 4.6.23 version.
💻 [Harbor Edge-Native Config - Additional Details](https://deploy-preview-7635--docs-spectrocloud.netlify.app/integrations/packs/?pack=harbor-edge-native-config&version=1.1.2&parent=1.1.x&tab=custom)
🎫 [DOC-2006](https://spectrocloud.atlassian.net/browse/DOC-2006)
[DOC-2078]: https://spectrocloud.atlassian.net/browse/DOC-2078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-2006]: https://spectrocloud.atlassian.net/browse/DOC-2006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Remove Tech Preview for Harbor Edge-Native Config pack

docs/docs-content/clusters/edge/networking/kubevip.md, docs/docs-content/release-notes/release-notes.md
This PR adds release notes for 4.7.8. 
💻 [Release notes](https://deploy-preview-7657--docs-spectrocloud.netlify.app/release-notes/#august-4-2025---release-478)
💻 [Kube-vip](https://deploy-preview-7657--docs-spectrocloud.netlify.app/clusters/edge/networking/kubevip/)
🎫 [DOC-2080](https://spectrocloud.atlassian.net/browse/DOC-2080)
Only 4.7.
[DOC-2080]: https://spectrocloud.atlassian.net/browse/DOC-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add 4.7.8 release notes DOC-2080

docs/docs-content/release-notes/release-notes.md
This PR adds a missing breaking change from the 4.7.0 release notes.
💻 [Automation](https://deploy-preview-7708--docs-spectrocloud.netlify.app/release-notes/#breaking-changes-automation-4.7.0)
🎫 [DOC-2084](https://spectrocloud.atlassian.net/browse/DOC-2084)
Only 4.7
[DOC-2084]: https://spectrocloud.atlassian.net/browse/DOC-2084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add isTwoNodeCluster to release notes DOC-2084

_partials/self-hosted/management-appliance/_installation-steps-prereqs.mdx
This PR documents how the Management Appliance automatically selects the drive for installation.
💻 [Palette Management Appliance](https://deploy-preview-7725--docs-spectrocloud.netlify.app/enterprise-version/install-palette/palette-management-appliance/#prerequisites) - The same change also applies to the VerteX equivalent.
🎫 [DOC-2068](https://spectrocloud.atlassian.net/browse/DOC-2068)
[DOC-2068]: https://spectrocloud.atlassian.net/browse/DOC-2068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-2068 - Management Appliance default drive selection behaviour

_partials/self-hosted/_smtp.mdx, docs/docs-content/enterprise-version/system-management/smtp.md, docs/docs-content/vertex/system-management/smtp.md
This PR specifies that **Insecure Skip TLS Verify** cannot be disabled for SMTP in Palette VerteX. At this time, you are able to mark the checkbox, but it is not functional. This field will be disabled in VerteX in the future.
- [Configure SMTP - Palette](https://deploy-preview-7721--docs-spectrocloud.netlify.app/enterprise-version/system-management/smtp/)
- [Configure SMTP - VerteX](https://deploy-preview-7721--docs-spectrocloud.netlify.app/vertex/system-management/smtp/)
🎫 [DOC-2086](https://spectrocloud.atlassian.net/browse/DOC-2086)
[DOC-2086]: https://spectrocloud.atlassian.net/browse/DOC-2086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-2086: Insecure Skip TLS Verify Not Applicable to VerteX

.github/workflows/aloglia_crawler.yaml, .github/workflows/pull_request.yaml, .github/workflows/release-branch-pr.yaml, .github/workflows/release-preview.yaml, .github/workflows/visual-comparison.yaml, .husky/pre-commit, README.md
This PR updates the names of release branches.
_No user facing changes._
🎫 [DOC-2085](https://spectrocloud.atlassian.net/browse/DOC-2085)
Backport everywhere. 
[DOC-2085]: https://spectrocloud.atlassian.net/browse/DOC-2085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: update release branch naming DOC-2085

docs/docs-content/automation/crossplane/crossplane.md, docs/docs-content/devx/services/service-listings/redis-db.md
This PR fixes some broken URLs found with the Monday checks.
Note that https://www.intel.com/content/www/us/en/learn/what-is-a-trusted-platform-module.html was also registered as broken, but it was likely a transient error, as the URL works correctly.
=> docs: Fix broken URLs found on 11th August 2025

_partials/self-hosted/management-appliance/_installation-steps-prereqs.mdx
This PR corrects the default drive behaviour explanation for the Management Appliance.
💻 [Palette Management Appliance](https://deploy-preview-7801--docs-spectrocloud.netlify.app/enterprise-version/install-palette/palette-management-appliance/#prerequisites) - Same changes apply to VerteX Management Appliance.
=> docs: fix default drive selection for Management Appliance

docs/docs-content/integrations/kubernetes-eks.mdx
This PR provides more elaborate and specific examples for node customization for EKS nodes.
This is an addition to the work in https://github.com/spectrocloud/librarium/pull/7692.
💻 [Configure Amazon Linux 2023 AMI Nodes](https://deploy-preview-7821--docs-spectrocloud.netlify.app/integrations/packs/?pack=kubernetes-eks&tab=custom#configure-amazon-linux-2023-ami-nodes)
🎫 [PCP-4774](https://spectrocloud.atlassian.net/browse/PCP-4774) (see [comment](https://spectrocloud.atlassian.net/browse/PCP-4774?focusedCommentId=159259))
Release ticket.
[PCP-4774]: https://spectrocloud.atlassian.net/browse/PCP-4774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PCP-4774 - Additional examples for EKS node customization

docs/docs-content/security-bulletins/security-advisories/security-advisories.md
This PR adds a Security Advisory regarding self-deleting nodes with `OwnerReference`.
💻 [Security Advisory](https://deploy-preview-7830--docs-spectrocloud.netlify.app/security-bulletins/security-advisories/)
=> docs: Security Advisory 3: Self-Deleting Nodes with OwnerReference

docs/docs-content/clusters/public-cloud/aws/architecture.md, docs/docs-content/release-notes/release-notes.md
This PR documents Karpenter support limitations for EKS.
💻 [AWS Architecture](https://deploy-preview-7823--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/architecture/#karpenter-support)
💻 [Release Notes](https://deploy-preview-7823--docs-spectrocloud.netlify.app/release-notes/#improvements)
🎫 [DOC-2098](https://spectrocloud.atlassian.net/browse/DOC-2098)
Release ticket.
[DOC-2098]: https://spectrocloud.atlassian.net/browse/DOC-2098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-2098 - Karpenter Support Limitations

docs/docs-content/troubleshooting/enterprise-install.md, docs/docs-content/vertex/upgrade/vertex-management-appliance.md
This PR documents how to fix stalled Linstor satellite pods during a VerteX Management Appliance upgrade.
It also improves an admonition for an existing upgrade issue.
💻 [Troubleshooting - Enterprise Install](https://deploy-preview-7910--docs-spectrocloud.netlify.app/troubleshooting/enterprise-install/#scenario---vertex-management-appliance-fails-to-upgrade-due-to-stuck-linstor-satellite-pods)
💻 [Upgrade VerteX Management Appliance](https://deploy-preview-7910--docs-spectrocloud.netlify.app/vertex/upgrade/vertex-management-appliance/)
🎫 [DOC-2137](https://spectrocloud.atlassian.net/browse/DOC-2137)
[DOC-2137]: https://spectrocloud.atlassian.net/browse/DOC-2137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-2137 - Troubleshooting steps for stalled VerteX Management Appliance upgrade due to stuck Linstor satellite pods

.github/workflows/url-checks.yaml, Makefile, linkinator/linkinator-ci.config.json, linkinator/linkinator-rate-limit-ci.config.json, linkinator/linkinator-rate-limit.config.json, linkinator/linkinator.config.json, scripts/url-checker-developer-portals.sh, scripts/url-checker.sh
- [docs: add developer portals to status checking (#7935)](https://github.com/spectrocloud/librarium/pull/7935)
=> [version-4-3] docs: add developer portals to status checking (#7935)

.github/workflows/url-checks.yaml, Makefile, linkinator/linkinator-ci.config.json, linkinator/linkinator-rate-limit-ci.config.json, linkinator/linkinator-rate-limit.config.json, linkinator/linkinator.config.json, scripts/url-checker-developer-portals.sh, scripts/url-checker.sh
- [docs: add developer portals to status checking (#7935)](https://github.com/spectrocloud/librarium/pull/7935)
=> [version-4-2] docs: add developer portals to status checking (#7935)

_partials/self-hosted/management-appliance/_upgrade-palette-enablement.mdx, _partials/self-hosted/management-appliance/_upload-packs-enablement.mdx, _partials/self-hosted/management-appliance/_upload-third-party-packs-enablement.mdx
This PR adds regular TLS cert examples for the Management Appliance when uploading packs using the Palette CLI.
💻 [Palette/VerteX Management Appliance - Installation](https://deploy-preview-7987--docs-spectrocloud.netlify.app/enterprise-version/install-palette/palette-management-appliance/)
💻 [Palette/VerteX Management Appliance - Upgrade](https://deploy-preview-7987--docs-spectrocloud.netlify.app/enterprise-version/upgrade/palette-management-appliance/)
=> docs: Add regular TLS certificate example for Management Appliance

docs/docs-content/automation/palette-cli/commands/ec.md, docs/docs-content/automation/palette-cli/commands/pcg.md, docs/docs-content/automation/palette-cli/install-palette-cli.md, docs/docs-content/release-notes/release-notes.md
This PR adds a breaking change re: Palette CLI authentication to the release notes and a limitation to the respective Palette CLI pages.
- [Release Notes](https://deploy-preview-8076--docs-spectrocloud.netlify.app/release-notes/#breaking-changes-4.7.b)
- [Palette CLI - Install](https://deploy-preview-8076--docs-spectrocloud.netlify.app/automation/palette-cli/install-palette-cli/#limitations)
- [Palette CLI - EC](https://deploy-preview-8076--docs-spectrocloud.netlify.app/automation/palette-cli/commands/ec/#limitations)
- [Palette CLI - PCG](https://deploy-preview-8076--docs-spectrocloud.netlify.app/automation/palette-cli/commands/pcg/#limitations)
🎫 [PLT-1948](https://spectrocloud.atlassian.net/browse/PLT-1948)
Release work.
[PLT-1948]: …
=> docs: PLT-1948: Palette CLI Breaking Change

_partials/self-hosted/management-appliance/_upgrade-palette-enablement.mdx
This PR  adds a warning about the Zot password to the Palette management appliance upgrade.
💻 [Upgrade](https://deploy-preview-8075--docs-spectrocloud.netlify.app/enterprise-version/upgrade/palette-management-appliance/#upgrade-palette)
💻 [Vertex Upgrade](https://deploy-preview-8075--docs-spectrocloud.netlify.app/vertex/upgrade/vertex-management-appliance/#upgrade-palette-vertex)
🎫 [DOC-2213](https://spectrocloud.atlassian.net/browse/DOC-2213)
[DOC-2213]: https://spectrocloud.atlassian.net/browse/DOC-2213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add Zot password warning DOC-2213

docs/docs-content/release-notes/release-notes.md
This PR adds Cilium agent mode Edge configuration introduced in #8129 to release notes.
💻 [Release notes](https://deploy-preview-8130--docs-spectrocloud.netlify.app/release-notes/#packs)
🎫 [PE-7417](https://spectrocloud.atlassian.net/browse/PE-7417)
[PE-7417]: https://spectrocloud.atlassian.net/browse/PE-7417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: Add Cilium agent mode Edge configuration to release notes

docs/docs-content/vertex/install-palette-vertex/vertex-management-appliance.md
This PR updates the Ubuntu version used in VerteX Management Appliance from 20.04 > 22.04. The [Palette Management Appliance](https://docs.spectrocloud.com/enterprise-version/install-palette/palette-management-appliance/) page already references 22.04.
💻 [VerteX Management Appliance](https://deploy-preview-8226--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/vertex-management-appliance/)
🎫 [DOC-2267](https://spectrocloud.atlassian.net/browse/DOC-2267)
[DOC-2267]: https://spectrocloud.atlassian.net/browse/DOC-2267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-2267: Update Vertex Management Appliance Ubuntu Version

docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap.md, docs/docs-content/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap.md
This PR clarifies where the directory `rpmrepo` originates by providing additional output and explaining the flags in the Docker commands. It also includes small QOL enhancements to reduce user error. 
- [PXK and RHEL](https://deploy-preview-8251--docs-spectrocloud.netlify.app/byoos/capi-image-builder/build-image-vmware/airgap-build/rhel-capi-airgap/)
- [PXK and Rocky](https://deploy-preview-8251--docs-spectrocloud.netlify.app/byoos/capi-image-builder/build-image-vmware/airgap-build/rocky-capi-airgap/)
🎫 [DOC-2264](https://spectrocloud.atlassian.net/browse/DOC-2264)
[DOC-2264]: https://spectrocloud.atlassian.net/browse/DOC-2264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DOC-2264: CAPI Airgap rpmrepo Clarification

docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle.md, docs/docs-content/deployment-modes/agent-mode/architecture.md, docs/docs-content/release-notes/release-notes.md
This PR updates the Palette CLI, Palette host agent, and Palette cluster agent versions with respect to the 4.7.20 release. I suspect when the 4.7.b placeholder was replaced, 4.7.20 was used across the board when it should not have been. 
- [Release Notes](https://deploy-preview-8266--docs-spectrocloud.netlify.app/release-notes/#release-notes-4.7.b)
- [Build Content Bundle](https://deploy-preview-8266--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos/build-content-bundle/#limitations)
- [Agent Mode Architecture](https://deploy-preview-8266--docs-spectrocloud.netlify.app/deployment-modes/agent-mode/architecture/#limitations)
🎫 [DOC-2275](https://spectrocloud.atlassian.net/browse/DOC-2275)
[DOC-2275]: …
=> docs: DOC-2275: Updating Palette CLI and Agent Versions

Makefile, README.md, scripts/release/generate-component-updates.sh, scripts/release/generate-release-notes.sh, scripts/release/templates/component-updates-cross-link.md, scripts/release/templates/component-updates-heading.md, scripts/release/templates/component-updates.md, scripts/release/templates/release-notes.md
This will backport the following commits from `master` to `version-4-6`:
- [docs: add component update generation DOC-2277 (#8289)](https://github.com/spectrocloud/librarium/pull/8289)
=> [version-4-3] docs: add component update generation DOC-2277 (#8289)

docs/docs-content/release-notes/release-notes.md, docs/docs-content/tenant-settings/password-policy.md
This PR creates a new password policy page and documents the maximum password length enforcement. 
💻 [Release Notes](https://deploy-preview-8334--docs-spectrocloud.netlify.app/release-notes/)
💻 [Password Policies](https://deploy-preview-8334--docs-spectrocloud.netlify.app/tenant-settings/password-policy/)
🎫 [PEM-8603](https://spectrocloud.atlassian.net/browse/PEM-8603)
No, release ticket.
[PEM-8603]: https://spectrocloud.atlassian.net/browse/PEM-8603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: password policy maximum character enforcement PEM-8603
