prow/functions.sh
prow/postsubmit.sh
prow/presubmit.sh

Till prow has S3 sync supported , comment out  s3 sync part

Comment out s3 sync for now

---

.npmrc
prow/functions.sh

Increase memory to 8GB for compilation

Run with 8G mem

---

packages/docs/content/06-integrations/dex.md
packages/docs/content/06-integrations/kibana.md
packages/docs/content/06-integrations/kubernetes-dashboard.md
packages/docs/content/06-integrations/kubevious.md
packages/docs/content/06-integrations/permission-manager.md
packages/docs/content/06-integrations/prometheus-operator.md
packages/docs/content/06-integrations/vault.md

PR contains doc changes for configuring Ingress on various integrations

Ingress support for Packs

---

packages/docs/content/06-integrations/externaldns.md

Example setting up ExternalDNS & troubleshooting

ExternalDNS example

---

packages/docs/content/06-integrations/prometheus-operator.md

Added Instructions on how to use custom secrets for alertmanager

Use custom secrets for alertmanager

---

packages/docs/content/02-getting-started.md

Fix permission

---

CHANGES

Docs on splunk agent
/test librarium_release_build

Docs on splunk agent

---

CHANGES

Release 1.5.0

---

CHANGES
prow/OWNERS

Tenant api chg

---

README.md
packages/shared/src/layouts/Default/search/input.js
packages/shared/src/mdx/components/codeBlock.js

Example
` ```yaml coloredLines=1-3|red,5-6|#fe1345`

Line highlighter

---

packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md

removed default admin password to user provided and 5 year cert duration instead of 1 year.

Added detail for secure passwords and cert

---

packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md

spectre -> spectro fix

---

CHANGES

Release 1.6.0 changes

---

packages/docs/content/02-getting-started.md

Correcting typos

---

packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md

Changes 1.7.0

---

packages/docs/content/12-enterprise-version.md

This probably needs a review for re-write to use Self-hosted or Self-managed more so than on-premises to align with other messaging but correcting premises for now.  Left Nav also needs to be updated

Change to On-Premises for correct usage

---

packages/docs/content/01-introduction/2-concept-overviews.md
packages/docs/content/03-cluster-profiles/1-task-define-profile.md
packages/docs/content/03-cluster-profiles/2-task-update-profile.md

Concept overviews, Profile changes

---

CHANGES

Release notes 1.8.0

---

packages/docs/content/06-integrations/00-centos.md
packages/docs/content/06-integrations/00-ubuntu.md

Pack Integrations added with Operating System Packs 
1. Ubuntu
2. CentOS

operating-system

---

packages/docs/content/04-clusters/1-new-clusters.md

new-cluster-page-changes

---

packages/docs/content/04-clusters/1-new-clusters.md

Sts 4 policies

---

packages/docs/content/04-clusters/1-new-clusters.md
packages/docs/content/04-clusters/4-cluster-features.md
packages/docs/content/09-registries-and-packs.md
packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
packages/docs/content/13-release-notes.md

2. EKS 
3. CLI and Registry versions
4. Cluster Features
5. AWS Policies -Names

1.9.0 Document Updates

---

packages/docs/content/04-clusters/1-new-clusters.md
packages/docs/content/13-release-notes.md

1.9.0-document-updates

---

packages/docs/content/06-integrations/00-kubernetes.md

K8S new packs updated to integrations:
1.20.5
1.20.6
1.19.10
1.19.9
1.18.17
1.18.18

k8s-pack-integrations-update1.9

---

packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md

Sub Page added to on-Premises Installation 
System Requirements
1. Quick Start Version
2. Enterprise Version

On-Prem System Requirements

---

packages/docs/content/09-registries-and-packs/3-add-custom-packs.md

Change addon type string

---

packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md

Change structure, flow etc

---

packages/docs/content/12-enterprise-version/00-on-prem-system-requirements.md

Requirement Document Updates

---

packages/docs/content/04-clusters/1-new-clusters.md
packages/docs/content/04-clusters/4-cluster-features.md
packages/docs/content/13-release-notes.md

2. Compliance Scan
3. Back up and Restore
4. EKS- Fargate Profiles
5. EKS - MIN-MAX Instance size
6. Controller Policy AWS Updated
7. Controller Policy EKS Updated

1.10 Major Doc Updates

---

packages/docs/content/04-clusters/4-cluster-features.md

OSPatchingPolicy 4-cluster-features.md

---

packages/docs/content/04-clusters/1-new-clusters.md
packages/docs/content/04-clusters/4-cluster-features.md

1.10-Doc-Updates

---

CHANGES

Push release notes 1.10 to Production

Release Notes 1.10

---

packages/docs/content/04-clusters/4-cluster-features.md
packages/docs/content/13-release-notes.md

1.10-doc-updates-05

---

packages/docs/content/13-release-notes.md

1.10-Minor changes

---

packages/docs/content/04-clusters/1-new-clusters.md
packages/docs/content/04-clusters/4-cluster-features.md
packages/docs/content/14-troubleshooting/01-orchestration-spectrocloud.md

Doc spell checks 

---

packages/docs/content/04-clusters/4-cluster-features.md

1.10-Spell Checks

---

packages/docs/content/04-clusters.md
packages/docs/content/14-troubleshooting.md

1. Procedure explanation revisited
2. link added to troubleshooting

cluster-logs-updates

---

packages/docs/content/13-release-notes.md

Release Notes Updated Spectro Cloud 1.11

Release-note-1.11-new

---

packages/docs/content/06-integrations/01-pack-constraints.md
packages/docs/content/09-registries-and-packs.md
packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
packages/docs/content/13-release-notes.md

updates on Spectro Packs and CLI

Release 1.11 packs and cli updates

---

packages/docs/content/06-integrations/01-pack-constraints.md

schema-constraint-readonly

---

packages/docs/content/04-clusters/1-new-clusters.md

OpenStack-Updates

---

packages/docs/content/04-clusters/1-new-clusters.md

correction in Azure Cluster creation

correction in Azure Cluster creation

---

packages/docs/content/01-introduction/3 - Architecture Overview.md

added architecture overview in Introduction section.

Create 3 - Architecture Overview.md

---

packages/docs/content/09-registries-and-packs.md
packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md

Spectro CLI updates 1.12.0
Spectro pack updates 1.12.0

Spectro release 1.12 CLI/Pack Updates

---

packages/docs/content/04-clusters/1-new-clusters.md
packages/docs/content/08-user-management/1-saml-sso.md

OIDC based SSO

---

packages/docs/content/04-clusters/1-new-clusters.md
packages/docs/content/04-clusters/2-brownfield-clusters.md

Generic Cluster Import
Bet-2741 resolved

Generic Cluster Import

---

packages/docs/content/04-clusters/1-new-clusters.md

Open Stack Updates

---

packages/docs/content/04-clusters/1-new-clusters.md
packages/docs/content/08-user-management/1-saml-sso.md

Updates as per review comments

1.12-updates-aks-oidc

---

packages/docs/content/08-user-management/1-saml-sso.md

Identity Provider Info 

---

packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md

-htpasswd -Bbn spectro {enter your secure password choice} > /root/auth/htpasswd-basic
+htpasswd -Bbn spectro {enter your secure password choice} >> /root/auth/htpasswd-basic
to openssl
-addext "subjectAltName = DNS:foobar.mydomain.svc"

adding-custom-registry updated

---

CHANGES

Merge changes related to 1.11 and 1.12 to production

Release 1.12 Changes

---

packages/docs/content/00-release-notes.md
packages/docs/content/04-clusters/1-new-clusters.md
packages/docs/content/09-registries-and-packs.md
packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md

2. MaaS
3. Packs and CLI updates

1.13.0 Release Docs

---

packages/docs/content/12-enterprise-version/01-deploying-the-platform-installer.md

spectrocloud.atlassian.net/browse/DOC-77

bug-doc-77

---

packages/docs/content/09-registries-and-packs/5-pack-constraints.md
packages/docs/content/16-glossary-all.md

remove: ["registry.ingress.host"]
in preset.yaml file

pack preset update

---

packages/docs/content/04-clusters/1-new-clusters/06-maas.md
packages/docs/content/12-enterprise-version/06-monitoring.md

Maas gateway 1.0.9

---

packages/docs/content/04-clusters/3-cluster-management/6-cloud-cost.md
packages/docs/content/12-enterprise-version/05-air-gap-repo.md

Air gap repo

---

packages/docs/content/04-clusters/1-new-clusters/08-vmware.md

Role-based privilege updated for VMware cluster creation.
1. Spectro role privilages
2. Root-level role privileges

vmware privilages update

---

packages/docs/content/09-registries-and-packs/6-helm-charts.md

Deployment and usage of Helm registry

Helm Registry

---

CHANGES

Push the latest changes to the Stage env

Latest changes to stage

---

packages/docs/content/12-enterprise-version/05-air-gap-repo.md

air-gapped-spell-check

---

packages/docs/content/05-workspace.md
packages/docs/content/10-audit-logs.md

1. workspace icon added
2. JSON alignment audit logs

workspace-icon

---

packages/docs/content/04-clusters/3-cluster-management/6-cloud-cost.md

formula-update-cloud-cost

---

packages/docs/content/04-clusters/1-new-clusters/08-vmware.md

Zone Tagging added to New Clusters-vSphere Cluster as a prerequisite

vsphere-zone-tagging

---

packages/docs/content/00-release-notes.md
packages/docs/content/06-integrations/00-kubernetes.md

Date of release 1st November
New K8S Packs Updates

release-notes-2.0.0

---

packages/docs/content/04-clusters/1-new-clusters/02-aks.md

https://spectrocloud.atlassian.net/browse/BET-2722

Bet-2722 : AAD Configuration for AKS

---

README.md

Update to correct git command that creates a branch

---

CHANGES

Release 2.0.0

---

packages/docs/content/04-clusters/3-cluster-management/3-compliance-scan.md

small-update-01

---

packages/docs/content/00-release-notes.md
packages/docs/content/08-user-management.md
packages/docs/content/09-registries-and-packs.md
packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md
packages/docs/content/09-registries-and-packs/5-pack-constraints.md
packages/docs/content/09-registries-and-packs/6-oci-registry.md

**2.1.0 Release docs**
2. Multi-Organization Support (User Management)
3. Multi-region support (OCI Registry)
4. Packs & CLI Tool update

2.1.0-release-docs

---

CHANGES

Release 2.1 changes to Production

Release 2.1.0 to Prod

---

packages/docs/content/06-integrations/00-kubernetes.md

2.1 Kubernetes version
1.20.12

2.1-k8s-1.20.12

---

packages/docs/content/03-cluster-profiles/2-task-update-profile.md
packages/docs/content/04-clusters/3-cluster-management/1-cluster-updates.md

Kubernetes version change recommendations
1. Upgrade
2. Downgrade

Bet-81 and Bet-82

---

packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
packages/docs/content/09-registries-and-packs/5-pack-constraints.md

small-update

---

packages/docs/content/04-clusters/1-new-clusters/04-eks.md
packages/docs/content/09-registries-and-packs/6-oci-registry.md

https://spectrocloud.atlassian.net/browse/BET-2933
AWS Instance Type and POD Capacity

bet-2933-doc-update

---

packages/docs/content/04-clusters/1-new-clusters/06-maas.md
packages/docs/content/04-clusters/1-new-clusters/07-openstack.md

24-dec-updates

---

packages/docs/content/04-clusters/3-cluster-management/5-backup-restore.md

Storage class compatibility for cluster backup - restore for EKS and other clouds
https://spectrocloud.atlassian.net/browse/DOC-74

bet-doc-74

---

CHANGES

Push release 2.2.0 changes to production

Release 2.2.0

---

packages/docs/content/17-glossary-all.md

A-Team is a group of users.
A Team is a group of users.

tiny-change

---

packages/docs/content/04-clusters/1-new-clusters/05-edge.md

-                         --user-no-proxy 172.0.0.1 
+                         --custom-cacert /tmp/ca.crt

pcge-command-argument-update

---

CHANGES

Push Edge changes to Production

Edge changes to production

---

packages/docs/content/04-clusters/1-new-clusters/05-edge.md
packages/docs/content/06-integrations/00-metallb.md

minor-updates-edge-lb

---

packages/docs/content/04-clusters/1-new-clusters.md
packages/docs/content/06-integrations/00-frp.md

Spectro Proxy command line update:
- "cluster-{{ .spectro.system.cluster.uid }}.{{ .spectro.system.reverseproxy.server }}"
+ - "cluster-{{ .spectro.system.cluster.uid }}.{{ .spectro.system.reverseproxy.server }}"

Spectro Proxy 

---

packages/docs/content/06-integrations/00-metallb.md

metal-lb-pack-update

---

packages/docs/content/00-release-notes.md
packages/docs/content/09-registries-and-packs/6-helm-charts.md

Hotfix 2.2.26

---

packages/docs/content/00-release-notes.md
packages/docs/content/09-registries-and-packs/6-helm-charts.md

helm-page-revisited

---

packages/docs/content/15-compliance.md
packages/docs/content/16-spectro-downloads.md

downloads-updated

---

packages/docs/content/04-clusters/1-new-clusters/05-edge.md
packages/docs/content/06-integrations/00-rook-ceph.md

https://spectrocloud.atlassian.net/browse/DOC-89

Instructions for picking the correct infra. 

---

packages/docs/content/04-clusters/1-new-clusters/09-vmware.md

"NTP configured on all Hosts." was repeated removed the repetition.

minor-correction

---

packages/api/content/1-introduction.md
packages/api/content/2-samples.md

API -DOC introduction page changed from Spectro Cloud to Palette (Minor Change)
https://spectrocloud.atlassian.net/browse/DOC-94

sc-palette-api-doc

---

packages/api/content/1-introduction.md

API Key authentication updated to API Docs

api-key-api-doc-updates

---

packages/docs/content/06-integrations/00-nginx.md
packages/docs/content/06-integrations/00-prometheus-operator.md
packages/docs/content/09-registries-and-packs.md
packages/docs/content/09-registries-and-packs/1-adding-a-custom-registry.md
packages/docs/content/09-registries-and-packs/2-spectro-cli-reference.md

**Release 2.3**
* Packs and CLI updates
*Version Updates Pack Integrations 
* nginx-1.0.4
* prometheus-operator-19.2.3
* prometheus-operator-30.0.3
* prometheus-operator-30.2.0

rel-2.3-packs-cli-updates

---

packages/docs/content/03-cluster-profiles/1-task-define-profile.md

** 2.3 Release Features**
** Multiple layers using the same pack **
Content added as part of cluster profile creationg
https://spectrocloud.atlassian.net/browse/DOC-103

2.3-rel-multiplelayers-samepack

---

packages/docs/content/04-clusters/3-cluster-management/5-backup-restore.md

**2.3 Release Feature**
**Workspace Operator**
Workspace Operator and Workspace Backup added to :
https://docs.spectrocloud.com/clusters/cluster-management/backup-restore/

2.3-rel-workspace-operator

---

packages/docs/content/04-clusters/3-cluster-management/9-cluster-rbac.md

Cluster Level RBAC and NS support 
* Added RBAC with NS support as part of "Cluster Management module"

2.3-release-rbac-ns

---

packages/docs/content/04-clusters/1-new-clusters/01-aws.md
packages/docs/content/04-clusters/3-cluster-management/8-taints.md

**2.3 Release Feature:**
**Node Pool Taints**
**Node Pool Labels**
* Feature added to the "manage Cluster" module as a new page.
* Feature added to AWS Cluster creation ( After review can be added to other clouds as well)

2.3-release-taints

---

packages/docs/content/04-clusters.md

**Release Feature 2.3**
**Support Cluster for Tenants**
Feature added as part of Cluster Page, after https://docs.spectrocloud.com/clusters/#day-2management

rel-2.3-support-cluster-for-tenants

---

packages/docs/content/00-release-notes.md
packages/docs/content/14-troubleshooting.md

**2.3 Release**
Release notes updated with source content location links.

links-for-rel-notes

---

packages/api/content/v1/02-apikey.md
packages/api/content/v1/12-edgehosts.md
packages/api/content/v1/api.json

Updated the api.json with 2.3 spec

2.3 api docs

---

packages/api/content/1-introduction.md

**2.3 Release**
API Key content link to API Doc

api-key-link-to-API_Doc

---

CHANGES

2.3 Release

---

packages/docs/content/04-clusters/3-cluster-management.md
packages/docs/content/04-clusters/3-cluster-management/0-reconfigure.md
packages/docs/content/04-clusters/3-cluster-management/1-cluster-updates.md
packages/docs/content/04-clusters/3-cluster-management/2-health-alerts.md
packages/docs/content/04-clusters/3-cluster-management/3-compliance-scan.md
packages/docs/content/04-clusters/3-cluster-management/4-os-patching.md
packages/docs/content/04-clusters/3-cluster-management/5-backup-restore.md
packages/docs/content/04-clusters/3-cluster-management/6-cloud-cost.md
packages/docs/content/04-clusters/3-cluster-management/7-workloads.md

Links to Cluster Management Features Updated

cluster-managemt-updates

---

packages/docs/content/04-clusters/1-new-clusters/02-eks.md

update to worker node pool description

---

packages/docs/content/06-integrations/00-certmanager.md
packages/docs/content/06-integrations/00-dex.md
packages/docs/content/06-integrations/00-kubernetes-dashboard.md

Version Updates on a few packs.

pack-version-updates

---

packages/docs/content/04-clusters/1-new-clusters/05-edge.md

edge-updaes

---

packages/docs/content/04-clusters/1-new-clusters/09-vmware.md

minor-update-zone-tagging

---

packages/docs/content/00-release-notes.md

Rolling updates added to release notes

rel-note-2.3-updated

---

packages/api/content/2-samples.md

In sample workflow:
-* Kubernetes: select version 1.17.X.
+    * Kubernetes: select version 1.19.X.
-* Update the cluster profile to bring the Kubernetes version to 1.18.X.
+* Update the cluster profile to bring the Kubernetes version to 1.21.X.

api-k8s-version-update

---

packages/api/content/2-samples.md

sample flow added for API Key Authentication

api-key-sampleflow

---

content/docs/16-spectro-downloads.md

minor-update

---

content/docs/13-terraform.md
content/docs/13-terraform/01-resources.md
content/docs/13-terraform/02-datasources.md

Spectro Cloud Terraform Provider section added to the documentation.
* Terraform provider details
* Resources List
* Data sources List
https://spectrocloud.atlassian.net/browse/DOC-90

terraform-provider

---

content/docs/13-terraform.md

minor - update on Terraform page

minor-changes

---

content/docs/06-integrations/00-kubernetes.md
content/docs/13-terraform.md

* Minor changes to Terraform page
* K8S Versions added : **1.23.4 1.22.11**

Tf page revisit

---

content/docs/16-complexity.md

**Palette component complexity matrix:**
The rough draft needs to be reviewed thoroughly.

palette-component-complexity-matrix

---

content/docs/06-integrations/00-opa-gatekeeper.md

New integration added - OpenPolicyAgent

opa-gatekeeper

---

content/docs/16-complexity.md

pcm-update

---

content/docs/04-clusters/1-new-clusters/01-aws.md
content/docs/04-clusters/1-new-clusters/02-eks.md
content/docs/04-clusters/1-new-clusters/03-azure.md
content/docs/04-clusters/1-new-clusters/04-aks.md
content/docs/04-clusters/1-new-clusters/05-edge.md
content/docs/04-clusters/1-new-clusters/06-gcp.md
content/docs/04-clusters/1-new-clusters/07-maas.md
content/docs/04-clusters/1-new-clusters/08-openstack.md
content/docs/04-clusters/1-new-clusters/09-vmware.md
content/docs/04-clusters/1-new-clusters/10-vmware.md

**2.5 Release Feature:**
Cluster Force Delete
added to all the clouds.
https://spectrocloud.atlassian.net/browse/DOC-133

rel-2.5-cluster-force-delete

---

content/docs/09-registries-and-packs.md
content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
content/docs/09-registries-and-packs/2-spectro-cli-reference.md

**Release 2.5**
CLI and Registries Update

cli-registries-update-2.5

---

content/docs/00-release-notes.md

**Palette Release 2.5**
Release Notes

release-notes-2.5

---

content/docs/04-clusters/3-cluster-management/05-backup-restore.md

**Release 2.5** 
GCP Backup Location

rel-2.5-gcp-bkup

---

content/docs/00-release-notes.md
content/docs/04-clusters/1-new-clusters.md
content/docs/06-integrations/00-kubernetes.md
content/docs/06-integrations/00-ubuntu.md
content/docs/16-component.md

Ubuntu 20.4.x updates
release notes updates
K8s Pack Updates:
* 1.23.4
* 1.22.7
* 1.21.10

2.5-updates

---

content/docs/13-terraform.md

Terraform Provider - Module Compatibility Matrix

terraform-provider-module-compatibility

---

content/docs/00-release-notes.md
content/docs/06-integrations/00-ubuntu.md

Ubuntu 18.4.x to Kubernetes Dependency Matrix

Ubuntu updates

---

CHANGES

Release 2.5.0

---

content/docs/00-release-notes.md
content/docs/04-clusters/1-new-clusters/10-tke.md

Infobox for TKE cluster profile creation (OS Layer).
Taints removed from TKE (2.6 feature)

Tke cluster profile

---

content/docs/04-clusters/1-new-clusters/01-aws.md
content/docs/04-clusters/1-new-clusters/02-eks.md
content/docs/04-clusters/1-new-clusters/06-gcp.md
content/docs/04-clusters/1-new-clusters/08-openstack.md
content/docs/04-clusters/1-new-clusters/10-tke.md
content/docs/04-clusters/1-new-clusters/11-vmware.md

Last update date added for:
-  aws
- eks
-  gcp
-  openstack
-  tke
-  vmware

dates-added-to-clous-permissions

---

content/docs/06-integrations/00-prometheus-operator.md

How to scrape metrics for controller-manager, kube-schedule & etcd
- added to Prometheus Integration

prometheus-scrape-matrics

---

content/docs/03-cluster-profiles/1-task-define-profile.md

**2.6 Release Feature**
Cluster Profile Versioning
* Added to the 'Creating Cluster Profiles' page both UI step and overview

rel-2.6-cluster-profile-versioning

---

content/docs/16-component.md

**2.6 Release Features**
Component metrics update

component-matrix-2.6

---

content/docs/09-registries-and-packs.md
content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
content/docs/09-registries-and-packs/2-spectro-cli-reference.md
content/docs/09-registries-and-packs/3-add-custom-packs.md
content/docs/09-registries-and-packs/4-adding-add-on-packs.md
content/docs/09-registries-and-packs/6-helm-charts.md

**2.6 Release**
CLI and Registries update

2.6-release-cli-and-registries

---

content/docs/16-component.md
content/docs/16-spectro-downloads.md

Release 2.6
PCG image update for OpenStack and MAAS

pcg-image-update-2.6

---

content/docs/13-terraform.md

terraform update :
relesase 0.7.2 
changes documented

terraform-0.7.2

---

content/docs/06-integrations/00-cilium.md

cilium-network-pack

---

content/docs/08-user-management/4-roles-permissions-and-project-scope.md
content/docs/08-user-management/5-roles-permissions-and-tenant-scope.md

Roles and Perms Matrix

---

content/docs/06-integrations/00-kubebench.md

kube-bench v.0.6.8

---

content/docs/06-integrations/00-aws-efs.md

Doc-140-New-AWS-EFS

---

CHANGES

Prod Push Jun 18

---

content/docs/06-integrations/00-openstack-cinder.md

To include latest packs versions.

Doc-179-Openstack_Cinder_CSI_1.22_1.23

---

content/docs/04-clusters/3-cluster-management/02-health-alerts.md

small-correction

---

content/docs/04-clusters/1-new-clusters/11-vmware.md

VMware permissions documentation about the alternate VDS permissions

vds-permission

---

content/docs/12-enterprise-version/04-enterprise-cluster-management.md

**2.7 Feature**
PCG Migration
added as a part of **Enterprise Management** (Enterprise cluster day 2 management)

2.7-feature-pcg-migration

---

content/docs/09-registries-and-packs/5-pack-constraints.md

**2.7 Release:**
Macros Update

macros-update-2.7

---

content/docs/04-clusters/1-new-clusters/04-aks.md
content/docs/04-clusters/1-new-clusters/07-maas.md

**2.7 Release Feature**
AKS Autoscaler added to AKS Cluster creation - node pool configuration.

2.7 Release Feature-aks-autoscaler

---

content/docs/04-clusters/3-cluster-management/07-workloads.md

**2.7 Feature**
Cluster Role Bindings and Role Binding support in Cluster Workloads Visibility

role-binding-workload-visibility-2.7

---

content/docs/06-integrations/00-azure-cni.md

**Release 2.7 Feature**
Azure CNI pack updated 
Policies updated

2.7-feature-azure-cni-pack

---

content/docs/06-integrations/00-ubuntu.md

Introduced UA and provided steps; notable parameters.

Doc-196-Canonical-UA-I-embedding-Ubuntu-MAAS

---

content/docs/04-clusters/2-brownfield-clusters.md

Doc-200-ImportClusterReadOnly

---

content/docs/03-cluster-profiles.md
content/docs/03-cluster-profiles/1-task-define-profile.md

**2.7 Feature -Hotfix**
Helm chart support for CSI/CNI Packs

helm-chart-csi-cni

---

content/docs/05-workspace.md
content/docs/05-workspace/1-adding-a-new-workspace.md
content/docs/05-workspace/2-workload-features.md

**2.7 Release Feature**
* Fix for Restore Pv Functionality is not working as expected.
Workspace-backup

pv-resource-update

---

content/docs/00-release-notes.md

2.7 Release Notes
Few links to be updated after merging the feature PR

2.7-release-notes

---

content/docs/04-clusters/1-new-clusters/04-aks.md

AKS-Windows-worker-node

---

content/docs/04-clusters/2-brownfield-clusters.md

Added install agent, explained full permissions and read-only; delete cluster steps.

Doc 200 import cluster read only with delete and install agent and migration

---

content/docs/05-workspace.md
content/docs/05-workspace/2-workload-features.md
content/docs/06-integrations/00-azure-cni.md

some-corrections

---

content/docs/09-registries-and-packs.md
content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
content/docs/09-registries-and-packs/2-spectro-cli-reference.md
content/docs/16-component.md

**Update:**
**CLI/Registries:**
Latest Palette pack registry Docker image
**Spectro CLI** 
linus
osx
**Components Matrics (no image changes):**
Palette CLI Versions
On-Premises Installer Version
Latest Air Gapped OVA Version
vSphere PCG Image Version
MAAS PCG Image Version

2.7-artifacts

---

content/docs/06-integrations/00-kubevious.md

DOC-211-Kubevious-minor-edits

---

content/docs/09-registries-and-packs/5-pack-constraints.md

tenant-macro

---

content/docs/00-release-notes.md
content/docs/04-clusters/1-new-clusters/05-edge.md

edge-review-updates

---

content/docs/04-clusters/3-cluster-management/05-backup-restore.md
content/docs/05-workspace/2-workload-features.md

**MinIO Back-up location** updated to 
!. Cluster Backup
2. Workspace Backup

minio-bkup

---

prow/functions.sh

Remove Robots.txt file for Production pushes

Remove robots for Production push

---

content/docs/13-terraform.md

* Provider 0.8.8
* Module 0.2.3
* Changes and updates for the updated provider and module.

terraform-update-0.8.8

---

content/docs/06-integrations/00-portworx.md

vSphere 2.9 & 2.10
Three Presets

Doc-178-Portworx-Vsphere-2.9-2.10

---

content/docs/04-clusters/3-cluster-management/05-backup-restore.md
content/docs/05-workspace/2-workload-features.md

custom bucket name to be appended as the resource name.

S3 Permission Update

---

content/docs/08-user-management/3-palette-resource-limits.md

api-rate-limit

---

content/docs/05-workspace/2-workload-features.md

**Workspace - Workload Visibility**  components Updated:
Jobs 
CronJobs 
RoleBinding
ClusterRoleBinding

Workspace Visibility

---

Dockerfile
Makefile
scripts/entry.sh

adds support to run gatsby in a docker container instead of having nodejs/npm installed locally on your machine

adding docker support

---

content/docs/09-registries-and-packs/6-oci-registry.md

Azure Basic authentication to OCI registries

azure-oci-registry

---

content/docs/13-terraform.md

tf-minor-rlse-8.9

---

content/docs/06-integrations/00-aws-ebs.md
content/docs/06-integrations/00-azure-disk.md
content/docs/06-integrations/00-nginx.md
content/docs/06-integrations/00-prometheus-operator.md

**Pack Version Update:**
1. Nginx 1.2.1
2. Prometheus Operator 35.5.1
3. AWS -EBS-CSI - 1.8.x and 1.5.x
4. Azure Disk CSI - 1.20.x

version-update-pcks

---

content/docs/06-integrations/00-istio.md

istio-version-update

---

content/docs/13-terraform.md

**Terraform Release** 
Provider 0.9.0 and Modules 0.3.0

terraform-rel-0.9.0

---

content/docs/04-clusters/1-new-clusters/02-eks.md

**2.8 Hotfix**
Add support disable AssociaProvider for the service account -EKS Clusters

2.8-HF-associate-oidc-provider

---

content/docs/06-integrations/00-portworx_operator.md

Fixes some typos and updates the documentation for the new presets in v2.11.2 of the `Portworx /w Operator` packs

updates and fixes for portworx 2.11.2

---

content/docs/04-clusters/3-cluster-management/04-os-patching.md

**2.8-Enhancement-OS-Patch-Monitoring**
Monitor OS patching from the Nodes page

2.8-Enhancement-OS-Patch-monitoring

---

content/docs/04-clusters/3-cluster-management.md
content/docs/04-clusters/3-cluster-management/12-palette-webctl.md

**2.8 Release Feature**
Web-based kubectl added as part of cluster management

release-2.8-Webctl

---

content/docs/04-clusters/1-new-clusters/02-eks.md

eks-troubleshoot

---

content/docs/08-user-management/3-palette-resource-limits.md

**2.8 Release Feature**
Set Palette resources from Tenant settings

2.8-enhancement-set-resource-limit

---

content/docs/04-clusters/3-cluster-management/13-palette-lock-cluster.md

**2.8 Release Feature**
Cluster Lock
1. Single Cluster
2. Project scope
3. Tenant scope

2.8-Release-cluster-lock

---

content/docs/08-user-management/4-saml-sso.md

**2.8 Release Feature**
Google OIDC 
Google SAML

2.8 Release Feature : google-idp

---

content/docs/05-workspace.md

**2.8 Hot Fix  Regex Expression**
~ for regex for namespace name filtering

2.8-hf-regex

---

content/docs/04-clusters/1-new-clusters/01-aws.md
content/docs/04-clusters/1-new-clusters/02-eks.md

IAMPOLICY attach for AWS cloud account

iam-policy-select

---

content/docs/06-integrations/00-rke2.md

RKE2-Updates

---

content/docs/00-release-notes.md

2.8-release-notes

---

content/docs/06-integrations/00-ubuntu.md

noted cc-eal is disabled in v20

Doc-213-Ubuntu-v20-cc-eal-disabled

---

content/docs/04-clusters/1-new-clusters/01-aws.md
content/docs/04-clusters/1-new-clusters/02-eks.md

iam-policy-descptn

---

content/docs/06-integrations/00-ubuntu-k3s.md

DOC-229-Ubuntu-K3s-pack

---

content/docs/04-clusters/1-new-clusters/03-azure.md
content/docs/04-clusters/1-new-clusters/04-aks.md

**2.8 Hot Fix**
Disable properties request based on the cloud account flag

2.8-hf-azure-diable-prop

---

content/docs/00-release-notes.md
content/docs/09-registries-and-packs.md
content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
content/docs/09-registries-and-packs/2-spectro-cli-reference.md
content/docs/16-component.md

**2.8 Release CLI and Registries Update**

2.8-release-cli-registries

---

CHANGES

Release Documentation for GA 2.8.0

2.8 Production Push

---

content/docs/00-release-notes.md
content/docs/04-clusters/3-cluster-management/13-palette-lock-cluster.md

**Lock cluster** feature name change updated to **pause platform update**

quick-fix-2.8

---

content/docs/00-index.mdx
content/docs/00-release-notes.md
content/docs/02-getting-started/04-onboarding-workflow.md
content/docs/04-clusters/01-public-cloud/01-aws.md
content/docs/04-clusters/01-public-cloud/02-eks.md
content/docs/04-clusters/01-public-cloud/03-azure.md
content/docs/04-clusters/01-public-cloud/04-aks.md
content/docs/04-clusters/01-public-cloud/06-tke.md
content/docs/04-clusters/02-data-center/03-vmware.md
content/docs/04-clusters/04-nested-clusters/nested-cluster-quickstart.md
content/docs/04-clusters/06-cluster-management/09-cluster-rbac.md
content/docs/05-workspace/1-adding-a-new-workspace.md
content/docs/06-integrations/00-rke2.md

link update part of doc restructuring.

links-update-02

---

content/docs/06-integrations/00-vsphere-csi.md

vSphere CSI Compatibility Matrix

vsphere-csi-compatibility-matrix

---

content/docs/04-clusters/05-brownfield-clusters.md

DOC-302-Importing-a-Brownfield-Cluster

---

content/docs/12-enterprise-version/00-on-prem-system-requirements.md

DOC-339-on-prem

---

content/docs/08-user-management/4-saml-sso.md

shortened first paragraph; removed msft from tabs

Doc-226-Azure-minor-edits

---

content/docs/04-clusters/01-public-cloud/01-aws.md
content/docs/04-clusters/01-public-cloud/02-eks.md

Dup of 775 to resolve for stale pr.

To resolve for stale pr

---

content/docs/06-integrations/00-external-secrets-operator.md

DOC-218-external-secrets-operator

---

content/docs/04-clusters/01-public-cloud/03-azure/1-gateways.md

link updates on self hosted pcg

link-updates

---

content/docs/18-knowledgebase/00-how-to.md
content/docs/18-knowledgebase/00-how-to/00-how-to.md
content/docs/18-knowledgebase/01-tutorials/2-cks-tutorial.md

How-to-dim-until ready

---

content/docs/06-integrations/00-aws-autoscaler.md

aws-autoscaler

---

content/docs/04-clusters/04-nested-clusters/nested-cluster-quickstart.md

Small Update on the nested cluster page on GKE clusters

gke-nested-cluster-info

---

content/api/1-introduction.md

project-id-introduction

---

content/docs/04-clusters/01-public-cloud/04-aks.md

**Release 3.0
AKS cluster maximum pod per node**

rel-3.0-maxpodlimit-aks

---

content/docs/04-clusters/06-cluster-management/09-cluster-rbac.md
content/docs/05-workspace.md
content/docs/05-workspace/2-workload-features.md
content/docs/18-knowledgebase/00-how-to.md
content/docs/18-knowledgebase/00-how-to/00-reverse-proxy-dashboard.md

**3.0 Feature
Reverse Proxy Kubernetes Dashboard**
Added as a `How To` guide.

3.0-Feature-reverse-proxy-dashboard

---

content/docs/04-clusters/06-cluster-management/14-noc-ui.md

3.0.0-noc-ui

---

content/docs/04-clusters/06-cluster-management/05-backup-restore.md
content/docs/05-workspace/2-workload-features.md

**Release 3.0.0
Azure Blob Backup**

3.0-azure-bkup

---

content/docs/13-terraform.md

Release 3.0
Terraform: 10.1 -0.4.1

terraform-10.1

---

content/docs/09-registries-and-packs.md
content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
content/docs/09-registries-and-packs/2-spectro-cli-reference.md
content/docs/16-component.md

**Release 3.0 
cli and registries update**

cli-registries-update

---

content/docs/04-clusters/06-cluster-management.md
content/docs/04-clusters/06-cluster-management/13-palette-lock-cluster.md

**Release 3.0
Auto Remediation**

rel-3.0-auto-remediation

---

content/docs/04-clusters/03-edge/02-native.md
content/docs/13-terraform.md

**Release 3.0
PLt :95**
and few edge fixes

tkt-plt-95

---

content/docs/00-release-notes.md

3.0-release-notes

---

README.md
content/docs/00-release-notes.md

This PR carries over changes that were originally previously closed PR. @resmaa and I collaborated on the changes together.

docs: minor suggetions to 3.0.0 releases

---

content/docs/13-terraform.md

terraform-update

---

README.md

This PR adds documentation for authors to reference when wanting to implement a redirect.  This PR is a child of PR #952

docs: added documentation about redirects to the README

---

CHANGES

This PR pushes the latest changes to production.

docs: push to production

---

CHANGES

This PR pushes the latest changes to prod

chore: push to production

---

content/docs/15-compliance.md

Please review new FIPS section on Compliance page. 
Jira [ticket](https://spectrocloud.atlassian.net/browse/DOC-393):

Add FIPS cert

---

CHANGES

Pushing changes to production.

Production release

---

CHANGES

This PR releases the latest changes to the download page to production.

docs: production release

---

content/docs/06-integrations/00-vsphere-csi.md

vSphere CSI parameters removed

csi-parameter-removed

---

CHANGES

Added date for Postman Collection for production push.
Jira: https://spectrocloud.atlassian.net/browse/DOC-398

Add Postman Collection date

---

content/docs/04-clusters/01-public-cloud/03-azure/1-gateways.md

logo removed for self hosted PCG

logo-remove-shpcg

---

README.md

Rearranged "read me" as per the previous conversation.

rearrange-read-me

---

content/docs/06-integrations/00-cilium-tetragon.md
content/docs/18-knowledgebase/00-how-to/00-reverse-proxy-dashboard.md

cilium-tetragon

---

content/docs/04.5-devx/07-palette-virtual-clusters.md

Updated table with new limits for virtual clusters: 
https://spectrocloud.atlassian.net/browse/PPD-804
/test librarium_release_build

Update new Virtual Cluster limits

---

content/docs/04.5-devx/05-app-profile/02-container-deployment.md

"how to" formatting of  Container deployment page

Container Deployment Update

---

content/docs/04-clusters/01-public-cloud/03-azure.md

Added API Allocation Load Balancer to Azure Cluster creation wizard

azure-endpoint-revisit

---

src/shared/utils/redirects.js

This PR fixes redirect for virtualized edge

chore: fix redirect

---

content/docs/04-clusters/02-data-center/01-maas.md

This PR updates the MaaS installer version specified.

update maas installer version

---

content/docs/04.5-devx/08-registries/00-helm-registry.md

This PR fixes a missed fix from PR #1022

fix language

---

content/docs/04-clusters/02-data-center/03-vmware.md

This PR addresses Jira ticket [DOC-277](https://spectrocloud.atlassian.net/jira/software/c/projects/DOC/boards/62?modal=detail&selectedIssue=DOC-277)

docs: fixes DOC-277

---

content/docs/18-knowledgebase/00-how-to/00-reverse-proxy-dashboard.md

Kubernetes Dashboard and Spectro proxy link added to the page

dashboard-link

---

content/docs/12-enterprise-version.md
content/docs/12-enterprise-version/00-on-prem-system-requirements.md

On Premise Deployment Document Updates

---

content/docs/04.5-devx/04-resource-quota.md

Added ephemeral storage for virtual clusters and revamped doc. 
Jira: https://spectrocloud.atlassian.net/browse/PPD-620
[Preview](https://deploy-preview-1029--docs-spectrocloud.netlify.app/devx/resource-quota)

Add ephemeral storage and revise

---

content/docs/04-clusters/03-edge/02-native.md

This PR addresses the feedback received from [Apzzi](https://spectrocloud.slack.com/archives/CTZ6394G2/p1670860343559279).

docs: fix for command not rendering correctly

---

content/docs/12-enterprise-version.md
content/docs/12-enterprise-version/00-on-prem-system-requirements.md
content/docs/16-spectro-downloads.md
content/docs/18-knowledgebase/00-how-to/00-reverse-proxy-dashboard.md

Images dec 22

---

.github/workflows/pull_request.yaml
content/docs/06-integrations/00-argo-cd.md
content/docs/06-integrations/00-aws-ebs.md
content/docs/06-integrations/00-cilium.md
content/docs/06-integrations/00-gce.md
content/docs/06-integrations/00-prometheus-operator.md
content/docs/06-integrations/00-vsphere-csi.md
content/docs/14-troubleshooting.md
vale.ini
vale/styles/Vocab/Internal/accept.txt

This PR updates the packs documentation and addresses the missing P1 documentation. See the Slack [thread](https://spectrocloud.slack.com/archives/CTZ6394G2/p1670961607892099) for more details 🧵

Packs P1 docs

---

prow/presubmit.sh

This PR fixes an issue where docs are getting released to prod during PR phase.

ci: fixes accidental prod release

---

content/docs/04-clusters/04-palette-virtual-clusters.md
content/docs/04.5-devx/07-palette-virtual-clusters/00-pause-restore-virtual-clusters.md
prow/postsubmit.sh
prow/release_build.sh
src/shared/utils/redirects.js

This PR adds a missing redirect related to Palette Virtual Clusters

docs: added missing redirects

---

content/docs/06-integrations/00-kubernetes-dashboard.md

link-dash-board

---

vale/styles/Vocab/Internal/accept.txt
vale/styles/Vocab/Internal/reject.txt

This PR adds accepted and rejected words to vale checks that we agreed on in our recent team meeting.

Add accepted and rejected words

---

content/docs/12-enterprise-version/00-on-prem-system-requirements.md

Updated On premise Configuration to be consistent with Quick start Configuration

Updated On premise Configuration

---

content/docs/04-clusters/06-cluster-management/04-os-patching.md

**3.1 Release Feature**
PCP-254: OS patch node reboot support

os-patch-boot

---

content/docs/04-clusters/06-cluster-management/14-noc-ui.md

**Release Feature 3.1**
Map view filter
PEM 455

filter-map-view

---

content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
content/docs/04-clusters/01-public-cloud/05-gcp.md
content/docs/04-clusters/01-public-cloud/06-tke.md
content/docs/04-clusters/06-cluster-management/15-node-pool.md
vale/styles/Vocab/Internal/accept.txt

This PR contains the changes in PR #1052 .

Node pools & autoscaler

---

content/docs/04-clusters/01-public-cloud.md
content/docs/04-clusters/01-public-cloud/03-azure/00-architecture.md
content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
content/docs/04-clusters/06-cluster-management/15-node-pool.md
vale/styles/Vocab/Internal/accept.txt

This PR carries over the changes from PR #1040 .

Azure Storage

---

content/docs/09-registries-and-packs.md
content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
content/docs/09-registries-and-packs/2-spectro-cli-reference.md

**3.1 Release** 
Spectro CLI and Registries Update

cli-registries

---

content/docs/09-registries-and-packs.md
content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
content/docs/09-registries-and-packs/2-spectro-cli-reference.md

Reverts spectrocloud/librarium#1065

Revert "cli-registries"

---

content/docs/09-registries-and-packs.md
content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
content/docs/09-registries-and-packs/2-spectro-cli-reference.md

This PR ensures PR #1065 gets into release-3-1 branch

Registries cli

---

content/docs/09-registries-and-packs/2-spectro-cli-reference.md

Fixes a minor oddity and forces a redeploy when merged.

docs: change to trigger redeploy

---

content/docs/00-release-notes.md
src/shared/utils/redirects.js

https://spectrocloud.slack.com/archives/CTZ6394G2/p1672824389688449

Pvc redirect

---

content/docs/03-cluster-profiles/1-task-define-profile.md

Quick fix to add add-on categories

pack-catagories

---

content/docs/04-clusters/03-edge/02-native.md
content/docs/17-glossary-all.md
vale/styles/Vocab/Internal/accept.txt

This PR adds two definitions to the docs glossary. A definition for each of the terms, PXK, and PXK-E are added.

Definitions for PXK and PXK-E

---

content/api/2-samples.md

This PR addresses feedback received, check out the [Slack thread](https://spectrocloud.slack.com/archives/CTZ6394G2/p1674819154285969) for more details 🧵

docs: fixed incorrect JSON paylaods in API sample

---

content/docs/08-user-management/2-palette-rbac/1-tenant-scope-roles-permissions.md
content/docs/08-user-management/2-palette-rbac/2-project-scope-roles-permissions.md

tag-update-permission

---

content/docs/08-user-management/1-user-authentication.md

This PR documents the new UI user authentication flow.
💻 [Preview](https://deploy-preview-1100--docs-spectrocloud.netlify.app/user-management/user-authentication)

Document changes to the sign-in experience

---

README.md

The word recommend was spelled wrong on the Readme file, so I corrected it.

docs: Fix Typo

---

content/docs/04-clusters/06-cluster-management/12-palette-webctl.md

This PR fixes an incorrect redirect URL

docs: fix incorrect redirect URL

---

content/docs/18-knowledgebase/00-how-to/02-palette-sso-with-adfs.md

This PR fixes the redirect URI for shelly and adds a Single Logout redirect URI for ADFS.

Improve redirect URIs

---

content/docs/04.5-devx/07-palette-virtual-clusters/05-resize-virtual-clusters.md

This PR provides a how to for resizing virtual clusters.
[Doc Preview](https://deploy-preview-1111--docs-spectrocloud.netlify.app/devx/palette-virtual-clusters/resize-virtual-clusters)

Create how to resize virtual clusters

---

content/api/1-introduction.md

made a quick rehash of this, but it may need to be checked for accuracy and formatting/style guide. I focused on cleaning up the text.

quick update  on project scope

---

content/api/1-introduction.md

edited for readability & conciseness

Further language clean up

---

content/docs/04-clusters/01-public-cloud/01-aws/09-eks.md

This PR fixes a link issue reported in Appzi

chore: fixed link issue

---

content/docs/04.5-devx/06-apps/05-deploy-app.md

This PR updates the tutorial tag

docs: updated tutorial tag

---

.github/pull_request_template.md

This PR adds a PR template to the repository.

ci: added PR template

---

.github/pull_request_template.md
content/docs/02.5-architecture/04-networking-ports.md
content/docs/04-clusters/03-edge/02-native.md

This PR fixes an incorrect network path in the arch diagram for SaaS. Additionally, markdown issues were fixed for the Edge Install page.  The PR template was also fixed.
💻 [Preview](https://deploy-preview-1168--docs-spectrocloud.netlify.app/clusters/edge/native)

docs: updated diagram and fixed markdown error

---

content/docs/02.5-architecture/04-networking-ports.md

This PR introduces an additional architecture diagram for SaaS and Edge.
💻 [Preview](https://deploy-preview-1169--docs-spectrocloud.netlify.app/architecture/networking-ports)

docs: added new diagram for edge

---

content/docs/02.5-architecture/04-networking-ports.md

This PR removes the architecture diagram due to recent feedback. 

docs: removing diagram

---

content/docs/02.5-architecture/04-networking-ports.md

This PR adds a new Edge Architecture image.
💻 [Preview](https://deploy-preview-1171--docs-spectrocloud.netlify.app/architecture/networking-ports)

docs: new diagram

---

content/docs/02.5-architecture/04-networking-ports.md

This PR updates the architecture table by adding outbound 443 for workload clusters.

docs: table update

---

content/docs/02.5-architecture/04-networking-ports.md

This PR updates the network table

docs: updated network ports table

---

content/docs/02.5-architecture/04-networking-ports.md

This PR adds a correction identified by the product management team.

docs: more updates

---

content/docs/00-release-notes.md

This PR contains the release notes for 3.3

Release notes 3 3

---

content/docs/00-release-notes.md

Change Public Cloud Gateway to Private
This PR renames the "Public Cloud Gateway" to "Private" cloud gateway. There is no "Public Cloud Gateway".

Change Public Cloud Gateway to Private

---

src/shared/components/common/PointOfInterest.js

DOC-734 Fix PointsOfInterest scroll

---

content/api/v1/api.json

3.3 APIs docs and postman json files

3.3 API docs

---

content/docs/00-release-notes.md
content/docs/09-registries-and-packs.md
content/docs/09-registries-and-packs/2-spectro-cli-reference.md
content/docs/16-component.md
content/docs/16-spectro-downloads.md

This PR introduces minor fixes to download URLs

docs: updated URLs and release note date

---

content/docs/04-clusters/03-edge/09-site-deployment/03-installer.md

This PR fixed the markdown issue on the Edge installer page.

docs: markdown fix

---

content/docs/00-release-notes.md
content/docs/16-component.md

This PR updates the release notes after feedback.

docs: updated release notes

---

content/docs/04-clusters/03-edge/01-architecture.md
content/docs/04-clusters/03-edge/09-site-deployment/05-site-installation.md

This PR fixes an incorrect Edge requirement related to TPM

docs: updated Edge prereqs

---

CODEOWNERS
content/OWNERS
content/OWNER_ALIASES

This PR adds GitHub CODEOWNERS to the docs repository.

ci: added CODEOWNERS

---

content/docs/04-clusters/03-edge/04-edgeforge-workflow/01-build-kairos-os.md
content/docs/04-clusters/03-edge/04-edgeforge-workflow/02-build-content-bundle.md
content/docs/04-clusters/03-edge/04-edgeforge-workflow/04-build-images.md

This PR adds a missing CLI flag in the EdgeForge workflow and a space to each shell command to remove the subtract highlight behavior.

docs: added new CLI flag

---

content/api/2-samples.mdx
content/docs/09-registries-and-packs/1-adding-a-custom-registry.md
content/docs/09-registries-and-packs/7-advanced-configuration.md
src/shared/mdx/components/codeBlock.js

This PR adds a cross-reference to the Let's Encrypt guide.

docs: minor update

---

content/docs/04.5-devx.md

This PR updates language reflecting what Palette platforms App Mode is available in. 
🎫 [PPD-1171](https://spectrocloud.atlassian.net/browse/PPD-1171)

Pde self hosted

---

content/docs/09-registries-and-packs/5-pack-constraints.md

This PR adds new macros related to the cluster profile. The macros have also been updated with descriptions.
💻 [Add Preview URL](https://deploy-preview-1250--docs-spectrocloud.netlify.app/registries-and-packs/pack-constraints#packmacros)
🎫 [PEM-1606](https://spectrocloud.atlassian.net/browse/PEM-1606)

docs: added new macros for pack PEM-1603

---

content/docs/12-enterprise-version/06-air-gap-repo.md

This PR fixes a broken URL reported by the broken docs links reporter automation.

docs: updated broken links

---

content/docs/12-enterprise-version/03.5-helm-chart-install-reference.md

This PR fixes a typo in the Helm reference page. 

docs: fixed Helm chart variable name

---

content/docs/16-spectro-downloads.md

This PR updated palette-edge-installer cli to 3.3.3
https://spectrocloud.atlassian.net/browse/PE-1563

PE-1563 Updating palette-edge-installer cli link

---

content/docs/04-clusters/02-data-center/01-maas/05-install-manage-maas-pcg.md

This PR adds a new diagram to the MaaS install guide.

docs: added MaaS image

---

content/docs/04-clusters/01-public-cloud/03-azure/00-architecture.md

This PR documents the three reserved tags for Azure that are unavailable to users.
💻 [Preview](https://deploy-preview-1273--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/architecture#tags)

docs: added reserved tags for Azure

---

content/docs/06-integrations/00-cloudanix.md
vale/styles/Vocab/Internal/accept.txt

This PR Contains adds the following.
- Support for Kubernetes 1.25 and higher
- Spectro Namespace Labeler 
- yaml file format example
💻 [Cloudanix](https://deploy-preview-1276--docs-spectrocloud.netlify.app/integrations/cloudanix)

Cloudanix Update

---

content/docs/09.5-security/20-security-bulletins.md

This PR adds 2 security bulletins

Added 2 security bulletins

---

.dockerignore
Dockerfile

This PR fixes an issue related to the Docker image failing to install node dependencies.

chore: fixed docker image issue

---

content/docs/00-release-notes.md
content/docs/06-integrations/00-kubernetes.md
content/docs/09-registries-and-packs/2-spectro-cli-reference.md
content/docs/12.5-palette-cli/10-install-palette-cli.md
content/docs/16-component.md
content/docs/16-spectro-downloads.md

This PR updates the download URLs and the packs for 3.4 release.

docs: updated download URLs

---

content/docs/00-release-notes.md
content/docs/12-enterprise-version.md
content/docs/12-enterprise-version/03-deploying-palette-with-helm.md
content/docs/12-enterprise-version/10-upgrade.md
content/docs/14-troubleshooting/04-cluster-deployment.md
content/docs/14-troubleshooting/06-nodes.md
content/docs/14-troubleshooting/12-edge.mdx
content/docs/14-troubleshooting/15-palette-upgrade.md

This PR adds an update section to the documentation and updates the breaking change section.
💻 [ Preview URL](https://deploy-preview-1307--docs-spectrocloud.netlify.app/)
🎫 [DOC-773](https://spectrocloud.atlassian.net/browse/DOC-773)

docs: added upgrade notes DOC-773

---

content/docs/04-clusters/01-public-cloud/80-deploy-k8s-cluster.md
content/docs/06-integrations/00-byoos.md
content/docs/16-spectro-downloads.md
content/docs/19-kubernetes-knowlege-hub/01-tutorials.md
content/docs/19-kubernetes-knowlege-hub/01-tutorials/06-deploy-stateless-frontend-app.md
src/shared/utils/redirects.js

This PR fixes a broken URL in production.
💻 [Preview URL](https://deploy-preview-1315--docs-spectrocloud.netlify.app/)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-774)

docs: fixed broken URL in PDE DOC-774

---

content/docs/04-clusters/01-public-cloud/01-aws/10-required-iam-policies.md

This PR updates the AWS IAM policy names to better reflect the actual name displayed in the UI.

docs: updated EKS policies

---

content/docs/16-spectro-downloads.md

This PR adds checksum values to the downloads page. 

docs: added checksum values for downloads

---

content/docs/04-clusters/01-public-cloud/80-deploy-k8s-cluster.md
content/docs/04-clusters/06-cluster-management/02.5-certificate-management.md
content/docs/18-knowledgebase/01-tutorials/80-deploy-k8s-cluster.md

This PR updates broken links reported by our friend, SpectroMate.

docs: update broken links

---

content/docs/04-clusters/02-data-center/01-maas/15-create-manage-maas-clusters.md

This PR states the updates on an MAAS error, received during deployment and upgrading of a cluster.
💻 [Preview](https://deploy-preview-1345--docs-spectrocloud.netlify.app/clusters/data-center/maas/create-manage-maas-clusters)
🎫 [DOC-775](https://spectrocloud.atlassian.net/browse/DOC-775)

Maas User Requirement Update

---

content/docs/04-clusters/01-public-cloud/01-aws/10-required-iam-policies.md

This PR addresses a comma issue with the EKS IAM policy.
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-785)

docs: fix IAM policy DOC-785

---

content/docs/04-clusters/01-public-cloud/80-deploy-k8s-cluster.md

This PR fixed the tutorial version image

docs: fix tutorial version

---

content/docs/06-integrations/00-byoos.md
content/docs/12-enterprise-version/00-on-prem-system-requirements.md

This PR applies a minor update to the Self-hosted Palette requirements page.
New vSphere version tab.
Storage Policies for v8
Storage Policies Spectro Role
💻 [Preview](https://deploy-preview-1361--docs-spectrocloud.netlify.app/enterprise-version/on-prem-system-requirements)
🎫 [PCP-1327](https://spectrocloud.atlassian.net/browse/PCP-1327)
🎫 [DOC-797](https://spectrocloud.atlassian.net/browse/DOC-797)

docs: Self-Hosted Sphere changes

---

content/docs/08-user-management/4-saml-sso.md

This PR updates the index page for SSO with a link to the new tutorial.

docs: update index page

---

content/docs/04-clusters/01-public-cloud/05-gcp/10-add-gcp-accounts.md
content/docs/04-clusters/01-public-cloud/05-gcp/90-required-permissions.md
content/docs/04-clusters/03-edge/02-edge-configuration/35-installer-reference.md
content/docs/04-clusters/03-edge/04-edgeforge-workflow/03-prepare-user-data.md
content/docs/08-user-management/4-saml-sso.md
content/docs/18-knowledgebase/01-tutorials/05-deploy-app.md
content/docs/18-knowledgebase/01-tutorials/4.5-deploy-pack.md
content/docs/18-knowledgebase/01-tutorials/80-deploy-k8s-cluster.md

This PR addresses minor feedback mentioned in Slack.
* [Updated GCP Required Permissions](http://localhost:9000/clusters/public-cloud/gcp/required-permissions)
* [Added cloud init headers to all Edge Installer configuration examples](http://localhost:9000/clusters/edge/edgeforge-workflow/prepare-user-data).
* Updated all tutorials to use the latest docker image version `1.0.6`

docs: Minor Fixes

---

content/docs/00-release-notes.md

This PR contains the removal of the https://www.spectrocloud.com/pricing/  link, as it appears to be broken.

DOCS:LINK_FIX (Release Notes)

---

gatsby-ssr.js

This PR updates the full story init script after guidance from the Full Story team. 
💻 [Preview URL](https://deploy-preview-1381--docs-spectrocloud.netlify.app/)

chore: updated ssr code for full story

---

content/docs/04-clusters/02-data-center/03-vmware.md

This PR re-adds the VMware videos. 
💻 [Preview URL](https://deploy-preview-1387--docs-spectrocloud.netlify.app/clusters/data-center/vmware)

docs: added videos back

---

vale/styles/Vocab/Internal/accept.txt

This PR updates our accepted terms list for Vale.

docs: update accept.txt to include MAAS

---

src/shared/components/common/Technologies/index.js

Reduce space between packs card logo and text

Packs Cards Style Fix

---

content/docs/06-integrations/00-kubernetes-edge.md
content/docs/06-integrations/00-kubernetes.md

This PR creates the PXK-E packs doc and documents OIDC options. It also fixes a couple of links in the PXK doc and adds a couple. 
💻 [PXK-E](https://deploy-preview-1406--docs-spectrocloud.netlify.app/integrations/kubernetes-edge)
💻 [PXK](https://deploy-preview-1406--docs-spectrocloud.netlify.app/integrations/kubernetes)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PE-2076) and [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-646)

Doc OIDC for edge native clusters

---

content/docs/06-integrations/00-antrea-cni.md
src/shared/components/common/Technologies/index.js

Adding the ability to add multiple category in front matter and filter it.
https://stackoverflow.com/questions/50881453/how-to-add-an-array-of-values-to-a-set
💻 [Preview URL](https://deploy-preview-1415--docs-spectrocloud.netlify.app/integrations)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PE-2139)

Add Multiple category selector 

---

content/docs/04-clusters/01-public-cloud/01-aws/10-required-iam-policies.md

This PR adds missing AWS permissions from the Deployment Policy.
🎫 [PCP-1460](https://spectrocloud.atlassian.net/browse/PCP-1460)

docs: PCP-1460 added missing permissions

---

styleguide/spectro-cloud-style-guide.md

This PR updates the style guide.

docs: updated style guide

---

content/docs/04-clusters/02-data-center/01-maas.md
content/docs/04-clusters/02-data-center/01-maas/05-install-manage-maas-pcg.md
content/docs/04-clusters/02-data-center/01-maas/10-register-manage-maas-cloud-accounts.md
content/docs/04-clusters/02-data-center/01-maas/15-create-manage-maas-clusters.md
content/docs/04-clusters/02-data-center/02-openstack.md
content/docs/04-clusters/02-data-center/03-vmware.md
content/docs/04.6-vm-management.md

Reverts spectrocloud/librarium#1405
This PR is getting reverted due to the feature not being available today.

Revert "PLT-452: replace Docker image flow with CLI flow in PCG docs"

---

content/docs/03-cluster-profiles/10-byoos/10-image-builder.md

This PR fixes verbiage in an InfoBox.
🎫 [Jira Ticket n/a]()

Update InfoBox in 10-image-builder.md

---

content/docs/04-clusters.md

DOC-821 Update 04-clusters.md

---

content/docs/04-clusters/02-data-center/03-vmware.md

This PR fixes a typo and other small fixes.

Update 03-vmware.md to fix typo and other small fixes

---

content/docs/04-clusters/01-public-cloud/01-aws/09-eks.md

This PR updates the KMS permissions required for AWS clusters.
💻 [Preview URL](https://deploy-preview-1447--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks#configurekms)

docs: updated KMS required permissions

---

content/docs/04-clusters/01-public-cloud/01-aws/05-add-aws-accounts.md
content/docs/04-clusters/01-public-cloud/01-aws/08-create-cluster.md
content/docs/04-clusters/01-public-cloud/03-azure/02-create-azure-cluster.md
content/docs/04-clusters/01-public-cloud/05-gcp/20-create-gcp-iaas-cluster.md
content/docs/04-clusters/01-public-cloud/05-gcp/30-create-gcp-gke-cluster.md
content/docs/04-clusters/02-data-center/01-maas/15-create-manage-maas-clusters.md
content/docs/04-clusters/02-data-center/02-openstack.md
content/docs/04-clusters/02-data-center/03-vmware.md
content/docs/04-clusters/03-edge/02-edge-configuration/35-installer-reference.md
content/docs/04-clusters/03-edge/04-edgeforge-workflow/12-build-artifacts.md
content/docs/04-clusters/03-edge/09-site-deployment/05-site-installation.md
content/docs/04-clusters/03-edge/09-site-deployment/05-site-installation/06-edge-host-registration.md
content/docs/12-enterprise-version/05-enterprise-cluster-management.md
content/docs/14-troubleshooting/04-cluster-deployment.md
content/docs/18-knowledgebase/01-tutorials/05-deploy-app.md
content/docs/19-kubernetes-knowlege-hub.md
content/docs/19-kubernetes-knowlege-hub/01-tutorials/06-deploy-stateless-frontend-app.md
styleguide/spectro-cloud-style-guide.md

This PR updates spelling mistakes across documentation. 
Have not checked if these mistakes exist in [spectrocloud/docs-prototype](https://github.com/spectrocloud/docs-prototype). @nagesh161007
💻 No preview.
🎫 No JIRA ticket.

Fix spelling across documentation

---

content/docs/00-release-notes.md
content/docs/12-enterprise-version/02-deploying-an-enterprise-cluster.md
content/docs/12.5-palette-cli/20-commands.md
content/docs/12.5-vertex/02-install-palette-vertex/10-install-on-vmware/10-install.md

This PR adds new release notes. Additional changes to the Palette CLI command page are also included. 
- [Release Note](https://release-updates-1--docs-spectrocloud.netlify.app/release-notes)
- [Palette CLI Commands](https://release-updates-1--docs-spectrocloud.netlify.app/palette-cli/commands)
💻 [Preview URL](https://release-updates-1--docs-spectrocloud.netlify.app/release-notes)

Release Notes Update

---

content/docs/09-registries-and-packs/1-adding-a-custom-registry.md

--port was specified instead of -p (or --publish, but not --port)

Correct typo in docker command

---

content/docs/12-enterprise-version/00-on-prem-system-requirements.md
content/docs/12-enterprise-version/02-deploying-an-enterprise-cluster.md
content/docs/12-enterprise-version/03-deploying-palette-with-helm.md
content/docs/12.5-vertex/02-install-palette-vertex.md
content/docs/12.5-vertex/02-install-palette-vertex/10-install-on-vmware/10-install.md
content/docs/12.5-vertex/02-install-palette-vertex/20-install-on-kubernetes/10-install.md
content/docs/16-spectro-downloads.md

This PR updates the Downloads page to reflect the usage of Palette CLI for installing PCG, Palette, and VerteX. New sizing recommendations for Palette VerteX installs are also included with this PR.
- [Vertex Size Guidelines](https://deploy-preview-1470--docs-spectrocloud.netlify.app/vertex/install-palette-vertex#sizeguidelines)
- [Palette Size Guidelines](https://deploy-preview-1470--docs-spectrocloud.netlify.app/enterprise-version/on-prem-system-requirements#self-hostedconfiguration)
- [Downloads Page](https://deploy-preview-1470--docs-spectrocloud.netlify.app/spectro-downloads)
💻 [Preview URL](https://deploy-preview-1470--docs-spectrocloud.netlify.app/introduction)

 Palette/Vertex sizing

---

content/docs/03-cluster-profiles/10-byoos/10-image-builder.md

This PR removes a git step that is not needed.
💻 [Preview URL](https://deploy-preview-1476--docs-spectrocloud.netlify.app/cluster-profiles/byoos/image-builder)

docs: Update 10-image-builder.md

---

content/docs/02.5-architecture/04.1-grps-proxy.md

This PR adds documentation for using gRPC with network proxies and captures limitations.
💻 [Preview URL](https://deploy-preview-1472--docs-spectrocloud.netlify.app/architecture/grps-proxy)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PEM-2194)

gRPC and Proxy

---

content/docs/12-enterprise-version/03-deploying-palette-with-helm.md
content/docs/12-enterprise-version/03.5-helm-chart-install-reference.md
content/docs/12.5-vertex/02-install-palette-vertex/20-install-on-kubernetes/10-install.md
content/docs/12.5-vertex/02-install-palette-vertex/20-install-on-kubernetes/20-vertex-helm-ref.md

This PR updates Helm values changes introduced by engineering.
[VerteX Helm Reference](https://deploy-preview-1478--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref)
[Palette Helm Reference](https://deploy-preview-1478--docs-spectrocloud.netlify.app/enterprise-version/helm-chart-install-reference)
💻 [Preview URL](https://deploy-preview-1478--docs-spectrocloud.netlify.app)
🎫 [DOC-841](https://spectrocloud.atlassian.net/browse/DOC-841)

Minor changes

---

.gitleaksignore
content/docs/00-release-notes.md
content/docs/04-clusters/06-cluster-management/15-node-pool.md
content/docs/06-integrations/00-aws-ebs.md
content/docs/06-integrations/00-calico.md
content/docs/06-integrations/00-frp.md
content/docs/06-integrations/00-kubernetes-edge.md
content/docs/06-integrations/00-kubernetes.md
content/docs/06-integrations/00-longhorn.md
content/docs/06-integrations/00-rke2.md
content/docs/06-integrations/00-vsphere-csi.md
content/docs/06-integrations/01-maintenance-policy.md

This PR adds minor updates called out before the release.
- [Release Notes](https://deploy-preview-1480--docs-spectrocloud.netlify.app/release-notes)
- [Maintenance Policy](https://deploy-preview-1480--docs-spectrocloud.netlify.app/integrations/maintenance-policy)
- [Packs List](https://deploy-preview-1480--docs-spectrocloud.netlify.app/integrations)
- [Worker Pool Update](https://deploy-preview-1480--docs-spectrocloud.netlify.app/clusters/cluster-management/node-pool#workernodepool)
💻 [Preview URL](https://deploy-preview-1480--docs-spectrocloud.netlify.app/)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-845)

Minor 4 0 changes

---

content/docs/00-release-notes.md

This PR fixes an incorrect URL in the release notes.

chore: fix release notes

---

content/docs/04-clusters/02-data-center/01-maas/05-install-manage-maas-pcg.md
content/docs/04-clusters/02-data-center/02-openstack.md
content/docs/04-clusters/02-data-center/03-vmware.md
content/docs/12.5-palette-cli/10-install-palette-cli.md
content/docs/12.5-palette-cli/20-commands.md

This PR fixes the updates to the Palette CLI `pcg` `install` command. 
💻 [Preview URL](https://deploy-preview-1484--docs-spectrocloud.netlify.app/palette-cli/commands/#pcg)
🎫 [DOC-846](https://spectrocloud.atlassian.net/browse/DOC-846)

docs: updated pcg install examples and reference page

---

content/docs/00-release-notes.md

This PR updates the release notes with a message clarifying the update path for RKE2 and PXKE
💻 [Preview URL](https://deploy-preview-1485--docs-spectrocloud.netlify.app/release-notes#release-4-0-edge)
🎫 [PE-2491](https://spectrocloud.atlassian.net/browse/PE-2491)

docs: PE-2491 update release notes

---

content/docs/00-release-notes.md
content/docs/01-introduction.md
content/docs/12.5-vertex/02-install-palette-vertex.md
content/docs/12.5-vertex/60-system-management/05-enable-non-fips-settings/09-allow-cluster-import.md

This PR corrects incorrect URLs found through the weekly, broken URL reporter.

docs: fixes broken URLs

---

.backportrc.json
.github/workflows/backport.yaml

This PR introduces backport capability. 
🎫 [DOC-848](https://spectrocloud.atlassian.net/browse/DOC-848)

ci: added backport capability

---

.backportrc.json
.github/workflows/backport.yaml

chore: validate backport

---

Makefile

This PR updates Makefile comments
.

ci: added comments to Makefile

---

content/docs/12.5-vertex/00-fips/01-fips-compliant-components.md

This PR updates the FIPS information page.

docs: updated fips page

---

content/docs/04.6-vm-management.md
content/docs/06-integrations/00-frp.md

This PR fixes a broken URL
💻 [Preview URL](https://deploy-preview-1495--docs-spectrocloud.netlify.app/integrations/frp)

docs: fix-dashboard URL

---

.backportrc.json
.github/workflows/pull_request.yaml
.github/workflows/version-branch-update.yaml

This PR adds a validation step to the backport PRs created by the backport logic. Today, there are no checks implemented on those PRs.
🎫 [DOC-857](https://spectrocloud.atlassian.net/browse/DOC-857)

ci: added logic for backport PRs

---

.github/workflows/version-branch-update.yaml

This PR fixes the backport PRs not having a CI check.

ci: final fix to backport CI

---

content/docs/04.6-vm-management.md

This PR correct minor language related to PR #1506 
🎫 [DOC-852](https://spectrocloud.atlassian.net/browse/DOC-852)

docs: Update 04.6-vm-management.md

---

.github/url-checks.yaml
Makefile
docs/CODEOWNERS
docs/docs-content/enterprise-version/enterprise-version.md
package-lock.json
package.json

This PR fixes broken URLs reported in the docs channel.

chore: fixed broken URLs

---

docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-static.md
docs/docs-content/clusters/cluster-management/backup-restore/create-cluster-backup.md

This PR adds guidance for when creating a backup with MinIO. 
🎫 [DOC-823](https://spectrocloud.atlassian.net/browse/DOC-823)

docs: DOC-823 update to MinIO steps

---

docs/docs-content/troubleshooting/troubleshooting.md

Fix Download cluster logs URL in troubleshooting.md

---

.github/workflows/pull_request.yaml
docs/docs-content/spectro-downloads.md

Updates the Palette CLI URL to 4.0.1
This PR updates the Palette CLI download URL to 4.0.1

Update Palette CLI download URI to 4.0.1

---

.github/workflows/version-branch-update.yaml
docs/docs-content/clusters/cluster-management/backup-restore/add-backup-location-static.md
docs/docs-content/clusters/cluster-management/backup-restore/restore-cluster-backup.md
docs/docs-content/clusters/cluster-management/cluster-updates.md
docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md
docs/docs-content/clusters/palette-virtual-clusters/deploy-virtual-cluster.md
docs/docs-content/enterprise-version/on-prem-system-requirements.md

This PR removes the `note` callout boxes.

chore: removed note callout boxes

---

docs/docs-content/clusters/public-cloud/azure/aks.md
docs/docs-content/troubleshooting/nodes.md
netlify.toml

This PR fixes broken URLs reported by the URL checker.

docs: url updates

---

src/components/MendableAIWidget/MendableAIWidget.tsx

Changed mendable AI widget asset urls

Change Mendable AI widget asset url

---

.github/workflows/version-branch-update.yaml
scripts/netlify.sh

This PR updates the logic for backport CI actions

ci: updated branch PR logic

---

.github/workflows/release-preview.yaml
.github/workflows/version-branch-update.yaml
scripts/netlify.sh
src/components/MendableAIWidget/MendableAIWidget.tsx

This PR implements the final changes to the backport CI/CD

ci: update to the backport post-PRs CI/CD

---

.github/workflows/version-branch-update.yaml

This PR updates the Netlify PR comment order.

ci: updated backport PR netlify logic

---

docs/docs-content/clusters/palette-virtual-clusters/deploy-virtual-cluster.md

This PR fixes a sentence in the Validation section. Adding a reviewer in case merge issues arise with the backport PR for 3.4.
💻 [Preview](https://deploy-preview-1599--docs-spectrocloud.netlify.app/clusters/palette-virtual-clusters/deploy-virtual-cluster)

Fix sentence in deploy-virtual-cluster.md

---

docs/docs-content/clusters/edge/site-deployment/site-installation/edge-host-registration.md
docs/docs-content/clusters/edge/site-deployment/site-installation/site-user-data.md

Small changes to the formatting of edge installation docs.

Tiny doc fixes for edge

---

docs/api-content/api-docs/1-introduction.md

This PR adds documentation that got accidentally dropped during the migration. This is original PR that merged the content #1431  

docs: added missing API rate documentation

---

docs/docs-content/clusters/data-center/maas/install-manage-maas-pcg.md

This PR fixes examples that incorrectly specified Openstack versus MAAS.
💻 [Preview URL](https://deploy-preview-1613--docs-spectrocloud.netlify.app/clusters/data-center/maas/install-manage-maas-pcg#pcg-installer-image)

docs: Update install-manage-maas-pcg examples

---

docs/docs-content/spectro-downloads.md

This PR updates the Palette CLI version.

docs: update palette-cli version

---

docs/docs-content/release-notes.md

This PR documents patch releases 4.0.17 and 4.0.19 (updated from 4.0.18)
💻 [Preview](https://deploy-preview-1653--docs-spectrocloud.netlify.app/release-notes)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-888)

Patch 4 0 19 and 4 0 17 release notes

---

.github/workflows/aloglia_crawler.yaml
.github/workflows/eslint-test.yaml
.github/workflows/image_optimizer.yaml
.github/workflows/pull_request.yaml
.github/workflows/release-preview.yaml
.github/workflows/release.yaml
.github/workflows/url-checks.yaml
.github/workflows/version-branch-update.yaml

This PR updates the CI labels per guidance from the devops team.

ci: updated labels

---

docs/docs-content/clusters/edge/edgeforge-workflow/palette-canvos.md

This PR fixes an EdgeForge spacing issue
💻 [Preview](https://deploy-preview-1670--docs-spectrocloud.netlify.app/clusters/edge/edgeforge-workflow/palette-canvos?difficulty=advanced_create_artifacts)

edgeforge: fix

---

docs/docs-content/security/security-bulletins/cve-index.md
docs/docs-content/security/security-bulletins/cve-reports.md

This PR .....
💻 [Preview URL](https://deploy-preview-1668--docs-spectrocloud.netlify.app/security/security-bulletins/cve-reports)

Included new CVE's

---

src/theme/MDXComponents/MDXComponents.ts

This PR adds the Docusaurus Table of Content to the global scope.

chore: added toc to the global scope

---

docs/docs-content/enterprise-version/install-palette/airgap/checklist.md
docs/docs-content/enterprise-version/install-palette/airgap/kubernetes-airgap-instructions.md
docs/docs-content/enterprise-version/install-palette/airgap/vmware-vsphere-airgap-instructions.md
docs/docs-content/vertex/install-palette-vertex/airgap/checklist.md
docs/docs-content/vertex/install-palette-vertex/airgap/kubernetes-airgap-instructions.md
docs/docs-content/vertex/install-palette-vertex/airgap/vmware-vsphere-airgap-instructions.md

This PR updates the airgap documents to specify the correct Oras version.

docs: airgap fix

---

.gitleaksignore
docs/docs-content/release-notes.md
docs/docs-content/troubleshooting/nodes.md
docs/docs-content/troubleshooting/pcg.md
docs/docs-content/vm-management/vm-management.md
docs/docs-content/vm-management/vm-packs-profiles/vm-packs-profiles.md

This PR updates the VMO docs and documents a known issue.
- [Release Notes](https://deploy-preview-1690--docs-spectrocloud.netlify.app/release-notes#known-issues)
- [OS Patch Debug](https://deploy-preview-1690--docs-spectrocloud.netlify.app/troubleshooting/nodes#os-patch-fails)
- [Velero Challange with VMO](https://deploy-preview-1690--docs-spectrocloud.netlify.app/vm-management/vm-packs-profiles/)
💻 [Preview URL](https://deploy-preview-1690--docs-spectrocloud.netlify.app/)
🎫 [PEM-3770](https://spectrocloud.atlassian.net/browse/PEM-3770)
🎫  [PCP-2058 ](https://spectrocloud.atlassian.net/browse/PCP-2058)

docs: added content for PEM-3770

---

.github/workflows/url-checks.yaml
Makefile

This PR fixes the false positives in the broken URL reports.
💻 [Preview URL](https://deploy-preview-1694--docs-spectrocloud.netlify.app/)
🎫 [DOC-895](https://spectrocloud.atlassian.net/browse/DOC-895)

chore: fixes broken URL logic

---

docs/api-content/api-docs/3-postman-collection.md
docs/docs-content/clusters/public-cloud/azure/architecture.md
docs/docs-content/release-notes.md
docs/docs-content/vertex/supported-platforms.md

This PR fixes the broken URL reported in URL report and fixes some minor issues reported.
- Incorrect VerteX support for Azure Gov
- Added missing release note for Azure upgrade channels.
💻 [Preview URL](https://deploy-preview-1699--docs-spectrocloud.netlify.app/)
🎫 [PCP-1888]()https://spectrocloud.atlassian.net/browse/PCP-1888)

docs: updated broken URL and added missing release note PCP-1888

---

Makefile

This PR fixes an issue in the Makefile and removes an outdated entry.

chore: touched up the Makefile

---

.github/workflows/pull_request.yaml
.github/workflows/release.yaml
docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md

This PR updates the GitHub Runners

CI Runner Changes

---

docs/docs-content/clusters/edge/edge-configuration/cloud-init.md
vale/styles/Vocab/Internal/accept.txt

This PR backports the changes introduced in #1705

User Data Netplan  (#1705)

---

.backportrc.json
.github/workflows/pull_request.yaml
.github/workflows/release.yaml
.github/workflows/version-branch-update.yaml
archiveVersions.json

This PR will backport the changes from #1710.

ci: cherry-pick of version-4-0

---

.backportrc.json
.github/workflows/pull_request.yaml
.github/workflows/release.yaml
.github/workflows/version-branch-update.yaml
archiveVersions.json

This PR backportst the changes from #1710.

ci: cherry-pick of version-3-4

---

.backportrc.json
.github/workflows/pull_request.yaml
.github/workflows/release.yaml
.github/workflows/version-branch-update.yaml
archiveVersions.json

This PR will backport changes from #1710.

ci: cherry-pick of version-4-1

---

docs/docs-content/clusters/public-cloud/aws/add-aws-accounts.md
docs/docs-content/clusters/public-cloud/aws/eks.md
docs/docs-content/clusters/public-cloud/aws/enable-secrets-encryption-kms-key.md
docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
docs/docs-content/integrations/kubernetes-generic.md

This PR backports to version-3-4 branch.
💻 [Create and Manage EKS Cluster](https://deploy-preview-1767--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/eks)
[Enable Secrets Encryption for EKS Cluster](https://deploy-preview-1767--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/enable-secrets-encryption-kms-key)
[Required IAM Policies](https://deploy-preview-1767--docs-spectrocloud.netlify.app/clusters/public-cloud/aws/required-iam-policies)

EKS journey cherry-pick for version-3-4 (#1715)

---

docs/docs-content/clusters/public-cloud/aws/architecture.md
docs/docs-content/clusters/public-cloud/aws/aws.md
docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
docusaurus.config.js

This PR backports #1763 to version-3-4

[version-3-4]backport/version-3-4/pr 1763

---

docs/docs-content/integrations/ngrok.md
docs/docs-content/integrations/trident.md
vale/styles/Vocab/Internal/accept.txt

This PR carries over the work @Sheldonwl started in #1389. @Sheldonwl the original PR was created under the previous versions of docs. To avoid merge conflicts and issues, I ported the content into this branch and touched up the language. 
💻 [Preview URL](https://deploy-preview-1773--docs-spectrocloud.netlify.app/integrations/trident)
🎫 [DOC-807](https://spectrocloud.atlassian.net/browse/DOC-807)

chore: packs page DOC-807

---

docs/docs-content/integrations/ngrok.md
docs/docs-content/integrations/trident.md
vale/styles/Vocab/Internal/accept.txt

This PR backports #1773 to version-3-4

[version-3-4] DOC-807 (#1773)

---

docs/docs-content/clusters/cluster-management/pack-monitoring.md

This PR fixes a typo in Pack Monitoring header

fix: typo in pack monitoring

---

docs/docs-content/clusters/edge/site-deployment/stage.md

Repeat steps one through four for all edge hosts.
should be...
Repeat steps 1 through 4 for all edge hosts.
This PR fixes a reference within a step to previous steps to make them numerals instead of spelled-out numbers per our internal style.
💻 [Preview URL](https://deploy-preview-1804--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/stage)

Change numbered steps spell-out to be numerals

---

.github/workflows/release-branch-pr.yaml

This PR adds logic to trigger Netlify build previews in release branches.

ci: release branch PRs triggers

---

docs/docs-content/clusters/cluster-management/cluster-rbac.md
docs/docs-content/integrations/k3s.md
docs/docs-content/integrations/kubernetes-edge.md
vale/styles/Vocab/Internal/accept.txt

This PR backports the K3s file to version 4.0. 

docs: manual backport of k3s pack doc

---

docs/docs-content/registries-and-packs/adding-a-custom-registry.md
docs/docs-content/registries-and-packs/advanced-configuration.md

This PR fixes minor command errors within Docker commands and updates the spectrocloud-registry tag.

fix: port arg and updated spectrocloud-registry tag

---

docs/api-content/api-docs/v1/api.json

This PR fixes the `v1/auth` APIs requirement of authorization header issue.

API docs - 4.1.x (Auth header fix)

---

docs/docs-content/clusters/edge/site-deployment/site-installation/cluster-deployment.md

This PR describes how to select NIC for edge host during cluster creation. 
💻 [Preview URL](https://6568df6b919de51839c18d4a--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/site-installation/cluster-deployment)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/jira/software/c/projects/PE/issues/PE-950?filter=myopenissues)

docs: add step to configure nic for edge hosts

---

.npmrc

This PR updates the npmrc heap size to accomadte the larger CI runners

npmrc heap increase

---

docs/docs-content/registries-and-packs/deploy-pack.md

This PR refines the wording in the deploy-pack.md tutorial file.
💻 [Preview URL](https://deploy-preview-1870--docs-spectrocloud.netlify.app/registries-and-packs/deploy-pack)

docs: minor update of the deploy-pack.md file

---

src/css/custom.scss
src/css/table.scss

This PR adds a CSS rule that centers images and a border radius that rounds image corners. 

chore: center images and round image corners

---

src/css/custom.scss
src/css/table.scss

This PR adds the changes @lennessyy introduced with #1884 

chore: center images and round image corners (#1884)

---

docs/docs-content/vertex/supported-platforms.md

This PR updates the VerteX-supported platforms documented to show support for Azure Gov.
💻 [Preview URL](https://657b6cf0a254e8278367d23c--docs-spectrocloud.netlify.app/vertex/supported-platforms)
🎫 [DOC-958](https://spectrocloud.atlassian.net/browse/DOC-958)

docs: added Azure regions and updated symbol DOC-958

---

docs/docs-content/vm-management/vm-management.md
docs/docs-content/vm-management/vm-packs-profiles/create-vmo-profile.md

This PR adds documentation on how to run VMO on an edge cluster. 
💻 [Preview](https://657b50ed5d2539140fe6b500--docs-spectrocloud.netlify.app/vm-management/vm-packs-profiles/create-vmo-profile)

docs: add edge additions to vmo docs

---

docs/docs-content/clusters/clusters.md

This PR adds a note about not being able to create Tenant-level edge clusters. 
💻 [Preview URL](https://657b62620bc1e01ade0c90c4--docs-spectrocloud.netlify.app/clusters/#scope)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PEM-4202)

docs: add note about tenant level edge cluster

---

docs/docs-content/registries-and-packs/spectro-cli-reference.md

Adds missing subsection for "build" subcommand for spectro cli

add missing  doc subsection

---

.gitleaksignore
docs/docs-content/integrations/ngrok.md
docs/docs-content/integrations/portworx_operator.md

This PR backports the changes introduced in PR #1917

[version-3-4] Update Portworx /w Operator docs (#1917) DOC-594

---

.gitleaksignore
docs/docs-content/integrations/ngrok.md
docs/docs-content/integrations/portworx_operator.md

This PR backports the changes introduced in PR #1917

[version-4-0] docs: Update Portworx /w Operator docs (#1917) DOC-594

---

.github/workflows/container-prune.yaml
.github/workflows/url-checks.yaml

This PR fixes an issue with the image pruning job not cleaning properly.

Image prune debug

---

docs/api-content/api-docs/v1/api.json

Regenerated docs for the fix https://github.com/spectrocloud/hapi/pull/1647

API docs - 4.2 - docs fix

---

docs/docs-content/clusters/edge/networking/local-registry.md

This PR adds the requirement to modify the k8s layer when deploying a cluster with a local image registry. 
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/jira/software/c/projects/PE/issues/PE-3352?filter=myopenissues)

docs: add note about local registry k8s change

---

docs/docs-content/integrations/longhorn.md

This PR adds instructions that address the issues pertaining to the ShareManger remaining in the incorrect state when nodes redeploy. This pertains to RWX volume.
💻 [Preview URL](https://659719f2a29484372a7f56ac--docs-spectrocloud.netlify.app/integrations/longhorn#deadlock-with-rwx-mode)
🎫 [DOC-990](https://spectrocloud.atlassian.net/browse/DOC-990)

Longhorn Manual Resolution

---

docs/docs-content/legal-licenses.md

This PR updates the open-source license list for 4.2
💻 [Preview URL](https://659839b31b14f02f14b8ddc4--docs-spectrocloud.netlify.app/legal-licenses)

docs: open source license

---

docs/docs-content/integrations/k3s.md
docs/docs-content/integrations/kubernetes-generic.md
docs/docs-content/integrations/rke2.md

This PR updates the pack versions for the introduction of Kubernetes version 1.28.

docs: update new pack versions

---

docs/docs-content/release-notes.md

This PR fixed the date from the release notes.

docs: date fix

---

docs/docs-content/clusters/data-center/maas/install-manage-maas-pcg.md
docs/docs-content/clusters/data-center/openstack.md
docs/docs-content/clusters/data-center/vmware.md
docs/docs-content/palette-cli/commands.md

This PR addresses the merge conflicts introduced when backporting #1990

[version-4-0] docs: updated PCG per feedback DOC-998 (#1990)

---

docs/docs-content/release-notes.md

This PR adds release notes for the 4.2.4 release.
🎫 [DOC-1011](https://spectrocloud.atlassian.net/browse/DOC-1011)

docs: add release notes - DOC-1011

---

README.md
docs/docs-content/clusters/data-center/openstack.md
docs/docs-content/clusters/data-center/vmware.md
docs/docs-content/clusters/public-cloud/azure/aks.md
docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md

fix video elements 4.2

---

README.md
docs/docs-content/clusters/data-center/openstack.md
docs/docs-content/clusters/data-center/vmware.md
docs/docs-content/clusters/public-cloud/azure/aks.md

docs: fix video elements - 3.4

---

README.md
docs/docs-content/clusters/data-center/openstack.md
docs/docs-content/clusters/data-center/vmware.md
docs/docs-content/clusters/public-cloud/azure/aks.md
docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md

docs: Video element fix 4 0

---

docs/docs-content/troubleshooting/palette-dev-engine.md
src/theme/CodeBlock/Content/String.js
src/theme/CodeBlock/CopyButton/index.js

This PR fixes the issue with the hideClipboard feature not working. 
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-1023)

chore: fix issues with hideclipboard not working

---

docs/docs-content/troubleshooting/generate-har-files.md

This PR fixes wording in the Prerequisites section of Generate HAR Files.
💻 [Preview URL](https://deploy-preview-2033--docs-spectrocloud.netlify.app/troubleshooting/generate-har-files)
🎫 [DOC-992](https://spectrocloud.atlassian.net/browse/DOC-992)

Generate HAR Files: Fix wording in Prerequisites

---

docs/docs-content/clusters/public-cloud/gcp/add-gcp-accounts.md
docs/docs-content/registries-and-packs/pack-constraints.md

This PR addresses the backport conflicts from PR #2055

[version-4-0] Backport/version 4 0/pr 2055

---

docs/docs-content/security/security-bulletins/cve-index.md
docs/docs-content/security/security-bulletins/cve-reports.md
vale/styles/Vocab/Internal/accept.txt

This PR addresses the backport conflicts for PR #1999

[version-4-1] docs: New CVEs included (#1999)

---

.prettierignore
src/components/IconMapper/dynamicFontAwesomeImports.js
vale/styles/spectrocloud/inclusive.yml

This PR adds back the vale rule for removing master/slave language

chore: add vale rule for master/slave language

---

docs/api-content/api-docs/v1/api.json
docs/docs-content/clusters/data-center/nutanix/nutanix.md
docs/docs-content/clusters/edge/networking/vxlan-overlay.md
docs/docs-content/integrations/harbor-edge.md
docusaurus.config.js
src/css/custom.scss
src/css/dark-mode.scss
src/css/light-mode.scss
src/theme/Admonition/Icon/TechPreview.js
src/theme/Admonition/Type/TechPreview.js
src/theme/Admonition/Types.js
src/theme/Admonition/index.js

This PR manually backports the custom Tech Preview admonition to v.4.2 due to a failed automatic backport (PR#2017).

Backport the Tech Preview Admonition to v.4.2

---

vale/styles/spectrocloud/inclusive.yml

chore: manual backport add vale rule

---

vale/styles/spectrocloud/inclusive.yml

chore: vale manual backport

---

.prettierignore
src/components/IconMapper/dynamicFontAwesomeImports.js
vale/styles/spectrocloud/inclusive.yml

chore: vale rule manual backport

---

docs/docs-content/clusters/edge/networking/local-registry.md
docs/docs-content/clusters/edge/site-deployment/deploy-private-registry.md

This PR adds a warning that private registry password must contain special characters. 
💻 [Preview URL](https://deploy-preview-2120--docs-spectrocloud.netlify.app/clusters/edge/site-deployment/deploy-private-registry)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PE-3568)

docs: add warning for private registry password

---

docs/docs-content/clusters/edge/networking/local-registry.md
docs/docs-content/clusters/edge/site-deployment/deploy-private-registry.md

docs: add warning for private registry password manual backport

---

docs/docs-content/clusters/cluster-groups/create-cluster-group.md
docs/docs-content/clusters/data-center/maas/install-manage-maas-pcg.md
docs/docs-content/clusters/edge/site-deployment/stage.md
docs/docs-content/clusters/public-cloud/aws/enable-secrets-encryption-kms-key.md
docs/docs-content/clusters/public-cloud/aws/required-iam-policies.md
docs/docs-content/clusters/public-cloud/azure/gateways.md
docs/docs-content/clusters/public-cloud/public-cloud.md
docs/docs-content/enterprise-version/system-management/backup-restore.md
docs/docs-content/palette-cli/commands/pde.md
docs/docs-content/profiles/app-profiles/create-app-profiles/container-deployment.md
docs/docs-content/profiles/app-profiles/create-app-profiles/create-out-of-box-app-profile.md
docs/docs-content/profiles/cluster-profiles/modify-cluster-profiles/update-cluster-profile.md
docs/docs-content/security/core-principles.md
docs/docs-content/vm-management/vm-packs-profiles/vm-packs-profiles.md
docs/docs-content/workspace/adding-a-new-workspace.md
docs/docs-content/workspace/workload-features.md

This PR addresses some issues that Prettier might have introduced like broken tables and missing titles.
💻 Previews:
[Install and Manage MAAS Private Cloud Gateway](https://deploy-preview-2122--docs-spectrocloud.netlify.app/clusters/data-center/maas/install-manage-maas-pcg#install)
[Palette CLI - PDE](https://deploy-preview-2122--docs-spectrocloud.netlify.app/palette-cli/commands/pde)
[Core Principles](https://deploy-preview-2122--docs-spectrocloud.netlify.app/security/core-principles)
[Self-hosted Palette - Backup and Restore](https://deploy-preview-2122--docs-spectrocloud.netlify.app/enterprise-version/system-management/backup-restore#prerequisites-1)
[VMO Pack](https://deploy-preview-2122--docs-spectrocloud.netlify.app/vm-management/vm-packs-profiles/)
[Enable Secrets Encryption for …

docs: fix prettier issues

---

docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md

This PR adds a missing page refactor from #2003 
- [VMware Install](https://deploy-preview-2137--docs-spectrocloud.netlify.app/enterprise-version/install-palette/install-on-vmware/install)
-  [VerteX VMware Install](https://deploy-preview-2137--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/install)
💻 [Preview URL](https://deploy-preview-2137--docs-spectrocloud.netlify.app)

chore: added missing refactor page

---

docs/docs-content/enterprise-version/install-palette/install-on-vmware/install.md
docs/docs-content/vertex/install-palette-vertex/install-on-vmware/install.md

This PR backports the issues from PR #2039

[version-4-2] chore: added missing refactor page (#2137)

---

docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/install.md
docs/docs-content/enterprise-version/install-palette/install-on-kubernetes/palette-helm-ref.md
docs/docs-content/enterprise-version/system-management/ssl-certificate-management.md
docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/install.md
docs/docs-content/vertex/install-palette-vertex/install-on-kubernetes/vertex-helm-ref.md
docs/docs-content/vertex/system-management/ssl-certificate-management.md

Reverts spectrocloud/librarium#2139 as copy-edits need to be incorporated

Revert "Helm install changes"

---

docs/docs-content/vm-management/vm-management.md

This PR fixes a typo in the VMO index page. 
🎫 [DOC-1054](https://spectrocloud.atlassian.net/browse/DOC-1054)

docs: DOC-1054 typo fix

---

src/components/MendableAIWidget/MendableAIWidget.tsx

This PR upgrades the Mendable component widget to the latest version.
💻 [Preview URL](https://deploy-preview-2187--docs-spectrocloud.netlify.app/)

Upgrade Mendable component

---

docs/docs-content/clusters/cluster-management/os-patching.md

This PR refactors the OS patching page and fixes an error on the page. 
💻 [Preview URL](https://deploy-preview-2192--docs-spectrocloud.netlify.app/clusters/cluster-management/os-patching)
🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/PEM-4485)

docs: refactor os patching page

---

docs/docs-content/clusters/cluster-management/backup-restore/create-cluster-backup.md
docs/docs-content/clusters/cluster-management/backup-restore/restore-cluster-backup.md
docs/docs-content/integrations/ubuntu.md
docs/docs-content/registries-and-packs/registries/registries.md

This PR fixes backport issues from #2194

[version-4-2]Backup and other fix (#2194)

---

docs/docs-content/clusters/cluster-management/backup-restore/create-cluster-backup.md
docs/docs-content/clusters/cluster-management/backup-restore/restore-cluster-backup.md
docs/docs-content/integrations/ubuntu.md

This PR addresses backport issues from #2194

[version-4-1] Backup and other fix (#2194)

---

docs/docs-content/clusters/cluster-management/backup-restore/create-cluster-backup.md
docs/docs-content/clusters/cluster-management/backup-restore/restore-cluster-backup.md
docs/docs-content/integrations/ubuntu.md

This PR addresses backport issues #2194

[version-4-0] Backup and other fix (#2194)

---

docs/docs-content/devx/apps/deploy-app.md

This PR updates the _Deploy an Application using Palette Dev Engine_ tutorial.
* Update the Tutorials container image version.
* Add Podman as a container engine option.
💻 [Preview URL](https://deploy-preview-2214--docs-spectrocloud.netlify.app/devx/apps/deploy-app#terraform-workflow)
🎫 [DOC-1008](https://spectrocloud.atlassian.net/browse/DOC-1008)

docs: add podman, update container image

---

docs/docs-content/clusters/public-cloud/deploy-k8s-cluster.md

This PR addresses the merge conflict from #2216.

docs: add podman to tutorials DOC-1010 DOC-1009 (#2216)

---

vale/styles/Vocab/Internal/accept.txt

This PR updates the list of words allowed by Vale.
🎫 [DOC-1074](https://spectrocloud.atlassian.net/browse/DOC-1074)

Update Vale to accept PCGs, vCPU, and vCPUs

---

docs/docs-content/release-notes.md

This PR adds an advisory for the PCP 2516 issue
💻 [Preview URL](https://deploy-preview-2251--docs-spectrocloud.netlify.app/release-notes#feb-16-2024---release-4212)
🎫 [DOC-1076](https://spectrocloud.atlassian.net/browse/PCP-2516)

docs: add release notes for pcp 2516

---

docs/docs-content/release-notes.md

This PR fixes a markdown issue related to a callout box not rendering correctly.

docs: Update release-notes callout

---

docs/docs-content/release-notes.md

I noticed a glitch in the affected services, which this PR will fix. Also, fixed a couple missing dots.

Small 4.2.12 releases nodes fixes

---

Makefile

This PR updates the Makefile pdf commands. Changes including:
- Raising timeout to 15 min
- Removing the `start` dependency on `local-pdf`.

chore: update pdf script

---

Makefile

This PR addresses the backport issues from PR #2268

[version-4-1] chore: update pdf script (#2268)

---

Makefile

This PR addresses the backport issues from PR #2268

[version-4-0] chore: update pdf script (#2268)

---

docs/docs-content/clusters/public-cloud/azure/azure-cloud.md

This PR addresses feedback about duplicate content.
💻 [Preview URL](https://deploy-preview-2305--docs-spectrocloud.netlify.app/clusters/public-cloud/azure/azure-cloud)
🎫 [DOC-1087](https://spectrocloud.atlassian.net/browse/DOC-1087)
[DOC-1087]: https://spectrocloud.atlassian.net/browse/DOC-1087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Update azure-cloud.md

---

docs/docs-content/clusters/public-cloud/azure/azure-cloud.md

This PR addresses backport issues for #2305

[version-4-1]docs: DOC-1087 Update azure-cloud.md (#2305)

---

docs/docs-content/clusters/public-cloud/azure/azure-cloud.md

This PR addresses backport issues for PR #2305

[version-3-4] docs: DOC-1087 Update azure-cloud.md (#2305)

---

Makefile
scripts/generate_robots.sh
scripts/versions.sh

This PR adds logic to auto-generate a robots.txt file that excludes the version branches in the current domain.
🎫 [DOC-1091](https://spectrocloud.atlassian.net/browse/DOC-1091)
[DOC-1091]: https://spectrocloud.atlassian.net/browse/DOC-1091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Configure Robots

---

docs/docs-content/tenant-settings/api-key-management.md

This PR updates the API docs language
💻 [Preview URL](https://deploy-preview-2320--docs-spectrocloud.netlify.app/tenant-settings/api-key-management)

docs: update api-key-management.md

---

docs/docs-content/clusters/edge/edge.md

This PR addresses backport issues from PR #2344

[version-3-4]docs: DOC-1093 removing link (#2344)

---

docs/docs-content/clusters/edge/networking/local-registry.md
docs/docs-content/integrations/harbor-edge.md

This PR documents how to disable image swap for Harbor registry for select namespaces. 
🎫 [PE-3740](https://spectrocloud.atlassian.net/browse/PE-3740)
[PE-3740]: https://spectrocloud.atlassian.net/browse/PE-3740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: document namespace-based image swap diabling
